### ISSUE TITLE
Can the library be provided through CocoaPods?

### ISSUE THREAD

**Issue by abhimanyujindal10** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#10]
It would be very helpful to provide this library through cocoapods. Easy for users to integrate the library

**Comment by superpoweredSDK** [comment]
Importing the Superpowered static library is a simple drag and drop of the .a file and the header files you use.

**Comment by Speakus** [comment]
Anyway 'cocoapod way' is preferred for external libraries. Especially of them who has only .a + .h files. It would be really useful to add this way to customers. Thanks.

**Comment by kvacquier** [comment]
+1

**Comment by frogg** [comment]
Any update on this? It feels kinda dirty to drag in a library file like this nowadays…

**Comment by frogg** [comment]
Just found my own comment by googling, from 1.5 years ago 😆
<img width="872" alt="image" src="https://user-images.githubusercontent.com/5204169/74294755-2b1fbc80-4d3f-11ea-874d-fc1b4d3bb997.png">

**Comment by patrickbdev** [comment]
Another issue raised here: https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/issues/457
