### ISSUE TITLE
Superpowered does not build properly with Android NDK r11

### ISSUE THREAD

**Issue by aviadmini** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#100]
These sources reference `__page_size` in unistd.h :
SuperpoweredSource/decoder/SuperpoweredDecoder.cpp:120 SuperpoweredSource/decoder/hlsreader.cpp:582

Since the most recent NDK release (as of March 2016) this doesn't work anymore, but there's a `getpagesize()` function that can be used instead and that is compatible with newest Android NDK versions as well.

**Comment by superpoweredSDK** [comment]
Yes, we are using getpagesize() and we don't use __page_size. Investigating.

**Comment by SeanAsby** [comment]
I am having the same issue

**Comment by vaprea** [comment]
Same issue too

2016-03-18 11:08 GMT+01:00 Sean Inge Asbjørnsen <notifications@github.com>:

**Comment by superpoweredSDK** [comment]
The new NDK did change access to the getpagesize function. Will release new binary today, watch GitHub for an update.
