### ISSUE TITLE
Possible to invert phase of channels?

### ISSUE THREAD

**Issue by axemanrio** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#101]
Hello Gabor and team:

Is it possible to invert phase/polarity of the Left/Right channels?

We're basically trying to generate the Center channel for audio files. Any info or help you can provide is much appreciated.

Thanks!

**Comment by superpoweredSDK** [comment]
Hello,

yes, it can be easily done directly on the buffers you're working on. We don't offer such feature, but you can iterate over the samples, and negate them.
