### ISSUE TITLE
Error when opening long audio files

### ISSUE THREAD

**Issue by Falrach** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#102]
Hi,

I'm trying to use Superpowered to play long audio (aac) files and i get the following error:

A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0xa29b8000 in tid 23021 (AudioFile Read)

I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG: UUID: 790abf3d-2b32-4bc7-98d8-5763b1cf651d
I/DEBUG: Build fingerprint: 'Sony/C6603/C6603:5.1.1/10.7.A.0.228/58103698:user/release-keys'
I/DEBUG: Revision: '0'
I/DEBUG: ABI: 'arm'
I/DEBUG: pid: 22036, tid: 23021, name: AudioFile Read  >>> mypackage.mypackage<<<
I/DEBUG: signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xa29b8000
I/DEBUG:     r0 a28b5218  r1 a2797008  r2 00040b7a  r3 05592037
I/DEBUG:     r4 b8127590  r5 fffffcf8  r6 fffffcf8  r7 0004745f
I/DEBUG:     r8 b97736e4  r9 00000000  sl a2ab5bcc  fp 00000000
I/DEBUG:     ip 00100000  sp a2ab5ae0  lr a146e16c  pc a1469cc0  cpsr 800f0010
I/DEBUG:     #00 pc 00023cc0  /data/app/mypackage.mypackage-1/lib/arm/libPlayback.so (aacFile::open(audioDataProvider*, unsigned int, audioFormatHelp*, long long*, unsigned int*, unsigned int*, unsigned int*, bool)+1544)
I/DEBUG:     #01 pc 000202e8  /data/app/mypackage.mypackage-1/lib/arm/libPlayback.so (SuperpoweredDecoder::open(char const*, bool, int, int)+2156)
I/DEBUG:     #02 pc 00014bb0  /data/app/mypackage.mypackage-1/lib/arm/libPlayback.so
I/DEBUG:     #03 pc 000135e7  /system/lib/libc.so (__pthread_start(void*)+30)
I/DEBUG:     #04 pc 00011513  /system/lib/libc.so (__start_thread+6)

After some testing I found out that the error only occurs if the audio track is longer than ~100 minutes. It seems like I need to reserve more memory somewhere. Do you have an idea on why this error occurs and how it could be solved?

Thank you in advance!

**Comment by superpoweredSDK** [comment]
Please send that specific audio file to gabor@superpowered.com for analysis.

**Comment by superpoweredSDK** [comment]
Thank you for the file, checking...

**Comment by superpoweredSDK** [comment]
The Superpowered Decoder could not open this file. We could not crash it though, and the memory address sanitizer did not display any invalid access either. Perhaps you have a problem handling decoder errors, and the crash happens there.

We could open the file with a little modification of the Superpowered Decoder (the allocated memory was too low to handle the frame table of this very long file). The next Superpowered update (in 2-3 weeks) will have this modification, and it will be able to open this file (and similar long files).

**Comment by Falrach** [comment]
Thank you for your help!
