### ISSUE TITLE
Android loop simple audio track

### ISSUE THREAD

**Issue by Orbyt** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#104]
I've run into some issues using Androids `MediaPlayer` and `AudioTrack` apis and was looking into various libs for an easier solution. I simply need to loop an audio track continuously for 20 minutes or so. The previous methods I've used have all had a noticeable gap between the loops.

How simple is it to implement gap-less looping playback using this sdk?

**Comment by superpoweredSDK** [comment]
Check the CrossExample example project in the SDK please.

**Comment by tylerwilson** [comment]
I had the same question, and I could not find any hints in the CrossExample project, so I will pipe in with an answer. Superpowered will, by default, loop (without gaps!) all players when given the play command. 

If you want to stop a loop, you handle the SuperpoweredAdvancedAudioPlayerEvent_EOF event in the player callback, and set the passed bool pointer to true. Something like:

```
    case SuperpoweredAdvancedAudioPlayerEvent_EOF: {
        bool *stopLooping = (bool *)value;
        *stopLooping = player->isLooping() == false;
    }
```
