### ISSUE TITLE
nextSliceItem 3rd parameter not working

### ISSUE THREAD

**Issue by pwnified** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#106]
In the SuperpoweredAudiopointerList, calling nextSliceItem, the 'samplesUsed' pointer is not being filled in with a value. I'm trying to calculate the latency through the time stretcher so maybe you know another way?

**Comment by superpoweredSDK** [comment]
samplesUsed is designed to calculate latency. When you initialize a buffer, please don't forget to initialize it's samplesUsed member with a meaningful value, that is, how many samples did you use to provide that buffer.
