### ISSUE TITLE
Feature request: number of samples in timestretcher

### ISSUE THREAD

**Issue by pwnified** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#107]
I'm trying to synchronize the output to another timebase, however there doesn't seem to be any property for getting the number of samples currently being held in the timestretcher. This information is necessary to know the relationship between input and output for synchronization.

I was considering keeping track of this myself, by adding to a running total whenever input samples are added, and subtracting the 'samplesUsed' floating point returned from each sliceItem, but then it would suffer from drift due to floating point imprecision.

**Comment by superpoweredSDK** [comment]
'samplesUsed' is the proper way to track where exactly the original input stream is when it comes out from the time stretcher. Of course it's floating point, as you are doing time stretching, so one input sample may be involved in the creation of multiple output samples. The samplePosition can also be set for each buffer to submit.

**Comment by pwnified** [comment]
'samplesUsed' is just a ratio between the sizes, not an absolute offset. And 'samplePosition' isn't even used, I can set it to zero with no effect. It isn't moved to the output buffers, it isn't part of the 'slice'. Having the number of samples currently in the stretcher is pretty common for a time stretcher.
