### ISSUE TITLE
SuperpoweredStereoToMono fails on iPhone 5S device

### ISSUE THREAD

**Issue by bforian** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#108]
Running the code below fails on 5S device with iOS 9.3.1.

    int numSamples = 10;
    
    float *stereoInput = (float *)malloc(numSamples*2*sizeof(float));
    memset(stereoInput, 0, numSamples*2*sizeof(float));

    float *monoOutput = (float *)malloc(numSamples*sizeof(float));
    memset(monoOutput, 0, numSamples*sizeof(float));
    SuperpoweredStereoToMono(stereoInput, monoOutput, 1.0, 1.0, 1.0, 1.0, numSamples);

Runs fine in simulator and there's no error if I set numSamples < 5.

Love the product btw.

**Comment by superpoweredSDK** [comment]
This will be fixed in the next release, but until then simply use power of 8 number of samples.
