### ISSUE TITLE
Recording audio to file

### ISSUE THREAD

**Issue by taraspaliy** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#109]
Hi,

I want to record audio with loopback (mic to speakers) with the lowest possible audio latency and ability to write recording into file simultaneously.
There are two classes - SuperpoweredAndroidAudioIO and SuperpoweredRecorder, which one fits most? Is it possible to use audioProcessingCallback for writing data into file?

Thanks!

**Comment by superpoweredSDK** [comment]
You need to use both. 
- SuperpoweredAndroidAudioIO handles audio input and output.
- SuperpoweredRecorder can capture audio samples and write them to a .wav file.
So essentially you need to use the recorder's process method in the audio IO's callback.

**Comment by shivamsingh** [comment]
Thanx a ton.
