### ISSUE TITLE
Can you provide the example how to use SuperpoweredOfflineAnalyzer class in iOS

### ISSUE THREAD

**Issue by abhimanyujindal10** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#11]
I will be grateful if you provide any example how to use SuperpoweredOfflineAnalyzer in iOS

**Comment by superpoweredSDK** [comment]
We plan to release an example code, but until then please take a look at the offline analyser example how to get samples from an audio file, and please read the header for the offline analyser, as it has just two methods to use.

**Comment by abhimanyujindal10** [comment]
Thank you so much for your response. I am currently trying to use offline
analyzer. Can you help me how to process the iTunes library audio file? Do
i need to write the audio in documents directory first to process it? I am
sorry, i am naive and haven't use core audio as well.

**Comment by abhimanyujindal10** [comment]
Hi,
I am able to detect bpm, key , waveformsize but not 
averageWaveform
peakWaveform

Can you please provide how to get these values. What I am trying to do is to get the waveform details.

**Comment by samyhajal** [comment]
Hi,
Could you let me know what kind of input you passed to the process function?
Thank you

**Comment by hool304** [comment]
Hi @abhimanyujindal10 
Can you give me a example code with bpm detection?

**Comment by abhimanyujindal10** [comment]
I did in the following way :- 

Use this code in view did load or somewhere else

{
SuperpoweredDecoder *decoder = [self getSongDecoderForFileURL:exportURL]; // where url is the audio song which is either in bundle or in your app document directory

if (!decoder) {
	NSLog(@"Handle Error that decoder is not created");
	return;
	}
[self processSongForDecoder:decoder];
}



- (void)processSongForDecoder:(SuperpoweredDecoder *)decoder {
	int sampleRate = decoder->samplerate;
	double durationSeconds = decoder->durationSeconds;

	SuperpoweredAudiobufferPool *bufferPool = new SuperpoweredAudiobufferPool(4, 1024 * 1024);             // Allow 1 MB max. memory for the buffer pool.

	SuperpoweredOfflineAnalyzer *analyzer = new SuperpoweredOfflineAnalyzer(sampleRate, 0, durationSeconds);

	short int *intBuffer = (short int *)malloc(decoder->samplesPerFrame * 2 * sizeof(short int) + 16384);

	int samplesMultiplier = 4; ////-->> Performance Tradeoff
	while (true) {
		// Decode one frame. samplesDecoded will be overwritten with the actual decoded number of samples.
		unsigned int samplesDecoded = decoder->samplesPerFrame * samplesMultiplier;
//		NSLog(@"Samples per Frame for decoding->%d->>>", samplesDecoded);
//		NSLog(@"Sample Position->%d->>>", decoder->samplePosition);
		if (decoder->decode(intBuffer, &samplesDecoded) != SUPERPOWEREDDECODER_OK) break;

		// Create an input buffer for the analyzer.
		SuperpoweredAudiobufferlistElement inputBuffer;

		bufferPool->createSuperpoweredAudiobufferlistElement(&inputBuffer, decoder->samplePosition, samplesDecoded + 8);

		// Convert the decoded PCM samples from 16-bit integer to 32-bit floating point.
		SuperpoweredStereoMixer::shortIntToFloat(intBuffer, bufferPool->floatAudio(&inputBuffer), samplesDecoded);
		inputBuffer.endSample = samplesDecoded;             // <-- Important!
		analyzer->process(bufferPool->floatAudio(&inputBuffer), samplesDecoded);
	}

	[self freeDecoder:decoder]; //this will free the allocated memory.
	delete bufferPool;
	free(intBuffer);

	unsigned char **averageWaveForm = (unsigned char **)malloc(150 * sizeof(unsigned char *));
	unsigned char **peakWaveForm = (unsigned char **)malloc(150 * sizeof(unsigned char *));
	char **overViewWaveForm = (char **)malloc(durationSeconds * sizeof(char *));

	int *keyIndex = (int *)malloc(sizeof(int));
	int *waveFormSize = (int *)malloc(sizeof(int));

	float *averageDecibel = (float *)malloc(sizeof(float));
	float *loudPartsAverageDecibel = (float *)malloc(sizeof(float));
	float *peakDecibel = (float *)malloc(sizeof(float));
	float *bpm = (float *)malloc(sizeof(float));
	float *beatGridStart = (float *)malloc(sizeof(float));

	analyzer->getresults(averageWaveForm, peakWaveForm, waveFormSize, overViewWaveForm, averageDecibel, loudPartsAverageDecibel, peakDecibel, bpm, beatGridStart, keyIndex);

	if (!resultModal) {
		resultModal = [WaveFormResultModal initialzeModal];
	}


	for (int i = 0; i < *waveFormSize; i++) {
		[resultModal.averageWaveForm addObject:[NSNumber numberWithUnsignedChar:averageWaveForm[0][i]]];
		[resultModal.peakWaveForm addObject:[NSNumber numberWithUnsignedChar:peakWaveForm[0][i]]];
	}
	for (int i = 0; i < durationSeconds; i++) {
		[resultModal.overViewWaveForm addObject:[NSNumber numberWithChar:overViewWaveForm[0][i]]];
	}

	resultModal.keyIndex = arrSongKeys[keyIndex[0]];
	resultModal.waveFormSize = [NSNumber numberWithInt:waveFormSize[0]];

	resultModal.averageDecibel = [NSNumber numberWithFloat:averageDecibel[0]];
	resultModal.loudPartsAverageDecibel = [NSNumber numberWithFloat:loudPartsAverageDecibel[0]];
	resultModal.peakDecibel = [NSNumber numberWithFloat:peakDecibel[0]];
	resultModal.bpm = [NSNumber numberWithFloat:bpm[0]];
	resultModal.beatGridStart = [NSNumber numberWithFloat:beatGridStart[0] / 1000];
	resultModal.durationSeconds = [NSNumber numberWithDouble:durationSeconds];
	resultModal.audioFileURL = exportURL;


	free(averageWaveForm);
	free(peakWaveForm);
	free(overViewWaveForm);
	free(keyIndex);
	free(waveFormSize);
	free(averageDecibel);
	free(loudPartsAverageDecibel);
	free(peakDecibel);
	free(bpm);
	free(beatGridStart);

	if ([self.delegate respondsToSelector:@selector(analyzer:didAnalyzeSongWithResult:)]) {
		[self.delegate analyzer:self didAnalyzeSongWithResult:resultModal];
	}
}

- (SuperpoweredDecoder *)getSongDecoderForFileURL:(NSURL *)fileURL {
	SuperpoweredDecoder *decoder = new SuperpoweredDecoder(false);
	const char *openError = decoder->open([exportURL fileSystemRepresentation]);
	if (openError) {
		NSLog(@"%s", openError);
		delete decoder;
		return nil;
	}
	return decoder;
}

**Comment by hool304** [comment]
Tnks!
