### ISSUE TITLE
SuperpoweredStereoMixer process crashes.

### ISSUE THREAD

**Issue by shivamsingh** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#110]
Hi,

I want to mix two audio files(wav & mp3) and save them.
But while processing app getting crashed. Here is code and stack trace.

**Code:**

`saveFxFile(const char *path, const char *backtrack,
                                     const char *destination, int *params) {
    SuperpoweredDecoder *decoder = new SuperpoweredDecoder();
    SuperpoweredDecoder *backTrackDecoder = new SuperpoweredDecoder();

    const char *openError = decoder->open(path, false, 0, 0, 0);
    if (openError) {
        delete decoder;
        return;
    };

    const char *openError2 = backTrackDecoder->open(backtrack, false, 0, 0, 0);
    if (openError2) {
        delete backTrackDecoder;
        return;
    };

    FILE *fd = createWAV(destination, decoder->samplerate, 2);
    if (!fd) {
        delete decoder;
        return;
    };

    // Create a buffer for the 16-bit integer samples coming from the decoder.
    short int *intBuffer = (short int *) malloc(
            decoder->samplesPerFrame * 2 * sizeof(short int) + 16384);
    // Create a buffer for the 32-bit floating point samples required by the effect.
    float *floatBuffer = (float *) malloc(decoder->samplesPerFrame * 2 * sizeof(float) + 2048);

    // Create a buffer for the 16-bit integer samples coming from the decoder.
    short int *intBTBuffer = (short int *) malloc(
            backTrackDecoder->samplesPerFrame * 2 * sizeof(short int) + 16384);
    // Create a buffer for the 32-bit floating point samples required by the effect.
    float *floatBTBuffer = (float *) malloc(
            decoder->samplesPerFrame * 2 * sizeof(float) + 2048);

    float *comboBuffer = (float *) malloc(
            decoder->samplesPerFrame * 2 * sizeof(float) + 2048);

    float **inputs = new float*[4];
    float **outputs = new float*[2];

    float *inputLevels = new float[8];
    float *outputLevels = new float[2];

    bool *channelSwitches = new bool[4];
    float *channelOutputLevels = new float[4];

    inputLevels[0] = 0.5f;
    inputLevels[1] = 0.5f;
    inputLevels[2] = 0.5f;
    inputLevels[3] = 0.5f;
    inputLevels[4] = 0.5f;
    inputLevels[5] = 0.5f;
    inputLevels[6] = 0.5f;
    inputLevels[7] = 0.5f;

    outputLevels[0] = 1.0f;
    outputLevels[1] = 1.0f;

    channelSwitches[0] = true;
    channelSwitches[1] = true;
    channelSwitches[2] = true;
    channelSwitches[3] = true;

    channelOutputLevels[0] = 1.0f;
    channelOutputLevels[1] = 1.0f;
    channelOutputLevels[2] = 1.0f;
    channelOutputLevels[3] = 1.0f;

    float inputMeters[8];
    float outputMeters[2];

    while (true) {
        unsigned int samplesDecoded = decoder->samplesPerFrame;
        unsigned int btSamplesDecoded = backTrackDecoder->samplesPerFrame;
        if (decoder->decode(intBuffer, &samplesDecoded) == SUPERPOWEREDDECODER_ERROR) break;
        if (samplesDecoded < 1) break;
        backTrackDecoder->decode(intBTBuffer, &btSamplesDecoded);
        // Convert the decoded PCM samples from 16-bit integer to 32-bit floating point.
        SuperpoweredShortIntToFloat(intBuffer, floatBuffer, samplesDecoded);
        SuperpoweredShortIntToFloat(intBTBuffer, floatBTBuffer, btSamplesDecoded);

        highPassFilter->process(floatBuffer, floatBuffer, samplesDecoded);

        inputs[0] = floatBTBuffer;
        inputs[1] = comboBuffer;
        inputs[2] = NULL;
        inputs[3] = NULL;

        outputs[0] = comboBuffer;
        outputs[1] = NULL;

        mixer->process(inputs, outputs, inputLevels, outputLevels, NULL, NULL, btSamplesDecoded);
        SuperpoweredFloatToShortInt(comboBuffer, intBuffer, btSamplesDecoded);
        fwrite(intBuffer, 1, samplesDecoded * 4, fd);
    }

    closeWAV(fd);
    delete decoder;
    free(intBuffer);
    free(floatBuffer);`

**Crash dump:**

Build fingerprint: 'ONEPLUS/A0001/A0001:5.0.2/LRX22G/34:user/release-keys'
pid: 27540, tid: 27540, name: ed.crossexample  >>> com.superpowered.crossexample <<<
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x61622f31
Stack frame #00 pc 0001f004  /data/app/com.superpowered.crossexample-1/lib/arm/libSuperpoweredExample.so (SuperpoweredStereoMixer::process(float**, float**, float*, float*, float*, float*, unsigned int)+372)
Stack frame #01 pc 0000efe0  /data/app/com.superpowered.crossexample-1/lib/arm/libSuperpoweredExample.so (SuperpoweredExample::saveFxFile(char const*, char const*, char const*, int*)+724)
Stack frame #02 pc 0000f37c  /data/app/com.superpowered.crossexample-1/lib/arm/libSuperpoweredExample.so (Java_com_superpowered_crossexample_MainActivity_saveFxFile+196)
Stack frame #03 pc 001a69d3  /data/dalvik-cache/arm/data@app@com.superpowered.crossexample-1@base.apk@classes.dex
\

Please let me know if more details are required.

**Comment by superpoweredSDK** [comment]
The problem is that the number of samples returned from one decoder may be different to the number of samples returned by the other decoder. Your code is not prepared for that.

**Comment by shivamsingh** [comment]
Thanks a ton for your prompt reply!

**Comment by shivamsingh** [comment]
Hi SuperPoweredSDK Team,

We have checked number of samples returned from both decoder is same.
Also when we tried to mix 2 same file then also it's getting crashed.

Can you please share some code snippet for input & output buffer.
