### ISSUE TITLE
SuperpoweredRecorder and backtrack player latency issue.

### ISSUE THREAD

**Issue by shivamsingh** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#116]
Hi Superpowered Team,

We are recording audio from mic and playing backtrack from a file at same time but once recording completes and we mix two files we see there is lag of few milliseconds(40-200ms) in recorded file.

This lag is caused because recording begins slightly before the backing track actually starts playing.

Here is our code:

`

 audioSystem = new SuperpoweredAndroidAudioIO(sampleRate, framesPerBuffer, true, true, audioProcessing, this, SL_ANDROID_RECORDING_PRESET_GENERIC, SL_ANDROID_STREAM_MEDIA, framesPerBuffer * 2);

bool AudioRecorder::process(short int *output, unsigned int numberOfSamples)
{
    pthread_mutex_lock(&mutex);

    bool processed = false;
    if(isRecording)
    {
        SuperpoweredShortIntToFloat(output, recordBuffer, numberOfSamples, NULL);

        processed = player->process(stereoBuffer, false, numberOfSamples);
        if(processed)
            SuperpoweredFloatToShortInt(stereoBuffer, output, numberOfSamples);
        
        recorder->process(recordBuffer, NULL, numberOfSamples);
        for(int i=0; i<(numberOfSamples * 2); i++)
        {
            if(fabs(recordBuffer[i]) > fabs(peakAmplitude))
                peakAmplitude = fabs(recordBuffer[i]);
        }
     }
    pthread_mutex_unlock(&mutex);

    return processed;
}

`

**Comment by superpoweredSDK** [comment]
Hello,

you can start recording in the same time when the player starts, if you seek to the point where the audio really starts in your audio file, and start recording and playback at the same time.
You will still get various latency due Android's 10 millisecond problem. Please read: http://superpowered.com/androidaudiopathlatency

**Comment by deepakrokz** [comment]
Hi @shivamsingh ,
Have you got rid of latency issue?

**Comment by shivamsingh** [comment]
Hi @deepakrokz,

NO, we did calibrate device to get the latency and skip the smples.

**Comment by deepakrokz** [comment]
Thanks for your reply, 
can you help me these links: [1](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/issues/462) & [2](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/issues/458)
