### ISSUE TITLE
Does your SDK perform audio loopback? (Record while hearing voice in real time)

### ISSUE THREAD

**Issue by roarribbit** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#12]
I'm trying to make a Karoake app where you can sing into the mic and hear yourself in real time with no latency (less enough where it is feasible to sing without being disturbed by your delayed echo). 

Do you support this feature?  How would you do it with your SDK?  I didn't see an option to feed the audio-in into the audio-out.

**Comment by superpoweredSDK** [comment]
The SuperpoweredIOSAudioOutput class handles connections with the media server. Set inputEnabled to true and you'll have it.

**Comment by roarribbit** [comment]
I was talking about for Android.  Do you have a way to perform audio loopback (record while hearing voice) in Android using your SDK?  Does SuperpoweredIOSAudioOutput do that for Android as well?

**Comment by superpoweredSDK** [comment]
Interfacing with the operating system is not part of the Superpowered Audio SDK. The SuperpoweredIOSAudioOutput class is an open-source addition to help iOS developers. On Android you should use the OpenSL ES API for this purpose. The example project shows how to do that for output, input is quite identical.

**Comment by kangear** [comment]
I want to know this too. :P
