### ISSUE TITLE
SuperpoweredResampler crahses while processing

### ISSUE THREAD

**Issue by shivamsingh** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#120]
Hi SuperPoweredTeam,

We're trying to resample a karaoke track to match the native recording sample rate of the android device. Eg. if we find that the device works at 48 KHz and our backing track is at 44.1 KHz, we want to automatically resample it to 48 KHz. So we decode PCM samples frame by frame and pass them to the resampler which, if my understanding is correct should output a greater number of samples than was passed to it, in case of upsampling. But when we get to the resampler function, it always crashes. Prior to this we were hearing small dropouts/glitches at a fixed rate. I assume this is because some of the audio data in each frame is being lost, causing a discontinuity in the signal. Could you explain how the resampler handles data? And how many samples are provided at its output.
`
SuperpoweredResampler *resampler = new SuperpoweredResampler();
    resampler->rate = sampleRate / 44100.0;
....
....
int intBufferSize = recordingDecoder->samplesPerFrame * 2 * sizeof(short int) + 16384;
int floatBufferSize = backTrackDecoder->samplesPerFrame * 2 * sizeof(float) + 1024;
short int *intBacktrack = (short int *) malloc(intBufferSize);
float *floatBacktrack = (float *) malloc(floatBufferSize);

backTrackDecoder->decode(intBacktrack, &samplesDecoded)

resampler->process(intBacktrack, floatBacktrack, samplesDecoded, false, true, 0.0f);

`
> ********** Crash dump: **********
Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/MOB30H/2751534:user/release-keys'
pid: 25183, tid: 25183, name: ing.tyunami_rnd  >>> com.sixstring.tyunami_rnd <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x9e980000
Stack frame #00 pc 00096420  /data/app/com.sixstring.tyunami_rnd-2/lib/arm/libTyunami.so: Routine SuperpoweredResamplerHQ at ??:?

**Comment by superpoweredSDK** [comment]
Your floatBacktrack's size is not big enough. I have no idea what's the value of your backTrackDecoder->samplesPerFrame, but floatBacktrack's size should be at least:

backTrackDecoder->samplesPerFrame * 2 * sizeof(float) * int(48000.0f / 44100.0f) + 1024

As you are submitting samplesDecoded samples, and expecting 8% more samples to get back.

intBacktrack's size should be bound to the backTrackDecoder too.

**Comment by iamyellow** [comment]
Hi! I'm reopening this issue because I'm facing a problem that has something to do w/ this. I'm trying to resample a file @ 48000 to 44100, on an iPhone/iPad (output at 44100). I'm doing this:
resampler->rate = 48000.0f/44100.0f;
the app is not crashing and the sound pitch is ok, but it sounds like distorted.
any clue?
