### ISSUE TITLE
SuperpoweredAdvancedAudioPlayer clicks with seek

### ISSUE THREAD

**Issue by felart** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#121]
Hi,

Superpowered is really a great audio engine.
I'm trying to make an app which use a lot of seek to navigate inside a loop.
I experienced clicks when I use seek with an SuperpoweredAdvancedAudioPlayer and I don't know how to remove them. Is there a way to add a fade In for example? I've tried to use cachePosition but with no success.

Any idea?

Thanks.

**Comment by superpoweredSDK** [comment]
Please send an audio recording example to gabor@superpowered.com

**Comment by nikolocogr** [comment]
Hi, I have also the same issue.

-I use your android example (cross)
-I want to loop one mp3 file, its a choir recording, 12 second duration (about 140kb mp3 at 128kbit) so as to crossfade the track endless till user stops it
-I ve managed to crossfade from PlayerA to PlayerB (and vise versa) when playing track reaches 90%
-Code looks ok and using loging seems to work fine
-The crossfade between the two players works great, I cant even suspect when the crossfade is happening
-But sound glitces and sounds bad and I think not only when seeking :(
-This happens some times (very often) and at some devices I ve tested this is even worst :(

Any ideas?

**Comment by superpoweredSDK** [comment]
Check the latest version of the CrossExample project in the latest SDK. It implements the infamous "fake touches" method in MainActivity, which may help on some devices.

**Comment by superpoweredSDK** [comment]
Strictly speaking there were no audio glitches, such as clicks and pops in the audio file you sent. There were no discontinuity or abruptly changing samples. The SupeproweredAdvancedAudioPlayer takes care of these and fades sound when you seek.

The popping sound came from the characteristics of your sound content. It's close to a calm wave, and abruptly cueing such sound causes the "pops", as the wave periods are long and cueing happens at random (user triggered) points, not zero crossings.
You need to take care of this, such as changing volume smoothly when cueing happens, such as ramping up volume in 0.1 sec or similar.

**Comment by superpoweredSDK** [comment]
The next build will come with a smoother algo for this.

**Comment by svenoaks** [comment]
Hopefully any smoothening of loop will be optional. My app shouldn't have volume raising or lowering when loop happens and shouldn't adjust the sample position (timing) to make it sound better at all.

**Comment by superpoweredSDK** [comment]
It will definitely not affect timing and looping.
