### ISSUE TITLE
iOS bitcode support ?

### ISSUE THREAD

**Issue by ksubox** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#124]
When I try to archive application I get:

`ld: bitcode bundle could not be generated because '/Users/sergey/Work/xcode/TvsLib/Superpowered/libSuperpoweredAudioIOS.a(SuperpoweredMixer.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
`

I wonder how to fix it ?

**Comment by superpoweredSDK** [comment]
Disable bitcode please. Bitcode doesn't allow high performance code (such as Assembly), it removes performance benefits. Don't afraid, bitcode never will be mandatory for iOS apps because of this limitation.

**Comment by DiscoverPioneer** [comment]
That worked for me!!! Thank you!
