### ISSUE TITLE
Pitch shifting sound quality

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#126]
Hello, is there anyway that there could be a higher quality pitch shifting option, even at the expense of more CPU cycles. I have both Superpowered and SoundTouch for pitch shifting available in my app, and many users report the pitch shifting sounds better with SoundTouch. I tend to agree, Superpowered sounds like it introduces some sort of vocoder effect when pitch shifting. I would like to no longer support SoundTouch, but the pitch shifting sound quality is holding me back.

**Comment by superpoweredSDK** [comment]
We've considered formant correction for pitch-shifting. It might be something we invest resources in later this year.

**Comment by svenoaks** [comment]
I've tried some libraries with formant correction, while it improves sound quality, there is something more basic in the pitch shifting going on. There seems to be like a warbly effect that is added. In other libraries, even with formant correction disabled, it sounds a lot crisper. Perhaps Superpowered pitch shifting could be improved in another way first.
