### ISSUE TITLE
Audio Panning 

### ISSUE THREAD

**Issue by Dhvanitp** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#128]
Hello, is it possible to implement audio panning for the players created with the SuperpoweredAdvanceAudioPlayer , I'm not sure if that can be achieved by using SuperpoweredStereoMixer class.
Thank you very much for your time in advance.

**Comment by superpoweredSDK** [comment]
Hello,

panning is definitely possible with Superpowered. 

The SuperpoweredStereoMixer's inputLevels and outputLevels parameters contain separate, per channel levels. So adjusting those provides panning.
