### ISSUE TITLE
Record mic input.

### ISSUE THREAD

**Issue by Dhvanitp** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#129]
Hello,
Thank you for your prompt response on my last question #128. 
I have another question this time,related to recording mic input on iOS.
How can I record mic input and send it to the SuperpoweredStereoMixer?
And is there any example project related to it?
Thank you for your time in advance.

**Comment by superpoweredSDK** [comment]
Use the SuperpoweredAndroidAudioIO class to set up audio I/O, just like in the frequency domain example project. Use the SuperpoweredRecorder class to record the incoming buffer into a WAV file.
