### ISSUE TITLE
Quick example of mike capture -> SuperpoweredAdvancedAudioPlayer

### ISSUE THREAD

**Issue by Opariti** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#13]
Hi Gabor,
I have read with interest your credo on site, the DJ video and appreciated the fast handshake from Patrick after SDK download. I've also did a succesfull Eclipse install of your Android example. Basically I am at ease with JNI but I would kindly ask you, to save "decryption" time, if possible, to drop the few lines of code for your player reading from a float (I imagine) buffer, so that I can test your challenging statement on the low latency performance, before playing with the special effects on Android; I shall use it with voice capture. Besides the fast processing algos, my understanding is that this latency reduction - your original catch - comes from the audio player implementation (not the mike capture input, at least for Android).  Thanks for considering this inquiry, I shall post here my implementation if okay.

**Comment by superpoweredSDK** [comment]
Hi,

what do you mean under "your player"? The Superpowered Audio SDK has various features, including two players, but they read from audio files. Yes, your understanding is correct: the Superpowered Audio SDK improves latency for all Android features except audio input and output. You must use OpenSL ES for those, our SDK runs inside your application and has no access to system internals.

**Comment by Opariti** [comment]
Thanks for the reply, it is clear!
