### ISSUE TITLE
Mic input recording 

### ISSUE THREAD

**Issue by Dhvanitp** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#130]
Hi, 
The last issue #129  was closed,so I have created a new one here.
1) Just wanted to confirm, you meant SuperpoweredIOSAudioIO class right because I want it to record on iOS devices and not android.
2)I am able to record mic input into a wav file using the SuperpoweredIOSAudioIO class and the recorder, but have issues while recording both the mic input and player playing music simultaneously.
It only records either the mic or the player at one time.

Help would be appreciated, Thank you.

**Comment by superpoweredSDK** [comment]
Hi,

you can reopen any issue with a comment, no need to open a new one.

1) Yes, correct.
2) Check your audio processing callback. You get a buffer with audio, you must put your output audio into that buffer as well. So pass that buffer to the recorder, then overwrite it's content with your player's process method.

**Comment by Dhvanitp** [comment]
Hello,
This is where I'm stuck now, I have both mic and player recording simultaneously but I can hear the mic on the output when I start the player to record.Is there a technique to stop that from happening.
Thank you very much.

**Comment by vipindhangar** [comment]
Hello,
Need help with this.
I am able to record with the player.

But not with a mic input, using the SuperpoweredIOSAudioIO class and the recorder. I need both the mic input and a player playing music simultaneously and record

It only records the player only.

Thanks
