### ISSUE TITLE
Always getting error Can't open this file 

### ISSUE THREAD

**Issue by AbhijeetCopper** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#131]
NSURL *inputUrl  =  var/mobile/Containers/Data/Application/42412EFB-DBC8-4E33-B783-64CEF0561CAD/Library/Caches/tempAudio.m4a
**Always getting error Can't open this file** 

 (void)applyAudioFilter:(NSNumber* )selectedFilterType inputUrl:(NSURL*)inputUrl  WithCompletionBlock:(void(^)(BOOL success, NSURL *outputUrl))block{
const char *openError = decoder->open([[inputUrl absoluteString] UTF8String], false, 0, 0);
    if (openError)-- **Always getting error (open error: Can't open this file.)**    {

        NSLog(@"open error: %s", openError);

        delete decoder;

        return;

    };

Please help me

**Comment by superpoweredSDK** [comment]
Does the file exist on that very specific location? Can you play it on that place with Quicktime?

**Comment by superpoweredSDK** [comment]
I will close this issue if you doesn't respond soon. You did not respond on Zendesk either.

**Comment by johnny-cao** [comment]
I use [[url absoluteString] UTF8String] for MPMediaItem, while [url fileSystemRepresentation] for the local file, and it works. Hope it's help for you.
