### ISSUE TITLE
The new gradle plugin doesn't include 64 bits libraries

### ISSUE THREAD

**Issue by 00christian00** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#135]
Previously the apk and libraries would embed all 4 variants arm,arm64, x86 and x86 64.
Now only the 32 bit variant are included.

**Comment by superpoweredSDK** [comment]
Please check your build.gradle in the app module. They look like this in the current SDK:

https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/blob/master/Android/CrossExample/app/build.gradle

All variants are included.

**Comment by 00christian00** [comment]
I tried the crossexample of the latest source and it dores have the same gradle settings but if you check the apk only 2 variants are included. it build 4 but include only 2.

**Comment by 00christian00** [comment]
I think I found the culprit but don't know how to solve it, probably will have to revert to the old build.gradle that worked perfectly.
Basically the abifilters specify the platform of the ndk l, but the ndk platform 16 specified in the gradle (platformVersion=16 ) only contain arm,mips and x86. If I specify platform 21 or later, then it create the additional files but it fail at linking, because I read it's not compatible with anything before:
http://stackoverflow.com/questions/36746904/android-linker-undefined-reference-to-bsd-signal

So to keep having 4 libraries I think the only option is to revert to the old way.

**Comment by superpoweredSDK** [comment]
Yes, please do the old (Android.mk) way then. Thank you finding this!
We will keep supporting the experimental plugin still, as it's much easier to use for many developers.
