### ISSUE TITLE
Mixed file audio volume is lower than SuperpoweredAdvancedAudioPlayer play?

### ISSUE THREAD

**Issue by falll2000** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#139]
Sorry about English is not my mother language.

I want to mix microphone and background music into a single file, just like karaoke function.

I use SuperpoweredAdvancedAudioPlayer to play background music and SuperpoweredAndroidAduioIO for record microphone and at callback deal with audio mix.

Now I can mix microphone and music into single file, But I meet an issue. I found after mix file's volume is lower than SuperpoweredAdvanceAudioPlayer play. I adjust SuperpoweredAdvanceAudioPlayer->process method the fouth params to control volume, but meet the same situation. SuperpoweredAdvanceAudioPlayer volume is lower, but mixed file audio is lower than  SuperpoweredAdvanceAudioPlayer play.

can I reduce SuperpoweredAdvancedAudioPlayer volume to meet mix file's volume? which method can do this function? 

Here is my code , if my code have issue, please let me know, thanks a lot.

initialize SuperpoweredAndroidAudioIO and SuperpoweredAdvancedAudioPlayer object
  

    songVolume = songValue;
    sIsDefaultFlowOn = isDefaultFlowOn;
    sIsAudioOutputSamplesCalculated = false;
    sIsSavedWithFX = false;

    mSavePath = new char [strlen(saveFolder) + strlen(songName) + 1];
    mSongPath = new char [strlen(songPath) + strlen(songName) + 1];

    Utils::prepareNewPath(mSavePath, saveFolder, songName);
    Utils::prepareNewPath(mSongPath, songPath, "");

    sFirstBuffer = new float [CHANNELS_NUMBER * mBufferSize + 128];
    sSecondBuffer = new float [CHANNELS_NUMBER * mBufferSize + 128];
    sFinalBuffer = new float [CHANNELS_NUMBER * mBufferSize + 128];

    sAudioInput = new SuperpoweredAndroidAudioIO(mSampleRate, mBufferSize, true, true,
                                                 recordAudioProcessing,
                                                 NULL,
                                                 -1,
                                                 -1,
                                                 mBufferSize * CHANNELS_NUMBER);
    sAudioInput->stop();

    sAudioOutput = new SuperpoweredAndroidAudioIO(mSampleRate, mBufferSize, false, true,
                                                  outputAudioProcessing,
                                                  NULL,
                                                  -1,
                                                  -1,
                                                  mBufferSize * CHANNELS_NUMBER);
    sAudioOutput->stop();

    sVoicePlayer = new SuperpoweredAdvancedAudioPlayer(NULL, audioPlayEvents, mSampleRate, 0);
    sSongPlayer = new SuperpoweredAdvancedAudioPlayer(NULL, audioPlayEvents, mSampleRate, 0);

    mFXManager = new FXManager(mSampleRate);`

SuperpoweredAndroidAudioIO  mix mic and background callback 

    if (sSongPlayer->process(sFirstBuffer, false, numberOfSamples, 1.0f)) {

        SuperpoweredShortIntToFloat(audioInput, sSecondBuffer, numberOfSamples);
        fwrite(audioInput, sizeof(short int), numberOfSamples * CHANNELS_NUMBER, sFile);
        SuperpoweredFloatToShortInt(sFirstBuffer, audioInput, numberOfSamples);
        return true;
    } else {
        return false;
    }

SuperpoweredAndroidAudioIO play callback

    if (sVoicePlayer->process(sFirstBuffer, false, numberOfSamples)) {
        if (sSongPlayer->playing) {
        if (sSongPlayer->process(sSecondBuffer, false, numberOfSamples, 1.0f )) {
                if (sIsDefaultFlowOn) {
                    SuperpoweredCrossMono(sFirstBuffer, sSecondBuffer, sFinalBuffer,
                                          1.0f, 1.0f,
                                          1.0f, 1.0f,
                                          sNumberOfSamplesAudioOutput);
                    FXManager::processAllFX(sFinalBuffer, numberOfSamples);
                }
            } else {
                return false;
            }
        } else {
            FXManager::processAllFX(sFirstBuffer, numberOfSamples);
        }
        SuperpoweredFloatToShortInt(sSongPlayer->playing ?
                                    sFinalBuffer : sFirstBuffer,
                                    audioOutput, numberOfSamples);
        return true;
    } else {
        return false;
    }

**Comment by superpoweredSDK** [comment]
I don't see any point in your code which changes volume. Please measure how big is the volume difference, it could help where the problem is.

Please note, never use fwrite in an audio processing callback. Disk operations may be too slow, resulting in audio glitches. Use SuperpoweredRecorder for this.

**Comment by falll2000** [comment]
thanks for your advice. I have finish mix mic and background music using SuperpoweredAndroidAudioIO for record mic & SuperpoweredStereoMixer & SuperpoweredRecorder and work well. 👍

**Comment by RockyLin** [comment]
@falll2000 Hi, there!
I'm trying to implement a function like karaoke on Android, to record voice audio while playing music. But sometimes the music is louder than the voice, so I almost can't hear the speaker, is there a way to lower the volume of the music by code without messing the voice? Thanks a lot !
