### ISSUE TITLE
Option to use existing gradle-plugin

### ISSUE THREAD

**Issue by leechunhoe** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#140]
I am attempting to integrate Superpowered SDK into an existing Android application.
Due to the fact that it is using gradle-experimental-plugin, it causes some issues with gradle of local library modules. Can I have an easy option of implementation using conventional gradle-plugin (with Android.mk and Application.mk for NDK integration) instead? A sample Android app would be good.

**Comment by superpoweredSDK** [comment]
Please check the older versions of this SDK, like this: https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/blob/6a7b93a36b25b5718a9deb54bc6abeb274c0c679/Android/CrossExample/app/src/main/jni/Android.mk
