### ISSUE TITLE
decoder, stereo / mono?

### ISSUE THREAD

**Issue by iamyellow** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#141]
hi! i'm starting to work w/ your SDK and so far so (very) good. I was able to fill an AudioBufferList in an AudioUnit input callback like this:
decode to short int buffer  > SuperpoweredShortIntToFloat to float buffer > SuperpoweredDeInterleave to mData of each channel from the float buffer. 
My question is: since w/ mono files the flow changes a bit (no need to deinterleaving), how could I know if the wav file is stereo or mono? I inspected the docs but I wasn't able to find anything. I must say I'm really a newbie in audio stuff, and sometimes I'm still a bit confused w/ some terms (frames, samples, sample frames...)  so hope don't bother you if it seems a really basic question. A hunch tells me that with decoder->samplesPerFrame, decoder->samplerate and some very basic maths I should know it. e.g. my wav is stereo and I'm getting 1024 samplesPerFrame (44100 samplerate). If it were mono, maybe I should get 512?

thanks in advance!

**Comment by svenoaks** [comment]
I'm pretty sure the decoder resamples it to 16-bit stereo interleaved with varying sample rate no matter what.

**Comment by superpoweredSDK** [comment]
The SuperpoweredDecoder will always emit stereo audio, even for mono sources.

**Comment by weepy** [comment]
it would be nice to indicate the number of channels on the source.
