### ISSUE TITLE
Can find some file when run the Demo in Android Studio

### ISSUE THREAD

**Issue by d9x2knv7** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#142]
![image](https://cloud.githubusercontent.com/assets/19966125/16410504/5f75434a-3d55-11e6-8036-4e30d9b8bfb5.png)

Hi, the photo shows when I open in the Android Studio, I can not run this Demo because I can not find those document, how can I solve this problem?
Than you!

**Comment by superpoweredSDK** [comment]
Set the correct path in local.properties please, as it's advised in both the project and the readme.
