### ISSUE TITLE
Audio output -  wireless device

### ISSUE THREAD

**Issue by Dhvanitp** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#143]
Is there a way I can route the audio output to a bluetooth speakers or headphones?

**Comment by superpoweredSDK** [comment]
On iOS yes, but Android doesn't offer a reliable way for this.

**Comment by Dhvanitp** [comment]
Can you point me in the direction to implement it in iOS ?
how can i use superpowered for that?
