### ISSUE TITLE
Is there something similar to OpenSLES SL_PLAYEVENT_HEADATEND.

### ISSUE THREAD

**Issue by chandraprakash5** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#144]
I have a playlist of songs stored on the device. I want to automatically start playing the next song once the first song ends. I was using OpenSLES where they provide SL_PLAYEVENT_HEADATEND event to suggest that the sound has been processed. I am currently trying to replace OpenSLES with Superpowered Advanced Audio Player. How can I implement the above functionality with superpowered?

**Comment by superpoweredSDK** [comment]
Yes, please check the CrossExample project, which handles the SuperpoweredAdvancedAudioPlayerEvent_EOF event.
EOF means "end of file".

**Comment by chandraprakash5** [comment]
I have already seen the CrossExample project. SuperpoweredAdvancedAudioPlayerEvent_EOF Event has been used nowhere in the project. Please update the code if you intend to use it. Also, there is no mention of this event in the documentation. Please update your docs. Its very painful to keep searching for each and every event.
