### ISSUE TITLE
audio level

### ISSUE THREAD

**Issue by Dhvanitp** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#145]
Hello,
I would like to know if there is a way I could calculate the decibels for creating a "audio level meter" in real time for a player ?
Or is there any other way of achieving it using superpowered ?

Thank you.

**Comment by superpoweredSDK** [comment]
Use the SuperpoweredPeak function. 20.0f * log10f(value) will provide you decibels.
