### ISSUE TITLE
Unpredictable Behavior of Audio Effects on Moto G (1st Gen)

### ISSUE THREAD

**Issue by shivamsingh** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#147]
Hi,
So I've implemented a system which takes an unprocessed WAV file as its input, processes it real-time using a cascade of Superpowered FX libraries and plays back the output.
FX used:
SuperpoweredFilter,Reverb,Echo, Flanger.
The user is allowed to choose between presets, each one having a different combination of FX.
This system works fine on most of our test devices (Nexus 5, Moto G 3rd Gen, Micromaxx Yuphoria) but when I test it on 2 different Moto G 1st Gen handsets the behavior is unpredictable and unusual.
If I simply play back one preset it seems to work okay but as I switch between presets having different reverb/echo objects one of 4 things happens:
1) App crashes
2) Extremely loud Static Noise (either constant or decaying as per reverb time of preset)
3) Silence
4) Preset change works as expected (50% of the time)

Could you please shed some light on what exactly could be at play here? In particular why it plagues only one device model.. I'd be very grateful.
The audio buffer size is 1920 samples which is what is natively supported by this device.
Here's how the preset code looks.

bool nonePreset = false;

    switch(preset)
    {
        case a:

            nonePreset = true;
            break;

        case b:

            parametric1->enable(true);
            lowShelf->process(input, input, numberOfSamples);
            parametric1->process(input, input, numberOfSamples);
            hiShelf->process(input, output, numberOfSamples);
            break;

        case c:

            lowShelf->process(input, input, numberOfSamples);
            hiShelf->process(input, input, numberOfSamples);
            reverbOne->process(input, output, numberOfSamples);
            break;

        case d:

            lowShelf->process(input, input, numberOfSamples);
            parametric1->process(input, input, numberOfSamples);
            hiShelf->process(input, input, numberOfSamples);
            reverbTwo->process(input, output, numberOfSamples);
            break;

        case e:

            lowShelf->process(input, input, numberOfSamples);
            parametric2->process(input, input, numberOfSamples);
            hiShelf->process(input, input, numberOfSamples);
            reverbTwo->process(input, output, numberOfSamples);
            break;
        case f:

            lowShelf->process(input, input, numberOfSamples);
            parametric1->process(input, input, numberOfSamples);
            hiShelf->process(input, input, numberOfSamples);
            hiShelf->process(input, input, numberOfSamples);
            flanger->process(input, input, numberOfSamples);
            reverbThree->process(input, output, numberOfSamples);
            break;

        case g:

            lowShelf->process(input, input, numberOfSamples);
            lowShelf->process(input, input, numberOfSamples);
            parametric1->process(input, input, numberOfSamples);
            hiShelf->process(input, input, numberOfSamples);
            reverbFour->process(input, output, numberOfSamples);
            break;

        case h:

            lowShelf->process(input, input, numberOfSamples);
            parametric2->process(input, input, numberOfSamples);
            parametric2->process(input, input, numberOfSamples);
            hiShelf->process(input, input, numberOfSamples);
            echo->process(input, output, numberOfSamples);
            break;

        case i:

            break;

        case j:

            lowShelf->process(input, input, numberOfSamples);
            parametric1->process(input, input, numberOfSamples);
            parametric2->process(input, input, numberOfSamples);
            hiShelf->process(input, input, numberOfSamples);
            echo->process(input, input, numberOfSamples);
            reverbTwo->process(input, output, numberOfSamples);
            break;
    }

**Comment by superpoweredSDK** [comment]
Hi,

we don't provide custom code review services for free, sorry. There is nothing wrong in this code snippet though, except that you should call every effect's process() method every time, and just enable(true/false) them at a different place.
http://superpowered.com/support

**Comment by shivamsingh** [comment]
Hi,

Thanks for the prompt reply. Though I wasn't asking you to review my code, so sorry if you misunderstood that bit. If you read my post carefully I was more interested in the cause of the aforementioned issues with preset processing, and I'd like to know if there are any known bugs associated with using such a large buffer size, for instance. I'd be grateful if you could steer me in the right direction as far as that is concerned.

Cheers.

**Comment by svenoaks** [comment]
Are there segfaults in log? If I had to guess you're under allocating a
buffer somewhere for the larger buffer size.

**Comment by shivamsingh** [comment]
Yes there are. Most commonly Fatal Signal 11 (SIGSEGV). You must be right.
I forced a smaller buffer size (960), so the segmentation faults have stopped and the noise/crashes are gone. But the audio now has a slight grainy noise during some of the heavier presets. Any solution to that?

**Comment by svenoaks** [comment]
Not using native buffer size can cause static for sure, use native size and
fix the size of your other buffers to match.

**Comment by shivamsingh** [comment]
Thanks for that info.
I don't mean to nag but I just want to understand this correctly. 
Here's the part where memory is allocated. Buffer size adheres to the requirement of the Superpowered audio player (as per documentation). Or am I missing something else?
framesPerBuffer is the native buffer size in samples.

audioSystem = new SuperpoweredAndroidAudioIO(sampleRate, framesPerBuffer, true, true,
                                                     audioProcessing, this, -1, SL_ANDROID_STREAM_MEDIA,
                                                     2*framesPerBuffer);
    stereoBufferSize = (framesPerBuffer + 16) * sizeof(float) * 2;
    stereoBuffer = (float *) memalign(16, stereoBufferSize);    
    reverbBuffer = (float *) memalign(16, stereoBufferSize);

**Comment by svenoaks** [comment]
Try a larger multiple and see what happens. I remember sometimes finding the minimum requirements by Superpowered to be too low. It can't hurt, just use tiny amount of memory more.
