### ISSUE TITLE
Missing OpenSLES definitions from SuperpoweredAndroidAudioIO.cpp 

### ISSUE THREAD

**Issue by jasoncopp** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#148]
I'm using this library in a manner than requires the AndroidIO cpp file to be compiled before my project (due to gradle constraints.) There are three references to definitions that are in the SuperpoweredAndroidAudioIO.cpp file:

SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION
SL_ANDROID_KEY_RECORDING_PRESET
SL_ANDROID_KEY_STREAM_TYPE

that are defined in SLES/OpenSLES_AndroidConfiguration.h. In your examples, the source includes this, but I can't do it this way so I've included it inside SuperpoweredAndroidAudioIO.cpp itself, along side the pre-existing SLES includes.

Could you add to that to the repo or tell me a better way to handle this?

**Comment by jasoncopp** [comment]
#include "OpenSLES_AndroidConfiguration.h" is inside OpenSLES_Android.h but my compiler misses it.. dunno why. But I see you've included this in the example app too, so I assume there's a silly detail causing it.

**Comment by superpoweredSDK** [comment]
I have no idea why you have this problem. Some path problem can it be, such as having a space in one of your paths can easily freak Android Studio's build system.

**Comment by svenoaks** [comment]
this happens to me too in the new version. `#include <SLES/OpenSLES_AndroidConfiguration.h> `should be in SuperpoweredAndroidAudioIO.cpp for it to work. Where is it included otherwise?
