### ISSUE TITLE
SuperpoweredDecoder does not detect EOF for wav/aiff files.

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#149]
[1a.aiff.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/366956/1a.aiff.zip)

SuperpoweredDecoder decode() never returns SUPERPOWEREDDECODER_EOF for most if not all wav or aiff files I have tested, it just keeps returning SUPERPOWEREDDECODER_OK with nothing decoded eternally at the end of the file. I attached one that does this.

Checking `if (decoder->samplePosition >= decoder->durationSamples)` seems to be a work-around, I also checked if  || samples decoded < 1, but it seems I have seen it decode 0 once in the middle of the file in some rare instances after seeking.

What is the 100% way to check EOF until it can be fixed?

**Comment by hohob28** [comment]
I am having the same issue

**Comment by svenoaks** [comment]
Another question about decoder: doc states 'After a succesful open(), samplePosition and duration may change.'

When and why would the duration change? Could it change at the beginning, middle and/or end of the file?

**Comment by superpoweredSDK** [comment]
Will investigate the attached file later this week.
Duration can change if the file is corrupted (shorter than advertised). It can happen for any kind of audio file. Happens very often for compressed formats where the last few frames may be missing. For WAV or AIFF it typically happens only if the file is truncated for some reason.

**Comment by superpoweredSDK** [comment]
Found a bug in the SDK. This happens for AIFF and WAV files only, when:

current position + the requested number of samples = duration - 1

Fix coming with the next update.

**Comment by superpoweredSDK** [comment]
Also discovered a bug in mono WAV/AIFF handling. Fix coming with the next update. Sorry for the inconvenience!

**Comment by tylerwilson** [comment]
Related to the mono WAV/AIFF bug you found: would this impact the looping of said sample? I am using 0.9.7 and found that looping a mono sound left a large audible gap. If I converted to stereo, it works perfectly.
