### ISSUE TITLE
Using Superpowered in Xcode 7 w/Swift

### ISSUE THREAD

**Issue by freak4pc** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#150]
Hey, 
I tried dragging all .h headers and `libSuperpoweredAudioIOS.a` to the app but I'm getting random errors such as : 

![image](https://cloud.githubusercontent.com/assets/605076/17058812/c441c900-502a-11e6-91f7-9609c90337e7.png)

Any ideas how to resolve this?

**Comment by superpoweredSDK** [comment]
Try to Clean, also check how Xcode recognized those header files. They should be recognized as C++ headers.

**Comment by freak4pc** [comment]
Hey, we're at different timezones so I didn't get a chance to reply... Not sure why this was closed. 

The issue was not solved. Cleaning won't solve this and all headers are set to C++ Headers
![image](https://cloud.githubusercontent.com/assets/605076/17076524/f6f5d0b6-50bc-11e6-98c4-1763b37adfbf.png)

Here's a demo project: 
[SPTest.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/379408/SPTest.zip)

**Comment by ILI4S** [comment]
@freak4pc you can't import C++ into Swift. You need to import it into Objective-C++ to wrap it into Swift.

**Comment by freak4pc** [comment]
That's a shame ... Meaning I'll have to wrap every feature in Objective-C++ and go around that? @ILI4S

**Comment by ILI4S** [comment]
@freak4pc currently, yes. It's easier than it seems though, the greatest challenge being juggling three different coding conventions in the same project.

this is just a wild guess but I estimate that Swift will support integration with C++ by Swift 5 (ie. a little over 2 years from now).
