### ISSUE TITLE
Restarting playback after EOF

### ISSUE THREAD

**Issue by tylerwilson** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#151]
I apologize if this has been asked before, but I looked and could not find it in previous issue reports.

After I receive the EOF for an active player, I set the return value to *true, to stop playbakc (if my looping flag is false of course). When I get a request to play the same sound, I try to do a seek(0) and play(false) to restart playback, but it is not working.

Should this work? If not, do I need to call open again?

**Comment by superpoweredSDK** [comment]
Your approach with seek(0), then play(false) should work. Does the player's position change after seek(0)?

**Comment by tylerwilson** [comment]
Okay, I have some additional data points. First, a short description of how I am using the library: 

I am using one instance of the AndroidAudioIO object, and one AdvancedAudioPlayer for each sound. On the audioIO callback, I call each player objects process - where it does any volume adjustments. Then I use the once Mixer instance to mix the top four player audio data.

When I receive an EOF player callback, I only set the return bool value to true or false, depending on whether my own loop flag is set. I am not making any calls into the player directly, as mentioned in the class comments.

When I get a play request for a player that has already finished, I call play(0) and seek(0) (togglePlayback works as well as play()).

I tested on the following devices, with the following results:
- Nexus 6 with Android N (API 24): plays the second time with no issues
- Android 5.0.2 (API 21) emulator: plays second time with no issues
- Samsung S3 mini with Android 4.4.4 (API 19): plays first time, but nothing after
- Android 4.4.2 (API 19) emulator: plays first time, nothing after

I put a Log message in the audioIO callback (I create the AudioIO on the first play request). During playback of the first audio, I cam getting callbacks and everything looks good. In the cases where it works, and the sound finishes, I continue to receive the audio callbacks. In the cases where trying to play the sound again fails, the audioIO callback has ceased to be called.

So, it appears this could be an Android version issue (what else is new?!), where the OpenSL system stops calling your callback (SuperpoweredAndroidAudioIO_OutputCallback), and thus stops calling my callback.

Perhaps you can run some tests on an API 19 emulator and reproduce the issue? I hope so, and I hope you do support this API level. (Our app is a BLE app, so we support API 18+).

Hope this is helpful to you and others.

**Comment by superpoweredSDK** [comment]
Superpowered is not a wrapper around OpenSL ES. The SuperpoweredAdvancedAudioPlayer, and every other Superpowered feature is fully implemented.
Do you call play first and seek second, or seek first and play second?

**Comment by tylerwilson** [comment]
I understand that Superpowered is not a wrapper. I was just going by the only source I can see, which is SuperpoweredAndroidAudioIO, which is at least using OpenSL to get the finished audio data to the speakers.

I was calling play first, then seek (I had seen this in other samples, even though it seems counter-intuitive). I change the order, and no change.

As mentioned above, I am seeing different behaviors on different Android versions - audioProcessing callback not being in the broken case - and so I suspected that bit of code.

**Comment by svenoaks** [comment]
Did you check log to see if there is some kind of error in the audio
processing thread, when it stops getting called?

**Comment by tylerwilson** [comment]
I have the log on verbose, and see no messages from Superpowered (SP) or lower-level audio components. (I have seen messages previously when I get a seg fault of course, but I fixed most of those issues). Is there any kind of debug switch or mode to see more output from SP?

**Comment by tylerwilson** [comment]
Also note that I did try to call the SuperpoweredAndroidAudioIO.start() method in my play method, in case it was stopped for some reason, but it did not have any effect.

**Comment by svenoaks** [comment]
I remember AudioPlayer did all kinds of weird things near the EOF when I
made a player of it a couple of versions ago (different behaviors for
different file). I had quite a few weird workarounds to make it work right
for all files. I could share it tonight when I get home. It did work on
Android 4.4, I have a S3 mini test device too.

On Jul 29, 2016 12:16 PM, "tylerwilson" <notifications@github.com> wrote:

Also note that I did try to call the SuperpoweredAndroidAudioIO.start()
method in my play method, in case it was stopped for some reason, but it
did not have any effect.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/issues/151#issuecomment-236224318>,
or mute the thread

**Comment by superpoweredSDK** [comment]
Superpowered doesn't use AudioPlayer or any other feature offered by OpenSL ES. The only exception is the SuperpoweredAndroidAudioIO, as OpenSL ES is the only legal way to access audio input or audio output.

Do you always call the process() method of the player, every time the audio processing callback is running? It's very important.

**Comment by tylerwilson** [comment]
If the player is in my 'active' list of players, then yes, I always call the process method from within the audio callback.

Though I do remove the player from my list when I receive the EOF event, it would not call process after that point (until I add it back to my list on the next play request). Do you expect the process to be called even after getting the EOF event? If so, that would be an issue.

**Comment by superpoweredSDK** [comment]
Always call the process() method, that was the problem. The process() method handles a lot of things, such as an internal lockless message queue. If you don't call process(), then messages (such as play and seek) may not be processed.

**Comment by tylerwilson** [comment]
Okay, just to confirm: I modified my code so that it continues to call process even after the EOF, and it is all good now. :-) 

Thank you very much for your assistance.
