### ISSUE TITLE
Feature Request: fade out on pause

### ISSUE THREAD

**Issue by tylerwilson** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#152]
There is a decelerate option on the pause function, but it results in an odd audio effect (to my ears). What I would like as an option is to have a simple volume fade to 0 over some number of seconds/milliseconds. And as a great bonus would be a notification when the volume reaches the target value, so that I know when I can clean up the player and associated resources.

**Comment by superpoweredSDK** [comment]
Thank you for the feature request. You are the first requesting for this. We will implement if there is a significant interest.
When SuperpoweredAdvancedAudioPlayer stops, there is a 64 samples long fade currently. You can implement this feature with your custom code, gradually decreasing the volume parameter of SuperpoweredAdvancedAudioPlayer's process() method, then calling pause when it reaches 0.
