### ISSUE TITLE
SuperpoweredTimeStretching gives out more samples than was given 

### ISSUE THREAD

**Issue by 2RKowski** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#153]
I tried to tinker your offline processing example to my needs. I try to pitch shift an array of int16_t's with length of 320 (sample rate 320k). But after I process it with SuperpoweredTimeStretching, it gives me 512 samples, which I cannot apply to my original array of 320 samples. Am I missing something?
Here's the code:
http://pastebin.com/72AZnnLL

**Comment by superpoweredSDK** [comment]
SuperpoweredTimeStretching works in the frequency domain, which has a much different temporal resolution. Depending on the current rate setting, the internal overlapping and step factors, the number of output samples can be wildly different.
