### ISSUE TITLE
Multiple songs playing after long sleep or when application enters from background to foreground

### ISSUE THREAD

**Issue by tush010** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#154]
I have used Superpowered SDK for iOS in my iPhone application which is primarily a music app with loads of features. The problem I am facing is that whenever I return to the application from background or from long sleep , I find another song plays randomly and hence I end up with multiple songs playing at a single go.

The reason for this I probably feel is that the instance of Superpowered.h class is created several times at different places in the application. To avoid this I tried to convert the Superpowered.h class into a singleton class so that no more than 1 object it can hold , but the entire application stopped working after doing that and the superpowered player wasn’t able to play any song in either way.

**Comment by superpoweredSDK** [comment]
This is not an issue of the Superpowered SDK, but your custom code. Please check our response via email.
