### ISSUE TITLE
Need mixer example for android

### ISSUE THREAD

**Issue by gnivsarkar007** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#155]
We have been trying to mix raw audio data from two sources.We have tried to mould the existing examples to our need but have failed so far,with no luck.The common error we are having is a
" A/libc(23631): Fatal signal 11 (SIGSEGV)" ,
so would it be possible to provide an example that we can refer to for mixing?
Thanks.

**Comment by superpoweredSDK** [comment]
The error you get is invalid memory access. Perhaps you provide NULL somewhere for an audio buffer. We have no plans for further examples yet, sorry for that.
