### ISSUE TITLE
Weird sound then no sound for a while

### ISSUE THREAD

**Issue by hohob28** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#156]
When I play a local MP3 file (short sound around 0.5~1s), sometimes, it happens randomly. The sound becomes weird for 0.1s and cannot play any sound for a period of time. Then, it comes back again. 
Here is a brief how I code for playing sound after initialization:
1. Open mp3 file with 
void open(const char *path, char **customHTTPHeaders = 0, int stemsIndex = 0);
2. Start SuperpoweredIOSAudioIO
3. Play mp3 with the player
4. When encounter an EOF event, I call pause() and then stop SuperpoweredIOSAudioIO

As there is no pattern of the above case, I am writing to ask about it. 

PS. other mp3 files are with the same behaviour, sometimes, it happens when the first time I play after app launched and sometimes it is after hundreds of times.

**Comment by superpoweredSDK** [comment]
When you receive the EOF event, the void * parameter is a pointer to a bool. Set it to false, and read SuperpoweredAdvancedAudioPlayer.h for docs.
Always call the player's process() method.
Don't forget to handle the case when player process() returns false.
Return with the appropriate silence value from your audio processing callback.

**Comment by hohob28** [comment]
@param value A pointer to a stemsInfo structure or NULL for LoadSuccess (you take ownership over the strings). (const char *) for LoadError, pointing to the error message. (double *) for JogParameter in the range of 0.0 to 1.0. (bool *) for EOF, set it to true to pause playback. Don't call this instance's methods from an EOF event callback!

It just mentions the value of true, but no description for value of false. May I know what will happen if it is set to false? Is it the inverse of setting to true?

Thank you.
