### ISSUE TITLE
[Q/A] How to play a mp3 file from internet?

### ISSUE THREAD

**Issue by hnvn** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#157]
Can I use SuperpoweredSDK to play a mp3 file from internet like MediaPlayer of AndroidSDK (just pass a uri to)?

**Comment by superpoweredSDK** [comment]
The Superpowered SDK doesn't support that yet. You need to download the mp3 file first, or embed it into an HLS stream.
