### ISSUE TITLE
Process Channels while playing

### ISSUE THREAD

**Issue by ziad-halabi9** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#158]
Hey SuperpoweredPeople!

I am trying to process an audio file, split its channels, modify one channel, the add them together and make them mono and play them. I want to make the inverse of one channel. And to do so, I loop over its buffer array and take the negative of the values. The whole process works and I get the expected results when I do it using a decoder and save it to a file. However if I do it on the fly, the audio stutters. I would like to have the option to turn on this feature at any point while playing an audio. Can this be achieved on the fly? Thanks!

Here's the process function:
(PS: if I comment the for loop out, I get mono audio without stutter)

```
bool SuperpoweredPlayer::process(short int *output, unsigned int numberOfSamples) {
    
    bool silence = !audioPlayer->process(stereoBuffer, false, numberOfSamples, 1.0, 0.0f, -1.0);

    if (!silence) {
        if (optionTurnedON) {
            SuperpoweredDeInterleave(stereoBuffer, leftBuffer, rightBuffer, 2 * numOfSamples);
            for (int i = 0; i < bufferSize ; i++) {
                rightBuffer[i] = rightBuffer[i] + (-leftBuffer[i]);
            }
            SuperpoweredInterleave(rightBuffer, rightBuffer, stereoBuffer, 4 * numOfSamples);
            SuperpoweredFloatToShortInt(stereoBuffer, output, numberOfSamples);
        }else {
            SuperpoweredFloatToShortInt(stereoBuffer, output, numberOfSamples);
        }
    }

    return !silence;
}
```

**Comment by superpoweredSDK** [comment]
- Call SuperpoweredDeInterleave with numberOfSamples, not 2x numberOfSamples.
- Call SuperpoweredInterleave with numberOfSamples, not 4x numberOfSamples.
- Process the buffers with numberOfSamples and not "bufferSize".
- As you process leftBuffer and rightBuffer with a "non-Superpowered" function and you both need SuperpoweredDeInterleave and SuperpoweredInterleave, a faster approach would be to do this completely with your own code. Such as:

float *buf = stereoBuffer;
for (int i = 0; i < numberOfSamples; i++) {
 float value = buf[1] - buf[0];
 *buf++ = value;
 *buf++ = value;
}
