### ISSUE TITLE
Commitment of .DS_Store?

### ISSUE THREAD

**Issue by jasoncopp** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#160]
In the last commit for 0.9.9 you committed all the .DS_Store files and other workspace files.. Not sure if you meant to or not but thought I'd mention it.

**Comment by superpoweredSDK** [comment]
Happens every time. We use a Mac. :-)

**Comment by jasoncopp** [comment]
I know, I am too, but you'd never committed those files before (and there is no point to) so I thought it may have been by accident. .DS_Store was normally in the gitignore, like you had added in 0.9.8 for the USB example code. It makes the commit a bit of a mess and introduces a unnecessary file load on a PC.
