### ISSUE TITLE
#include <SLES/OpenSLES_AndroidConfiguration.h>

### ISSUE THREAD

**Issue by jasoncopp** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#161]
You've removed this from the SuperpoweredAndroidAudioIO.cpp file again, but myself (and others) have noted that even though this is included in OpenSLES_Android.h, some identifiers such as SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION aren't declared unless OpenSLES_AndroidConfiguration.h is specifically included in SuperpoweredAndroidAudioIO.cpp.

**Comment by superpoweredSDK** [comment]
SuperpoweredAndroidAudioIO compiles happily without the include. In what configuration it doesn't for you?

**Comment by jasoncopp** [comment]
Right out of the box, the default configuration doesn't work. Compiling the examples fails on SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION not being declared.

There've been a couple other people with this problem, if you recall / look back in the issues. Keeping the OpenSLES_AndroidConfiguration header doesn't hurt anything so if possible, keeping it in place would help.

**Comment by superpoweredSDK** [comment]
It works for most developers. I wonder which Android Studio version are you using?

**Comment by jasoncopp** [comment]
2.2RC, but it has always done it with my machine from 2.1 on. I'm using ndkBuild:

externalNativeBuild {
            ndkBuild {
                arguments "NDK_APPLICATION_MK:=Application.mk"
                cFlags "-O3", "-fsigned-char"
                cppFlags "-fsigned-char", "-Ilibs"
                abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
            }
        }

Here's my application make.

NDK_TOOLCHAIN_VERSION := clang
APP_OPTIM := debug
#APP_OPTIM := release
APP_STL:=stlport_static

I'm using a hybrid app with Ionic2 so I was forced to use externalNativeBuild from the get-go.

CMake with 2.2 is a change I'm looking forward to, if you go that route.

**Comment by jasoncopp** [comment]
(To be clear, it *shouldn't* behave this way; obviously something in Studio is wonky, but as it doesn't hurt anything for now, at least people can find the solution here in the issue report.)

**Comment by jasoncopp** [comment]
I should have given you my Android.mk file too, here it is:

```
LOCAL_PATH := $(call my-dir)
SUPERPOWERED_PATH = libs/Superpowered

include $(CLEAR_VARS)
LOCAL_MODULE := Superpowered
ifeq ($(TARGET_ARCH_ABI),armeabi-v7a)
	LOCAL_SRC_FILES := $(SUPERPOWERED_PATH)/libSuperpoweredAndroidARM.a
else
	ifeq ($(TARGET_ARCH_ABI),arm64-v8a)
		LOCAL_SRC_FILES := $(SUPERPOWERED_PATH)/libSuperpoweredAndroidARM64.a
	else
		ifeq ($(TARGET_ARCH_ABI),x86_64)
			LOCAL_SRC_FILES := $(SUPERPOWERED_PATH)/libSuperpoweredAndroidX86_64.a
		else
			LOCAL_SRC_FILES := $(SUPERPOWERED_PATH)/libSuperpoweredAndroidX86.a
		endif
	endif
endif
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE    := AudioEngine
LOCAL_C_INCLUDES += libs
LOCAL_SRC_FILES := $(wildcard cpp/*.c*) \
libs/Superpowered/AndroidIO/SuperpoweredAndroidAudioIO.cpp
LOCAL_LDLIBS := -llog -landroid -lOpenSLES
LOCAL_STATIC_LIBRARIES := Superpowered
LOCAL_CFLAGS = -O3
include $(BUILD_SHARED_LIBRARY)
```

**Comment by superpoweredSDK** [comment]
Sure, we will put the include in the next update. The reason why it didn't work for you is your custom build environment.
