### ISSUE TITLE
Crash on android emulator when you enable mic input 

### ISSUE THREAD

**Issue by jasoncopp** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#163]
If I run this init with the mic enabled on the android emulator:

```
audioOutput = new SuperpoweredAndroidAudioIO(samplerate, buffersize, true, true,audioProcessing, this, SL_ANDROID_RECORDING_PRESET_GENERIC,SL_ANDROID_STREAM_MEDIA, buffersize * 2);
```

I get a crash here in SuperpoweredAndroidAudioIO.cpp, line 182:
```
(*internals->inputBufferQueueInterface)->RegisterCallback(internals->inputBufferQueueInterface, SuperpoweredAndroidAudioIO_InputCallback, internals);
```

The inputBufferQueueInterface is nil. I thought that maybe the emulator didn't have a mic, but sadly hasSystemFeature(PackageManager.FEATURE_MICROPHONE) returns true, so the emulator *thinks* it has a mic. Here is the code I used to work around it, but bleh, it's bad.

```
if (enableInput) { // Initialize the audio input buffer queue.
        (*internals->inputBufferQueue)->GetInterface(internals->inputBufferQueue, SL_IID_ANDROIDSIMPLEBUFFERQUEUE, &internals->inputBufferQueueInterface);
        if (internals->inputBufferQueueInterface) {
            (*internals->inputBufferQueueInterface)->RegisterCallback(internals->inputBufferQueueInterface, SuperpoweredAndroidAudioIO_InputCallback, internals);
            (*internals->inputBufferQueueInterface)->Enqueue(internals->inputBufferQueueInterface, internals->fifobuffer, (SLuint32)buffersize * 4);
        }
        else {
            internals->inputBufferQueue = NULL;
        }
    };
```

Advice? Or is this a bug? I need to be able to go back and forth from a device to an emulator. I can either use my above code or I can turn off the mic in the SuperpoweredAndroidAudioIO init when I want to use the emulator, but that doesn't seem correct.

**Comment by superpoweredSDK** [comment]
We are not interested in the Android Emulator, sorry. We have never ever run it, not even for a single second.
Your workaround is not bad, and the emulator shouldn't return NULL when hasSystemFeature reports the mic present. So this is an emulator bug.
