### ISSUE TITLE
Native Crash

### ISSUE THREAD

**Issue by fatihm85** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#165]
I get too many native crashes from some Android devices. Is there a solution for these crashes?

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/zeroltexx/zerolte:6.0.1/MMB29K/G925FXXS4DPGK:user/release-keys'
Revision: '10'
ABI: 'arm'
pid: 13146, tid: 13146, name: *****  >>> ***** <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
    r0 00000000  r1 f357aca1  r2 f4b77ba0  r3 f72436c9
    r4 ee4b8a38  r5 f7240fed  r6 f7251618  r7 f3637db4
    r8 ffabb0f4  r9 00000f00  sl 0000bb80  fp f4b77ba0
    ip ffabac2c  sp ffabb090  lr f723cfc9  pc f357b090  cpsr 600f0030

backtrace:
    #00 pc 00036090  /data/app/*******-1/lib/arm/libSuperpoweredAudio.so (_ZN26SuperpoweredAndroidAudioIOC1EiibbPFbPvPsiiES0_iii+763)
    #01 pc 0003417f  /data/app/******-1/lib/arm/libSuperpoweredAudio.so (_ZN17SuperpoweredAudioC2EiPKciii+574)
    #02 pc 000355fb  /data/app/*****-1/lib/arm/libSuperpoweredAudio.so (Java_*****_MainActivity_SuperpoweredAudio+70)
    #03 pc 00c387af  /data/app/*****-1/oat/arm/base.odex (offset 0x8bd000)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'asus/WW_a500cg/ASUS_T00F1:4.4.2/KVT49L/WW_user_2.22.40.54_20151120_16:user/release-keys'
Revision: '0'
pid: 8965, tid: 9542, name: AudioTrack  >>> ****** <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr bc0f869e
    eax 632aca9c  ebx 62e4fdbc  ecx 632acaa0  edx 632aca9b
    esi 6308ff90  edi bc0f869e
    xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
    eip 62d6c85f  ebp 632aca78  esp 632ac6b0  flags 00210282

backtrace:
    #00  pc 0006c85f  /data/app-lib/****1/libSuperpoweredAudio.so
    #01  pc 0006c81d  /data/app-lib/*****/libSuperpoweredAudio.so
    #02  pc 0005c0ce  /data/app-lib/******/libSuperpoweredAudio.so
    #03  pc 0005c87b  /data/app-lib/*****-1/libSuperpoweredAudio.so
    #04  pc 0005e71b  /data/app-lib/*****-1/libSuperpoweredAudio.so
    #05  pc 00008be8  /system/lib/libwilhelm.so
    #06  pc 0005f108  /system/lib/libmedia.so
    #07  pc 0005fdb1  /system/lib/libmedia.so
    #08  pc 00017e10  /system/lib/libutils.so
    #09  pc 00018016  /system/lib/libutils.so
    #10  pc 0001c0c2  /system/lib/libc.so
    #11  pc 0004b8f5  /system/lib/libc.so
    #12  pc 00017f1f  /system/lib/libutils.so
    #13  pc 0003472f  [anon:libc_malloc]

**Comment by superpoweredSDK** [comment]
Can't decipher these logs, sorry.
