### ISSUE TITLE
Volume fade out and Reverb

### ISSUE THREAD

**Issue by tylerwilson** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#167]
Good day,

I am having issue when I try to fade out the volume while also using reverb. It appears that the reverb is not considering the volume, and so it cuts off abruptly at the end of the sound. When I do the same with only pitch control, it sounds fine.

I am doing the following:

```
// volume is adjusted elsewhere for the fade effect
bool dataToWrite = player->process(buffer, false, numberOfSamples, volume);

if (dataToWrite && reverb != nullptr) {
    // use same buffer for in and out
    reverb->process(buffer, buffer, numberOfSamples);
}
```

Is the expected logic when handling reverb and volume changes?

Thank you.

**Comment by superpoweredSDK** [comment]
Always call reverb->process, even if you have no dataToWrite. If dataToWrite is false, set reverb's input buffer to NULL.

**Comment by tylerwilson** [comment]
Okay, I changed the logic of the code to this:

`    bool sendToOutput = player->process(stereoBuffer, false, numberOfSamples, volume);

    if (reverb != nullptr) {
        float *outputBuffer = nullptr;

        if (sendToOutput) {
            outputBuffer = stereoBuffer;
        }

        reverb->process(outputBuffer, stereoBuffer, numberOfSamples);
    }`

But it still clips at the end of the audio. Again, like the reverb is overriding the volume. So that at the end, when the volume should be 0, it is not. And we get a click at the end of the track due to the volume cutting off too quickly.

**Comment by tylerwilson** [comment]
A related question, which seems appropriate to ask here: it appears there is a kind of natural decay to the reverb effect from the time I set any dry or wet value. If so, perhaps there could be a way to know this value. Then, if I am doing a volume fade out I could synchronize with the reverb and end at the proper point to minimize any potential clicks. ?
