### ISSUE TITLE
Processing more than 1024 sample frames with SuperpoweredReverb

### ISSUE THREAD

**Issue by sclimber** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#168]
When I use the SuperpoweredReverb for processing more than 1024 sample frames at once for an Android app a SIGSEGV occurs as soon as the SuperpoweredRevern instance gets deleted. Setting 
`numberOfSamples` to 16,32,64,1008 or 1024 in the following code works fine but setting  `numberOfSamples` to 1032, 2048 or another multiple of 8 >= 1024 leads to this error message:

A/libc: invalid address or address of corrupt block 0x63647000 passed to dlfree
A/libc: Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 7148 (Thread-4888)

```cpp
SuperpoweredReverb* superpoweredReverb = new SuperpoweredReverb(44100);
superpoweredReverb->enable(true);
int numberOfSamples = 3056;
float* buffer = new float[numberOfSamples * 2] {};
superpoweredReverb->process(buffer, buffer, numberOfSamples);
delete(superpoweredReverb); //<-- error SIGSEGV
delete[](buffer);
```
Is there a limit for the buffer size when using SuperpoweredReverb not mentioned in the docs? (I didn't get this problem when using another effect like the SuperpoweredFilter.)

Thanks

**Comment by superpoweredSDK** [comment]
This bug was fixed in the latest version of the SDK (0.9.9), please update.

**Comment by sclimber** [comment]
Thanks for your fast reply but this error happens also using the latest version (0.9.9). Is this bug really fixed?

**Comment by superpoweredSDK** [comment]
Perhaps the fix did not make it until the release. Meanwhile, just process in <= 1024 chunks.
