### ISSUE TITLE
How to mix a track and export it to a file

### ISSUE THREAD

**Issue by ditimtriky** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#17]
Hi!
I want to change pitch of a track and save result into a file (like add baby-effect into a music).
I can change pitch, it's so easy with SupperPoweredSDK but I don't know how to export.
Can SupperPoweredSDK do that?

Thanks

**Comment by superpoweredSDK** [comment]
Please check the offline processing example project, which saves the result into WAV.
