### ISSUE TITLE
Stop fooling us!

### ISSUE THREAD

**Issue by geek-paulwong** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#171]
Does this SDK support recording sound while playing background music, like Karaoke, for Android? You promise all these features on the website, but do not even provide (decent) examples.

Please stop fooling us, and just simply tell us that this SDK is not going anywhere for Karaoke apps.

**Comment by superpoweredSDK** [comment]
Yes, this SDK supports recording sound while playing background music. The SuperpoweredRecorder and the SuperpoweredAdvancedAudioPlayer classes can be used for this for example.
We are not able to provide an example for every use case (= writing the app for you), as Superpowered offers many features. Several Karaoke apps are using Superpowered, such as Voloco.

**Comment by geek-paulwong** [comment]
Oh, ok, thank you! ;)
