### ISSUE TITLE
Error:(8, 45) SuperpoweredAdvancedAudioPlayer.h: No such file or directory

### ISSUE THREAD

**Issue by RockyLin** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#172]
Nexus5x, 6.1

After importing the "CrossExample" in the Android fold, encountered this problem trying to run this application.

I think the problem is the superpowered SDK is not included. 

So, I add "superpowered.dir=/Users/rockylin/Documents/GitHubAndroid/Low-Latency-Android-Audio-iOS-Audio-Engine/Superpowered" in local.properties, and get more errors below:
![Uploading Screen Shot 2016-10-04 at 8.20.01 PM.png…]()

**Comment by superpoweredSDK** [comment]
screenshot?

**Comment by RockyLin** [comment]
@superpoweredSDK sreenshot
[https://www.dropbox.com/s/rf66zde7h2fxw3i/Screen%20Shot%202016-10-04%20at%208.20.01%20PM.png?dl=0](url)

**Comment by RockyLin** [comment]
![screen shot 2016-10-04 at 8 20 01 pm](https://cloud.githubusercontent.com/assets/6820710/19096610/5837f76c-8ad0-11e6-94de-edc6309dd211.png)

**Comment by superpoweredSDK** [comment]
You have a path problem. "Multiple definition of..." Perhaps you copied one of the Superpowered header files into another place in your paths, so it exists in two instances.

**Comment by RockyLin** [comment]
@superpoweredSDK I redownloaded the sample and SDK, repeated the steps, problem solved. Thanks a lot!
