### ISSUE TITLE
App rejection for microphone usage

### ISSUE THREAD

**Issue by namannik** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#174]
My app binary was recently rejected, with the following message in an automatically-generated e-mail:

> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.

My app doesn't actually use the microphone, and I can't figure out what API call has triggered this rejection.  I contacted Apple support, and they haven't been very helpful so far.  Is there anything in the Superpowered SDK that might have triggered this?

**Comment by superpoweredSDK** [comment]
It can happen if you are using the SuperpoweredIOSAudioIO class for audio I/O, and initializing it with an audio session category involving audio input (such as AVAudioSessionCategoryPlayAndRecord).

**Comment by namannik** [comment]
I'm only using `AVAudioSessionCategoryPlayback`.  I have a feeling that this rejection was triggered by the usage of some specific API be used in SuperpoweredIOSAudioIO, even though my app is not using the microphone.  I will experiment with removing portions of SuperpoweredIOSAudioIO that my app doesn't need to see which ones are triggering the rejection.

**Comment by namannik** [comment]
After submitting several builds, I found that the APIs related to requesting permission to the microphone are what triggered the binary rejection.

**Comment by pabitra-moonfrog** [comment]
@namannik : could you please let us know, what API's on triggering requested for microphone permission, and what to do to avoid app rejection.. !!

**Comment by namannik** [comment]
The API call that caused the rejection turned out to be `requestRecordPermission`. Here's the change I made to prevent rejection:

https://github.com/heartv/Low-Latency-Android-Audio-iOS-Audio-Engine/commit/1e7b4dddafc093b0bd1cf3d3b2dde71cc24e179a

**Comment by namannik** [comment]
I should add a fix for this issue was incorporated into Superpowered.  In `SuperpoweredIOSAudioIO.mm`, change:

`#define USES_AUDIO_INPUT 1`

to:

`#define USES_AUDIO_INPUT 0`

This is the line that needs to be changed:

https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/blob/master/Superpowered/SuperpoweredIOSAudioIO.mm#L16

**Comment by pabitra-moonfrog** [comment]
Thanks a ton for responding quickly @namannik 
your support helped us a lot.
