### ISSUE TITLE
Superpowered as alternative to Soundpool

### ISSUE THREAD

**Issue by ziad-halabi9** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#175]
I want to use Superpowered as an alternative to Soundpool since Superpowered has better latency. I am interested to know what is the best practice to have multiple sounds playing from different inputs and may be at the same time. For instance, say we 5 buttons. Each button plays a sound. 5 buttons can be clicked at the same time. Thank you.

**Comment by superpoweredSDK** [comment]
Use 5 instances of SuperpoweredAdvancedAudioPlayer.
