### ISSUE TITLE
iPhone 6s and sample rate issue

### ISSUE THREAD

**Issue by mobinzk** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#177]
I am developing an app using AdvancedAudioPlayer and when I load the track which has sample rate of 44100 and set the same sample rate for SuperpoweredAdvancedAudioPlayer and output.
Then the track is out of tune when I listen to it on iPhone 6s (without headphone) but it's fine with headphone.
Do you have any advice on this?

**Comment by marafat** [comment]
The speaker on the iPhone 6s can only work with 48K sampling rate. You need to do sampling rate conversion.

**Comment by mobinzk** [comment]
Thanks for your help, could you please give me some direction how I can do sampling rate conversion?

**Comment by marafat** [comment]
I haven't used it before, but check `SuperpoweredResampler`.

**Comment by superpoweredSDK** [comment]
You need to set the sample rate of SuperpoweredAdvancedAudioPlayer to the current sample rate of your device (and not the sample rate of the file being playing).
Many Superpowered features have a setSamplerate method for this purpose.

**Comment by superpoweredSDK** [comment]
Oh, and you can find an example in the cross example project, where it sets the sample rate in the audio processing callback.

**Comment by mobinzk** [comment]
Thanks a lot, solved my problem by re-setting the sample rate in audioProcessing.

**Comment by kristijanzrno** [comment]
@marafat Will the 48k samplerate work fine on the devices older than the 6s? As I've seen the samplerate on them is not jammed at 48k and is adjustable so it should work, but I don't have a device to test it.

**Comment by marafat** [comment]
@kristijanzrno it has been a while since I worked on that project, so I can't give a good answer. If it is important to you and your app's consumers, then I think it is worth it buy a phone and test.
