### ISSUE TITLE
Windowing function on FFT

### ISSUE THREAD

**Issue by nevosegal** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#178]
You mention [here](http://superpowered.com/docs/class_superpowered_frequency_domain.html) that a hanning window is applied prior to the Fourier Transform. Can you please confirm that this is indeed the case? If so, is there a boolean to toggle this ON/OFF? Also, is it possible to use other windowing functions (blackman, hamming etc.)?

**Comment by superpoweredSDK** [comment]
It applies for the SuperpoweredFrequencyDomain class only. It can not be turned off and it's a Hanning window only.
If you need custom stuff, use the SuperpoweredFFT functions here: http://superpowered.com/docs/_superpowered_f_f_t_8h.html
