### ISSUE TITLE
Issue for playing 4 tracks at the same time

### ISSUE THREAD

**Issue by mobinzk** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#179]
I've used the SuperpoweredCrossExample to play 4 tracks (with the same length) together but when I'm printing out the positionMs of each player. Sometimes (When I seek forward) they go out of time and first player is differ from last player. Any suggestion why that's happening?
I only need to play them all together.

The positionMS for each player at specific time is as following:
`Player 0: 1152.698413`
`Player 1: 1175.918367  `
`Player 2: 1152.698413  `
`Player 3: 1164.308390`

Thanks in advanced.

**Comment by palad1** [comment]
Feature request: ability to track each player at the (resampled) frame level would be awesome

> Sent from my iPhone

**Comment by mobinzk** [comment]
@palad1 Is that means superpowered is not capable of playing 4 tracks at the same time?

**Comment by palad1** [comment]
I play up to 20 tracks without issues. Use the beat feature to synchronise start. If you need more control it gets tricky as you need to approximate with durations (in my case everything starts at the same time but I want to add variable-length silence before looping)

> Sent from my iPhone

**Comment by mobinzk** [comment]
The start should be 0ms don't need to sync the beats! Also all tracks have same length!

**Comment by mobinzk** [comment]
I've created an example project that lets you to re-create the issue I'm having.
https://github.com/mobinzk/SP-Sync-issue

If you play the tracks then change tempo a few times in quick succession you should see the log times for the players go out of sync, this is easiest if you paused.

In this example we've used the sample track from cross fade so definitely the same length etc. In our actual project we have different tracks but all in the same length.

**Comment by superpoweredSDK** [comment]
@mobinzk If you have the built-in time stretcher enabled then positions will fluctuate, because the time stretcher's handling of transients. Transients are passed purely for high audio quality, and then the time stretcher compensates the difference in speed.

@palad1 Positions always try to reflect to be the closest as possible to what's coming out from the player at the moment (the buffer's first sample). Of course this will fluctuate with time stretching.

**Comment by mobinzk** [comment]
@superpoweredSDK Thanks for your respond so just to clarify we cannot play same track simoustanly without getting any delay between them?
