### ISSUE TITLE
Ogg support

### ISSUE THREAD

**Issue by rafradek** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#18]
Are there any plans to add ogg file support?

**Comment by superpoweredSDK** [comment]
Not yet, sorry. You are the first asking for this, really.

**Comment by GQAdonis** [comment]
Ogg support would be helpful for using your SDK as part of a native WebRTC implementation.  Do you guys see a way to use GStreamer along with your SDK for this purpose?

**Comment by superpoweredSDK** [comment]
We have our focus on native app development currently, no plans so far for higher level "umbrella apis".

**Comment by Zomby2D** [comment]
I am also surprised to see it's not supported yet. Since, unlike MP3, there are no licensing fees involved when using OGG, it's always my preferred file format for mobile development.

**Comment by tbaranes** [comment]
I'd love to see ogg support in superpowered, that's currently the only reason why we can't use it. Can we expect to see this anytime soon?

**Comment by superpoweredSDK** [comment]
We don't have OGG support on our roadmap. Perhaps if somebody funds it! :-)
