### ISSUE TITLE
Can't get waveform data from SuperpoweredOfflineAnalyzer from SDK for OSX

### ISSUE THREAD

**Issue by AndreasMatapolo** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#180]
Hello,

I try to get bpm, waveform and beatgrid information from the SuperpoweredOfflineAnalyzer. I get correct bpm and beatgrid values, but the waveform data is always empty. I use the OSX SDK to develop a macos application and I used examplecode from the downloaded SDK and from this community. 

In the following is my code. Do anywhere know what is wrong on my code to get waveform data?

`-(void)offlineAnalyze:(NSURL *)songurl {
    // Open the input file.
    SuperpoweredDecoder *decoder = new SuperpoweredDecoder();
    
    const char *openError = decoder->open([[songurl path] UTF8String], false, 0, 0);
    
    if (openError) {
        NSLog(@"open error: %s", openError);
        delete decoder;
        return;
    };
    
    int sampleRate = decoder->samplerate;
    double durationSeconds = decoder->durationSeconds;
    
    // Create the analyzer.
    SuperpoweredOfflineAnalyzer *analyzer = new SuperpoweredOfflineAnalyzer(sampleRate, 0, durationSeconds);
    
    // Create a buffer for the 16-bit integer samples coming from the decoder.
    short int *intBuffer = (short int *)malloc(decoder->samplesPerFrame * 2 * sizeof(short int) + 16384);
    // Create a buffer for the 32-bit floating point samples required by the effect.
    float *floatBuffer = (float *)malloc(decoder->samplesPerFrame * 2 * sizeof(float) + 1024);
    
    // Processing.
    while (true) {
        // Decode one frame. samplesDecoded will be overwritten with the actual decoded number of samples.
        unsigned int samplesDecoded = decoder->samplesPerFrame;
        if (decoder->decode(intBuffer, &samplesDecoded) == SUPERPOWEREDDECODER_ERROR) break;
        if (samplesDecoded < 1) break;
        
        // Convert the decoded PCM samples from 16-bit integer to 32-bit floating point.
        SuperpoweredShortIntToFloat(intBuffer, floatBuffer, samplesDecoded);
        
        // Submit samples to the analyzer.
        analyzer->process(floatBuffer, samplesDecoded);
        
        // Update the progress indicator.
        progress = (double)decoder->samplePosition / (double)decoder->durationSamples;
    };
    
    // Get the result.
    unsigned char *averageWaveform;
    unsigned char *lowWaveform;
    unsigned char *midWaveform;
    unsigned char *highWaveform;
    unsigned char *peakWaveform;
    unsigned char *notes;
    char *overviewWaveform;
    
    int waveformSize = 0;
    int overviewSize = 0;
    int keyIndex = 0;
    
    float loudpartsAverageDecibel = 0;
    float peakDecibel = 0;
    float bpm = 0;
    float averageDecibel = 0;
    float beatgridStartMs = 0;
    
    analyzer->getresults(&averageWaveform, &peakWaveform, &lowWaveform, &midWaveform, &highWaveform, &notes, &waveformSize, &overviewWaveform, &overviewSize, &averageDecibel, &loudpartsAverageDecibel, &peakDecibel, &bpm, &beatgridStartMs, &keyIndex);
    
    // Cleanup.
    delete decoder;
    delete analyzer;
    free(intBuffer);
    free(floatBuffer);
}`

Thanks for your help.

**Comment by superpoweredSDK** [comment]
What do you mean the waveform data is always empty? What does empty mean?

**Comment by AndreasMatapolo** [comment]
The analyzer->getresults method returns an empty string for the averageWaveform, lowWaveform, midWaveform, highWaveform and peakWaveform.

**Comment by superpoweredSDK** [comment]
The waveform data is not a string. From the documentation:

"150 points/sec waveform data displaying the average volume. Each sample is an unsigned char from 0 to 255. You take ownership on this (must free memory)."

The size of the returned data is returned in the waveformSize parameter.
