### ISSUE TITLE
Linking Superpowered to a command line tool

### ISSUE THREAD

**Issue by nevosegal** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#181]
I would like to use superpowered in a command line tool. Is that possible? I keep getting linking errors in xcode. Thanks.

**Comment by superpoweredSDK** [comment]
You mean you build a command line tool for Mac OSX? Yes, this is possible. Superpowered doesn't involve any user interface elements.

**Comment by nevosegal** [comment]
@superpoweredSDK I am getting `Undefined symbols for architecture x86_64`, which doesn't happen with other libraries I use. Any idea why this is happening?

**Comment by DocRace** [comment]
Same question. When building with libSuperpoweredAudioOSX.a for a mac command line program, getting `Undefined symbols for architecture x86_64 `
