### ISSUE TITLE
Sample rate changing Android

### ISSUE THREAD

**Issue by marafat** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#182]
@superpoweredSDK are you aware of the issue reported [here](https://goo.gl/ZWIB2a) ? Does Superpowered implements a protection against it?

**Comment by superpoweredSDK** [comment]
Looks like an S6 specific bug in the audio stack? There is no "protection" against bugs in the Android audio stack, if a manufacturer does something wrong in the audio driver or HAL...

**Comment by marafat** [comment]
Thanks for feedback...
