### ISSUE TITLE
Reverb Pre-delay workaround

### ISSUE THREAD

**Issue by shivamsingh** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#183]
Hi Superpowered,

For a while I've been wondering if it is possible to add a pre-delay to the wet component of the reverb as there's no control in the SuperpoweredReverb class to explicitly do so. Right now it sounds like it is set to zero by default, which makes any audio track sound perceptually further back. I'd like to somehow get the reverberant sound to begin about 1-60 ms after the direct excitation, to more accurately model real environments where there is a significant time gap between direct and reflected sound. Is there any workaround using Superpowered FX/functions that could allow me to do this? 
And if not, could you possibly consider making this possible in a subsequent version of the SDK?

Thanks

**Comment by superpoweredSDK** [comment]
You are the first asking for this feature, so we don't consider implementing this feature yet. You need to make a fifo or circle buffer implementation before submitting samples to reverb.
