### ISSUE TITLE
Noise and distorted sound from the input channel

### ISSUE THREAD

**Issue by romanbsd** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#185]
Good day,

I've been struggling for days now, and there's some weird problem.
If a player exists (it's enough to have one player), the audio from the microphone comes distorted and there're also some noises.
The audio track is played flawlessly. If I toggle the `loopbackEnabled` (referenced in the code below) in runtime, then the noise disappears.
The weird part, is that if I use the same code in a trivial application with one activity, then everything works as expected.

Here's the process callback:
```cpp
bool AudioAPI::process(short int *audioIO, unsigned int numberOfSamples) {
    bool hadSamples;
    // TODO
    float volA = 1.0f; // Volume for the original (first) audio track
    float volB = 1.0f; // Volume for the recording or subsequent audio tracks

    // Process input if we're recording or just passing the input to the mixer
    if (loopbackEnabled) {
        SuperpoweredShortIntToFloat(audioIO, recordBuffer, numberOfSamples);
    }

    bool producedAudio = false;
    // Mix microphone with an audio file or mix two or three players
    if (players.size() > 0) {
        unsigned int i = 0;
        float *inputs[4];
        memset(inputs, 0, sizeof(inputs));
        float inputLevels[8];
        memset(inputLevels, 0, sizeof(inputLevels));
        float outputLevels[] = {1.0f, 1.0f};
        float *outputs[] = {outputBuffer, NULL};

        if (loopbackEnabled) {
            inputLevels[i * 2] = inputLevels[i * 2 + 1] = volB;
            inputs[i++] = recordBuffer;
        }

        std::vector<PlayerTuple *>::const_iterator pi;
        for (pi = players.begin(); pi != players.end(); ++pi) {
            assert(i <= 3);
            float vol;
            hadSamples = (*pi)->process(numberOfSamples);
            if (hadSamples) {
                producedAudio = true;
                inputs[i] = (*pi)->buffer;
                inputLevels[i * 2] = inputLevels[i * 2 + 1] = volA;
                i++;
            }            
        }
        if (producedAudio) {
            mixer->process(inputs, outputs, inputLevels, outputLevels, NULL, NULL, numberOfSamples);
            SuperpoweredFloatToShortInt(outputBuffer, audioIO, numberOfSamples);
        } else {
            SuperpoweredFloatToShortInt(recordBuffer, audioIO, numberOfSamples);
        }
    } else if (loopbackEnabled) {
        SuperpoweredFloatToShortInt(recordBuffer, audioIO, numberOfSamples);
    } // else we don't modify the audioIO
    return producedAudio;
}
```

the `(*pi)->process(numberOfSamples)` simply does `player->process(buffer, false, numberOfSamples);`

All buffers are created with:
```cpp
static float *createBuffer(unsigned int bufferSize) {
    return (float *) memalign(16, (bufferSize + 16) * sizeof(float) * 2);
}
```

The io is created with:
```cpp
io = new SuperpoweredAndroidAudioIO(sampleRate, bufferSize, enableInput, enableOutput,
                                        processCallback, this,
                                        SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION,
                                        SL_ANDROID_STREAM_MEDIA, bufferSize * 2);
```
And if I try to record the recordBuffer to a file using the SuperpoweredRecorder, then the recorded file also has these artefacts and noise.

What am I doing wrong, or is there some bug in buffers handling in SuperpoweredAndrioidIO.cpp?

The sampleRate is 48000 and the bufferSize is 192.

**Comment by superpoweredSDK** [comment]
Since this is not an issue with the Superpowered SDK but your custom code, i close this. You can ask for support here: support@superpowered.zendesk.com

When loopbackEnabled == false, players.size() > 0 and producedAudio == false, the contents of recordBuffer is memory garbage or some previous content.

**Comment by romanbsd** [comment]
We're talking about the case when loopbackEnabled == true. With loopbackEnabled == false it's ok.

**Comment by romanbsd** [comment]
I added this "else" lately when trying to figure out what's the problem. Anyway, I fixed it to become `else if (loopbackEnabled) {`

**Comment by romanbsd** [comment]
Just upgraded from 0.9.9 to 1.0.0 and it seems that the problem is gone. Was there some memory corruption that was fixed?

**Comment by superpoweredSDK** [comment]
Yes, we found a very rare bug in SuperpoweredFloatToShortInt. Glad that it's solved for you.
