### ISSUE TITLE
Seeking SuperpoweredAdvancedAudioPlayer instance

### ISSUE THREAD

**Issue by iamyellow** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#186]
Hi!

I'm having a hard time trying to seeking a SuperpoweredAdvancedAudioPlayer, but first some context: I have a file with multiple samples, instead of one file per sample. For the moment, in order to test seeking and understanding how the SDK works, I'm just playing the 1st sample of the file in sequence, but seeking (`setPosition`) before `process`. The seek time before process is just the `positionMs` after `process` in the previous render cycle.
The thing is, if I'm not seeking (not setting position), the sample is playing perfectly. But as soon as I'm setting position, you can hear some clicks specially when the sample starts to play.

This render method is called always in the audio render thread, each cycle:

```
double EllSample::render(UInt32 frameCount, double ms, int pitchShiftCents, float* buffer) {
    
   // double d1 = _player->positionMs;
   double d1 = ms;
    
    _player->setPosition(ms, false, false);
    
    if (!_player->process(buffer, false, frameCount)) {
        return 0;
    }
    
    printf(">> %f vs %f\n", d1, ms);
    
    return _player->positionMs - d1;
}
```

I've tested several things and the ms parameter I'm passing render has the same value that _player->positionMs after calling its render method, and I've tested that without seeking -and printing values- and seeking.

Actually, just doing this before `process`:
```
_player->setPosition(_player->positionMs, false, false);
```
the clicks are audible!

Any clue? What am I doing wrong?

**Comment by iamyellow** [comment]
FYI, the piece of code that is executing the render method is this:

```
double ms = _samples->render(frameCount, voice->fc / (_sampleRate / 1000), voice->pitchCents, _outputBuffer);
double frames = ms * (_sampleRate / 1000);
voice->fc += frames;
```

`_sampleRate` is 41100, the audio file is a wav 24 bit @ 48000, and `voice` is just a class holding a `fc` which is a simple total frame counter.

and finally, the link with Core Audio iOS rendering:

```
float* outL = (float*)_renderAbl->mBuffers[0].mData;
float* outR = (float*)_renderAbl->mBuffers[1].mData;
SuperpoweredDeInterleave(_outputBuffer, outL, outR, frameCount);
```

**Comment by iamyellow** [comment]
ops! finally, the logs written by the `println`:

```
>> 0.000000 vs 0.000000
>> 23.208333 vs 23.208333
>> 46.416667 vs 46.416667
>> 69.625000 vs 69.625000
>> 92.833333 vs 92.833333
>> 116.041667 vs 116.041667
>> 139.250000 vs 139.250000
>> 162.458333 vs 162.458333
>> 185.645833 vs 185.645833
>> 208.854167 vs 208.854167
>> 232.062500 vs 232.062500
>> 255.270833 vs 255.270833
>> 278.458333 vs 278.458333
>> 301.666667 vs 301.666667
>> 324.854167 vs 324.854167
>> 348.062500 vs 348.062500
>> 371.270833 vs 371.270833
>> 394.479167 vs 394.479167
>> 417.666667 vs 417.666667
>> 440.875000 vs 440.875000
>> 464.083333 vs 464.083333
>> 487.291667 vs 487.291667
>> 510.500000 vs 510.500000
>> 533.708333 vs 533.708333
>> 556.895833 vs 556.895833
>> 580.083333 vs 580.083333
>> 603.270833 vs 603.270833
>> 626.458333 vs 626.458333
>> 649.645833 vs 649.645833
>> 672.833333 vs 672.833333
>> 696.020833 vs 696.020833
>> 719.229167 vs 719.229167
>> 742.437500 vs 742.437500
>> 765.645833 vs 765.645833
>> 788.854167 vs 788.854167
>> 812.062500 vs 812.062500
>> 835.270833 vs 835.270833
>> 858.479167 vs 858.479167
>> 881.687500 vs 881.687500
```

as you can see, with that approach I'm getting exactly the same `ms` as `positionMs` after calling `process`, as I said.

**Comment by superpoweredSDK** [comment]
You are performing seeking every 1024 samples, which means you seek every 1024/44.1 = 23 milliseconds. Seeking does a "crossfading" between the previous audio and the current one, but if you perform it every 0.023 second, you will hear continuous artifacts. Why do you seek in every 23 millisecond?

**Comment by iamyellow** [comment]
i'm making a synth, and each voice is using the same audio player instance. so, eg for 10 voices at the same time means 10 seeks per render. this is because every synth sound is in the same file, that makes a huge difference of ram usage instead of having a lot of files opened.
then, is there any way to disable the 'crossfade' thing?  i guess the approach is going to be using the decoder and resampler, and the truth is that was the first i tried, but when i started to play with the sdk long time ago i wasn't able to make it work without clicks... so an example just resampling a file and playing it would really help.

**Comment by superpoweredSDK** [comment]
The SuperpoweredAdvancedAudioPlayer is not designed for this use case. If you have 10 voices please use 10 instances of the player.
