### ISSUE TITLE
Sound artifacts decoding + resampling

### ISSUE THREAD

**Issue by iamyellow** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#187]
Hi again,

As an alternative approach for the problems I found [here](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/issues/186), I'm using now a decoding + resampling approach, but I'm hearing some continuous clicks resampling an playing a file. The click volume is low but audible, like a small helicopter flying around. I'm playing a 24 bit @ 48KHz file resampled to 44.1. Here the code:

Rendering:
```
float* outL = (float*)_renderAbl->mBuffers[0].mData;
float* outR = (float*)_renderAbl->mBuffers[1].mData;

// _outputBuffer is a float* buffer of 1024 * 2 * 4 + 64 bytes
// frameCount is 1024

UInt32 renderCount = _sample->render(frameCount, _outputBuffer);
SuperpoweredDeInterleave(_outputBuffer, outL, outR, renderCount);
// I also tried w/ frameCount instead of renderCount, same effect
// SuperpoweredDeInterleave(_outputBuffer, outL, outR, frameCount);
```

Decoding+resampling:
```
UInt32 EllSample::render(UInt32 frameCount, float* buffer) {    
    UInt32 sampleCount = UInt32((double)frameCount * (48/44.1));

    // _pcm = (short int*)std::malloc(2048 * 4 + 16384);
    _decoder->decode(_pcm, &sampleCount);
    
    // _resampler->rate = 48/44.1;
    UInt32 processCount = _resampler->process(_pcm, buffer, sampleCount);
    printf(">> %d vs %d\n", sampleCount, processCount);
    
    return processCount;
}
```

output log is always the same:
```
>> 1114 vs 1024
>> 1114 vs 1023
>> 1114 vs 1024
>> 1114 vs 1023
...
```
I guess it has something to do w/ the fact of getting 1024, then 1023, back to 1024, etc. What am I doing wrong here?? I'm not figuring out what I'm missing in this code :(

**Comment by superpoweredSDK** [comment]
processCount is the number of samples you output, alternating between 1023 and 1024 according to your output log.
I'm guessing you still process with 1024 at a later stage.
Since this is not an issue with the SDK but your custom code, i close this now. This is not a support forum -- it is here: http://superpowered.com/support
