### ISSUE TITLE
SIGBUS: illegal alignment

### ISSUE THREAD

**Issue by romanbsd** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#188]
Happens sometimes when called like this:
```cpp
hadSamples = mPlayer1->process(buffer1, false, numberOfSamples);
```
https://www.dropbox.com/s/x7ddvkpfx80onke/Screenshot%202016-11-08%2015.02.22.png?dl=0

The buffer is created with:
```cpp
static float *createBuffer(unsigned int bufferSize) {
    return (float *) memalign(16, (bufferSize + 16) * sizeof(float) * 2);
}
```

**Comment by superpoweredSDK** [comment]
Please show me the full log.

**Comment by romanbsd** [comment]
If you're referring to the call-stack, then it's the interesting part, below it's the android java runtime. If you're asking about other threads, then I'll have to reproduce it, and it's not happening often.

**Comment by superpoweredSDK** [comment]
Please debug in native mode and show the full call-stack.

**Comment by superpoweredSDK** [comment]
Can you please debug in native mode and show the full call-stack?

**Comment by romanbsd** [comment]
I'm not sure what you mean by "debug in native mode". The Android Studio has a hybrid debugging mode, where it uses the java debugger (for java code) and lldb powered debugger (for native code) in the same "Debugger" tab. When this crash happens again, I can try to take a snapshot of all the threads that might be relevant. This crash rarely happens though, so it might take some time to reproduce.

**Comment by superpoweredSDK** [comment]
Perhaps this hybrid debugging is a new thing in Android Studio 2.2? I had to switch to native debugging before. Yes, please make a snapshot. I can't help without information.
