### ISSUE TITLE
Strange noise when using SuperpoweredStereoMixer 

### ISSUE THREAD

**Issue by siddharthkchatterjee** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#189]
I am trying out the SuperpoweredStereoMixer and I seem to be hearing some strange noises right over the playing track. The track plays perfectly correctly other than this strange cyclic noise that sort of sounds like it is playing on top of the track. 

Here is a snippet. 

```
    short int *output = (short int *)memalign(16, (1024 + 16) * sizeof(short int) * 2);
    short int *input = javaEnvironment->GetShortArrayElements(inputArray, 0);
    float *audioBuffer = (float *)memalign(16, (1024 + 16) * sizeof(float) * 2);
    float *outputBuffer = (float *)memalign(16, (1024 + 16) * sizeof(float) * 2);
    SuperpoweredShortIntToFloat(input, audioBuffer, 1024, 2);
    float *inputs[4] = { audioBuffer, NULL, NULL, NULL };
    float *outputs[2] = { outputBuffer, NULL };
    float inputLevels[8] = { 1.0f, 1.0f, NULL, NULL, NULL, NULL, NULL, NULL };
    float outputLevels[2] = { 1.0f, 1.0f };
    SuperpoweredStereoMixer *mixer = new SuperpoweredStereoMixer();
    mixer->process(inputs, outputs, inputLevels, outputLevels, NULL, NULL, 1024);
    SuperpoweredFloatToShortInt(outputBuffer, output, 1024, 2);
```

There is **no** noise when I simply remove the mixer as follows which leads me to think it is somehow introduced by the mixer. 

```
    short int *output = (short int *)memalign(16, (1024 + 16) * sizeof(short int) * 2);
    short int *input = javaEnvironment->GetShortArrayElements(inputArray, 0);
    float *audioBuffer = (float *)memalign(16, (1024 + 16) * sizeof(float) * 2);
    float *outputBuffer = (float *)memalign(16, (1024 + 16) * sizeof(float) * 2);
    SuperpoweredShortIntToFloat(input, audioBuffer, 1024, 2);
    SuperpoweredFloatToShortInt(audioBuffer, output, 1024, 2);
```

The buffer sizes of 1024 work perfectly otherwise and the input is standard PCM 16-bit audio. 

Any ideas why the noise is occurring or what I can do to fix it?

**Comment by siddharthkchatterjee** [comment]
@superpoweredSDK ^

**Comment by siddharthkchatterjee** [comment]
This is certainly an issue with the mixer or something I'm doing with the mixer. On further inspection, a set of samples sent to the mixer return as follows:

`input`
0 = -37
1 = -6162
2 = -404
3 = -6013
4 = -161
5 = -5341
6 = -21
7 = -4732
8 = -544
9 = -4676
10 = -552
11 = -4165
12 = -247
13 = -3292
14 = -591
15 = -2832
16 = -730
17 = -2076
18 = -275
19 = -694
20 = 55
21 = 679
22 = 345
23 = 2050
24 = 847
...(1024)

`output`
0 = 0
1 = 0
2 = 0
3 = -2
4 = 0
5 = -4
6 = 0
7 = -5
8 = 0
9 = -7
10 = -1
11 = -8
12 = 0
13 = -7
14 = -1
15 = -7
16 = -2
17 = -6
18 = 0
19 = -2
20 = 0
21 = 2
22 = 1
23 = 8
24 = 3

All the above are 16 bit PCM short * values and are a result of the first snippet above. 

The track plays correctly other than the noise on top, @superpoweredSDK

**Comment by siddharthkchatterjee** [comment]
This occurs when there is a single input and the other input buffer pointers are set to `NULL`. Such a drastic change in sample values seems unusual. Can you please tell me what I am doing wrong, @superpoweredSDK?

**Comment by superpoweredSDK** [comment]
NULL doesn't always translates to 0.0f. Set the input levels to 0.0f instead of NULL.

**Comment by siddharthkchatterjee** [comment]
@superpoweredSDK, just tried that, doesn't help.

**Comment by superpoweredSDK** [comment]
I see no problem in your snippets. Did you update to Superpowered version 1.0.0, and are you sure you are linking to it's latest .a files with CMake?

**Comment by siddharthkchatterjee** [comment]
Yes, I updated to 1.0.0 a few days ago and have linked to the latest as well. 
Would you like me to link you to the app repo so you can run and reproduce? 
Get Outlook for iOS




On Fri, Nov 11, 2016 at 8:13 PM +0530, "Super Powered" <notifications@github.com> wrote:












I see no problem in your snippets. Did you update to Superpowered version 1.0.0, and are you sure you are linking to it's latest .a files with CMake?

**Comment by superpoweredSDK** [comment]
I'm not able to provide you custom code review for free. Please check our various support options here: http://superpowered.com/support

Please also note that there are hundreds of apps using Superpowered and the stereo mixer, it is very likely that there is a problem in your code and not Superpowered.
