### ISSUE TITLE
Can I supply my own PCM data?

### ISSUE THREAD

**Issue by vicyap** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#190]
Hello, is it possible to use this library to process my own stream of PCM data (frames of 16-bit shorts)? My application gets data from a stream and I would like to process the stream before audio output. I was looking at [advanced_audio_player](http://superpowered.com/docs/class_superpowered_advanced_audio_player.html) but I only see a way to use it with files.

**Comment by superpoweredSDK** [comment]
You can't supply your own pcm data for the SuperpoweredAdvancedAudioPlayer, however every other feature operates on raw buffers and you can input whatever you want.
