### ISSUE TITLE
Question: sequencer and process calls

### ISSUE THREAD

**Issue by tyler-at-uv** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#191]
Good day,

I have an architectural question, and so I thought it might be most useful here so others may learn. 

I have written a straight forward sequencer on top of the Superpowered audio engine (currently just on Android). The basic gist is that I preload X Superpowered Audio Players, each with a separate file/sample. Later, the client adds any number of samples by name to the sequencer queue. And then when played it plays each in order. When I receive the EOF for one, I go on to the next one in the queue, or simply loop the last one if the queue is currently empty.

The issue I run into is that I get either gaps (of a multiple of 0.022 seconds) or small clicks at times. I think it is related to not calling process after receiving the EOF for the previous sample (I posted a separate issue here a while back discussing this).

What I did as a stop-gap is to simply call process for all samples for each process call to the sequencer. This does help with the gaps, but I still sometimes get a click or noise. And of course it is very inefficient. 

So what I would like to know is if there is a suggestion as to how to handle this best. Do I simply call the process once on the previous sample that finished, to ensure that there are no gaps. Is there a flag in the AudioPlayer I can check for (playing perhaps?).

Thank you for your assistance.

**Comment by superpoweredSDK** [comment]
Calling process() every time is not inefficient. If the player is in a paused state, then process() doesn't do significant amount of work. However process() also drives an internal message queue and handles fade in/out, so it's important to call every time.
Use the play/pause methods for your app.
