### ISSUE TITLE
SuperpoweredDecoder stops decoding before the real EOF is reached

### ISSUE THREAD

**Issue by romanbsd** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#194]
The decoder returns EOF after decoding about 8 sec out of the 32 sec file.
The file in question was created by SuperpoweredRecorder btw.
This is the minimal test case (extracted from our code). It returns the following:

Duration: 31.970000 (__1534560__ samples), sampleRate: 48000, samplesPerFrame: 1024
Finished decoding user recording: __384000__

```cpp
#include <stdio.h>
#include <stdlib.h>
#include <SuperpoweredDecoder.h>

int main(void) {
  const char userRecording[] = "USK4W07225902016-11-27_11_36_10.wav";
  SuperpoweredDecoder mDecoder1;
  mDecoder1.open(userRecording);

  printf("Duration: %lf (%lld samples), sampleRate: %u, samplesPerFrame: %u\n",
    mDecoder1.durationSeconds, mDecoder1.durationSamples, mDecoder1.samplerate, mDecoder1.samplesPerFrame);

  const unsigned int numberOfSamples = mDecoder1.samplesPerFrame;
  short int *tmpBuf1 = (short int *) malloc(numberOfSamples * 4 + 16384);
  unsigned int nSamples1 = 0;
  unsigned int decoder1samples;

  bool decoder1Done = false;
  do {
        decoder1samples = 0;
        if (!decoder1Done) {
            decoder1samples = numberOfSamples;
            unsigned char res = mDecoder1.decode(tmpBuf1, &decoder1samples);
            nSamples1 += decoder1samples;
            switch (res) {
                case SUPERPOWEREDDECODER_EOF:
                    decoder1Done = true;
                    printf("Finished decoding user recording: %d\n", nSamples1);
                    break;
                case SUPERPOWEREDDECODER_ERROR:
                    printf("Error decoding user recording\n");
                    break;
                case SUPERPOWEREDDECODER_OK:
                default:
                    break;
            }
        }
    } while (!decoder1Done);
  return 0;
}

```

**Comment by superpoweredSDK** [comment]
Please make sure that you are using the latest version of Superpowered. Is this with that version?

**Comment by romanbsd** [comment]
Version 1.0.0

**Comment by superpoweredSDK** [comment]
There is a bug in the SDK for WAV and AIFF files. Please check the offline example project on how to decode the full file (hint: don't listen to EOF and check how many samples were returned).
That bug will be fixed in the next release, but listening to EOF may still not be the best for broken mp3 and aac files (there are many!).

**Comment by romanbsd** [comment]
What does the EOF mean in that case? I think that it implies that calling decode again will produce an error. If you use EOF to signal some broken file, then it's maybe better to have another result code for this case. Some kind of "recoverable error".

**Comment by romanbsd** [comment]
This bug is still not fixed. The SuperpoweredDecoder spits out a lot of EOFs. The wav file in question was created with SuperpoweredRecorder @ 48000Hz sample rate.
