### ISSUE TITLE
Error compiling android usb

### ISSUE THREAD

**Issue by untihunt** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#195]
Hello all,

Thank you very much for the great project. Unfortunately i was unable to compile the project. I got to the point with it saying that there is a problem with the cmakelist.txt file. It does not say exactly where the problem is that is why I want to know if any one ran into such problem. I have ndk v12 and cmake v3.6.3155560

`Build command failed.
Error while executing 'C:\Users\admin\AppData\Local\Android\sdk\cmake\3.6.3155560\bin\cmake.exe' with arguments {-HC:\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\SuperpoweredUSBExample\simpleusb\src\main\jni -BC:\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\SuperpoweredUSBExample\simpleusb\.externalNativeBuild\cmake\debug\armeabi-v7a -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi-v7a -DANDROID_NDK=C:\Users\admin\AppData\Local\Android\sdk\ndk-bundle -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\SuperpoweredUSBExample\simpleusb\build\intermediates\cmake\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=C:\Users\admin\AppData\Local\Android\sdk\cmake\3.6.3155560\bin\ninja.exe -DCMAKE_TOOLCHAIN_FILE=C:\Users\admin\AppData\Local\Android\sdk\cmake\3.6.3155560\android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=16 -DCMAKE_C_FLAGS=-O3 -fsigned-char -DCMAKE_CXX_FLAGS=-fsigned-char -Inull -DANDROID_PLATFORM=android-16 -DANDROID_TOOLCHAIN=clang -DANDROID_ARM_NEON=TRUE -DANDROID_STL=gnustl_static -DPATH_TO_SUPERPOWERED:STRING=null}
-- Check for working C compiler: C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/debug/armeabi-v7a
CMake Warning in C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_7b930.dir/
  has 235 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    testCCompiler.c.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
CMake Warning in C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_df058.dir/
  has 235 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    CMakeCCompilerABI.c.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
CMake Warning in C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_90d95.dir/
  has 235 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    testCXXCompiler.cxx.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
CMake Warning in C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_f2974.dir/
  has 235 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    CMakeCXXCompilerABI.cpp.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
armeabi-v7a
CMake Error at CMakeLists.txt:12 (add_library):
  Cannot find source file:
    null/AndroidIO/SuperpoweredAndroidAudioIO.cpp
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
CMake Error: CMake can not determine linker language for target: SuperpoweredExample
Error:executing external native build for cmake C:\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\SuperpoweredUSBExample\simpleusb\src\main\jni\CMakeLists.txt
Build command failed.
Error while executing 'C:\Users\admin\AppData\Local\Android\sdk\cmake\3.6.3155560\bin\cmake.exe' with arguments {-HC:\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\SuperpoweredUSBExample\simpleusb\src\main\jni -BC:\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\SuperpoweredUSBExample\simpleusb\.externalNativeBuild\cmake\release\armeabi-v7a -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi-v7a -DANDROID_NDK=C:\Users\admin\AppData\Local\Android\sdk\ndk-bundle -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\SuperpoweredUSBExample\simpleusb\build\intermediates\cmake\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=C:\Users\admin\AppData\Local\Android\sdk\cmake\3.6.3155560\bin\ninja.exe -DCMAKE_TOOLCHAIN_FILE=C:\Users\admin\AppData\Local\Android\sdk\cmake\3.6.3155560\android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=16 -DCMAKE_C_FLAGS=-O3 -fsigned-char -DCMAKE_CXX_FLAGS=-fsigned-char -Inull -DANDROID_PLATFORM=android-16 -DANDROID_TOOLCHAIN=clang -DANDROID_ARM_NEON=TRUE -DANDROID_STL=gnustl_static -DPATH_TO_SUPERPOWERED:STRING=null}
-- Check for working C compiler: C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/release/armeabi-v7a
CMake Warning in C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_cd950.dir/
  has 237 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    testCCompiler.c.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
CMake Warning in C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_be5ff.dir/
  has 237 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    CMakeCCompilerABI.c.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
CMake Warning in C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_72c06.dir/
  has 237 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    testCXXCompiler.cxx.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
CMake Warning in C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/simpleusb/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_3e26b.dir/
  has 237 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    CMakeCXXCompilerABI.cpp.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
armeabi-v7a
CMake Error at CMakeLists.txt:12 (add_library):
  Cannot find source file:
    null/AndroidIO/SuperpoweredAndroidAudioIO.cpp
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
CMake Error: CMake can not determine linker language for target: SuperpoweredExample
Error:executing external native build for cmake C:\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\SuperpoweredUSBExample\simpleusb\src\main\jni\CMakeLists.txt
Build command failed.
Error while executing 'C:\Users\admin\AppData\Local\Android\sdk\cmake\3.6.3155560\bin\cmake.exe' with arguments {-HC:\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\SuperpoweredUSBExample\complexusb\src\main\jni -BC:\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\SuperpoweredUSBExample\complexusb\.externalNativeBuild\cmake\debug\armeabi-v7a -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi-v7a -DANDROID_NDK=C:\Users\admin\AppData\Local\Android\sdk\ndk-bundle -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\SuperpoweredUSBExample\complexusb\build\intermediates\cmake\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=C:\Users\admin\AppData\Local\Android\sdk\cmake\3.6.3155560\bin\ninja.exe -DCMAKE_TOOLCHAIN_FILE=C:\Users\admin\AppData\Local\Android\sdk\cmake\3.6.3155560\android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=16 -DCMAKE_C_FLAGS=-O3 -fsigned-char -DCMAKE_CXX_FLAGS=-fsigned-char -Inull -DANDROID_PLATFORM=android-16 -DANDROID_TOOLCHAIN=clang -DANDROID_ARM_NEON=TRUE -DANDROID_STL=gnustl_static -DPATH_TO_SUPERPOWERED:STRING=null}
-- Check for working C compiler: C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/debug/armeabi-v7a
CMake Warning in C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_be705.dir/
  has 236 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    testCCompiler.c.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
CMake Warning in C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_8d5d2.dir/
  has 236 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    CMakeCCompilerABI.c.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
CMake Warning in C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_42a29.dir/
  has 236 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    testCXXCompiler.cxx.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
CMake Warning in C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_79646.dir/
  has 236 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    CMakeCXXCompilerABI.cpp.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
armeabi-v7a
CMake Error at CMakeLists.txt:12 (add_library):
  Cannot find source file:
    null/AndroidIO/SuperpoweredAndroidAudioIO.cpp
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
CMake Error: CMake can not determine linker language for target: SuperpoweredExample
Error:executing external native build for cmake C:\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\SuperpoweredUSBExample\complexusb\src\main\jni\CMakeLists.txt
Build command failed.
Error while executing 'C:\Users\admin\AppData\Local\Android\sdk\cmake\3.6.3155560\bin\cmake.exe' with arguments {-HC:\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\SuperpoweredUSBExample\complexusb\src\main\jni -BC:\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\SuperpoweredUSBExample\complexusb\.externalNativeBuild\cmake\release\armeabi-v7a -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi-v7a -DANDROID_NDK=C:\Users\admin\AppData\Local\Android\sdk\ndk-bundle -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\SuperpoweredUSBExample\complexusb\build\intermediates\cmake\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=C:\Users\admin\AppData\Local\Android\sdk\cmake\3.6.3155560\bin\ninja.exe -DCMAKE_TOOLCHAIN_FILE=C:\Users\admin\AppData\Local\Android\sdk\cmake\3.6.3155560\android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=16 -DCMAKE_C_FLAGS=-O3 -fsigned-char -DCMAKE_CXX_FLAGS=-fsigned-char -Inull -DANDROID_PLATFORM=android-16 -DANDROID_TOOLCHAIN=clang -DANDROID_ARM_NEON=TRUE -DANDROID_STL=gnustl_static -DPATH_TO_SUPERPOWERED:STRING=null}
-- Check for working C compiler: C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/release/armeabi-v7a
CMake Warning in C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_0cdf1.dir/
  has 238 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    testCCompiler.c.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
CMake Warning in C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_18955.dir/
  has 238 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    CMakeCCompilerABI.c.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
CMake Warning in C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_09a55.dir/
  has 238 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    testCXXCompiler.cxx.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
CMake Warning in C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/SuperpoweredUSBExample/complexusb/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_00768.dir/
  has 238 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    CMakeCXXCompilerABI.cpp.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
armeabi-v7a
CMake Error at CMakeLists.txt:12 (add_library):
  Cannot find source file:
    null/AndroidIO/SuperpoweredAndroidAudioIO.cpp
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
CMake Error: CMake can not determine linker language for target: SuperpoweredExample
Error:executing external native build for cmake C:\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\SuperpoweredUSBExample\complexusb\src\main\jni\CMakeLists.txt`

Please help :(

**Comment by superpoweredSDK** [comment]
The log says this at multiple points: "The maximum full path to an object file is 250 characters (see CMAKE_OBJECT_PATH_MAX). Object file ABCD.o cannot be safely placed under this director. The build may not work correctly."
You need to change that value or you need to change the path where you put the files. (C:/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master is very long.)
