### ISSUE TITLE
Allow choosing number of channels for input/output

### ISSUE THREAD

**Issue by theyonibomber** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#196]
In SuperpoweredAndroidAudioIO you can specify the sample rate and the buffer size.
It would be nice to also be able to specify that you want MONO instead of STEREO input/output.

**Comment by superpoweredSDK** [comment]
SuperpoweredAndroidAudioIO is open source, you can modify to have mono input. Please note however that low latency audio I/O on Android is stereo. It's better to leave it stereo and do the mono conversion yourself with SuperpoweredStereoToMono.
