### ISSUE TITLE
Build with flutter.io?

### ISSUE THREAD

**Issue by jtrunick** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#197]
I'd love to use Superpowered with flutter.io. The trouble is figuring out how to add the superpowered build to flutter's build. It keeps telling me to use experimental build for the ndk support, even though both projects build using com.android.tools.build:gradle:2.2.2. Any pointers appreciated.

It would possibly help if I could understand how to build just a JNI library to superpower (a gradle submodule)

**Comment by jtrunick** [comment]
I'd love to use Superpowered with flutter.io. The trouble is figuring out how to add the superpowered build to flutter's build. It keeps telling me to use experimental build for the ndk support, even though both projects build using com.android.tools.build:gradle:2.2.2. Any pointers appreciated.

**Comment by marafat** [comment]
Hi Joel,
The latest update of Superpowered (v1.0.0) started using cmake for building native code.

Please take a look at the last secsion here: http://superpowered.com/cpu-frequency-scaling-android?mc_cid=5f5fc9c626&mc_eid=ec2ee493ca

Also, check out this tweet from the CTO of Superpowered: https://twitter.com/szantog/status/792035166826991616

The support for native code by Android studio has been evolving unexpectedly. I started writing native code for Android and using Superpowered about 4 months ago. During this time I have learned to setup my dev env with all three building tools that Gabor mentioned in his tweet. So far, Google seems to be pushing CMake, and I guess the people behind Superpowered saw that too and started using it for thier examples with the latest release.

I hope this was helpful.

**Comment by superpoweredSDK** [comment]
Yes, the 1.0 release blog post has:

"CMake & Updated and Modernized Android Example Projects
As of today, every Superpowered Android example project supports the latest official development environment, Android Studio 2.2.2."

"The build environment is also upgraded to Gradle+CMake, which is now the new official build environment, recommended by Google. In the past 3 years we have seen 3 different environments and we hope Google finally settles with the current solution, as Android’s build system should be finally "ready".
CMake builds faster than ndkbuild and the experimental gradle plugin and CMake is somewhat less complex. Don’t expect Xcode-like speeds though."

**Comment by IHNEL** [comment]
Hi, have you find anyway to integrate superpowered into Flutter project?
