### ISSUE TITLE
Crash in AACDecoder

### ISSUE THREAD

**Issue by romanbsd** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#198]
A fellow developer sent me this crash. I'm not sure if you can make anything out of it, but anyway...
![screen shot 2016-12-06 at 12 18 12](https://cloud.githubusercontent.com/assets/49660/20922092/a0d7b8bc-bbaf-11e6-84c2-ed71b28e8dcf.png)

**Comment by superpoweredSDK** [comment]
Please ask the developer if the crash happens for the same aac file every time. If yes, please send the file.

**Comment by tuxxon** [comment]
Hello.
I failed to port your sample apps to T-R42 tvbox (Rockchip rk3188, ARMv7a - 32bit cpu). Could you help me to do that? What should I do to modify your code for porting?

**Comment by drorsun** [comment]
That developer was me. It happened once and I can't say on what file exactly. I am working on the area with various videos. If it happens again I will update.

**Comment by superpoweredSDK** [comment]
@drorsun Yes, please send the file when it happens again. I close this now, but please don't forget to send.
