### ISSUE TITLE
Record sound issue

### ISSUE THREAD

**Issue by gostik** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#20]
Hi!
Currently working on recording with the microphone on Android. Faced with the problem: using class SuperpoweredRecorder.h fails to record from the microphone. I use the 'start' method with path params  (//mnt//sdcard//Music//music.wav) and then stop() . No fails or fatals, but the file itself does not appear.

Can you provide me with right way for work with SuperpoweredRecorder.h on Android?
Thanks for the reply!

**Comment by superpoweredSDK** [comment]
Hi,

the recorder records whatever you put into it's process() method. It's not a generalized high level solution with connections to the audio i/o. Please check the example projects in the Android NDK, you will find an audio input example there. You can submit the incoming audio to the recorder's process() method.

**Comment by gostik** [comment]
Thanks for your reply!
But can you describe what for SuperpoweredRecorder.h can be used?

**Comment by svenoaks** [comment]
It makes writing to .wav file really easy.

**Comment by WitoldAgile** [comment]
Hi Steve,
How are you

If you have real experiences to use SuperpoweredRecorder APIs, please let me know.
I implemented recorder function in process module(using crossexample source code), and I couldn't get any result(recorded file). 
I am not sure that record APIs of SuperpoweredRecorder works.

Looking for your support!

**Comment by svenoaks** [comment]
I got it to work, trick is to correctly enable the input in the SuperpoweredAndroidAudioIO. You need to instantiate like this:

audioSystem = new SuperpoweredAndroidAudioIO(samplerate, buffersize, true, true, audioProcessing, this, buffersize * 2);

If you leave latencySamples at 0 instead of buffersize*2 minimum, the sound will be all screwed, this is probably a bug and class should internally allocate enough size.

Then you will call start() on the audiorecorder
Then 'short int *output' will contain the microphone input and you can put the output to the speakers there as well. Convert to float* in stereobuffer and call process() on audio recorder every time.

Then call stop() on audio recorder and your .wav will be there. Use different names for temp and permanent file, I haven't tried with same name.

You have to give the permissions in manifest WRITE_EXTERNAL_STORAGE and RECORD_AUDIO.

**Comment by WitoldAgile** [comment]
Thanks for your support.

I didn't set audioSystem like that in constructor. I did like this
audioSystem = new SuperpoweredAndroidAudioIO(samplerate, buffersize, false, true, audioProcessing, this, 0);

3rd param is different with yours. I will follow it with your guide. 
However, if you have example to work, you can contribute that sample project in Git?
Thanks.

**Comment by WitoldAgile** [comment]
Hello Steve,

As you mentioned, I detected the sound(recorded audio) will be all screwed.
Of course, I set latencySamples buffersize*2

And I checked the piece of code in SuperpoweredAndroidAudioIO()
internals->latencySamples = (latencySamples < buffersize) ? buffersize : latencySamples;
Currently I am checking the SuperpoweredAndroidAudioIO

If you solved this issue, you would like to guide me. Thanks
And if sample audio file size is very small(for ex, about 1s), there can be any issue?

**Comment by svenoaks** [comment]
Did you convert to float in the stereoBuffer, do you have any files generated at all.

SuperpoweredShortIntToFloat(input, stereoBuffer, numberOfSamples);
recorder.process(stereoBuffer, NULL, numberOfSamples);

**Comment by WitoldAgile** [comment]
Thanks for your support!
I didn't find out the issue which the recorded audio was noised. But it was fixed now. Thanks

**Comment by JMDidon** [comment]
I am having the same issue, how did you do to resolve it ?

**Comment by ijmorgado** [comment]
Hi"!, Can you give a complete example how did you solve this? @JMDidon  I would appreciate it too much :)

**Comment by ijmorgado** [comment]
@svenoaks have you any working example about this?

**Comment by proishere** [comment]
@svenoaks 
With the recorder, I am able to record whatever is being played but I am unable to record the voice along with it.

// SuperpoweredAndroidAudioIO constructor 
audioSystem = new SuperpoweredAndroidAudioIO(samplerate, buffersize, true, true, audioProcessing, this, buffersize * 2);

// recorder init
recorder = new SuperpoweredRecorder(tempPath, samplerate);

// recorder started
recorder->start(destPath);

// process method
    
    bool SuperpoweredExample::process(short int *output, unsigned int numberOfSamples) {
    pthread_mutex_lock(&mutex);
    bool masterIsA = (crossValue <= 0.5f);
    float masterBpm = masterIsA ? playerA->currentBpm : playerB->currentBpm;
    double msElapsedSinceLastBeatA = playerA->msElapsedSinceLastBeat; // When playerB needs it, playerA has already stepped this value, so save it now.

    bool silence = !playerA->process(stereoBuffer, false, numberOfSamples, volA, masterBpm, playerB->msElapsedSinceLastBeat);
    if (playerB->process(stereoBuffer, !silence, numberOfSamples, volB, masterBpm, msElapsedSinceLastBeatA)) silence = false;

    short int *recorderInt;
    if (!silence) {
        recorderInt = recorder->process(stereoBuffer, 0, buffersize);
    }

    pthread_mutex_unlock(&mutex);

    // The stereoBuffer is ready now, let's put the finished audio into the requested buffers.
    if (!silence)  {
        SuperpoweredFloatToShortInt(stereoBuffer, output, numberOfSamples);
    }
    return !silence; 
    }

** I am not understanding the "recorder process" part that u said, could you please explain it again. Hence, I dont know what to do with "recorderInt"

I want to write the audio that is being played along with the voice from the microphone

Thanks in advance :)

**Comment by superpoweredSDK** [comment]
Audio input comes in with the "output" parameter of the process() method. But it's not used, but overwritten with audio coming from the "stereoBuffer" at the end. "stereoBuffer" is also passed to the recorder, but nothing from "output". You need to mix output with stereoBuffer, then pass that to the recorder.

**Comment by proishere** [comment]
Ok i have now understood the concept. But how do I "mix the audio input with the stereoBufferer"?

I tried setting the bufferAdd parameter to true in the playerA->process() method, but it didnot work.

// not working
bool silence = !playerA->process(stereoBuffer, true, numberOfSamples, volA, masterBpm, playerB->msElapsedSinceLastBeat);

Thanks in advance.
