### ISSUE TITLE
I have failed to port samples apps to T-R42box

### ISSUE THREAD

**Issue by tuxxon** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#201]
Hello.
I failed to port your sample apps to T-R42 tvbox (Rockchip rk3188, ARMv7a - 32bit cpu). Could you help me to do that? What should I do to modify your code for porting?

**Comment by superpoweredSDK** [comment]
We have no such device. Does it run the "normal" Android system? What do you mean you "failed"? What happened?

**Comment by tuxxon** [comment]
CPU : ARMv7a - 32bit.
I think your sdk has been developed on 64bit cpu for the current android devices. right?
