### ISSUE TITLE
Typo in Android Cross Example

### ISSUE THREAD

**Issue by mateusgrb** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#203]
When trying to run the android cross example, I get this error:

`ninja: error: '/home/mateus/AndroidStudioProjects/Low-Latency-Android-Audio-iOS-Audio-Engine/Superpowered/libSuperpoweredAndroidx86.a', needed by '/home/mateus/AndroidStudioProjects/Low-Latency-Android-Audio-iOS-Audio-Engine/Android/CrossExample/app/build/intermediates/cmake/debug/obj/x86/libSuperpoweredExample.so', missing and no known rule to make it`

The problem is that inside the sdk folder the referred file is named "libSuperpoweredAndroidX86.a", with an upper case "X", when it should be "x". The build succeeds after that change.

**Comment by superpoweredSDK** [comment]
In the SDK folder it has a lowercase "x", perhaps you mixed one of the older SDKs with the current one.

**Comment by mateusgrb** [comment]
I cloned the repo yesterday for the first time ever.

Here are the files with "X": 
https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/blob/master/Superpowered/libSuperpoweredAndroidX86.a

https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/blob/master/Superpowered/libSuperpoweredAndroidX86_64.a

**Comment by marafat** [comment]
I have uppercase as well but I am able to build successfully. @mateusgrb Did you try to 'clean' the project before building?

**Comment by mateusgrb** [comment]
I don't remember, but the minute I changed it to lowercase the build worked.

**Comment by romanbsd** [comment]
maybe it's due to case sensitive vs case-insensitive fs
