### ISSUE TITLE
Small gap between loops for a m4a file

### ISSUE THREAD

**Issue by mateusgrb** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#204]
Hi! I've downloaded the android cross example and added a new m4a file under res/raw to play on playerA instead of lycka.mp3.

The issue is that there's a small gap/glitch between the loops. I'm attaching an audio file so that you can hear the gap. I tried with another m4a file and could also notice the gap.

The file size is 220 KB and ~10 seconds long. I'm trying it on a Nexus 4, Android 5.1.

The only changes I made to the CrossExample were playing my track rather than lycka.mp3, setting playerA bpm to 95 and set firstBeatMs to 0, although I have tried other values and the gap persists. 

Do you know how to fix this problem?

[Gravacao_0072.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/642872/Gravacao_0072.zip)

**Comment by superpoweredSDK** [comment]
Every compressed format (such as mp3 and aac) starts with silence and may end with silence too. Don't loop the entire file, but a portion of it.

**Comment by weepy** [comment]
ogg doesn't have this problem
