### ISSUE TITLE
SuperpoweredAdvancedAudioPlayer pointer is null on callback

### ISSUE THREAD

**Issue by mateusgrb** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#205]
Hi, I started from the Android CrossExample app, and I'm currently trying to enable it to play multiple tracks rather than two fixed ones(playerA and playerB). So I'm creating a local SuperpoweredAdvancedAudioPlayer object everytime the constructor is called.

```
 stereoBuffer = (float *) memalign(16, (buffersize + 16) * sizeof(float) * 2);
    SuperpoweredAdvancedAudioPlayer *player = new SuperpoweredAdvancedAudioPlayer(&player,
                                                                                  playerEventCallback, samplerate, 0);
    player->open(path);
    player->syncMode = SuperpoweredAdvancedAudioPlayerSyncMode_TempoAndBeat;

    SuperpoweredCPU::setSustainedPerformanceMode(true);
    audioSystem = new SuperpoweredAndroidAudioIO(samplerate, buffersize, false, true,
                                                 audioProcessing, this, -1, SL_ANDROID_STREAM_MEDIA,
                                                 buffersize * 2);
```

And here is the callback:
```
static void playerEventCallback(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event,
                                void *__unused value) {
    if (event == SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess) {
        SuperpoweredAdvancedAudioPlayer *player = *((SuperpoweredAdvancedAudioPlayer**) clientData);
        player->setBpm(95.0f);
        player->setFirstBeatMs(353);
        player->setPosition(player->firstBeatMs, false, false);
        player->play(true);
    };
}
```

The issue is that when I get the player on the callback, it is null. I'm a Java developer trying to integrate this library to an android app, so I might be missing something obvious about C++. I'm wondering if passing `&player` to the SuperpoweredAdvancedAudioPlayerEvent constructor is the issue, since it is a local variable, and also, it hasn't been declared yet. At the same time I read that when you create objects with `new`, they are allocated on the heap, so you should be able to access them outside the function scope. I'm really confused on this one... 

Could you please help me with that? How would you be able to instantiate multiple players and pass their pointer to the callback?

Thanks in advance

**Comment by superpoweredSDK** [comment]
1. Your "player" variable is on the stack. The instance is allocated on the heap, but "player" is a local variable holding the address of the instance, on the stack.
2. When you create the player with new, the local variable "player" has memory garbage, as the equal sign's right side runs first.

This is not an issue with the Superpowered SDK, but a generic C++ programming topic.

**Comment by mateusgrb** [comment]
Thanks for your response, it's indeed a C++ question.

If you could further help me...

Given the signature of SuperpoweredAdvancedAudioPlayer's constructor, which expects a clientData pointer upfront, is it safe to say I will need a global SuperpoweredAdvancedAudioPlayer variable to pass as first parameter on the constructor? I wish I could instantiate a SuperpoweredAdvancedAudioPlayer first, then pass its instance address as clientData to access on callback. But as it's not possible, I think the only way to go is to use a global variable. I tried here and it works, but not sure if it's the best solution.
