### ISSUE TITLE
iOS SuperpoweredDecoder open "Can't open this file."

### ISSUE THREAD

**Issue by peterworth** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#206]
I'm recording an audio file in swift like this:

	let documentsUrl = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
    	let url = documentsUrl.appendingPathComponent("test")

	let settings:[String:Any] = [
            AVFormatIDKey: kAudioFormatLinearPCM,
            AVLinearPCMIsFloatKey:true,
            AVLinearPCMBitDepthKey: NSNumber(value:32),
            AVLinearPCMIsBigEndianKey: false,
            AVLinearPCMIsNonInterleaved: false,
            AVSampleRateKey: 44100.0,
            AVNumberOfChannelsKey: 1,
            AVEncoderAudioQualityKey: AVAudioQuality.high.rawValue
        ]

        audioRecorder = try AVAudioRecorder(url: url, settings: settings)
        //audioRecorder!.delegate = self
        audioRecorder!.record()

Which works fine, i can play it back using as AVAudioPlayer. But i can't seem to open it with the SuperpoweredDecoder:

	SuperpoweredDecoder *decoder = new SuperpoweredDecoder();
	const char *openError = decoder->open([[url absoluteString] UTF8String], false, 0, 0);

always returns "Can't open this file."

I've tried it with lots of different settings for the file (16 bit, int, float etc). Any idea what is wrong?

Better error strings from the decoder would be useful - i can't tell if it can't find the file (a problem with opening files in the documents directory?) or has a problem with the format.

**Comment by superpoweredSDK** [comment]
The output of your recorder is not wav, aiff, aac, mp3 or alac. I'm guessing it's some proprietary Apple format, such as caf or some raw structure.

**Comment by johnny-cao** [comment]
I use [[url absoluteString] UTF8String] for MPMediaItem, while [url fileSystemRepresentation] for the local file, and it works. Hope it's help for you.

**Comment by sacred0x01** [comment]
@johnny-cao you lifesaver, dude

**Comment by danho322** [comment]
@johnny-cao +1 to this.
