### ISSUE TITLE
"free(stereoBuffer)" method in Version 1.0.0 app crashes

### ISSUE THREAD

**Issue by shivamsingh** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#207]
"free(stereoBuffer)" method in Version 1.0.0 app crashes while it works perfectly on Version 0.9.0.

`float *stereoBuffer = (float *) malloc(decoder->samplesPerFrame * 2 * sizeof(float) + 1024);
free(floatBuffer);`

Getting following error:

> A/libc: invalid address or address of corrupt block 0x55a6b95620 passed to dlfree

**Comment by superpoweredSDK** [comment]
This is not an issue with the Superpowered library, but your own custom code.
Please note the typo in your code: you are allocating "stereoBuffer", but free-ing "floatBuffer".
