### ISSUE TITLE
integration with android studio

### ISSUE THREAD

**Issue by minafared** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#208]
Thanks for this excellent library . but iam confused to use it in android , as integration steps is  not clear for me . i tried to integrate and i found this error
Error:A problem occurred configuring project ':app'.
> executing external native build for cmake F:\super\LowLatencyAndroidAudioiOSAudioEnginemaster\Android\CrossExample\app\src\main\jni\CMakeLists.txt

cmake_minimum_required(VERSION 3.4.1)

set(
	PATH_TO_SUPERPOWERED  
	CACHE STRING "F:\Apptrax\super\LowLatencyAndroidAudioiOSAudioEnginemaster\Superpowered"
)

message(${ANDROID_ABI})

file(GLOB CPP_FILES "*.cpp")

add_library(
	SuperpoweredExample
	SHARED
	${CPP_FILES}
	${PATH_TO_SUPERPOWERED}/AndroidIO/SuperpoweredAndroidAudioIO.cpp
)

include_directories(src/main/jni)
include_directories(${PATH_TO_SUPERPOWERED})

target_link_libraries(
    SuperpoweredExample
    log
    android
    OpenSLES
    ${PATH_TO_SUPERPOWERED}/libSuperpoweredAndroid${ANDROID_ABI}.a
)

**Comment by superpoweredSDK** [comment]
This is not an issue with the Superpowered library. Please check our various support options, and explain your problem in detail with the full build log. http://superpowered.com/support
