### ISSUE TITLE
Getting error can't open file

### ISSUE THREAD

**Issue by ckroll2** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#209]
I've noticed this error mentioned in the forums, but none of the solutions really worked for me. I'm downloading mp3 samples from the Spotify API. Here is an example URL:

https://p.scdn.co/mp3-preview/4fa89ace286252c33a1ca0d36e7555d6a451a2db?cid=null

I save the file locally to cache and am able to load it successfully as an AVAsset. Any idea why superpowered can't open it? I'm using the offline processing example code.

Thanks!

**Comment by superpoweredSDK** [comment]
Downloaded and tested the file, Superpowered plays it properly. There must be a bug in your offline processing example modification.
