### ISSUE TITLE
Gapless playback between songs

### ISSUE THREAD

**Issue by p-dahlback** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#21]
Hello! I've been testing this library in an iOS application, and I have a question that I haven't seen answered here yet.

In my use case, I need to switch between two songs on the file system gaplessly, so that one file plays straight into the next one. I want to keep effects such as tempo etc. so that the user can't immediately distinguish where one song ends and the next begins. As far as I can see in the docs, there is no dedicated API that would do this for me right now.

I've tried creating two SuperpoweredAdvancedAudioPlayers and playing one of them after the other, which produces a noticeable gap. I guess I could try to cross-fade between them during the last second or so, but if at all possible I'd prefer for them to just flow into each other with no overlap. 

Any suggestions for solving this would be very much appreciated!

**Comment by superpoweredSDK** [comment]
I recommend to have two players, and check the positionMs property in every callback turn. You will also need precise information where track A ends and track B begins. For compressed files such as mp3 you need to calculate more as they always begin with silence due the decoder's nature.

**Comment by p-dahlback** [comment]
Thanks, this seems to work pretty well. Just to double-check - from what I can find online, 529 samples is the most used decoder delay in MP3's. Is this the case for Superpowered as well?

**Comment by superpoweredSDK** [comment]
Depends on the encoding, but something around that.
