### ISSUE TITLE
Adding library to XCode

### ISSUE THREAD

**Issue by jtrunick** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#210]
I was able to integrate Superpowered with my Android application, but my XCode skills are lacking. I need to add Superpowered to my xcode project. I tried mimicking a Superpowered project, but with no success. 

Is there instructions on how to include superpowered in a separate iOS project? I'd start with an example project, but in this case I don't have that option.

**Comment by superpoweredSDK** [comment]
Drag-and-drop the .a file and the required headers into your project.
Set library search paths to the folder where your .a file and headers are.
That's it.

**Comment by jtrunick** [comment]
That was much simpler than I expected. However, now I'm stuck on the build step:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MPMusicPlayerController", referenced from:
      objc-class-ref in SuperpoweredIOSAudioIO.o
ld: symbol(s) not found for architecture x86_64

I tried adding x86_64 architecture to the build settings, although I don't see that parameter in the example projects, but it doesn't help anyway.
