### ISSUE TITLE
beatgrid start is always zero

### ISSUE THREAD

**Issue by marcuseckert** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#212]
Hi,
I'm using the sample code from https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/blob/master/SuperpoweredOfflineProcessingExample/SuperpoweredOfflineProcessingExample/ViewController.mm to get some info from a track but the beatgridStartMs value is always zero. The bpm seems to be correct but even if I shorten the song a bit the start remains zero. Does that mean it couldn't find a start? I've tried different songs as well without any luck.

**Comment by superpoweredSDK** [comment]
The example project works properly returning with meaningful results. It means that your custom implementation has some problems. This is not an issue of the Superpowered SDK, but your custom code, so i close this. Please check our support options: http://superpowered.com/support
