### ISSUE TITLE
Quality issue with pitchshift in iOS

### ISSUE THREAD

**Issue by proishere** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#213]
Hi,

I am using the same code as the cross-example both for android and ios. I am using wav files. If I use playerA->setPitchShift(-1) or playerA->setPitchShift(1), the android version has no quality issue, i mean it is sounding great, but in iOS, same code, same file, but the quality degrades. Technically the sound quality should sound the same but it is not, it is very poor in iOS. 

Can you please help me out?

Thanks

**Comment by superpoweredSDK** [comment]
We experience the same audio on both operating systems (as Superpowered is independent from the OS). Please send a recording for both iOS and Android.

**Comment by proishere** [comment]
Hi,

Here "*cs.wav" have a pitchshift of 0 and "*c.wav" have a pitchshift of -1. Please listen carefully the files "android c.wav" and "iphone c.wav". Both of them are playing the same file with a pitchshift of -1.

I have recorded all the files from the same device (Nexus 4). 

iOS device is iPhone 6s (os ver: 10.2)
Android device is Nexus 6 (os ver: 6.0.1)

Here is the zipped file containing 4 files
[superpoweredsdk.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/669542/superpoweredsdk.zip)

Thanks

**Comment by superpoweredSDK** [comment]
These recordings are not clean enough to hear properly what's going on. Use the SuperpoweredRecorder for direct recording, or record directly from the headphone output of the devices please.

**Comment by proishere** [comment]
Hi,

I have recorded via speaker out. 

Please have a look, "ios_c.wav" and "android_c.wav", hear the quality.

[superpoweredsdk.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/670760/superpoweredsdk.zip)

Thanks

**Comment by superpoweredSDK** [comment]
The iOS output for both the clean and the pitched version sounds like "doubled", like two players playing with a little phase difference.
Are 100% sure you are using exactly the same code on both iOS and Android, and the same audio file?

**Comment by proishere** [comment]
Hi,

Yes the code is same as cross-example (android and ios), I am only adding setPitchShift() on player load callback. Also, I am not applying any roll, filter or flanger effect like it is shown in the example.

I also ran your crossexample (ios) project and replaced playerA with my file. While checking I noticed that the sound is ok in the simulator but not on the device. I am attaching the same file I used in the android.

[player1.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/671269/player1.zip)

Thanks

**Comment by superpoweredSDK** [comment]
Is this with the latest version of Superpowered? Version 1.0.1?

**Comment by proishere** [comment]
No, I am using 0.9.8

**Comment by superpoweredSDK** [comment]
Can you please update and let me know? There were significant bugfixes in areas of the code involved with your features.

**Comment by proishere** [comment]
Yes I checked it on 1.0.1, its having the same output as 0.9.8. Also, in that version 1.0.1, the loop is not happening properly, it is not playing till the end.

I used the cross example for iOS.

**Comment by superpoweredSDK** [comment]
Tested here with various setups, but we hear the same sound regardless of the device. The only sound difference we hear is the devices themselves, which obviously have some different colorization.
Please download the "DJ Player" app for iOS and listen to your file with that application. It has the same Superpowered player inside. https://itunes.apple.com/app/dj-player/id339810085

**Comment by proishere** [comment]
Hey, I downloaded and checked on iphone 6s [os version 10.2(14C92)]. When I change pitch, its the same problem and also, looping is not happening till the end.

I think this is a problem with the os version or a device issue i guess.

**Comment by superpoweredSDK** [comment]
You mean with the DJ Player app?

**Comment by proishere** [comment]
Yes

**Comment by superpoweredSDK** [comment]
Perhaps your problem is the different sound color of the hardware of your different mobile devices.
