### ISSUE TITLE
setBpm has no effect

### ISSUE THREAD

**Issue by bdauria** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#215]
I need to be able to stretch a track up and down, by changing its BPM value. I've been trying to do this using the CrossExample code, but the setBpm has no effect, so I'm wondering what I'm missing. I'm actually able to change the tempo using the setTempo method, but I do need to jump from an actual BPM to another. 

I haven't changed anything to the player initialization:

```
static void playerEventCallbackA(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event, void * __unused value) {
    if (event == SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess) {
    	SuperpoweredAdvancedAudioPlayer *playerA = *((SuperpoweredAdvancedAudioPlayer **)clientData);
        playerA->setBpm(126.0f);
        playerA->setFirstBeatMs(353);
        playerA->setPosition(playerA->firstBeatMs, false, false);
    };
}
```

And I've tried the SyncMode TempoAndBeat, as well as Tempo, no difference.

Thanks in advance for your help.

**Comment by superpoweredSDK** [comment]
SetBpm sets the track's original bpm for syncing. It doesn't change the tempo itself, setTempo does.
