### ISSUE TITLE
Build android examples failed when SDK placed on case sensitive filesystem.

### ISSUE THREAD

**Issue by SiarheiVolkau** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#216]
CMake project looks for libraries as follows:
libSuperpoweredAndroid${ANDROID_ABI}.a

but for x86 and x86_64 its failed to find.
Because CMake looked for libSuperpoweredAndroidx86.a, 
but library named libSuperpoweredAndroidX86.a

same for X86_64.

**Comment by superpoweredSDK** [comment]
That's why that part is renamed in the current versions of the Superpowered SDK.

**Comment by SiarheiVolkau** [comment]
I post this issue for current version.
And where i can get new version?
Why you not push it here?

I think this issue must be closed after releasing related changes here.
