### ISSUE TITLE
[[SuperpoweredIOSAudioIO alloc] initWithDelegate:

### ISSUE THREAD

**Issue by jtrunick** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#219]
Calling this constructor with anything other than preferredBufferSize:12 seems to fail. I get 512 bytes, and would like to get 1024, but setting it to 24 seems to die silently.

**Comment by superpoweredSDK** [comment]
Check line 341 in SuperpoweredIOSAudioIO.mm and modify the limit.
