### ISSUE TITLE
How to include in Android Studio Project

### ISSUE THREAD

**Issue by soundcat** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#22]
Can you please explain how to use the static library in android studio?

**Comment by JMDidon** [comment]
First, you need to download the Android NDK in order to work with the SDK : https://developer.android.com/tools/sdk/ndk/index.html

Then, install the SuperpoweredExample project as stated in the README.txt : 
- Open local.properties. Set ndk.dir to your ndk folder. (note : I personnaly put it in ~/Library/Android/ndk)
- Open build.gradle for the app module. Check for ndk-build, and set the appropriate path.
- Before building the project, uncomment the jni.srcDirs line. This makes the C folder disappear from the view, but don't worry. After a successful build, comment the line again.

I think the easier way to get started is to use the SuperpoweredExample projet and then modify it to suit your needs.

**Comment by b2renger** [comment]
Hello,

I've tried to get started with with superpowered sdk but I failed, I must say that I'm not really a developper and I'm more used to eclipse and uncomfortable with gradle.

So I basically tried to follow the steps, but my build fails complaining about not being able to load a png file and I don't really get it (graddle console log below).  Meanwhile I'll try it with eclipse and see how it goes.

I'm on windows 8, android studio 1.1.0, ndk-r9d, sdk up to date.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Error: Failed to run command:
	D:\Code\Android\sdk\build-tools\build-tools-21.1.2\aapt.exe s -i D:\Code\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\CrossExample\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-ldrtl-xxhdpi\abc_ic_ab_back_mtrl_am_alpha.png -o D:\Code\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\CrossExample\app\build\intermediates\res\debug\drawable-ldrtl-xxhdpi-v17\abc_ic_ab_back_mtrl_am_alpha.png
Error Code:
	42
Output:
	D:\Code\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Android\CrossExample\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-ldrtl-xxhdpi\abc_ic_ab_back_mtrl_am_alpha.png ERROR: Unable to open PNG file

```

**Comment by superpoweredSDK** [comment]
Perhaps you accidentally deleted that file?

**Comment by b2renger** [comment]
Actually i would have prefered because it would have been an easy fix :) I went to check it, it was here and opened fine.

**Comment by b2renger** [comment]
Hello 

I've moved forward a little now I get the error below
(the paths have changed as I moved from windows to latest lts ubuntu and ndk-9rb)

btw what is the  version of the ndk I should use ?


```
:app:ndkBuild
Android NDK: NDK Application 'local' targets unknown ABI(s): arm64-v8a    

/home/berenger/Android_dev/android-ndk-r9b/build/core/setup-app.mk:91: *** Android NDK: Aborting    .  Stop.

Android NDK: Please fix the APP_ABI definition in /home/berenger/Android_dev/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/CrossExample/app/src/main/jni/Application.mk    
make: Entering directory `/home/berenger/Android_dev/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/CrossExample/app/src/main/jni'
make: Leaving directory `/home/berenger/Android_dev/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Android/CrossExample/app/src/main/jni'
:app:ndkBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:ndkBuild'.
> Process 'command '/home/berenger/Android_dev/android-ndk-r9b/ndk-build'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by superpoweredSDK** [comment]
The r9b version of the Android NDK idoesn't contain 64-bit ARM support. We are using r10d, please update.

**Comment by b2renger** [comment]
ok ! this worked for me with ndk-r10d on ubuntu !

maybe you should mention, the ndk version you currently use in the main readme but those indications work :) time to try with another example.
