### ISSUE TITLE
How much time does it take to mix two audios(could be in different formats like mp3 and m4a). Do you have any data on this as you have for latency?

### ISSUE THREAD

**Issue by Kshitij1792** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#220]
Hi,
       I am supposed to mix two audio files(both in different formats) on android. I want to know how much time does Superpowered library take to mix the audios. Does it take almost equal time of the duration of the audio? (like say for 3 min audio 3 mins for mixing?).
    I tried ffmpeg library before moving over to Superpowered. Ffmpeg took almost same same time as of the duration of the audio. So before I dig deeper into C++ code I just want to know if Superpowered does it quickly or it would remain same due to mobile device hardware limitations?

I saw the latency test webpage of Superpowered lib, If you have done test on "time taken to mix 2 audios",
please let me know

**Comment by superpoweredSDK** [comment]
Decoding a 3 minutes long audio file with the SuperpoweredDecoder is typically under 5 seconds on the current Android devices. So for two files it will be 10 seconds.

Mixing 3 minutes will take significantly less than 1 seconds. 

You can do the overall job in less than 11 seconds with Superpowered. Your bottleneck will be writing the result to disk.

**Comment by Kshitij1792** [comment]
Just a few follow up questions.
1. "Decoding a 3 minutes long audio file with the SuperpoweredDecoder is typically under 5 seconds "
    Is it true for all of the formats? Even MP3?
2. How long could it typically take just to write MIXED AUDIO on the disk? Any value less than 20 seconds is fine for me. 
and last question.
3. As I know little C++, what book/article or website would you recommend me to go thorough to learn only as much of C++ as its required to deal with Superpowered library? 

I appreciate your efforts for such a quick reply. thanks
