### ISSUE TITLE
Expanding SuperpoweredSimple API

### ISSUE THREAD

**Issue by tipycalFlow** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#221]
Is it possible to add some APIs to SuperpoweredSimple API similar to SuperpoweredAdd2 as provided by iOS vDSP? For ex, the SuperpoweredAdd2 call adds vectors but there are no methods to multiply/divide/subtract vectors or similar signal processing vector operations available in vDSP. Is there any such API expansion planned?

**Comment by superpoweredSDK** [comment]
You are the very first asking for this. Since this is not an "issue" with Superpowered, i close this. If you'd like to continue the discussion with a list of functions you'd like to see, please email hello at superpowered.com.

**Comment by tipycalFlow** [comment]
Yeah, this is an enhancement request. You could mark this issue as an enhancement if the team has plans to add such methods to the SDK in the future.
