### ISSUE TITLE
How to mix two audio files of different lenght and format when smaller audio must repeat after it finishes?

### ISSUE THREAD

**Issue by Kshitij1792** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#222]
I have been trying mix 2 audios using Superpowered lib. Could you tell me the steps to do it correctly.

I have one audio which is say 30 seconds long(in MP3), and I have other "recorded audio" which could be of any length(in .m4a format).
I want to mix it in such a way that MP3 is repeated after 30 seconds for the length of longer audio(the one in .m4a)

How could I achieve this?

What I get through the threds on internet is that I have to take one SuperpoweredMonoMixer object and pass two array of buffer of both audios as first parameter in process(params...) method.

But I dont know HOW TO READ THESE AUDIOS IN BUFFER(because both formats have different formats and headers might be different as well) to pass in process(params...) method, 
and also HOW TO DEFINE SIZE OF output buffer and store output in file.

Could you tell me proper steps. I went through docs but couldn't find examples on mixing.
If you could provide any code template it would be great.

Thanks

**Comment by superpoweredSDK** [comment]
Hello,

this is not an issue with the Superpowered SDK. Please check our various support options here: http://superpowered.com/support , then write us an email.
