### ISSUE TITLE
How to convert wav format to m4a format by superpowered?

### ISSUE THREAD

**Issue by bing2006200** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#223]
I created the wav file with superpowered, but found in the synthesis of WAV files and video files not only too big and error, so I think in the wav file generated by superpowered can real-time into m4a files.
I did not find the corresponding encoder in superpoweredSDK, so how should I do？ @superpoweredSDK, thx a lot.

**Comment by superpoweredSDK** [comment]
Superpowered Audio SDK has no encoder features, sorry. Decoders only.
