### ISSUE TITLE
Recorded file is not written synchronously upon recorder.stop?

### ISSUE THREAD

**Issue by romanbsd** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#225]
Good day,
We are observing a following situation, which looks like a race condition:
1. The java code calls some c++ code via jni, which uses the recorded and at the end of its processing calls recorder->stop()
2. The calling code in java doesn't file the file in the expected location
3. Doing adb shell and ls shows the file in place (with a correct timestamp)
Could it be that stop is not synchronous in this respect? If so, what would be the best way to ensure that the file exists before returning to the calling code?
Thanks.

**Comment by romanbsd** [comment]
We're also observing some even more troubling behavior, after a some Recorder instantiations, once in 5-10 times, the `stop` doesn't produce the result file, and the temporary files are left there lingering (the fileXXX and fileXXX.txt)

**Comment by superpoweredSDK** [comment]
Yes, SuperpoweredRecorder offloads writing to disk to another thread, as disk operations are too slow for an audio processing callback. After calling stop, the actualing closing of the file happens on this thread, which may take some time to complete.

**Comment by romanbsd** [comment]
1. I'd expect that stop would wait for the writing thread, so after stop has returned the file is there. Or provide some other means, e.g. another method.
2. There's still a bug, there sometimes the stop doesn't produce the recording file, and the temporary files are left.
