### ISSUE TITLE
Feature request: vocals separation

### ISSUE THREAD

**Issue by loretoparisi** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#226]
To add vocals separation from music audio sources using advanced audio filtering, out of phase stereo, etc.

**Comment by superpoweredSDK** [comment]
Thank you for the feature request. Please note, this is not an issue with the Superpowered SDK. We're happy to read your feedback at hello@superpowered.com instead.

**Comment by loretoparisi** [comment]
@superpoweredSDK ok, I did it here since some github projects uses labels to categorize issues, and would label this as "featurerequest".
