### ISSUE TITLE
Question: Can we expect distortion and phaser added to Superpowered?

### ISSUE THREAD

**Issue by EtherBit** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#227]
Hello,

Do you guys plan on adding phaser, distortion, and perhaps more effects.

**Comment by superpoweredSDK** [comment]
Hello, yes, there are some plans. Please note, this is not an "issue" with Superpowered, so we close this. We're happy to answer your questions at hello@superpowered.com
