### ISSUE TITLE
loop in reverse mode

### ISSUE THREAD

**Issue by felart** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#229]
hi, superpowered is a really great sdk. 
Actually it's not possible to loop in reverse mode and for me it's a big lake for my project.

Is there any technical reason which could explain it's not possible? Can you plan this functionnality in the future? 

thanks.

**Comment by superpoweredSDK** [comment]
The next update will include this feature.

**Comment by felart** [comment]
good news! thanks.
