### ISSUE TITLE
Question : distortion "effect" with Superpowered SDK

### ISSUE THREAD

**Issue by JMDidon** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#23]
Hello,

I have a simple question : is it possible to "simulate" a distortion effect with Superpowered SDK ? What I mean is the clipping of a signal (e.g : http://en.wikipedia.org/wiki/Distortion_(music)#Theory_and_circuits ). If it is not, how could I do to simulate it ?

Thank you in advance !

**Comment by superpoweredSDK** [comment]
Hello,

the SDK doesn't have a distortion effect yet, sorry.
