### ISSUE TITLE
Feature Request.       Size of .WAV file is way too large(30MB for 3 mins mixed audio file). Could provide a feature to convert it using Superpowered lib itself instead of using other lib for just this task?

### ISSUE THREAD

**Issue by Kshitij1792** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#230]
I am using SuperPowered for audio mixing. Its way too fast compare to other alternatives on the web but it writes the data in only .WAV file and the  file size is way too large(30MB for 3 mins mixed song).

Could you provide some way to write audio files in other formats like .M4A or compressed .WAV or .OGG which would take less memory on the disk?
I read in the issues that you don't provide any encoders. But just to encode the audio into other format using one more extra lib is an overkill. If you could provide audio format conversion in SuperPowered itself. It would help us avoid using anything extra for conversion.
Thanks.

**Comment by superpoweredSDK** [comment]
Thank you for the feature request. Encoders are in our product roadmap, but we're not sure when we get to it.

**Comment by Kshitij1792** [comment]
Thank you very much. Meanwhile could you suggest a way to reduce the size of superpowered generated .WAV file on the disk?  Or the BEST WAY to convert generated .WAV file to other formats(like say .M4A) in minimum time?
I dont want to use ffmpeg again as it takes many MBs of space in the app and its quite slow.
Also when could we expect the encoders to be implemented in the library?

**Comment by svenoaks** [comment]
Generating .wav first is not a good strategy, many users will run out of storage space if the file is of any length. 

You could put the bytes through LAME instead of SuperpoweredRecorder and make mp3 directly. LAME isn't that big. Also you can compile your own custom FFMPEG with only components you need and --enable-small and make really small FFMPEG binaries. I think it will be easier to use LAME in your case though if only for this task.

**Comment by Kshitij1792** [comment]
@svenoaks  Thanks for the valuable info. I agree user may run out of disk space. But correct me if I am mistaken,  mp3 is a licensed format(though its patent-free in the European Union and will become patent-free after Dec 2017 in US too). I was looking for an open format(not licensed). 
1. Could you guide me which open format could I convert my wav file to, in shortest time. I am trying to convert it into .M4A file as of now.
      And I thought of using LAME but MP3 format held me back. 
2. I tried using ffmpeg but the speed to convert 30MB file from WAV to m4a was way too slow. It took ffmpeg around 2 mins to convert this big of a file. 
 Users would never wait for that long. I need something that could do it quickly. 
So in terms of "appropriate disk space" and "quick conversion", which library do you think would suit my needs the best?

**Comment by svenoaks** [comment]
Not legal advice, but you only need a license MP3 if your entity makes over $100K annual gross according to http://mp3licensing.com/help/index.html#2. Also very unlikely anything will happen at this point, and they are about to expire as you said.

Encoding is slow on mobile, I have not used or seen anything that is very fast. LAME does 5:30 file in 30 seconds on my Moto X Pure (2015). It could easily be 2 mins on some devices. I have found native FFMPEG m4a encoding to be about the same speed as LAME. Just do it on separate thread in some notification.

**Comment by Kshitij1792** [comment]
Agreed. 
FFMPEG took around 3 mins on my MOTO G4 plus. Though from your statements it seems like its quite quicker than this. Would you please explain a brief about this 
"I have found native FFMPEG m4a encoding to be about the same speed as LAME. "
What does "native ffmpeg" encoding means? I was using this https://github.com/WritingMinds/ffmpeg-android wrapper library before for mixing... and it was quite slow. 
But from your comments I can make out I am not doing it the right way.
Do you mean I have to compile my own version of FFMPEG for directly passing the int arrays(after mixing) from Superpowered to ffmpeg for writing the .M4A file?
Thanks a lot for all this guidance so far.

**Comment by Kshitij1792** [comment]
@superpoweredSDK @svenoaks  And one last thing. Can I directly pass these short array buffers from superpowered lib to ffmpeg so that I dont have to write it in .WAV file. Because as you pointed out user might run out of space for large files.

**Comment by svenoaks** [comment]
If you don't use SuperpoweredRecorder you will have to handle the threading
yourself with a wait free queue in between them, but it will be better.

**Comment by Kshitij1792** [comment]
@svenoaks could you post a link here for guidance. I am reading about "wait free queues" and threading in C++... But a post to provide a some sample about it would help alot. 
thanks

**Comment by svenoaks** [comment]
If you are processing audio live in the opensl callback you can not block. So if you are recording and writing to SuperpoweredRecorder and wanted to something else besides use SuperpoweredRecorder there you would need to have a structure to push the recorded bytes to and another thread which will do encoding and writing to disk. You can not use locks in audio processing thread so you need lock-free structure. 

This will work on Android and can grow dynamically: https://github.com/cameron314/readerwriterqueue

Also the boost spsc_queue lock free which is the one I use, but I'm not sure if it can grow dynamically which seems important for this application.

**Comment by Kshitij1792** [comment]
@svenoaks  I am not using SuperpoweredRecorder for recording because my user can try out many different background sounds to mix with, before he actually saves it on disk with the chosen one. That's why I am using android's AudioRecord class for recording.
After I have the users recording saved on the disk I am using just SuperpoweredStereoMixer instance to decode it and mix... and the huge size issue comes in here... So all I need is an encoder here to pass those decoded buffer of short int array to encode the audio file right away.
And I am still studying the things you pointed out. They indeed require deep knowledge. You seem to have quite good understanding of audio processing. Thanks for all of your valuable comments on this issue @svenoaks .

**Comment by svenoaks** [comment]
If using API 18+ you can also MediaCodec/MediaMuxer to make m4a in Java w/o any libraries.

**Comment by Kshitij1792** [comment]
Thanks for pointing this out. I hadn't thought of using it at all. :) And it worked great to convert the 30 MB .wav file to m4a. The only thing I couldn't manage is to pass directly the raw audio buffers from Superpowered library to MediaCodec class. Is it possible at all? or I have to write the WAV file first anyway and then convert?
If MediaCodec could directly accept buffers from Superopowered library, then this task would be all done. 
Any idea about it? I am already reading out threads on internet. No significant info so far.
