### ISSUE TITLE
Require help with SuperPoweredMonoMixer

### ISSUE THREAD

**Issue by AniOktalk** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#231]
Hello, I've trying to use the mono mixer in an Android app. The problem is, I can't get it to work. I follow the following steps for this:

- Get the 2 audio streams as PCM 16 bit LE, and put them in Short Buffers
- Convert into float values between [-1, 1]
- Pass these values to SuperPoweredMixer method. The input** points to these 2 float arrays. I pass output array as the output*. Output gain is 1. Samples is input as 2048
- After processing, I convert the float* output back to shorts, and store in an output file
When I run the code, it gives me Segfault sometimes. When it does work, the output is just noise.

Please point me in the right direction. I am not well versed in Audio/DSP. Please bear with foolish questions, if any.

**Comment by superpoweredSDK** [comment]
When does it segfault, at which line? What are you doing at that line?

**Comment by AniOktalk** [comment]
1. Java code which gets the InputStreams from audio files and calls the JNI method:
`private static void mixAudioSuperpowered(InputStream foregroundStream, InputStream backgroundStream,
        OutputStream outputStream) throws IOException {

        DataInputStream disFG = new DataInputStream(foregroundStream);
        int fgBufferSize = disFG.available();
        byte[] byteArrayFG = new byte[fgBufferSize];
        disFG.read(byteArrayFG);
        ByteBuffer bb = ByteBuffer.wrap(byteArrayFG);
        bb.order(ByteOrder.LITTLE_ENDIAN);

        short[] foregroundArray = new short[fgBufferSize / 2];
        int index = 0;
        while (bb.hasRemaining()) {
            foregroundArray[index] = bb.getShort();
            index++;
        }
        disFG.close();

        DataInputStream disBG = new DataInputStream(backgroundStream);
        int bgBufferSize = disBG.available();
        byte[] byteArrayBG = new byte[bgBufferSize];
        disBG.read(byteArrayBG);
        ByteBuffer bbBG = ByteBuffer.wrap(byteArrayBG);
        bbBG.order(ByteOrder.LITTLE_ENDIAN);

        short[] backgroundArray = new short[fgBufferSize / 2];
        int indexBG = 0;
        while (indexBG < fgBufferSize / 2) {
            // If the bg buffer has reached the end, rewind the buffer and add the bytes again
            if (!bbBG.hasRemaining()) {
                bbBG.rewind();
            }
            backgroundArray[indexBG] = bbBG.getShort();
            indexBG++;
        }
        disBG.close();

        // Convert to [-1, 1] float range before transferring to Superpowered
        float[] floatBufferFG = AudioRecordingTask.shortsToFloats(foregroundArray);
        float[] floatBufferBG = AudioRecordingTask.shortsToFloats(backgroundArray);

        // Superpowered Lib call
        float[] outputBuffer = new SuperPoweredLib().audiomix(floatBufferFG, floatBufferBG);

        // Convert output from [-1, 1] float to PCM shorts
        short[] outputShorts = AudioRecordingTask.floatsToShort(outputBuffer);

        DataOutputStream dos = new DataOutputStream(outputStream);
        for (short outShort : outputShorts) {
            dos.writeShort(outShort);
        }
        dos.close();
    }`

1.5. Helper methods for short to float and float to short conversions:
`public static float[] shortsToFloats(short[] shorts) {
        float[] floats = new float[shorts.length];
        for (int i = 0; i < shorts.length; i++) {
            // Range between -1 and 1
            floats[i] = shorts[i] / 32768.0f;
        }
        return floats;
    }`

`public static short[] floatsToShort(float[] audioFloats) {
        short[] audioShorts = new short[audioFloats.length];
        for (int i = 0; i < audioFloats.length; i++) {
            float processedFloat  =  audioFloats[i] * 32768;

            if (processedFloat < -32768 )
                processedFloat = -32768;
            else if (processedFloat > 32768 - 1)
                processedFloat = 32768 - 1;

            audioShorts[i] = (short) processedFloat;
        }
        return audioShorts;
    }`

2. JNI method which calls the Superpowered lib function:

`extern "C" JNIEXPORT jfloatArray Java_com_oktalk_superpoweredsdk_SuperPoweredLib_audiomix(JNIEnv * __unused javaEnvironment, jobject __unused obj,
    jfloatArray bgSoundBuffer, jfloatArray fgSoundBuffer) {

    __android_log_print(ANDROID_LOG_ERROR, "SuperPoweredLib", "%s", "Inside Java_com_oktalk_superpoweredsdk_SuperPoweredLib_audiomix");
    int fgArrayLength = javaEnvironment->GetArrayLength(fgSoundBuffer);
    // Get c++ handles to the jfloat arrays
    float* bgInputArr = new float[fgArrayLength];
    float* fgInputArr = new float[fgArrayLength];
    javaEnvironment->GetFloatArrayRegion(bgSoundBuffer, 0, fgArrayLength, bgInputArr);
    javaEnvironment->GetFloatArrayRegion(fgSoundBuffer, 0, fgArrayLength, fgInputArr);

    // Declare the Result array
    float* outputArr = new float[fgArrayLength];

    int lengthBG = javaEnvironment->GetArrayLength(bgSoundBuffer);
    int lengthFG = javaEnvironment->GetArrayLength(fgSoundBuffer);
    __android_log_print(ANDROID_LOG_ERROR, "SuperPoweredLib", "%s %d %d", "Initialised arrays", lengthBG, lengthFG);
    // Prepare 2d array of inputs
    float** inputArr = new float*[4];
    inputArr[0] = bgInputArr;
    inputArr[1] = fgInputArr;

    // Set input levels for the input sounds
    float* inputLevels = new float[4];
    inputLevels[0] = 0.5;
    inputLevels[1] = 1;

    __android_log_print(ANDROID_LOG_ERROR, "SuperPoweredLib", "%s", "Calling SuperPowered Lib method");
    // SUPERPOWERED LIB CALL: Mix audio signal buffers and write into output file
    SuperpoweredMonoMixer *monoMixer = new SuperpoweredMonoMixer();
    monoMixer->process(inputArr, outputArr, inputLevels, 1, fgArrayLength);

    // Set the output in jFloatArray
    __android_log_print(ANDROID_LOG_ERROR, "SuperPoweredLib", "%s", "Setting result array");
    jfloatArray result = javaEnvironment->NewFloatArray(fgArrayLength);
    javaEnvironment->SetFloatArrayRegion(result, 0, fgArrayLength, outputArr);

    // Free the input array
    __android_log_print(ANDROID_LOG_ERROR, "SuperPoweredLib", "%s", "Freeing memory");
    free(inputArr);
    free(inputLevels);
    free(outputArr);
    free(bgInputArr);
    free(fgInputArr)

    __android_log_print(ANDROID_LOG_ERROR, "SuperPoweredLib", "%s", "Processing done");
    return result;
}`

monoMixer->process is where the segfault happens. Sometimes, it goes through, and the output is mostly noise. Am I doing anything wrong here?

**Comment by AniOktalk** [comment]
There is another approach which I took. I am directly working on the files, and getting the buffers in the JNI method now. Here's the code:

`extern "C" JNIEXPORT void Java_com_oktalk_superpoweredsdk_SuperPoweredLib_audiomixfiles(JNIEnv * __unused javaEnvironment, jobject __unused obj,
    jstring jBgSoundFile, jstring jFgSoundFile, jstring jOutputFile) {

    __android_log_print(ANDROID_LOG_ERROR, "SuperPoweredLib", "%s", "Inside Java_com_oktalk_superpoweredsdk_SuperPoweredLib_audiomixfiles");
    // Get c++ handles to the jfloat arrays
    const char* bgSoundFile = (char *) javaEnvironment->GetStringUTFChars(jBgSoundFile, NULL);
    const char* fgSoundFile = (char *) javaEnvironment->GetStringUTFChars(jFgSoundFile, NULL);
    const char* outputFilePath = (char *) javaEnvironment->GetStringUTFChars(jOutputFile, NULL);

    __android_log_print(ANDROID_LOG_ERROR, "SuperPoweredLib", "%s\n%s\n%s\n%s\n",
                        "Inside Java_com_oktalk_superpoweredsdk_SuperPoweredLib_audiomixfiles",
                        bgSoundFile, fgSoundFile, outputFilePath);

    FILE *fileBG = fopen(bgSoundFile, "r");
    fseek(fileBG, 0, SEEK_SET );
    FILE *fileFG = fopen(fgSoundFile, "r");
    fseek(fileFG, 0, SEEK_SET );

    __android_log_print(ANDROID_LOG_ERROR, "SuperPoweredLib", "%s", "Calling SuperPowered Lib method");

    std::ofstream outputFile;
    outputFile.open(outputFilePath);

    SuperpoweredMonoMixer* mixer = new SuperpoweredMonoMixer();
    // Processing.
    while (true) {
        // Create a buffer for the 16-bit integer samples coming from the decoder.
        short int *intBufferBG = (short int *) malloc(1024 * sizeof(short int));
        // Create a buffer for the 16-bit integer samples coming from the decoder.
        short int *intBufferFG = (short int *) malloc(1024 * sizeof(short int));

        size_t ret = fread(intBufferBG, sizeof(short), 1024, fileBG);
        if (ret == 0) {
            __android_log_print(ANDROID_LOG_ERROR, "SuperPoweredLib", "%s", "Rewind BG buffer");
            fseek(fileBG, 0, SEEK_SET );
            fread(intBufferBG, sizeof(short), 1024, fileBG);
        }
        size_t retfg = fread(intBufferFG, sizeof(short), 1024, fileFG);
        if (retfg == 0) {
            __android_log_print(ANDROID_LOG_ERROR, "SuperPoweredLib", "%s", "FG Buffer over, closing loop");
            break;
        }

        __android_log_print(ANDROID_LOG_ERROR, "SuperPoweredLib", "%s %d %d", "SamplesDecoded:",
                            ret, retfg);

        // Prepare 2d array of inputs
        float** inputArr = new float*[4];
        // Will store bg array here
        inputArr[0] = (float *) malloc(1024 * sizeof(float));
        // Will store fg array here
        inputArr[1] = (float *) malloc(1024 * sizeof(float));
        // Convert the decoded PCM samples from 16-bit integer to 32-bit floating point.
        SuperpoweredShortIntToFloat(intBufferBG, inputArr[0], 1024, 1);
        // Convert the decoded PCM samples from 16-bit integer to 32-bit floating point.
        SuperpoweredShortIntToFloat(intBufferFG, inputArr[1], 1024, 1);

        // Set input levels for the input sounds
        float* inputLevels = new float[4];
        inputLevels[0] = 0.5;
        inputLevels[1] = 1.0;

        float* outputBufferFloat = (float *) malloc(1024 * sizeof(float));

        __android_log_print(ANDROID_LOG_ERROR, "SuperPoweredLib", "%s", "mixer->process call");
        // Apply the effect.
        mixer->process(inputArr, outputBufferFloat, inputLevels, 1, 1024);

        // Convert the PCM samples from 32-bit floating point to 16-bit integer.
        short int* outputBufferInt = (short int *) malloc(1024 * sizeof(short int));
        SuperpoweredFloatToShortInt(outputBufferFloat, outputBufferInt, 1024);

        __android_log_print(ANDROID_LOG_ERROR, "SuperPoweredLib", "%s", "Write to output file");
        // Write the audio to disk.
        outputFile.write(reinterpret_cast<const char *>(&outputBufferInt), sizeof(outputBufferInt));

        // Free the input array
        __android_log_print(ANDROID_LOG_ERROR, "SuperPoweredLib", "%s", "Freeing buffer memories");
        free(intBufferBG);
        free(intBufferFG);
        free(outputBufferFloat);
        free(outputBufferInt);
        free(inputLevels);
        free(inputArr);
    }

    // Free the input array
    __android_log_print(ANDROID_LOG_ERROR, "SuperPoweredLib", "%s", "Close files");
    fclose(fileBG);
    fclose(fileFG);
    outputFile.close();
    __android_log_print(ANDROID_LOG_ERROR, "SuperPoweredLib", "%s", "Processing done");
}`

Which leads to the following output:

`01-19 23:43:23.392 3365-3929/com.oktalk.app E/SuperPoweredLib: Inside Java_com_oktalk_superpoweredsdk_SuperPoweredLib_audiomixfiles
01-19 23:43:23.393 3365-3929/com.oktalk.app E/SuperPoweredLib: Inside Java_com_oktalk_superpoweredsdk_SuperPoweredLib_audiomixfiles
                                                               /storage/emulated/0/Android/data/com.oktalk.app/files/Music/49fc8cad-1052-4292-8d0b-900055eaa925.pcm
                                                               /storage/emulated/0/Android/data/com.oktalk.app/files/Music/8796ade1-8a2f-4289-a048-ac18e6df60a8.pcm
                                                               /storage/emulated/0/Android/data/com.oktalk.app/files/Music/bg_merged.pcm
01-19 23:43:23.393 3365-3929/com.oktalk.app E/SuperPoweredLib: Calling SuperPowered Lib method
01-19 23:43:23.393 3365-3929/com.oktalk.app E/SuperPoweredLib: SamplesDecoded: 1024 1024
01-19 23:43:23.393 3365-3929/com.oktalk.app E/SuperPoweredLib: mixer->process call
                                                               
                                                               --------- beginning of crash
01-19 23:43:23.393 3365-3929/com.oktalk.app A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x656c6966 in tid 3929 (Thread-31)
                                                    
                                                    [ 01-19 23:43:23.394   398:  398 W/         ]
                                                    debuggerd: handling request: pid=3365 uid=10349 gid=10349 tid=3929
01-19 23:43:23.487 3940-3940/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-19 23:43:23.488 3940-3940/? A/DEBUG: Build fingerprint: 'motorola/athene_f/athene_f:7.0/NPJ25.93-11/12:user/release-keys'
01-19 23:43:23.488 3940-3940/? A/DEBUG: Revision: 'p2a0'
01-19 23:43:23.488 3940-3940/? A/DEBUG: ABI: 'arm'
01-19 23:43:23.488 3940-3940/? A/DEBUG: pid: 3365, tid: 3929, name: Thread-31  >>> com.oktalk.app <<<
01-19 23:43:23.488 3940-3940/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x656c6966
01-19 23:43:23.488 3940-3940/? A/DEBUG:     r0 000000ff  r1 ac315204  r2 8852e914  r3 8d8ad010
01-19 23:43:23.488 3940-3940/? A/DEBUG:     r4 8d8ae010  r5 656c6966  r6 00000073  r7 8d8af000
01-19 23:43:23.488 3940-3940/? A/DEBUG:     r8 00000073  r9 656c6966  sl ac315200  fp 8852e978
01-19 23:43:23.488 3940-3940/? A/DEBUG:     ip 84bb09e0  sp 8852e894  lr 84b40a70  pc 84b43128  cpsr 200f0010
01-19 23:43:23.489 3940-3940/? A/DEBUG: backtrace:
01-19 23:43:23.489 3940-3940/? A/DEBUG:     #00 pc 00012128  /data/app/com.oktalk.app-2/lib/arm/libSuperpoweredlib.so`

I think i may not be correctly providing the inputs to the process method. P.S. both the input files are PCM 16 bit LE.

**Comment by superpoweredSDK** [comment]
This crash is related to your custom code, not Superpowered itself, so i close this issue.
We are a digital signal processing technology research and development company. We don't provide custom code review services for free.
Please check our various support options here: http://superpowered.com/support
Hint: yes, you are passing some invalid memory addresses.
