### ISSUE TITLE
decoder returns incorrect data

### ISSUE THREAD

**Issue by nevosegal** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#233]
I am trying to open a _mono_ 16-bit wav file. the length of the file is 100,000 samples. The decoder returns 100,000 samples, but every other sample is a duplicate of the previous one, something like interleaved stereo. But as the length remains 100,000 samples, some data doesn't exist.

Is this related to the bug you mentioned in #149 ?

Thanks.

**Comment by superpoweredSDK** [comment]
The SuperpoweredDecoder returns with stereo data for mono sources, it's not a bug, but a feature!

**Comment by nevosegal** [comment]
Yes, but if it were stereo the length of the data would have been double, and it's not... So there is something weird happening.
