### ISSUE TITLE
mips64 ABI build FAILED

### ISSUE THREAD

**Issue by bhavishy6** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#234]
I am trying to use the superpowered library in my Android project. I have included the CMakeLists.txt, SuperpoweredExample.cpp, and SuperpoweredExample.h. In the IDE, the java source files and the cpp methods are properly linked and I am able to call the methods I need (ie onPlayPause(boolean play)). 
However, when I go to run on my Google Pixel XL , I get the following message

> `Error:error: '~/Developer/Superpowered/libSuperpoweredAndroidmips64.a', needed by '/Users/Bhavish/Developer/AndroidStudioProjects/Loop/app/build/intermediates/cmake/debug/obj/mips64/libSuperpoweredExample.so', missing and no known rule to make it`

Any tips on how to go about fixing this would be greatly appreciated.
Thank you.

**Comment by superpoweredSDK** [comment]
Superpowered supports 32-bit Intel and ARM, and 64-bit Intel and ARM processors. MIPS is not supported. The number of Android devices with MIPS on the market is extremely low.

**Comment by bhavishy6** [comment]
Using the same CMakeLists.txt from the examples, my ANDROID_ABI is always being detected as MIPS. However, I know that is the wrong instruction set for the device chosen. Do you have any suggestions on how to fix this?
