### ISSUE TITLE
SuperpoweredAndroidAudioIO multiple recycling

### ISSUE THREAD

**Issue by bing2006200** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#235]
hi，@SuperpoweredSDK,
I want to record after the playback, I can play, SuperpoweredAndroidAudioIO crash, I would like to ask, how can we do SuperpoweredAndroidAudioIO multiple recycling (parameters are not the same)?

**Comment by superpoweredSDK** [comment]
I don't fully understand. Just destruct the one instance of SuperpoweredAndroidAudioIO, wait a little bit (destruction happens asynchronously), then create a new one.
Or just set up SuperpoweredAndroidAudioIO with recording, and while you don't need audio input, just ignore the incoming buffer.
