### ISSUE TITLE
Can superpowered library feed output buffers after mixing  to MediaCodec API of Android in C++ only?(instead of passing it to java code for encoding)

### ISSUE THREAD

**Issue by Kshitij1792** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#236]
I tried to feed the "output buffer" (after mixing two audios from Superpowered lib) to MediaCodec API of android. But its not working. I passed the "short int" output buffers to JAVA code using callback but it didnt work. Also I am not sure if the MediaCodec API of android can keep pace with the mixing speed of Superepowered. 
I know MediaCoded class also uses C++ api to do all the stuff at low level. So could you tell me how can I directly pass raw output data(short int output buffer) to MediaCodec API for encoding in native way using C++? I dont think passing the output buffers to Java code from C++ and then encode is a right choice. Encoding in C++ itself would save a lot of burden and time.

**Comment by superpoweredSDK** [comment]
We can help with this, sorry. Since this is not an issue with the Superpowered SDK, i close this.

**Comment by Kshitij1792** [comment]
At least guide the users of Superpowered if it is possible at all or not?
