### ISSUE TITLE
Can an instance of SuperpoweredAdvancedAudioPlayer switch between different audio files?

### ISSUE THREAD

**Issue by dkorobov2** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#237]
I am trying to make an instance of SuperpoweredAdvancedAudioPlayer play different audio files in succession depending on user input. When I open the first audio file it plays without problems, but subsequent audio files do not get opened or played. This is how I am trying to switch between audio files:

`playerA->open(apkPath,start_index,file_size);
 playerA->seek(0);
 playerA->play(false);`

Am I doing something wrong or is this just a limitation in the Superpowered SDK? Thanks

**Comment by svenoaks** [comment]
You probably are not waiting for the callback, it is opening asynchronously.

**Comment by dkorobov2** [comment]
I made some adjustments based on your advice but I am still having the same problem. In my current implementation when I want to change a track, I call: 
`playerA->pause();` 
`playerA->open(apkPath,start_index,file_size);`,
wait for the LoadSuccess event to trigger and then call 
`playerA->seek(0); `
`playerA->play(false) `
in the callback. Am I missing something here?

**Comment by superpoweredSDK** [comment]
Do you get the loadsuccess event after the subsequent opens?

**Comment by dkorobov2** [comment]
No, I am only getting a loadsuccess for the first open.

**Comment by superpoweredSDK** [comment]
Then your subsequent loads are not happening at all. Perhaps start_index and file_size are wrong.
start_index should have the byte offset where the audio file starts in apkPath
file_size should indicate the audio file's size in bytes (byte length from start_index)

**Comment by mlostekk** [comment]
I am having the same issue with loading the exact same file subsequently (with waiting for SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess for the first load)
