### ISSUE TITLE
SuperpoweredCompressor / SuperpoweredLimiter gain volume where they should not

### ISSUE THREAD

**Issue by Nicknag** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#238]
Hi,
I am using the SuperpoweredCompressor on an audio input. I noticed that the volume peaks with the compressor enabled are higher than without. I have set up the compressor as follows:
```
    compressor = new SuperpoweredCompressor(recordingSamplerate);
    compressor->inputGainDb = 0.0f;
    compressor->wet = 1.0f;
    compressor->hpCutOffHz = 1.0f;
    compressor->attackSec = 0.003f;
    compressor->releaseSec = 0.3f;
    compressor->ratio = 6.0f;
    compressor->thresholdDb = -6.0f;
    compressor->outputGainDb = 0.0f;
    compressor->enable(true);
```

Without the compressor enabled I get a maximum input level of 1.0f and with the compressor enabled with the settings above I get a maximum value of 1.27f. Similar issue with the limiter.

This is how I do the processing and get the peak value.
```
bool OverdubSession::process(short int *in_out, unsigned int numberOfInputSamples) {

    SuperpoweredShortIntToFloat(in_out, stereoInputBuffer, numberOfInputSamples);

    compressor->process(stereoInputBuffer, stereoInputBuffer, numberOfInputSamples);

    // Getting the peak value
    recordingPeak = std::max(SuperpoweredPeak(stereoInputBuffer, 2 * numberOfInputSamples), recordingPeak);
```
Any help on this? 

Thanks
Nick

**Comment by superpoweredSDK** [comment]
Please record this and put it into a wave editor to see what actually happens.

**Comment by Nicknag** [comment]
Hi,
I recorded three tracks and compared them visually. I attached three screenshots for you. In each one the first track is plain playback, the second is with compressor enabled and the third with limiter enabled.

Compressor settings
```
    compressor->inputGainDb = 0.0f;
    compressor->wet = 1.0f;
    compressor->hpCutOffHz = 1.0f;
    compressor->attackSec = 0.003f;
    compressor->releaseSec = 0.3f;
    compressor->ratio = 3.0f;
    compressor->thresholdDb = -6.0f;
    compressor->outputGainDb = 0.0f;
    compressor->enable(true);
```

Limiter settings:
```
    limiter->thresholdDb = -6.0f;
    limiter->ceilingDb = 0.0f;
    limiter->enable(true);
```

![plain_comp_limit01](https://cloud.githubusercontent.com/assets/19332273/22650490/bf91b874-ec7f-11e6-80e2-ea65fad05de7.PNG)
![plain_comp_limit02](https://cloud.githubusercontent.com/assets/19332273/22650491/bf951eba-ec7f-11e6-9799-096d0180a258.PNG)
![plain_comp_limit03](https://cloud.githubusercontent.com/assets/19332273/22650492/bf9b019a-ec7f-11e6-8663-0a1c561f1e59.PNG)

**Comment by Nicknag** [comment]
You can even hear that the limited file is louder. I attach them for you as well.

[wavfiles.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/754869/wavfiles.zip)

**Comment by Nicknag** [comment]
Hi Superpowered Team,
did you have a look at this?
Regards
Nick
