### ISSUE TITLE
Timing Bug / Issues With Small Audio Loops (Clips)

### ISSUE THREAD

**Issue by developeruk** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#239]
Hi there.. was wondering if anyone could help

I'm using SuperpoweredSDK on Android. I started off by going through the Cross Example project. and have now begun my own project. 

My idea, is to create a program which triggers off small Audio loops / clips (no more than 4 bars or so) across the different players,  these loops should all be in sync, locked to a master BPM. Well...thats the plan anyway.....

1) So i've started off  having a couple of short audio clips, Which are in WAV format. I've loaded them into the player, They load and playback fine. 

However, my issue is, the looping, first of all, they dont seem to lock in together. So instead, for test purposes, i've loaded a copy of the same sample in two different players. 

They start off looping as normal, but when i leave the loops to play for a while, the loop starts to mess up majorly. This will happen to just one of the players playing on its own...

Each time it loops, the duration of the loop gets shorter and shorter. For example, I have a Drumbeat which starts off as 3000 ms when its first loaded..upon several loops in, its gradually shortens to 2035 ms and continues to reduce, which of course is not the full loop anymore, so you can imagine the playback is off. Also i have a tempo slider, which is connected to master tempo..when i change that. sometimes it all goes out of sync badly especially with the loop issue.

Im notified whenever the loop duration shrinks by the "SuperpoweredAdvancedAudioPlayerEvent_DurationChanged" callback..

in this callback, i've tried to set it back to what it was each time it shrinks..  and all types of things, but to no avail. No matter what, the loop never gets bigger, only smaller..Even at a steady tempo, It will still modify the loop to shrink?
What i doing wrong? Am i using the SDK the right way, or is this a glitch? 

Has anybody got a basic project with a couple of short loops looping in sync they are willing to share? I'd be really grateful (incrediblesoftwareuk@gmail.com)

I've attached a link to my unloopy project here
https://drive.google.com/open?id=0B4FOgcvR0zWCZ1VJM29QYUp4d2s

2) My next question, is there a way to get the individual beat of the master tempo. I.e whenever it plays a quarternote, is there a way to get a callback or something. so i can hear or create a metronome to hear if the loops are playing on the "grid"

Id be grateful if anyone has had similar issues, and has found a solution or workaround, id be thankful to hear from you

Thank You

**Comment by smukdp** [comment]
Hi,

we had a similar issue, had a lot of drifting with loops. Had no choice but to align manually every 4th bar (align every sound with Master BPM). Maybe it is wrong but it does the job for us atm (also corrects sounds that do not play on time, which happens when we have queues - like starting 4 sounds at a time). Hope it helps. Below is a snippet of the code which syncs every sound with master BPM every 4th bar - I don't have a simple example though.

// Process sound items, manually set time of sounds to zero if snyc to beat failed (diff is more than 10 ms). Set starting position to -1 ms so it does not leave a possibly selected loop.
        for (int i = 0; i < self.mainApp.boardViewController.soundItems.count; i++) {
            SoundItem *si = [self.mainApp.boardViewController.soundItems objectAtIndex:i];
            if (si.syncWithMasterBpm == YES && si.isPlaying == YES) {
                if (([si getCurrentTimeMs] - [si getClosestBeatMs] - playerMasterBpm->msElapsedSinceLastBeat) > 10 || ([si getCurrentTimeMs] - [si getClosestBeatMs] - playerMasterBpm->msElapsedSinceLastBeat) < -10) {
                    // Set track to position 0 + current position of master bpm.
                    [si setPosition:[si getCurrentTimeMs] - ([si getCurrentTimeMs] - [si getClosestBeatMs] - 1) + playerMasterBpm->msElapsedSinceLastBeat];
                }
            }
        }

**Comment by developeruk** [comment]
Thanks a lot smukdp,

Im on Android, so im going to study that IOS code, and see if i can make sense of it. Im extremely grateful for you to take the time out, and send that.

I cant tell you the amount of hours i've put into trying to fix that issue, i thought it was a mistake that id made somewhere. 

You said your code syncs every sound with master BPM every 4th bar. Im still finding my way around the SDK. How would one go about doing something like that . i.e. getting the beat or bars from the master BPM, is that built into the SDK or something that needs to be written myself?

Thank you very much for your help

**Comment by smukdp** [comment]
No problem.

We get every 1st (or 4th) bar of master BPM like this:

`
  // Get master bpm beat index.
  int masterBmpBeatIndex = self->playerMasterBpm->beatIndex;

... some other stuff ...

if (masterBmpBeatIndex == 1 && playerMasterBpm->msElapsedSinceLastBeat > 0 && queueSynced == false) { `

After this is the code I sent you before. We trigger this in onDisplayLink cycles (that means every couple of ms). We had this in audioProcess of main output before but this is not advised (although it used to work fine for us on iPads).

Again, I don't think it is a by-the-book solution but it works for us - we also had problems when you play a track that is longer (3mins) and then play a loop (both are synced to master bpm) - it starts drifting after couple of loops.

**Comment by developeruk** [comment]
Thank you for your time smukdp. Its much appreciated, im going to give it a go now. Although thinking about it, it sounds as tho i may have a slightly different problem. 

In my case, The loop triggers off ok, but for some reason, the loop begins to shrink after a while as opposed to drifting (which it probably will do when i have a few loops goin so your solutions defo gonna be handy). Its that, or the master tempo is gettin faster on its own, if you catch my drift. 

You did answer my second question about the Master Tempo, and its given me a path as to how im going to solve that problem as i didnt have a clue before lol, So thanks again, youve been very helpful!

**Comment by superpoweredSDK** [comment]
For looping always use the loop() or loopBetween() methods of SuperpoweredAdvancedAudioPlayer.

**Comment by developeruk** [comment]
Thank you SuperpoweredSDK, 

I tried this, during my many attempts and it didnt seem to work, maybe i put it in the wrong place. 

Seeing as looping is already switched on by default, Where would you suggest i put the "loop()" or "loopBetween()"? Would that be in the "SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess" part of the callback, or "SuperpoweredAdvancedAudioPlayerEvent_EOF"

Thank you

**Comment by superpoweredSDK** [comment]
before or after calling play() -- EOF is _not_ looping, but "end of file"
