### ISSUE TITLE
React native bindings?

### ISSUE THREAD

**Issue by hoopes** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#240]
Hi,

I am pretty new to mobile development, so if this question is dumb, please pardon me. I have what I think to be a cool idea for an app, and your library looks good. The library itself is cross platform, and react native is cross platform, so if I can write once and deploy everywhere, that would be great. Are there examples of how to do this? 

If not (or there are obvious reasons why this is a bad idea I'm not aware of yet), then falling back to writing it "natively" is totally fine.

Thank you very much for your time!

**Comment by superpoweredSDK** [comment]
Hi,

we're not React Native users so can't help, sorry.
