### ISSUE TITLE
Bluetooth stuttering issue

### ISSUE THREAD

**Issue by ericharlow** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#241]
There is an issue when routeing the audio output on Android to a Bluetooth speaker or headphone. I experience stuttering and glitches in the audio playback. I have found this to be repeatable on a Samsung S5 running Android 6.0.1 API 23. The stuttering and glitches do not occur during playback when playing on the phone's speakers. I experimented with the default android.media.MediaPlayer it can play audio to Bluetooth devices without stutter on the Samsung S5 Android 6.0.1. Please address this issue.

**Comment by superpoweredSDK** [comment]
Please try with increased buffer size when initializing audio I/O, make it double. Android's lower latency "fast mixer" mode is not very good for Bluetooth. Please let me know your result -- we don't have an S5 to test with.

**Comment by ericharlow** [comment]
Thank you for the response here is what I discovered. I tried setting the buffer size on SuperpoweredAndroidAudioIO to 512. (I feel this is a large number) It did not help the situation. Then I tried changing the (new/newish) internalBufferSizeSeconds in SuperpoweredAdvancedAudioPlayer from 2 to the max 60. My Bluetooth stuttering/glitching is now gone. Such a relief! Thank you for pointing me in the general direction.

Now that I have the internalBufferSizeSeconds set to 60. What is a good size for my SuperpoweredAndroidAudioIO buffer to be? Is there any correlation between what sizes the two buffers should be?

**Comment by superpoweredSDK** [comment]
Please check the cross example project on how the Android device's "native" buffer size is passed from Java to the native (C++) layer. I feel you need to use that buffer size for Bluetooth. As the S5 is likely operating with 48000 Hz sample rate natively, i think the native buffer size will be a multiple of 240. With 960 you'd have rock solid Bluetooth on the S5 --- latency will go up of course.
More data: http://superpowered.com/latency
