### ISSUE TITLE
issue in SuperpoweredCrossExample with small samples

### ISSUE THREAD

**Issue by felart** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#242]
Hi,

I think there's a problem of synchronisation in SuperpoweredCrossExample.

I just replaced example samples  with both of mine (1 bar with 4 beats) :
0006 3-Audio.aif-->120 bpm (detected with SuperpoweredOfflineAnalyzer)
0007 3-Audio.aif-->76.919998 bpm (detected with SuperpoweredOfflineAnalyzer)

they're not synced at all after first loop. I really don't undertstand what's is going on. Maybe a problem with msElapsedSinceLastBeat ?(I don't what it is for).

SDK quality is awesome, bur for me it's hard to understand how to synchronize loops with different bpm.

I put samples and source code in attachment.

Thanks.

[samples and code.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/762057/samples.and.code.zip)

**Comment by superpoweredSDK** [comment]
We're not able to provide you free source code review services. Please check: http://superpowered.com/support

Please check the correctness of your bpm values with another tool. Please set the firstbeatms of the beatgrid to a correct value.

**Comment by felart** [comment]
Hi,

 Thanks for your response.
I understand you can't provide free supprort.

I just wanted advertise about a potential bug. Source code was to illustrate the problem.

bpm value are correct. I export sample from ableton live. firstbeatms of the beatgrid is correct to (it only a kick) and SuperpoweredOfflineAnalyzer give correct information.

I think problem only occurs with short samples.
Thanks.
