### ISSUE TITLE
SuperpoweredDecoder decoded more samples than decoder.durationSamples

### ISSUE THREAD

**Issue by sclimber** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#243]
I used the SuperpoweredDecoder for decoding a 16-bit .wav-file which has 337806 samples on Android. But the SuperpoweredDecoder decoded 337853 samples. I think my file is a valid .wav-file. For other files with more or less samples the SuperpoweredDecoder worked okay.

The file can be downloaded here: https://1drv.ms/u/s!AirBfMLwnS-S-n-8vM40xCsVaPhT
(This file is intended for educational and testing purposes only)

**Comment by superpoweredSDK** [comment]
The four bytes size indicator in the data chunk contains 675612, which indicates 337806 samples, yes.

But the file has 675750 bytes, minus the header of 44 bytes brings 675706 bytes, giving 337853 samples.

WAV files contain many many times bad headers, so SuperpoweredDecoder looks for the entire thing. Will fix this soon.

**Comment by sclimber** [comment]
Thanks

**Comment by superpoweredSDK** [comment]
The next update (coming soon) will have the fix.
