### ISSUE TITLE
 About SuperpoweredSDK on a Samsung phone

### ISSUE THREAD

**Issue by bing2006200** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#245]
hi，@superpoweredSDK, I try to use SuperpoweredSDK to do our audio engine, when found in the Samsung mobile phone will be on the sound, and the delay in testing Samsung mobile phone delay is relatively large, my question is SuperpoweredSDK is not compatible with Samsung mobile phone? Have you tried to call Samsung's jack library?

**Comment by superpoweredSDK** [comment]
Our example projects are not using the Samsung Professional Audio SDK, because it would make our example projects too complex to understand for many developers.
The Superpowered SDK works great with the Samsung Professional Audio SDK.
