### ISSUE TITLE
How to record sound using bluetooth headset

### ISSUE THREAD

**Issue by shivamsingh** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#246]
HI Superpowered Team,

Is it possible to record audio using bluetooth headset ?.
If yes, can you please refer the documents or source code where I can refer it.

**Comment by superpoweredSDK** [comment]
That kind of audio routing can be controlled in Java in Android: https://developer.android.com/reference/android/media/AudioManager.html
