### ISSUE TITLE
Memory Leak SuperpoweredAdvancedAudioPlayer::open ?

### ISSUE THREAD

**Issue by mlostekk** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#247]
Hello,

first of all great library. I am currently evaluating the library and i am not sure, but i guess i have found a memleak. But maybe i am simply using it wrong. Well this is the code.

I wrapped the stuff in `AudioPlayer` class which looks like this

```objc
- (instancetype)init
{
    LOGI(@"initializing audio player");
    self = [super init];
    if(self)
    {
        // init the audio stuff
        lastSampleRate = 0;
        vol            = 1.0f * headroom;
        if(posix_memalign((void **) &stereoBuffer, 16, 4096 + 128) != 0)
        {
            LOGW(@"posix_memalign error, aborting");
            abort();
        }
        player = new SuperpoweredAdvancedAudioPlayer((__bridge void *) self, playerEventCallback, 44100, 0);
        output = [[SuperpoweredIOSAudioIO alloc]
                                          initWithDelegate:(id <SuperpoweredIOSAudioIODelegate>) self
                                          preferredBufferSize:12
                                          preferredMinimumSamplerate:44100
                                          audioSessionCategory:AVAudioSessionCategoryPlayback
                                          channels:2
                                          audioProcessingCallback:audioProcessing
                                          clientdata:(__bridge void *) self];
    }
    return self;
}
 
- (void)cleanup
{
    player->pause(0, 0);
    [output stop];
    output = nil;
    free(player);
    player = NULL;
}

- (void)load:(NSString *)path
{
    LOGI(@"loading track '%@'", path);
    [output stop];
    player->open(path.fileSystemRepresentation);
    [output start];
}

static bool audioProcessing(void *clientdata,
                            float **buffers,
                            unsigned int inputChannels,
                            unsigned int outputChannels,
                            unsigned int numberOfSamples,
                            unsigned int samplerate,
                            uint64_t hostTime)
{
    __unsafe_unretained AudioPlayer *self = (__bridge AudioPlayer *) clientdata;

    if(samplerate != self->lastSampleRate)
    {
        // Has sample rate changed?
        self->lastSampleRate = samplerate;
        self->player->setSamplerate(samplerate);
    };
    bool silence = !self->player->process(self->stereoBuffer, false, numberOfSamples, self->vol, 0.0, -1.0);
    if(!silence)
    {
        SuperpoweredDeInterleave(self->stereoBuffer, buffers[0], buffers[1], numberOfSamples);
    }
    return !silence;
}

void playerEventCallback(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event, __unused void *value)
{
    AudioPlayer *player = ((__bridge AudioPlayer *) clientData);
    switch(event)
    {
        case SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess:
            LOGI(@"SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess");
            break;
        case SuperpoweredAdvancedAudioPlayerEvent_LoadError:
            LOGW(@"SuperpoweredAdvancedAudioPlayerEvent_LoadError");
            break;
        case SuperpoweredAdvancedAudioPlayerEvent_EOF:
            LOGI(@"SuperpoweredAdvancedAudioPlayerEvent_EOF");
            break;
        case SuperpoweredAdvancedAudioPlayerEvent_JogParameter:
            LOGI(@"SuperpoweredAdvancedAudioPlayerEvent_JogParameter");
            break;
        case SuperpoweredAdvancedAudioPlayerEvent_DurationChanged:
            LOGI(@"SuperpoweredAdvancedAudioPlayerEvent_DurationChanged");
            break;
        case SuperpoweredAdvancedAudioPlayerEvent_NetworkError:
            LOGW(@"SuperpoweredAdvancedAudioPlayerEvent_NetworkError");
            break;
        case SuperpoweredAdvancedAudioPlayerEvent_LoopEnd:
            LOGI(@"SuperpoweredAdvancedAudioPlayerEvent_LoopEnd");
            break;
    }
}
```

And if i repeatedly executing

        if(audioPlayer != nil)
        {
            [audioPlayer cleanup];
        }
        audioPlayer = [[AudioPlayer alloc] init];
        [audioPlayer load:currentSong.audioURL];

(Of course both after waiting for the `SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess` callback) I can observe a growing memory allocation. Each time around 4kb.

![shot](https://cloud.githubusercontent.com/assets/10534316/23311088/1981ac16-fab5-11e6-88bb-b0ad965172ff.jpg)

*Is this a mem leak? Or should i have anything in mind re-loading a song? Any tips and tricks for that?*

P.S. Using the audio player pre-instantiated repeatedly

        [audioPlayer load:currentSong.audioURL];
 Does not work at all. The process stops in `load` in `sleepRecursive`

P.S.S. I downloaded the version just right now (24.2.2017)

**Comment by superpoweredSDK** [comment]
I see your allocation summary, not your leak summary. Can you please show that?

**Comment by mlostekk** [comment]
I have reduced my project to a minimum. You can see it here https://github.com/mlostekk/SuperpoweredLeak

If you simply hit "Load" often, you can see the memory growing.

**Comment by superpoweredSDK** [comment]
You are not looking at leaks, but you are looking at your allocation summary, which has the entire history of memory allocations. It's a _history_ of allocations, not the list of _active_ allocations.
So can we look at leaks?
(Btw, please don't use free(player) in your code, it doesn't call the destructor of the player. Use delete player;)

**Comment by mlostekk** [comment]
Thanks for point out to use `delete` instead of `free`. I changed that, but it did not fix it.

Well, Instruments does not show any useful information about leaks. Nevertheless (in the github example above too) the memory keeps growing with each load and at some point the app crashes due to OOM.

![shot2](https://cloud.githubusercontent.com/assets/10534316/23331841/5052fbdc-fb6e-11e6-91cd-1ce5d303dc71.JPG)

I guess i am not cleaning it up properly.

**Comment by superpoweredSDK** [comment]
Seems like you don't free() your stereoBuffer?

**Comment by mlostekk** [comment]
okay. this seems to even more minimize the memory consumption over time.. i will investigate the remaining stuff.. thanks
