### ISSUE TITLE
Queueing AudioBufferLists

### ISSUE THREAD

**Issue by AlexEKoren** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#248]
Hey Superpowered,
The library looks great, but unfortunately I'm not streaming via HLS or reading local files. Is there anyway to, as I stream it audio, queue AudioBufferLists or any other format of PCM data directly and have Superpowered handle the playback?

Thanks!

**Comment by superpoweredSDK** [comment]
If you mean custom data into SuperpoweredAdvancedAudioPlayer, then sorry, we don't offer such feature. Otherwise you can handle audio buffers into a real-time audio processing callback in any ways you want.
