### ISSUE TITLE
Two questions:  WebRTC and Noise Canceling Algorithms

### ISSUE THREAD

**Issue by GQAdonis** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#25]
Have you considered the use of your library as part of a native WebRTC implementation (perhaps in conjunction with the GStreamer-based [OpenWebRTC](http://www.openwebrtc.io/) stack from Ericsson?

Also, do you have any implementation of noise cancellation in the SDK, or would this need to be handled as part of transcoding through Streamer for a WebRTC or audio conferencing app?

Do you have a Google Group set up for this project?

**Comment by superpoweredSDK** [comment]
We have our focus on native app development currently, no plans so far for higher level "umbrella apis", sorry.

We don't have a noise cancelling implementation yet.

As we are getting traction, setting up a group makes sense! :-)
