### ISSUE TITLE
How do I set gain for a audio played by SuperpoweredAdvancedAudioPlayer

### ISSUE THREAD

**Issue by ProsperDevelopment** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#250]
Hi I'm trying to figure out how to control gain. Do I have to use SuperpoweredCompressor somehow? Or SuperpoweredNBandEQ?

I couldn't find any sample code and I havn't been able to figure it out yet with only the class documentation.

**Comment by superpoweredSDK** [comment]
The process() method of the SuperpoweredAdvancedAudioPlayer has a "volume" parameter.
