### ISSUE TITLE
Decoder returns EOF for mp3, and resulting buffer is empty

### ISSUE THREAD

**Issue by 80prozent** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#251]
Hey

I am trying to use the Superpowered decoder on Android to decode mp3 files.

Using it on wav-data, gives me expected results, but for mp3 files, it returns a 0 (SUPERPOWEREDDECODER_EOF).
Inspecting the resulting buffer, all entries are still 0.

After testing with my own mp3 files for a bit, i am now doing some tests on the provided CrossExample.

The AdvancedAudioPlayer plays the file "lycka.mp3" fine:

```
playerA = new SuperpoweredAdvancedAudioPlayer(&playerA , playerEventCallbackA, samplerate, 0);

playerA->open(path, fileAoffset, fileAlength);
```

Now instead of using the AdvancedAudioPlayer, i am trying to run the decoder with the same path/offset/length. But it returns a SUPERPOWEREDDECODER_EOF, and the buffer does not seem to have received any data at all.

```
SuperpoweredDecoder *decoder = new SuperpoweredDecoder();

    decoder->open(path, false, fileAoffset, fileAlength, 0);

    short int * intbuffer=(short int *)malloc(decoder->durationSamples * 4 + 16384);

    unsigned int sam=decoder->durationSamples;

    int decoderResult=decoder->decode(intbuffer, &sam);
```

I would be very happy for any help / info on this topic.

Thanks!

**Comment by superpoweredSDK** [comment]
Check the returning value of decoder->open(). I think you have an open error. Path, fileAoffset or fileAlength may not be correct.

**Comment by 80prozent** [comment]
Hey

Checked the returned value of decoder->open() . It returns NULL, so it should be no error on open.
Also i am using the exact same Path, fileAoffset and fileAlength that is used by the CrossExample-Example to open the file. 
So i think either i have something wrong with the num of samples i request to decode, or there is a bug in the decoder that prevents the buffer from being filled with valid data for mp3.
