### ISSUE TITLE
SuperPowered Spatializer: the absence of a Windows library severely hinders the development of Gear VR / mobile VR applications (e.g. using Unity)

### ISSUE THREAD

**Issue by mathieu-b** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#252]
I wanted to use the spatializer to develop a Gear VR application using Unity on Windows.

When developing for mobile VR (and especially for Gear VR) it is *super* useful to be able to just hit Play and run everything on desktop.

As of now, the only way of listening to the application when developing on Windows, is to upload the binary to the mobile device.

- Running an application by directly hitting play from the editor takes around 5 seconds (good!)
- On the other hand, uploading to the mobile device can take anything between 30 seconds up to more than a minute, depending on the way the mobile devices is connected to the machine running the Unity editor.

This is highly impractical and completely breaks the development / prototyping flow when using Unity on a Windows machine.

Also notice that the vast majority of Unity programmers use the editor on Windows platforms, see: http://hwstats.unity3d.com/editor/

Other existing sound spatialization libraries provide windows binaries, and often OSX ones too.
(e.g. Google VR SDK audio spatializer, Oculus spatializer, Steam Audio Spatializer...)

A solution might be to spin up a Windows 10 developer virtual machine:
https://developer.microsoft.com/en-us/windows/downloads/virtual-machines
and compile the proprietary part of SuperPowered SDK on it.

Cheers!

**Comment by superpoweredSDK** [comment]
Thanks for the feature request!

**Comment by sonicviz** [comment]
+10 to this. Windows version please!

**Comment by mathieu-b** [comment]
@superpoweredSDK Yep, the issue is closed, but no Windows dll seems to be available yet...?

Regards

**Comment by maxv56** [comment]
Hi @superpoweredSDK 
Any release of windows library is planned soon ? 
thanks

**Comment by superpoweredSDK** [comment]
Windows version is available now.

**Comment by sonicviz** [comment]
Awesome! ty

**Comment by mathieu-b** [comment]
Great!
Thanks for the effort

**Comment by hackspanner** [comment]
Why is this issue closed? There does not seem to be a DLL for Windows that we can use for Unity.
