### ISSUE TITLE
only first "open" call is working

### ISSUE THREAD

**Issue by mlostekk** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#253]
When i am trying to "load" a second track into the same `SuperpoweredAdvancedAudioPlayer` the call gets stuck in the "open" call within "sleepRecursive".

You can reproduce it with this app

https://github.com/mlostekk/SuperpoweredLeak

simply hit the button "reload" or "load" once, wait until the song is loaded.. and then hit "reload" again.

**Comment by superpoweredSDK** [comment]
The process() callback of the player should be continuously called. You stop audio I/O, so it doesn't.

**Comment by Xcoder89** [comment]
Can we have a more sophisticated explanation of this? Would be nice to have a AVPlayer replaceCurrentItemWithPlayerItem like function. Calling player->open() seems to get stuck.

**Comment by swan488** [comment]
Hi owner, I tried keeping the audio I/O alive, ie, keep process is being called continuously after calling SuperpoweredAdvancedAudioPlayer::pause(), and the second call to open() still gets stuck in  sleepRecursive. Any advice on how to open another song? are we supposed to destroy the player all together?

**Comment by JazariMusic** [comment]
I have the same issue, and a more detailed explanation would be very helpful. It seems normal that audio processing would be suspended as a user enters an audio file picker view and processing would resume after a selection has been made, but it's my understanding that this is not supported. Seems odd. I can create a new player every time a file is loaded, but that's suboptimal.
