### ISSUE TITLE
No audio for short sounds

### ISSUE THREAD

**Issue by pabitrapadhy** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#255]
Hello,

I have used Superpowered audio engine in our game.
However, we are not able to hear the audio of one of our file click.mp3 (which is short and is of size 4KB).
I see the EOF event, but without any audio.
We presume, it could be a limitation on the engine side, or may be needed some tweak in the stereo buffer or something.

Our settings are same as of the cross-example app.

Here's a link to the sound.
https://drive.google.com/file/d/0B-IgfsAh9Mn4VkJvZXA1NjJzd3M/view?usp=sharing

Let us know, if we could provide some more details.

**Comment by superpoweredSDK** [comment]
Yes, the decoder considers the file too short. Just add some silence.
