### ISSUE TITLE
SuperpoweredIOSAudioIO: Automatically calls `start` when the app enters the foreground, whether I had started the AudioIO or not.

### ISSUE THREAD

**Issue by KevinGAleman** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#257]
In `initWithDelegate` of  `SuperpoweredIOSAudioIO.m`,  the class subscribes to the Notification Center and hooks into a bunch of the iOS lifecycle methods (enter foreground, enter background, media server reset, etc.), and I'm having an issue with my app in some of these circumstances. 

I'm building an app that has scenarios very similar to VoIP apps (audio may start whenever, whether the app is in the foreground or background). In these scenarios, I manually call `start` in `SuperpoweredIOSAudioIO` when I want to start getting data from the microphone, and `stop` when the microphone is no longer in use. However, if my app enters the background and then reenters into the foreground, `onForeground` in `SuperpoweredIOSAudioIO` calls `endInterruption`, which calls `[self start]`, and the microphone starts recording again and sending audio to my delegate, which is not expecting any audio to come through, and can cause issues if I want to start the audio myself later.

Is this design purposeful, or is there a way to refactor the `endInterruption` method to only call `start` if the AudioIO had previously been started?

**Comment by namannik** [comment]
@KevinGAleman, I was running into a similar issue a while back in my app that uses Superpowered.  I ended up making a couple changes to `SuperpoweredIOSAudioIO.h` and `SuperpoweredIOSAudioIO.mm`.  I submitted a pull request for these changes, but I don't believe the changes were pulled in to the Superpowered main branch.

Here are the changes I made:

e9f74668524f9fab18aa7faae609a49c08c7b6e4
c56ea1fc9d0556cab4f950e0b7dd12b89dcf6219

And here's the pull request, which describes the issue I was seeing:

https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/pull/170

**Comment by KevinGAleman** [comment]
@namannik, thanks for pointing me to these commits. I had tested doing something similar in my local fork, and your code looks like a really clean way to fix this, so I pulled what I needed into my project. Hopefully this gets picked up by the Superpowered team; I can't imagine that we're the only people with this scenario.

**Comment by KevinGAleman** [comment]
Another observation on this, @namannik, is that if a phone call or other form of interruption begins, once `endInterruption` is called, the audio session will start once again, whether I wanted it to be started or not. Looks like I have more work to do to ensure my scenarios work properly.

**Comment by superpoweredSDK** [comment]
Extended the class for this. Will update in the SDK later. Until then the fresh code is attached.

[Archive.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/857951/Archive.zip)

**Comment by flagoworld** [comment]
So the newest version never restarts AudioIO if it gets stopped, even if it was stopped due to the operating system? Well, when an app idles in the background(player paused) for a period of time, the AudioIO seems to stop itself and pressing play from the lock screen player or resuming the app causes superpowered to lock up waiting for audio processing.

The solution of course is to make sure AudioIO is started when an interaction event comes in to the app. However, is this documented anywhere? It should be, since iOS is so adamant about releasing unused resources and apps only have to idle for a short period in order to run into this issue.
