### ISSUE TITLE
EXC_BAD_ACCESS in SuperpoweredShortIntToFloat

### ISSUE THREAD

**Issue by alexfoxy** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#258]
I'm getting a crash in the decoder code adapted from the example: 

```
// Create a buffer for the 16-bit integer samples coming from the decoder.
short int *intBuffer = (short int *)malloc(decoder->samplesPerFrame * 2 * sizeof(short int) + 32768);
// Create a buffer for the 32-bit floating point samples required by the effect.
float *floatBuffer = (float *)malloc(decoder->samplesPerFrame * 2 * sizeof(float) + 32768);        
      
// Processing.
while (true) {
    // Decode one frame. samplesDecoded will be overwritten with the actual decoded number of samples.
    unsigned int samplesDecoded = decoder->samplesPerFrame;
    if (decoder->decode(intBuffer, &samplesDecoded) == SUPERPOWEREDDECODER_ERROR) break;
    if (samplesDecoded < 1) break;
            
    // Convert the decoded PCM samples from 16-bit integer to 32-bit floating point.
    SuperpoweredShortIntToFloat(intBuffer, floatBuffer, samplesDecoded);
           
    ...

}
```

The crash log from Firebase is : 

```
Exception name: EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
1 KRFT SuperpoweredStereoMixerShortIntToFloatInterleaved + 1752956
2 KRFT SuperpoweredShortIntToFloat(short*, float*, unsigned int, unsigned int) (SuperpoweredMixer.cpp:665)
3 KRFT Library::sync_load_unlocked(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::function<void (bool)>) + ...
```

Unfortunately I don't have the audio file since it was a userfile. The obvious guess is that the samplesDecoded runs off the end of one of the buffers, but I can't see why this would be given the rest of the sample code.

**Comment by weepy** [comment]
Same dev group here .... 

I could "fix" by making sure that the samplesDecoded doesn't run over the length and reducing before converting to floats. However this seems odd behaviour.

```            if(samplesAdded + samplesDecoded > length) {
                samplesDecoded = length - samplesAdded;
            }
            SuperpoweredShortIntToFloat(intBuffer, floatBuffer, samplesDecoded);
```
            
Here's the file that causes issues ... 
https://drive.google.com/file/d/0Bz-oyxOvcACQM3I3blJITER1bHBHVXNWWmU2dzFWaXpRUWln/view?usp=sharing

**Comment by superpoweredSDK** [comment]
Will test this week.

**Comment by superpoweredSDK** [comment]
Can't reproduce the crash or any memory error with the file attached. There can be a bug in your adaptation.

**Comment by anthonymattana** [comment]
@superpoweredSDK We too are experiencing this same issue and have been debugging for months. Can you recommend some steps to take in attempts to resolve? Can you recommend what might be causing this crash? Anything? Cleary @alexfoxy is not alone, an recommendations or further troubleshooting tips would be greatly appreciated.
