### ISSUE TITLE
[Android] App freezes when opening a file when AndroidAudioIO is stopped

### ISSUE THREAD

**Issue by WendelVolm** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#259]
While testing I encountered a problem which freezes my whole (Android) app. When stop() has been called on AndroidAudioIO, calling open() on the AudioPlayer will cause this issue. 

Reproduction is simple in e.g. the CrossExample. In `SuperpoweredExample.cpp`, at the end of the constructor (line 47), place the following two lines:
```
    audioSystem->stop();
    playerA->open(path, fileAoffset, fileAlength);
```
But it happens at any time, not just right after initialization.

For now, my workaround is calling start(), open(), then stop() again.

**Comment by superpoweredSDK** [comment]
Correct. The player has an internal message queue. If it doesn't run by the audio I/O, it blocks forever.
