### ISSUE TITLE
"AudioFile Read" thread overflow when changing songs often (iOS)

### ISSUE THREAD

**Issue by p-dahlback** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#26]
Hi, I've used the library to implement a playlist, and come across an error that I'd appreciate some help with. During normal usage playing and paging between songs works fine. However, if I start to aggressively and repeatedly page through all the songs, I encounter this error.

What happens is that the callback to my SuperpoweredAdvancedAudioPlayer gets an error with the value "Slip thread launch error." Afterwards, I get a bunch of memory errors before the application crashes. If I look at the threads in my application process, I can see around two hundred "AudioFile Read" and "AudioFile Shadow" threads lying around, so it seems safe to say this is the underlying problem. These only appear after I call SuperpoweredAdvancedAudioPlayer::open, so I assume that the deal is some resources not being properly released when I open new songs.

My question is: are there any limitations on using SuperpoweredAdvancedAudioPlayer::open that would explain this, and is there a form of delete/release management that needs to be done between songs that I'm missing? I didn't find anything in the documentation for this case.

**Comment by superpoweredSDK** [comment]
Please wait with the next open until the player's callback returns with open success or error. I wonder why you open a song so often?
