### ISSUE TITLE
Any way to use the BPM analyzer on the Microphone Input In Swift (iOS)

### ISSUE THREAD

**Issue by kvacquier** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#262]
Hello. Is there any way to get the ppm from the microphone stream in swift (or IOS). Exemple are not clear about microphone and i could not find any interesting information in documentation

**Comment by superpoweredSDK** [comment]
The SuperpoweredOfflineAnalyzer can retrieve bpm. The SuperpoweredIOSAudioOutput can be set up to handle audio input (example in the frequencies example project).

**Comment by kvacquier** [comment]
I understand but how could i give SuperpoweredIOSAudioOutput datas to SuperpoweredOfflineAnalyzer
