### ISSUE TITLE
Problem in Example With CmakeFile

### ISSUE THREAD

**Issue by talpanika6** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#263]
i imported the CrossExample To android Studio and i have this problem:
the main problem that he cant find the file:
CMake Error at CMakeLists.txt:12 (add_library):
  Cannot find source file:
    /Volumes/iMect/iphone/SuperpoweredSDK/Superpowered/AndroidIO/SuperpoweredAndroidAudioIO.cpp

the Log: 
External Native Build Issues
Build command failed.
Error while executing 'C:\Users\talpa\AppData\Local\Android\Sdk\cmake\3.6.3155560\bin\cmake.exe' with arguments {-HC:\Users\talpa\AndroidStudioProjects\BackUp\Github Lib\SuperpoweredSDK\Examples_Android\CrossExample\app\src\main\jni -BC:\Users\talpa\AndroidStudioProjects\BackUp\Github Lib\SuperpoweredSDK\Examples_Android\CrossExample\app\.externalNativeBuild\cmake\debug\armeabi-v7a -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi-v7a -DANDROID_NDK=C:\Users\talpa\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\talpa\AndroidStudioProjects\BackUp\Github Lib\SuperpoweredSDK\Examples_Android\CrossExample\app\build\intermediates\cmake\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=C:\Users\talpa\AppData\Local\Android\Sdk\cmake\3.6.3155560\bin\ninja.exe -DCMAKE_TOOLCHAIN_FILE=C:\Users\talpa\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=16 -DCMAKE_C_FLAGS=-O3 -fsigned-char -DCMAKE_CXX_FLAGS=-fsigned-char -I/Volumes/iMect/iphone/SuperpoweredSDK/Superpowered -DANDROID_PLATFORM=android-16 -DANDROID_TOOLCHAIN=clang -DANDROID_ARM_NEON=TRUE -DANDROID_STL=gnustl_static -DPATH_TO_SUPERPOWERED:STRING=/Volumes/iMect/iphone/SuperpoweredSDK/Superpowered}
-- Check for working C compiler: C:/Users/talpa/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Users/talpa/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/talpa/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: C:/Users/talpa/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/talpa/AndroidStudioProjects/BackUp/Github Lib/SuperpoweredSDK/Examples_Android/CrossExample/app/.externalNativeBuild/cmake/debug/armeabi-v7a
armeabi-v7a
**CMake Error at CMakeLists.txt:12 (add_library):
  Cannot find source file:
    /Volumes/iMect/iphone/SuperpoweredSDK/Superpowered/AndroidIO/SuperpoweredAndroidAudioIO.cpp**
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
CMake Error: CMake can not determine linker language for target: SuperpoweredExample
Build command failed.
Error while executing 'C:\Users\talpa\AppData\Local\Android\Sdk\cmake\3.6.3155560\bin\cmake.exe' with arguments {-HC:\Users\talpa\AndroidStudioProjects\BackUp\Github Lib\SuperpoweredSDK\Examples_Android\CrossExample\app\src\main\jni -BC:\Users\talpa\AndroidStudioProjects\BackUp\Github Lib\SuperpoweredSDK\Examples_Android\CrossExample\app\.externalNativeBuild\cmake\release\armeabi-v7a -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi-v7a -DANDROID_NDK=C:\Users\talpa\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\talpa\AndroidStudioProjects\BackUp\Github Lib\SuperpoweredSDK\Examples_Android\CrossExample\app\build\intermediates\cmake\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=C:\Users\talpa\AppData\Local\Android\Sdk\cmake\3.6.3155560\bin\ninja.exe -DCMAKE_TOOLCHAIN_FILE=C:\Users\talpa\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=16 -DCMAKE_C_FLAGS=-O3 -fsigned-char -DCMAKE_CXX_FLAGS=-fsigned-char -I/Volumes/iMect/iphone/SuperpoweredSDK/Superpowered -DANDROID_PLATFORM=android-16 -DANDROID_TOOLCHAIN=clang -DANDROID_ARM_NEON=TRUE -DANDROID_STL=gnustl_static -DPATH_TO_SUPERPOWERED:STRING=/Volumes/iMect/iphone/SuperpoweredSDK/Superpowered}
-- Check for working C compiler: C:/Users/talpa/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Users/talpa/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/talpa/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: C:/Users/talpa/AppData/Local/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/talpa/AndroidStudioProjects/BackUp/Github Lib/SuperpoweredSDK/Examples_Android/CrossExample/app/.externalNativeBuild/cmake/release/armeabi-v7a
armeabi-v7a
CMake Error at CMakeLists.txt:12 (add_library):
  Cannot find source file:
    /Volumes/iMect/iphone/SuperpoweredSDK/Superpowered/AndroidIO/SuperpoweredAndroidAudioIO.cpp
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
CMake Error: CMake can not determine linker language for target: SuperpoweredExample

please help,
tal

**Comment by superpoweredSDK** [comment]
You need to set your appropriate paths in local.properties

**Comment by talpanika6** [comment]
like this for example:
C:\Users\talpa\AndroidStudioProjects\BackUp\Github Lib\SuperpoweredSDK\Superpowered

**Comment by Nicknag** [comment]
For me it works like this:
superpowered.dir="C\:/path/to/your/Superpowered"

**Comment by talpanika6** [comment]
its work....
thanks

**Comment by bhuvinetsmartz** [comment]
> like this for example:
> C:\Users\talpa\AndroidStudioProjects\BackUp\Github Lib\SuperpoweredSDK\Superpowered

where can i download "SuperpoweredSDK\Superpowered"
