### ISSUE TITLE
Buffer allocation for SuperpoweredAdvancedAudioPlayer::process

### ISSUE THREAD

**Issue by sigmadeltasoftware** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#264]
[According to the SuperpoweredAdvancedAudioPlayer header](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/blob/master/Superpowered/SuperpoweredAdvancedAudioPlayer.h#L456), the process method should get a pointer to a buffer defined as follows:  
> 32-bit interleaved stereo input/output buffer. Should be numberOfSamples * 8 + 64 bytes big

Yet the [CrossExample project](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/blob/master/Examples_Android/CrossExample/app/src/main/jni/SuperpoweredExample.cpp#L33) for example defines it as such: 
`stereoBuffer = (float *)memalign(16, (buffersize + 16) * sizeof(float) * 2);
`

Wouldn't it make more sense to define it like this: 
`stereoBuffer = (float *)memalign(32, (buffersize * sizeof(float) * 2) + 64);` ?

Is there a certain reasoning behind the 16-bit alignment?

**Comment by superpoweredSDK** [comment]
ARM CPU-s are slightly faster for 16 byte (not bit) alignment memory blocks. 32 is not better.
