### ISSUE TITLE
Noise and distorted

### ISSUE THREAD

**Issue by Samsu7609** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#265]
Test CrossExample version 1.0.3
samplerate : 48000  , buffersize : 192
SuperpoweredAndroidAudioIO  audioSystem = new SuperpoweredAndroidAudioIO(samplerate, buffersize, enableInput , true, audioProcessing, this, SL_ANDROID_STREAM_MEDIA, -1, buffersize * 2);

when I set enableInput = true 
player will become Noise and distorted

but wired is same project in "Nexus 6P" work fine but in "Oppo r9s plus"  player will become Noise and distorted

i guess is microphone problem , when i test "Oppo r9s plus" but with headphone player no Noise and distorted ....

Sorry for my poor English..

**Comment by superpoweredSDK** [comment]
The cross example project was made to not handle microphone input, it only outputs audio.
Try the frequency domain example project.
