### ISSUE TITLE
Unable to build Android app on windows

### ISSUE THREAD

**Issue by G7495x** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#268]
I'm stuck trying to build the frequency domain example android app in Windows. Tried modifying local.properties file but no good... Other examples not working either...! Please fix!

**Comment by superpoweredSDK** [comment]
Several other developers are building successfully with Superpowered on Windows. Try to look into the log provided and find the error. Perhaps you need to do slashes in the paths differently.
