### ISSUE TITLE
Capitalization issue

### ISSUE THREAD

**Issue by ILI4S** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#269]
I believe
```
typedef bool (*audioProcessingCallback_C) (void *clientdata, float **inputBuffers, unsigned int inputChannels, float **outputBuffers, unsigned int outputChannels, unsigned int numberOfSamples, unsigned int samplerate, uint64_t hostTime);
```

should be
```
typedef bool (*audioProcessingCallback_C) (void *clientData, float **inputBuffers, unsigned int inputChannels, float **outputBuffers, unsigned int outputChannels, unsigned int numberOfSamples, unsigned int sampleRate, uint64_t hostTime);
```

Since "client data" and "sample rate" are typically represented as two words, camel case should apply. 

The documentation already specifies "client data" as `@param clientData` whereas "sample rate" is `@param samplerate`. Literature available online suggests that sample rate is sometimes written as one word, however—without consulting the OED—my belief is that the term "sample rate" is clearer when written as two words. 🙂

**Comment by superpoweredSDK** [comment]
You know how we love you ILI4S!

**Comment by ILI4S** [comment]
Have  fun in TechStars 👍
