### ISSUE TITLE
SuperpoweredAdvancedAudioPlayer cannot open short audio files (Android)

### ISSUE THREAD

**Issue by Uscher1** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#27]
**SuperpoweredSDK Version 0.8 for Android**
Calling SuperpoweredAdvancedAudioPlayer::open() for an audio file (.m4a) with duration less than 2 seconds results in SuperpoweredAdvancedAudioPlayerEvent_LoadError. On iOS it works fine.
```javascript
SuperpoweredAdvancedAudioPlayer *player;
player = new SuperpoweredAdvancedAudioPlayer(this, callback, "11025", 0);
player->open("/storage/emulated/0/myApp/AudioShort.m4a");
```
The LoadError value parameter returns the error description *"Unknown file format"*.
Find a sample file here: www.eco-soft.ch/download/temp/audioshort.m4a

**Comment by superpoweredSDK** [comment]
I just opened it successfully on Android (and there is no difference between iOS and Android decoder code). Are you sure you are using the latest SDK .a files in your project please?

Please note the 3rd parameter (samplerate) should be an integer. "11025" is a string, use 11025.

**Comment by Uscher1** [comment]
Thank you for taking care about this issue. Since in our use case we play voice samples we prefer a lower sample rate. It also happens that just single words like "yes", "no" or "please" are played. With a minimum length of almost one second I could live. But the player really fails to load audio with length up to 2 seconds.
And you are right with the parameter. My code provided here is just prosa.
