### ISSUE TITLE
OfflineAnalyzer Always appear memory errors in iOS

### ISSUE THREAD

**Issue by jfyGiveMeFive** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#271]
NSString *string = [self.recordfilePath stringByAppendingPathComponent:@"test.wav"];
    NSLog(@"%@",string);
    
    SuperpoweredDecoder *decoder = new SuperpoweredDecoder();
    const char *openError = decoder->open([string UTF8String], false, 0, 0);
    if (openError) {
        NSLog(@"open error: %s", openError);
        delete decoder;
        //        return nil;
    };
    int sampleRate = decoder->samplerate;
    double durationSeconds = decoder->durationSeconds;
    
    SuperpoweredOfflineAnalyzer *offlineAnalyzer = new SuperpoweredOfflineAnalyzer(sampleRate,0,durationSeconds);
    
    short int *intBuffer = (short int*)malloc(decoder->samplesPerFrame * 2 * sizeof(short int) + 16384);
    
    float *floatBuffer = (float *)malloc(decoder->samplesPerFrame * 2 * sizeof(float) + 1024);
    
    while (true) {
        unsigned int samplesDecoded = decoder->samplesPerFrame;
        if (decoder->decode(intBuffer, &samplesDecoded) == SUPERPOWEREDDECODER_ERROR) break;
        if (samplesDecoded < 1) break;
        
        SuperpoweredShortIntToFloat(intBuffer, floatBuffer, samplesDecoded);
        
        offlineAnalyzer->process(floatBuffer, samplesDecoded);
        
        // progress = (double)decoder->samplePosition / (double)decoder->durationSamples;
    };
    
    
    
   // unsigned char *averageWaveform,*lowWaveform,*midWaveform,*highWaveform,*peakWaveForm,*notes;
   // char *overviewWaveform;
    
    //int waveFormSize,overviewSize,keyIndex;
    
    float averageDecibel,loudpartsAverageDecibel,peakDecibel,bpm,beatgridStartMs;
    
    offlineAnalyzer->getresults(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, &averageDecibel, &loudpartsAverageDecibel, &peakDecibel, &bpm, &beatgridStartMs, NULL);
    
    NSLog(@"%f\n%f",loudpartsAverageDecibel,peakDecibel);

    delete decoder;
    delete offlineAnalyzer;
    free(intBuffer);
    free(floatBuffer);

this is my code. But why always appear      
 malloc: *** error for object 0x16413804: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug

please help me. thank you

**Comment by superpoweredSDK** [comment]
Xcode stops at the line which crashes for you. Which line is that?

**Comment by jfyGiveMeFive** [comment]
this line  crashes
 offlineAnalyzer->getresults(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, &averageDecibel, &loudpartsAverageDecibel, &peakDecibel, &bpm, &beatgridStartMs, NULL);

**Comment by jfyGiveMeFive** [comment]
@superpoweredSDK   this line crashes
offlineAnalyzer->getresults(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, &averageDecibel, &loudpartsAverageDecibel, &peakDecibel, &bpm, &beatgridStartMs, NULL);

**Comment by jfyGiveMeFive** [comment]
@superpoweredSDK  I have been solved

**Comment by unkonwnyao** [comment]
How to solve the problem?
