### ISSUE TITLE
SuperpoweredAdvancedAudioPlayer::process description

### ISSUE THREAD

**Issue by G7495x** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#272]
In the documentation, there is very little information about SuperpoweredAdvancedAudioPlayer::process() function and the bufferAdd parameter. Can you elaborate what this function does please...?

 My requirement is to be able to play from a decoded PCM buffer (Mono/Stereo)... How do I achieve the same...

Thanks in advance

**Comment by superpoweredSDK** [comment]
SuperpoweredAdvancedAudioPlayer has no feature to play from a decoded PCM buffer, sorry. It handles decoding inside.
