### ISSUE TITLE
Offline Processing Example for Android

### ISSUE THREAD

**Issue by yadidl** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#273]
Hi,

i tried the cross platform example and it's working good :)
Now i am trying to put filter on some local file(on sdcard) without any success .
i saw that you put example for something like this on ios and linux. 

can you make same example for Android too ?

Thanks.

**Comment by superpoweredSDK** [comment]
Superpowered code is cross-platform. It's almost like copy-paste.
