### ISSUE TITLE
How to change microphone volume in SuperpoweredAndroidAudioIO callback method 

### ISSUE THREAD

**Issue by falll2000** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#274]
Hi~ Superpowered team 
Thanks a lot for this SDK.

I met a problem in change microphone volume in SuperpoweredAndroidAudioIO callback.
I had try two method to do this fuction.

1. I try to use SuperpoweredChangeVolume as below, and I got very loud noise mic sound. 
            SuperpoweredChangeVolume(recordBuffer, recordBuffer, 1.0f, 2.0f, numberOfSamples);

2. I try the other method is through SuperpoweredMixer to change microphone volume.
recordBuffer is microphone buffer in float type array.
musicBuffer is player data buffer.
bgmOutputBuffer is mixed result data buffer.

If I want to raise microphone volume in bgmOutputBuffer, what buffer value should I change ?bgmInputVolume and bgmOutputVolume? 

            bgmInputs[0] = recordBuffer;
            bgmInputs[1] = musicBuffer;
            bgmInputs[2] = NULL;
            bgmInputs[3] = NULL;

            bgmOutputs[0] = bgmOutputBuffer;
            bgmOutputs[1] = NULL;

            bgmInputVolume[0] = 1.0f;
            bgmInputVolume[1] = 1.0f;
            bgmInputVolume[2] = 1.0f;
            bgmInputVolume[3] = 1.0f;
            bgmInputVolume[4] = 0.0f;
            bgmInputVolume[5] = 0.0f;
            bgmInputVolume[6] = 0.0f;
            bgmInputVolume[7] = 0.0f;

            bgmOutputVolume[0] = 1.0f;
            bgmOutputVolume[1] = 1.0f;

            sSongMixer->process(bgmInputs, bgmOutputs, bgmInputVolume, bgmOutputVolume, NULL, NULL, numberOfSamples);

Sorry about my poor English. 
If any other method can modify microphone volume, please let me know. Thanks a lot.

**Comment by superpoweredSDK** [comment]
SuperpoweredChangeVolume 1.0f - 2.0f means you ramp volume from 1.0f to 2.0f for every single buffer. You need to do this only once, then do 2.0f every time.

**Comment by jfyGiveMeFive** [comment]
@falll2000 bgmInputVolume and bgmOutputVolume.  you can change bgmOutputVolume. The minimum  is 1.0. you can  try to change to 4.0 .
