### ISSUE TITLE
SuperpoweredAdvancedAudioPlayer sound drops out on loop restart

### ISSUE THREAD

**Issue by jsonfellin** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#275]
When playing an audio file with SuperpoweredAdvancedAudioPlayer, the audio drops out slightly when the file loops so it doesn't sound smooth. Is there any way to avoid this? I can provide a sample if needed.

**Comment by superpoweredSDK** [comment]
Perhaps you are looping a compressed audio file. A compressed audio file, such as MP3 or AAC always starts with a small amount of silence. Set the loop start time accordingly.

**Comment by jsonfellin** [comment]
Thanks for the response. Is there a trick for determining the ms of silence?
