### ISSUE TITLE
Problem getting a seamless loop on Android

### ISSUE THREAD

**Issue by ProsperDevelopment** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#276]
Hi I can't get a seamless loop when using SuperpoweredAdvancedAudioPlayer. You can hear a little cut on Android <5.1. The problem occur on later versions as well but is less common.

Have I understood it right if I need to supply the bpm so SuperPowered perform some kind of beatsync? I set the masterBpm to the audio's bpm. The audio files should have the first beat at 0.0 so i set msElapsedSinceLastBeat to 0 is that correct?

player->process(stereoBuffer, false, numberOfSamples, volume, masterBpm, msElapsedSinceLastBeat);

**Comment by jsonfellin** [comment]
+1 I'm facing the same problem. @ProsperDevelopment If you find a solution, please post it here.

**Comment by svenoaks** [comment]
A solution though maybe not a good one, is to use an older version of Superpowered. It was seamless around 0.9 I think.

**Comment by superpoweredSDK** [comment]
Do you loop a compressed audio file, such as MP3 or AAC?

**Comment by ProsperDevelopment** [comment]
Yes its compressed mp3 192kbps

**Comment by superpoweredSDK** [comment]
Every compressed audio file, such as MP3 or AAC starts with some silence. Use the loopbetween or loop methods to start from a specific point to a specific point, skipping the silence from the start.

**Comment by ProsperDevelopment** [comment]
I see but is this amount of time with silence static on every device/file? I mean is it possible to solve this way, or do I have to convert them to wav?

**Comment by jsonfellin** [comment]
Is there a way to get the ms of silence at the beginning of a compressed file?

**Comment by ProsperDevelopment** [comment]
I think its like this

samples / Khz

for me it was 528 / 44100 ~ 12ms

528 samples i got from the LAME tech FAQ:

_"All *decoders* I have tested introduce a delay of 528 samples.  That
is, after decoding an mp3 file, the output will have 528 samples of
0's appended to the front."_

Much better but still some glitch, but after setting a cache point at the seam

So heres my idea

     ```
   player->loopBetween(12, player->durationMs, true, 1, true);
        player->cachePosition(12,1);
```

But I don't know if we need to have cache at the end also?

      ```
        player->loopBetween(12, player->durationMs, true, 2, true);
        player->cachePosition(12,1);
        player->cachePosition(player->durationMs-1000,2);

```
 or does the +/-1 cover the and if i set it at the beginning? Setting the position like  player->cachePosition(player->durationMs,2) makes a glitch in the seam.

**Comment by ProsperDevelopment** [comment]
When reading the LAME tech FAQ, I understand there is also an delay at the end, do I need to skip that too?
