### ISSUE TITLE
change speed of and save to file 

### ISSUE THREAD

**Issue by yadidl** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#277]
hi,
I am using the CrossExample and i want to add SeekBar that will control the speed (setTempo).
Once i did it. how can i write the result (that running on the player) to file.
Kind of export to file when user finished choose the speed and filter.

I thought to add func that will do the export something like the offline example .
In this case, how can i set the speed there ?

Thanks.

**Comment by superpoweredSDK** [comment]
Use an instance of the SuperpoweredRecorder to save any audio to disk from a live audio processing callback.

In the offline example the example method starts with adjusting speed.

**Comment by yadidl** [comment]
can i use SuperpoweredRecorder to write all the file that i load to the player but with all the changes that i set on the player ? (FX & setTempo for example) ? 

The plan is to load file (some mp3) and give the user the ability to change the speed and add some effects to it (on the player , because i want to give him the ability to listen to the changes when he change it ). Then when he finished i want to give him the option to save the result.

So what it the right way to use Superpowered in this case ?
