### ISSUE TITLE
Compatibility with Android OS 7.1.1

### ISSUE THREAD

**Issue by shivamsingh** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#278]
Hi Superpowered,

Just wondering if the libraries have been tested for compatibility with the newest Android OS. We tested our app on OS 7.1.1 and while recording happens correctly, playback gives us an output of white noise.
Please advise.

Thanks!

**Comment by superpoweredSDK** [comment]
Hello, yes, we tested every example project on Android 7.1.1 on the Nexus 9 and Nexus 6P.

**Comment by shivamsingh** [comment]
Just to clarify, in which version of Superpowered was the support for Android 7.1.1 added? We're currently running 0.9.2. Could that be the issue?
