### ISSUE TITLE
Error while loading exampleapps [really frustrated now]

### ISSUE THREAD

**Issue by themakerman** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#279]
Please see the attached log file. I am trying to solve this error since a week now but unable to resolve it. Would be grateful if you can help me out with this. SuperpoweredSDK is awesome but it is really hard for developers just starting with NDK to even configure the environment just because of lack of documentation. A video or two over youtube can solve 80% of issues. Why are you guys not making some tutorial videos?? Well for time being would be grateful if you guys can help me out.
[gradle_sync_error.txt](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/895411/gradle_sync_error.txt)

**Comment by superpoweredSDK** [comment]
I recommend to read the log you included. It says:

    C:\Android\sdk\Superpowered/AndroidIO/SuperpoweredAndroidAudioIO.cpp
  Invalid character escape '\A'.

You have a path error. It should be something like: C:\\Android\\sdk ...

**Comment by themakerman** [comment]
But in which file should i fix the path? In cmakeList.txt? This is my cmakelist.txt file
`cmake_minimum_required(VERSION 3.4.1)

set(
	PATH_TO_SUPERPOWERED
	CACHE STRING ""
)

message(${ANDROID_ABI})

file(GLOB CPP_FILES "*.cpp")

add_library(
	SuperpoweredExample
	SHARED
	${CPP_FILES}
	${PATH_TO_SUPERPOWERED}/AndroidIO/SuperpoweredAndroidAudioIO.cpp
)

include_directories(src/main/jni)
include_directories(${PATH_TO_SUPERPOWERED})

target_link_libraries(
    SuperpoweredExample
    log
    android
    OpenSLES
    ${PATH_TO_SUPERPOWERED}/libSuperpoweredAndroid${ANDROID_ABI}.a
)`

**Comment by themakerman** [comment]
Do you mean to say that whereever PATH_TO_SUPERPOWERED is mentioned i have to replace it with the actual path? Do i have to do the same for ${CPP_FILES} (in this case what should i replace the string with)?
My superpoweredSDK path is C:/Android/sdk/Superpowered. Please help me out

**Comment by deepakrokz** [comment]
Hi @themakerman I hope you have resolved your issue
It should be something like 

> ndk.dir=E\:\\Softwares\\AndroidStudio\\Sdk\\ndk-bundle
sdk.dir=E\:\\Softwares\\AndroidStudio\\Sdk
superpowered.dir=D\://Test//Superpowered

**Comment by themakerman** [comment]
@deepakrokz yup fixed long time back.
