### ISSUE TITLE
SuperpoweredBandpassFilterbank return NaN or Infinity 

### ISSUE THREAD

**Issue by DASAR** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#28]
I was working on Android application which use Superpowered SDK for audio analysis 2 weeks ago. 
App record audio using Android [AudioRecorder](http://developer.android.com/reference/android/media/AudioRecord.html) class and pass recorded buffer to native library (NDK). I wrote simple JNI wrapper for Superpowered [BandpassFilter](http://superpowered.com/docs/class_superpowered_bandpass_filterbank.html) to do that.

First issue was in Superpowered StereoMixer shortIntToFloat() function for audio conversion from short 16 bit to float 32 bit. Sometimes this convert function crashes with SIG ACCESS (as I understand access to wrong address). I respect rules in docs which says: input and output MUST be numOfSamples +8 big minimum and numOfSamples must be divisible by 8.

After long debugging I fix it by replacing this bogus function by simple for loop (on same data in same NDK level).

But, most critical issue in both cases (with Superpowered converter or my own loop) BandpassFilter sometimes starting return band array filled with NaN or Infinity values and continue doing so with new input (even if I recreate & init new BandPassFilter object). I was found it happens before my JNI return value to Java level and also I was checked my input audio buffer: it was always in correct range [-1,1] and do not content NaN or Infinite values. I use C++ 11 isnan() and isinf() functions to check each value in my input audio buffer. When I check output bands values using same functions it was NaN or Infinite (in case when issue shows up).

This issues happens not always, but frequent. Which makes imposible to use Superpowered in project even if it works sometimes.
I can share some code if you request.

My testing device: Nexus 5 (Android 5.1).
Audio sample rate 44100, stereo.
Superpowered SDK ver 0.7.1
Android NDK ver: android-ndk-r10d

**Comment by superpoweredSDK** [comment]
Both bugs seems related to a memory handling error in your code. The short int to float function should not crash with access error if the buffer is big enough, neither the bandpass filter should return with nan or infinity for good input. Perhaps you treat stereo samples as mono and allocate only half the space needed?

**Comment by DASAR** [comment]
Quote from docs for SuperpoweredShortIntToFloat function:
each input and output "Should be numberOfSamples + 8 big minimum".

According to this read short 16 bit buffer from AudioRecord and then reduce readCount (in samples) value by 8. So my input buffer is +8 bigger than numOfSamples value which I pass to ShortToInt function. Also I allocate output buffer +8 samples bigger than numOfSamples.

**Comment by DASAR** [comment]
## Last version without Superpowered shortToInt, but still return NaN or Infinity band values sometimes.

### Java:

```java
@Override
	public void run() {
		super.run();

		Log.d(TAG, "Start initialization stuff...");

		// Set URGENT priority
		android.os.Process.setThreadPriority(android.os.Process.THREAD_PRIORITY_URGENT_AUDIO);

		// Create bandpass filter
		filter = new BandpassFilterbank(numBands, preset.freq,preset.widths,
				SAMPLE_RATE_IN_HZ);

		// Initialize recorder instance
		recorder = createRecorder();

		// Start recording
		recorder.startRecording();

		Log.d(TAG, "Initialized.");

		while (isActive) {
			// Read audio
			// readCount = recorder.read(audioData, 0,bufferSizeInSamples);

			readCount = recorder.read(audioData, bufferSizeInSamples * 2);

			// Success rea

d
			if (readCount != AudioRecord.ERROR_INVALID_OPERATION
					&& readCount != AudioRecord.ERROR_BAD_VALUE) {

				Log.v(TAG, "Has been read bytes: " + readCount);

				// Calc numOfSamples for filter
				numOfSamples = readCount / 2;

				// must be bigger
				if (numOfSamples >= 0) {

					// clear previous output
					Arrays.fill(bands, 0);
					Arrays.fill(peakAndSum, 0);

					// Filter audio
					filter.process(audioData, bands, peakAndSum, numOfSamples);

					Log.d(TAG, "Bands " + Arrays.toString(bands));

					// Scale bands in range [0,1]
					for (int i = 0; i < bands.length; i++) {
						bands[i] /= numOfSamples;
					}

					band = bands[preset.band];

					// Remember in sampler
					q.add(band);

					if (band > 0.0003) {

						// Calc min|max|avg
						min = 0;
						max = 0;
						avg = 0;

						// find current MIX | MAX | AVG
						for (float v : q) {
							max = Math.max(max, v);
							min = Math.min(min, v);
							avg += v;
						}

						avg /= q.size();

						// calc value in range [0,1]
						value = (band - avg) / ((max - avg) * 0.01f) * 0.01f;

						if (value < sensetivity)
							value = 0;

						if (value > 1f)
							value = 1f;

					} else {
						value = 0;
					}

					// Draw on surface
					doDraw(value);

				}
			}

		}

		Log.d(TAG, "Stopping...");

		// Clear with black
		doDraw(0f);

		// Stop recording
		recorder.stop();

		// Release native resources
		recorder.release();

		recorder = null;

		// Release bandpass filter
		filter.release();

		filter = null;

		Log.d(TAG, "Processing stopped.");
	}
```

### JNI:

```cpp
JNIEXPORT void JNICALL Java_uz_shift_audio_BandpassFilterbank_process
(JNIEnv * env, jobject obj, jobject input, jfloatArray bands, jfloatArray peakAndSum, jint numberOfSamples) {

	// Not initialized
	if(!bandFilter) {
		LOGE("Bandpass filter not initialized.");
		return;
	}

	jshort *in_input = (jshort*) env->GetDirectBufferAddress(input);

	jfloat *in_bands = env->GetFloatArrayElements(bands, NULL);

	jfloat *peakandsum = env->GetFloatArrayElements(peakAndSum, NULL);

	// Should be numberOfSamples
	float * output = (float*) calloc (numberOfSamples,sizeof(float));

	if(in_input && in_bands && peakandsum && output) {

		// Convert to 32-bit interleaved float array  [-32768,32767] => [-1,1]
		//SuperpoweredStereoMixer::shortIntToFloat(in_input,output,numberOfSamples);

		unsigned int i;
		float v;

		for (i = 0; i < numberOfSamples; i++) {
			//short int v = *(in_input+i);
			//float f = ((float) v) / 32768.0f;
			//if( f > 1 ) f = 1;
			//if( f < -1 ) f = -1;

			*(output+i) = ((float)*(in_input+i)) / 32768.0f;
		}

		// Filter
		bandFilter->process(output, in_bands,  &peakandsum[0], &peakandsum[1], numberOfSamples);

	} else {
		LOGE("Bandpass Filter processing error.");
    }

    free(output);

    if(in_bands) {
        env->ReleaseFloatArrayElements(bands, in_bands, 0);
    }

    if(peakandsum) {
        env->ReleaseFloatArrayElements(peakAndSum, peakandsum, 0);
    }

}
```

**Comment by DASAR** [comment]
I will create repository for my test application on GitHub and post link here. So you can see what's wrong.
