### ISSUE TITLE
File Operations in process() for SuperpoweredAdvancedAudioPlayer

### ISSUE THREAD

**Issue by dkorobov2** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#281]
I'm writing an application that plays different audio files in response to audio input in real time. The audio files are small, but they would need to be opened and played with minimum latency. 

My problem is that opening a file in process() takes too long and the audio files do not get loaded successfully. I have checked that I am calling open() correctly with the right path, offset, and length, since the audio files play just fine if I open them on a button press. I have also tried opening the files in a separate thread, but this leads to a segmentation fault. Do you have any advice on how to do this?

**Comment by superpoweredSDK** [comment]
Opening audio files happen in an internal thread of SuperpoweredAdvancedAudioPlayer. That thread has the lowest priority in order to not interfere with anything else.
Do not call open() in an audio processing callback. Call it from somewhere else.
