### ISSUE TITLE
setTempo effecting on pitch 

### ISSUE THREAD

**Issue by yadidl** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#284]
Hi,

When i did **setTempo(3.0f,true)** its changed the pitch too (the tone changed) ,even the masterTempo is true.
But when i am changing the speed offline with SuperpoweredTimeStretching like this:
**timeStretch->setRateAndPitchShift(3, 0);**
Its working good without any change on the pitch.

There is some solution for that ?
How can i change the speed on the player without changing the tone ?
(so it will sounds like the SuperpoweredTimeStretching).

Thanks

**Comment by superpoweredSDK** [comment]
Please read the documentation. There are two properties of the player you can change for this:

minTimeStretchingTempo 
Will not time-stretch, just resample below this tempo. Default: 0.501f (recommended value for low CPU on older mobile devices, such as the first iPad). Set this before an open() call. 

maxTimeStretchingTempo 
Will not time-stretch, just resample above this tempo. Default: 2.0f (recommended value for low CPU on older mobile devices, such as the first iPad).
