### ISSUE TITLE
SuperpoweredAdvancedAudioPlayer: open a downloaded HLS file

### ISSUE THREAD

**Issue by ericharlow** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#285]
how would I open a .m3u8 audio file I have downloaded?
so for example if the file has a path of 

> /storage/emulated/0/Android/data/com.superpowered.hlsexample/files/downloads/playlist.m3u8

What would I pass into Open() as a parameter?
I tried `"file:////storage/emulated/0/Android/data/com.superpowered.hlsexample/files/downloads/playlist.m3u8"` but that didn't work.

I have the .key file and the .ts files in the same folder, but am wondering if the .ts files are in a different folder how could I accommodate for that?

**Comment by superpoweredSDK** [comment]
Hello,

downloaded m3u8 files can not be used, sorry. Our player handles network communication on it's own, and file:// urls are not recognized.
