### ISSUE TITLE
SuperpoweredAdvancedAudioPlayer duration decreases in every loop

### ISSUE THREAD

**Issue by inna4209** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#286]
Hello,

I have started to use Superpowered SDK in my iOS project and faced with one problem. I need to play audio in loop. And every new loop duration of player decrease in 40-80 ms.
I checked it also with SuperpoweredCrossExample and my audio file (format .wav) duration 9 seconds.
I made logs of player duration in milliseconds: 
NSLog(@"duration A = %d", playerA->durationMs );
And hear are results:
2017-04-23 11:52:00.268 SuperpoweredCrossExample[18950:5734073] duration A = 8868
2017-04-23 11:52:09.268 SuperpoweredCrossExample[18950:5734073] duration A = 8783
2017-04-23 11:52:18.268 SuperpoweredCrossExample[18950:5734073] duration A = 8736
2017-04-23 11:52:26.268 SuperpoweredCrossExample[18950:5734073] duration A = 8678

As the result, after some period of loops I don’t hear end of audio record.
What need to do to fixed this problem?
Thank you.

**Comment by superpoweredSDK** [comment]
The next update will fix this. Coming in 1-2 weeks.

**Comment by yadidl** [comment]
I was have something like this too (its become more problematic when the sound looping many times or if the simple rate is low). I thought it something in my code ...good to hear that you going handle it 👍 .
If there is a way to release this fix soon as possible it will be great.
I must to say that your lib is very helpful. And make things working much better (and faster) .
Thanks for it and thanks for the quick response.

**Comment by inna4209** [comment]
Hi,
I see that there is new update of SDK. Did it fix this bug?
