### ISSUE TITLE
Player setReverse() sequence not working after upgrading to Superpowered 1.0.0+

### ISSUE THREAD

**Issue by duvernea** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#287]
Hi Superpowered,

I recently upgraded from 0.9.7 to 1.0.3 of Superpowered. I think most things appear to be working as expected, except that my previously working code to use Superpowered Audio Player to play an audio wav file in reverse no longer seems to work.

Here is the code. I setReverse(), set the position to the end of the file, and then play:
```c
            playerA->setReverse(true, 5);
            playerA->setPosition((double) playerA->durationMs, false, false);
            playerA->play(0);
```

After upgrading Superpowered library, this code sequence no longer works. I also checked the Superpowered versions in between. My code appears to work fine on 0.9.9, but does not work on 1.0.0. Should this code work on version 1.0.0+?

Thanks,
Brian

**Comment by superpoweredSDK** [comment]
There was no change in that part of the code. Please try this:

setReverse(true, 0); // 5 was a too low number for slip
setPosition((double) playerA->durationMs - 1, false, false);
play(false); // 0 doesn't always mean false

**Comment by duvernea** [comment]
Yes, with those code changes, it now works as expected on version 1.0.3.  Thank you!
