### ISSUE TITLE
Problem with destroying Player after getting SuperpoweredAdvancedAudioPlayerEvent_EOF

### ISSUE THREAD

**Issue by romanoss** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#288]
Hello,
Thx for this great lib.
I use the Superpowered engine to play and filter mp3 files on Android.
If I use skip to next song in the gui, I call the destructor of my cpp player class from java and I construct a new instance of it with the new filepath.
Everything works fine.
I want to do the same after a song finishes, but calling the destructor crashes the engine at this line:

SuperpoweredAndroidAudioIO.cpp
SuperpoweredAndroidAudioIO::~SuperpoweredAndroidAudioIO()
        (*internals->outputBufferQueue)->Destroy(internals->outputBufferQueue);

So something is different after the SuperpoweredAdvancedAudioPlayerEvent_EOF event.
Do I have to handle this in another way or is there an error in SuperpoweredAndroidAudioIO.cpp

kind regards
Roman

**Comment by superpoweredSDK** [comment]
Perhaps you are destructing it twice? The player has no impact on destructing the audio I/O object.

**Comment by romanoss** [comment]
hmm - debugger says no second call to SPNotchPlayerNative::~SPNotchPlayerNative()

I derived my code from the CrossExample with  the main difference that I don't use a playerB ,mixer, roll or flanger object, but just a filter on playerA. Does this give any clue?

**Comment by romanoss** [comment]
I can provide a crossexample version with my adaptions to demonstrate the behaviour.

**Comment by romanoss** [comment]
To be more exact: I am not destroying SuperpoweredAdvancedAudioPlayer() but the cpp class that encapsulates it, which is your example: SuperpoweredExample()

**Comment by superpoweredSDK** [comment]
Perhaps destroying/creating a new audio I/O in an unsynchronized way is the problem. OpenSL ES/Android media server might not like it. Destroy first, wait until it finishes, then create again?

**Comment by romanoss** [comment]
but I do the same when skipping - it works: which is calling the destructor an the cpp class and then creating new class:
DeconstructSuperpoweredExample();
SuperpoweredExample(Integer.parseInt(samplerateString), Integer.parseInt(buffersizeString), getPackageResourcePath(), fileAoffset, fileAlength, 0, 0);

I can send you some few files which you can exchange in the crossexample to see the behaviour.

**Comment by marafat** [comment]
@romanoss in your "Song-end" scenario, do you call the destructor from the audio callback thread? I feel this could be a big difference compared to when you tap on "Skip" from the UI.

**Comment by superpoweredSDK** [comment]
I think @marafat has the point! The events can be called from the audio processing thread directly.

**Comment by romanoss** [comment]
@marafat and @superpoweredSDK 
cpp: in playerEventCallbackA I call the java side method 'SPCallbackEOF' which initiates the call to 
SuperpoweredExample::~SuperpoweredExample() and the creation of a new  SuperpoweredExample class - I put the necessary files into this msg so you can see.

/////////////////////////////////////////////////////////////////////////////////
if (event == SuperpoweredAdvancedAudioPlayerEvent_EOF) {
        SuperpoweredAdvancedAudioPlayer *playerA = *((SuperpoweredAdvancedAudioPlayer **)clientData);

        JNIEnv *env;
        int status = g_vm->GetEnv((void**)&env, JNI_VERSION_1_6);
        if(status < 0) {
            status = g_vm->AttachCurrentThread(&env, NULL);
            if(status < 0) {
                return;
            }
        }
        jmethodID mID2 = env->GetMethodID(globalClass,  "SPCallbackEOF", "()V");
        if (mID2 != NULL)
            env->CallVoidMethod(g_obj, mID2);

        if (env->ExceptionCheck())
            env->ExceptionDescribe();
        g_vm->DetachCurrentThread();
    }
/////////////////////////////////////////////////////////////////////////////


[SuperpoweredExampleFiles.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/966806/SuperpoweredExampleFiles.zip)

**Comment by romanoss** [comment]
and calling 
 playerA->~SuperpoweredAdvancedAudioPlayer();
in playerEventCallbackA which you propose leads to an SIGSEGV in process():
bool silence = !playerA->process(stereoBuffer, false, numberOfSamples, volA, masterBpm, -1);

which seems quite reasonable....

**Comment by superpoweredSDK** [comment]
The EOF event is called in the audio processing thread. Never ever call Java from there please.

**Comment by romanoss** [comment]
Maybe I dont understand what the audio processing thread is...

>The EOF event is called in the audio processing thread
I am not sure if I understand you. In my understanding the audio processing thread is where playerEventCallbackA() lives. From there I have to inform the java side that EOF happened (where else?) and I init  the deconstruction on the java side. @marafat I never did call the deconstructor from the audio processing thread.

>Never ever call Java from there please.
How to inform the java side of the EOF?

**Comment by romanoss** [comment]
Ok - I think I solved it.
The trick is to call the destructor on the UIThread, while the java callback method is not executed on the UIThread. This was the difference to the skip-case and this solved the issue.

Thanks for helping!!!! @superpoweredSDK and @marafat

**Comment by superpoweredSDK** [comment]
Regarding the audio processing thread: if there is a live audio input and/or output, the audio stack of the operating system is calling your audio processing callback at regular intervals. That call happens on a special high priority thread in order to smooth timing. If the timing is not smooth, audio dropouts can happen.
