### ISSUE TITLE
problem with loop and setReverse

### ISSUE THREAD

**Issue by felart** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#289]
Hi,

I think there's an issue with looping in reverse mode if looping duration is near sample duration.
In this case playback stop  at starting point instead of looping to ending point.

The problem occurs if looping loop end is >(sample duration - 500ms)

Working:
player->loopBetween(0, player->durationMs-**500**, false, 255, false);
player->setReverse(true, 0);

Not working
player->loopBetween(0, player->durationMs-**499**, false, 255, false);
player->setReverse(true, 0);

I test it with SuperpoweredPerformance example project.

Thanks.
Erick.

**Comment by superpoweredSDK** [comment]
Thank you for the bug report. We could reproduce the issue. The fix is coming with the next update, in a short time.

**Comment by superpoweredSDK** [comment]
Updated the library with the fix.

**Comment by felart** [comment]
Hi, problem is still present with some files.

for example problem is present for this file: 
[101-guira-rockbeat.aif.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/977647/101-guira-rockbeat.aif.zip)


Working:
player->loopBetween(0, player->durationMs-**543**, false, 255, false);
player->setReverse(true, 0);

Not working
player->loopBetween(0, player->durationMs-**542**, false, 255, false);
player->setReverse(true, 0);

Thanks.
