### ISSUE TITLE
CrossExample full of static on a test device

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#29]
Hi, I have two devices I'm testing CrossExample app on. First one is Nexus 9 with Android 5.0.1, no problems there. Second is HTC One (m7) Google Play Edition with Android 4.4.4 (Beats Audio turned off). The CrossExample project generates static when playing (just playing, not messing with UI controls), as if the a buffer is under run. It gets worse when home key is pressed and app goes into background. I can run the NativeAudio sample project included with NDK with no problems, and even alter the code for it to be in background with no problem. 
The only thing I can notice from the log is excessive V/AudioMixer enable and disable many times per second when the app starts playing. This does not occur with NativeAudio example app or on Nexus 9.

04-25 16:04:59.851      269-651/? D/AudioStreamOutALSA﹕ write:: buffer 0xb7de8788, bytes 1024
04-25 16:04:59.861      269-651/? V/AudioMixer﹕ disable(1)
04-25 16:04:59.871      269-651/? V/AudioMixer﹕ enable(1)
04-25 16:04:59.871      269-651/? V/AudioMixer﹕ disable(1)
04-25 16:04:59.871      269-651/? V/AudioMixer﹕ enable(1)
04-25 16:05:00.001      269-651/? V/AudioMixer﹕ disable(1)

This happen with superpoweredSDK 0.8 and android-ndk-r10d

It doesn't happen on any other audio apps. Only time I have seen is when using very small buffer size with Java SDK AudioTrack.

Please help I don't know enough about OpenSL to debug yet.

**Comment by svenoaks** [comment]
Also increasing 'latencySamples' to SuperpoweredAndroidAudioIO constructor does not fix. Increasing 'buffersize' is generating fatal signal.

**Comment by superpoweredSDK** [comment]
Did you modify the example code in any way? What value do you have for buffer size?

**Comment by svenoaks** [comment]
No, all I did was add the path to NDK in local.properties and in build.gradle. I only start changing things when the sound is not good. Device is GPE so just about stock Android 4.4.4 (I have not upgraded to 5.x for testing purposes). They do add Beats Audio to it which could be significant, though I tried with it enabled and disabled. 

I believe the AudioMixer disabling and enabling could be significant, any idea what could cause that?

The buffersize as determined by AudioManager.PROPERTY_OUTPUT_FRAMES_PER_BUFFER in the Java code is 512.

**Comment by svenoaks** [comment]
I should note V/AudioMixer enable/disable is entire time when audio is playing not just when first start playing, it basically spams the log. I don't see this in any other audio app, and not happening on other device with CrossExample.

**Comment by svenoaks** [comment]
I took a quick look at source of AudioFlinger for what can be calling enable() and disable() on AudioMixer from KitKat source. From https://android.googlesource.com/platform/frameworks/av/+/kitkat-release/services/audioflinger/

It looks to me like what causes mixer->disable() is a buffer underrun-

if (framesReady < frameCount) {
                    if (framesReady == 0) {
                        underruns.mBitFields.mEmpty++;
                        underruns.mBitFields.mMostRecent = UNDERRUN_EMPTY;
                        mixer->disable(name);


$ grep -nr enable\( .
./AudioMixer.cpp:206:        // setBufferProvider(name, AudioBufferProvider *) is required before enable(name)
./AudioMixer.cpp:215:        // setParameter(name, TRACK, MAIN_BUFFER, mixBuffer) is required before enable(name)
./AudioMixer.cpp:392:void AudioMixer::enable(int name)
./AudioMixer.cpp:400:        ALOGV("enable(%d)", name);
./AudioMixer.h:108:    void        enable(int name);
./Effects.cpp:942:status_t AudioFlinger::EffectHandle::enable()
./Effects.cpp:1134:        return enable();
./Effects.h:174:    virtual status_t enable();
./FastMixer.cpp:330:                        mixer->enable(name);
./FastMixer.cpp:450:                        mixer->enable(name);
./FastMixer.cpp:455:                    mixer->enable(name);
./Threads.cpp:3111:            mAudioMixer->enable(name);

**Comment by superpoweredSDK** [comment]
What happens if you pass 1024 as buffer size in C++?

**Comment by svenoaks** [comment]
I will try that again, but it looks like setting buffersizeString in Java would have the same effect, since it is sent through JNI.

**Comment by svenoaks** [comment]
I investigated how OpenSL works further. There are a couple design flaws I perceive which are causing the problem. No matter how big the buffer is it will not correct the problem.

The source of the audio glitches (which is probably going to manifest on many devices) is because you are not using double buffering or non-locking io. In 0.8 and the previous version, all of the action is happening in the OpenSL callback (In 0.7.2, you are showing an appearance of using double buffering, but it is really just alternating between the two buffers, there is no concurrent producing and consuming since it is all happening in the callback thread, where successive calls can not be overlapping). 

Read http://mobilepearls.com/labs/native-android-api/ndk/docs/opensles/ about callbacks and threads. "To avoid audible glitches, the buffer queue callback handler must execute within a small and predictable time window." You are doing all the processing in the callback handler.

Also, even when no audio is playing (the paused state) the callback handler is continuously firing and you are filling with 'silence'. This is bad on battery life and wasting CPU cycles. I would suggest that there should be a processLoop which executes off the main thread and waits when the two buffers are full for the callback to notify and unlock it.  When paused, this loop will not run. This loop would be filling one buffer from the players even when the other is being enqueued.

Take look at https://audioprograming.wordpress.com/2012/03/03/android-audio-streaming-with-opensl-es-and-the-ndk/ for how to do the double buffering. They also have more advanced non-locking using ringbuffer which might be better for lower latency. https://audioprograming.wordpress.com/2012/10/29/lock-free-audio-io-with-opensl-es-on-android/

**Comment by superpoweredSDK** [comment]
In the previous version we did double buffering, which is alternating between two buffers in the audio world, and very similar to the article you linked. Now we do a fifo buffer.
For low latency audio we must do our processing in the callback, which is not a bad thing. Superpowered is tuned for this. This is what all pro audio systems are doing. We have to run processing even for silence, to look for several events such as play(). Again, this is how pro systems work. You can extend the class (it's open source) to stop if silence is happening for more than a few seconds if you like.
As CrossExample uses output only, the mutex is not called from any other thread, so locking/unlocking happens instantly. You can comment pthread_mutex_lock at line 50, and comment pthread_mutex_unlock at line 58 to see if it improves the situation.
Also please try setting latencySamples to 10 * buffersize and see what happens.

**Comment by svenoaks** [comment]
Ok, I can see how everything you say about pro audio makes sense, and I see that the guides claim it is possible to rendering in the OpenSL callback. However Android is not a pro audio device. It seems like it can not keep up on some devices with no buffering.

I agree with you the mutex_locks as you have them should not lock, they would only be relevant for locking the UI control calls from happening in the middle of a callback. I did try removing them anyway, with no help.

I think you are on the right track with the latency samples option. However as you have now, I don't see how the FIFO buffer would ever fill past one buffersize chunk, since there is no action outside of the OpenSL callback (I am going to attempt to verify this tonight, with some log outputs). This is the same with the double buffering you had in the last version, it doesn't appear to really do anything. I did increase latencySamples to buffersize * 10 with no help. If you notice link with double buffering they are running android_AudioOut() in a separate thread, it only locks when the both buffers are full, and is only notified by the OpenSL callback.

I am going through the code and going to attempt to add in some real buffering, to see if that improves it on this HTC device. I am wondering if there will be a way to detect if the buffering is needed and only use it then, since i think you are correct about the latency issues. If its not needed I would say just deliver the one rendered buffersize chunk to Enque, there is no point in having the FIFO buffer.

Also I tried a couple more devices and could not repo the problem again:
Samsung Note 4 (Android 4.3)
2012 Nexus 7 (Android 5.1)

**Comment by superpoweredSDK** [comment]
"I don't see how the FIFO buffer would ever fill past one buffer size chunk"

This is the key. I see now the bug in the SuperpoweredAndroidAudioIO_OutputCallback: latencySamples is not taken into account when hasInput is false.

Please enable input and set latencySamples = 10 * bufferSize to check if this is the problem. Let's hope that fixes it and i can update the class quickly.

**Comment by svenoaks** [comment]
Hi I set hasInput to true and 10 * buffersize but it still has the problem.

I did manage to edit it to play fine on the HTC with double buffering, rendering happening on another thread. No audio glitches or AudioMixer calls, at least when app is in foreground. Problem is it now crashes on all other devices.  I will get it stable when I have more time. Also want a way to either a fast low latency way or buffered way. Not sure how the app will choose which to use though, there doesn't seem to be much rhyme or reason to it atm.

**Comment by superpoweredSDK** [comment]
There are many misconfigured Android devices unfortunately, including that HTC. Too bad i have no access to it, all devices here are running great.

**Comment by svenoaks** [comment]
Thanks for your continued support. I found another couple interesting things in log. When play button is pressed on HTC.

04-29 19:58:34.842      269-651/? V/AudioMixer﹕ creating resampler from track 44100 Hz to device 48000 Hz
04-29 19:58:34.852      269-651/? V/AudioMixer﹕ setParameter(RESAMPLE, SAMPLE_RATE, 44100)
04-29 19:58:34.792    269-16826/? V/AudFlgTh﹕ AUDIO_OUTPUT_FLAG_FAST denied: isTimed=0 sharedBuffer=0xb7ec1520 frameCount=4146 mFrameCount=256 format=1 isLinear=1 channelMask=0x3 sampleRate=44100 mSampleRate=48000 hasFastMixer=0 tid=25787 fastTrackAvailMask=0xfe

I have verified that samplerateString is being pulled as 48000. I even resampled the tracks at 48000 in Audacity. I don't see anywhere in your code where you hard coded 44100, so somehow AudioTrack is getting created at 44100?? I guess it can't use FastMixer cause device sample rate doesn't match track sample rate?

**Comment by superpoweredSDK** [comment]
The app has the samplerate coming from Java, you can check what you pass. FastMixer can be denied because the samplerate or the buffer size doesn't match.

**Comment by svenoaks** [comment]
The samplerate coming from Java is 48000, but internal AudioTrack is created at 44100. This could be due to this device being misconfigured, but maybe there is something we could on our end?

**Comment by superpoweredSDK** [comment]
There are some Android devices exist with misconfigured or poorly implemented HAL. It seems like this device too... What happens if you force 44100?

**Comment by svenoaks** [comment]
Crackling is even worse if I force 44100. I tested a few apps in the store, mostly piano and synth apps. Some have the crackling on this device, but some do not - even ones that I know use OpenSL. 

Only way I have found so far is to run processing in separate thread, but this has problems too cause that thread will not have elevated priority.

The guy in this article has been through the ringer with this, very informative http://heatvst.com/wp/2013/11/30/high-performance-low-latency-audio-on-android-why-it-still-doesnt-work/ but ironically his app has crackling on my HTC, even when playing with all the settings.

**Comment by superpoweredSDK** [comment]
We know many things about the Android audio stack: http://superpowered.com/androidaudiopathlatency

We think there is no good solution for your HTC device. There are Android devices out there with misconfigured audio parts in the stack, and/or bad HAL code.

**Comment by svenoaks** [comment]
Alright, thanks alot for your help, I think you are right - Android can be really frustrating this way!. I got stable threaded version going, I am going to just put a switch in my settings to use it, "Check this if you experience static during playback" type of thing.

**Comment by superpoweredSDK** [comment]
Okay, so offloading processing into another thread is the solution. As it can not run with elevated priorities, moving the fifo buffer into that thread can be an okay implementation. I will play with that approach for the next update. Certainly, the fifo buffer must be quite long there (high latency), due the fair (CFS) scheduling.

**Comment by svenoaks** [comment]
Yes, you can move the processing and filling the buffer into another thread, I would only have it as an option though since it will add latency. I used atomics for synchronization of the shared memory since mutex locking was too slow and still had crackles if I locked the openSL callback with mutex.
