### ISSUE TITLE
SuperpoweredFrequencyDomain API

### ISSUE THREAD

**Issue by loki666** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#290]
I'm a bit confused on the SuperpoweredFrequencyDomain API...

here is my setup running on Nexus 5X

AudioManager.PROPERTY_OUTPUT_FRAMES_PER_BUFFER return 192
i create a SuperpoweredFrequencyDomain with a FFT_LOG_SIZE of 10.
thus the window size is 1024 points and the spectum will have 512 bins

in audioProcessing callback, I print the numberOfInputSamplesNeeded and feed it with the stereo frames.

```
LOGD("numberOfInputSamplesNeeded: %f", frequencyDomain->numberOfInputSamplesNeeded);
frequencyDomain->addInput(inputBufferFloat, numberOfSamples); // Input goes to the frequency domain.
```
(BTW numberOfSamples should be named numberOfFrames since it's stereo sampling)

for my understanding
the FFT can starts wokring as soon as I feed it with 1024 samples, not frames

looking at the logs, it is as if the FFT use left and right sample as input...

```
numberOfInputSamplesNeeded: 1024
numberOfInputSamplesNeeded: 640 // 1024 - (192 frames, or 384 interleaved stereo samples)
numberOfInputSamplesNeeded: 256
...
```

how can a 1024 FFT works with 1024 stereo samples ?

Thanks in advance for your explainations.

**Comment by superpoweredSDK** [comment]
The frequencyDomain class does FFT, polar transformation and windowing as well, it's not just FFT. 
The SuperpoweredFrequencyDomain project is set up to use native buffer size * 2, so every step has 384 "frames", not 192.

**Comment by loki666** [comment]
ok, could you then, update the names of the arguments in the differents and variables...
it's very confusing

**Comment by loki666** [comment]
also, in the audioProcessing callback, if I print log the numberOfSamples argument, (which are frames and not samples) i get 192 not 384...
