### ISSUE TITLE
SuperpoweredOfflineAnalyzer freeze with some files

### ISSUE THREAD

**Issue by felart** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#291]
Hi,

With some files SuperpoweredOfflineAnalyzer freeze at line:

analyzer->getresults(&averageWaveform, &peakWaveform, &lowWaveform, &midWaveform, &highWaveform, &notes, &waveformSize, &overviewWaveform, &overviewSize, &averageDecibel, &loudpartsAverageDecibel, &peakDecibel, &bpm, &beatgridStartMs, &keyIndex);

Tested with sample project and this file
[101-guira-rockbeat.aif.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/977669/101-guira-rockbeat.aif.zip)

thanks

**Comment by superpoweredSDK** [comment]
Hi,

thank you for the file to test with. Just tested with the offline processing iOS example project and current version (1.0.3) of the Superpowered library. Can't reproduce the problem, it works okay.

**Comment by felart** [comment]
Hi, thanks for trying to reproduce. I have issue with iOS.
In fact, cpu goes to 99%. I give you project and screenshot.

For information, with the same file problem with loop and setReverse #289 is still present (but ok with some other files).


<img width="1680" alt="capture d ecran 2017-05-08 a 08 38 46" src="https://cloud.githubusercontent.com/assets/1297424/25793012/50847f06-33ca-11e7-85a3-05943c0f5f13.png">

[SuperpoweredOfflineProcessingExample.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/982548/SuperpoweredOfflineProcessingExample.zip)

**Comment by superpoweredSDK** [comment]
Interestingly, this issue did not come up when the file was loaded from the iTunes library. Thanks for the example project. The next update of Superpowered will have the fix.

**Comment by roman-upnext** [comment]
Hi, could you provide any date for when this will be fixed? It happening very often for me on Android.
