### ISSUE TITLE
SuperpoweredOfflineProcessingExample for android

### ISSUE THREAD

**Issue by nvquockhtn** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#293]
Who can share with me SuperpoweredOfflineProcessingExample for ANDROID (same as /Examples_iOS/SuperpoweredOfflineProcessingExample)? Now I'm processing audio effects and I'm need this example to more understand and can apply sdk to my app. Thanks so much.

**Comment by superpoweredSDK** [comment]
Since this is not an issue (such as a bug) with the Superpowered Audio SDK, i close this. I recommend to post this question on StackOverflow.

**Comment by nvquockhtn** [comment]
@superpoweredSDK When you fixed this issue, please mention me. Thanks you.
