### ISSUE TITLE
Superpowered player duration problem

### ISSUE THREAD

**Issue by inna4209** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#295]
Hi,

My problem is described in this issue: #286
I updated my code to new version, but problem still exists. 
Have you fixed it in new update? 
Thank you.

**Comment by superpoweredSDK** [comment]
Yes, i did. Please check if you are building against the new .a static library file.

**Comment by inna4209** [comment]
I checked with the newest version of sdk.
This is the log:
2017-05-10 11:22:40.799 SuperpoweredCrossExample[6214:2009995] duration A = 8868
2017-05-10 11:22:48.799 SuperpoweredCrossExample[6214:2009995] duration A = 8822
2017-05-10 11:22:56.799 SuperpoweredCrossExample[6214:2009995] duration A = 8775
2017-05-10 11:23:04.799 SuperpoweredCrossExample[6214:2009995] duration A = 8729
2017-05-10 11:23:12.799 SuperpoweredCrossExample[6214:2009995] duration A = 8682

**Comment by superpoweredSDK** [comment]
Please send the audio file which has this problem, and perhaps your project too if you like.

**Comment by inna4209** [comment]
This are files, recorded by Apple's AVAudioRecorder, .wav format. Maximum duration of files is 42 seconds.  I also tested them with SuperPoweredCrossExamples project.

**Comment by superpoweredSDK** [comment]
Where are the files please?

**Comment by superpoweredSDK** [comment]
I don't see the attached files, please submit them again.

**Comment by inna4209** [comment]
[here is file](https://drive.google.com/file/d/0BzudQqHf5x47VFVHY3NjSkxDUjA/view?usp=sharing)

**Comment by superpoweredSDK** [comment]
Thank you for the file. I could reproduce the issue, it was related to data position handling in the file if it has some garbage. The fix is coming with the next Superpowered update in a few weeks.

**Comment by ILI4S** [comment]
@superpoweredSDK I am experiencing this issue with latest superpoweredSDK version 1.0.6 (and 1.0.5 prior). I have the same bug report as @inna4209: player changes duration from 7575ms to 7497ms to 7418ms and so on every time it loops. I would be happy to provide any more information to help. In my case my input audio files are .mp3s

**Comment by ILI4S** [comment]
@superpoweredSDK The behavior has changed with v1.0.7, but I still get the same effect. Now  my player reports changes in duration from 7575ms to 7497 to 7444. I have another longer loop that in the same period changes from 30066ms to 30014ms. After either one changes duration, it becomes too short to loop cleanly, and since both are updating, they go out of sync.
