### ISSUE TITLE
CrossExample effects 

### ISSUE THREAD

**Issue by Julisons** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#297]
Flanger, roll,echo .... no effect noticed while changing .   The audio is just flat, anyone whose working for?

**Comment by superpoweredSDK** [comment]
It should work while you hold the slider. Just checked, works on all iOS and Android example projects on various devices.

**Comment by Julisons** [comment]
Yea, just as you said it's working while holding the slider ( so what was the point with the slider? would be fine with just radio button selection) anyway it's rocking.

**Comment by Julisons** [comment]
For a Java developer writing the C or C++ part is difficult,  would have more of the C jni classes available,  covering all or most of the api?

**Comment by superpoweredSDK** [comment]
High performance audio is not possible in Java. Superpowered has no "abstract" layer, it processes the raw data directly, so it must be in C++. We've no plans to provide an abstract graph connection API ("audio engine") for Java and other higher level languages.
