### ISSUE TITLE
SuperpoweredCPU won't work again after setting setSustainedPerformanceMode(false)

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#299]
When I use it a monitor will show all the cores at elevated frequency and two of them at 100% usage. However after setting `setSustainedPerformanceMode(false)` it doesn't seem like it will work again until the process is cleared. If you `setSustainedPerformanceMode(true)` or even create a new object it will not work again.

**Comment by svenoaks** [comment]
Upon further testing the performance mode can be reactivated again - but only if the app has an Activity in the foreground when `setSustainedPerformanceMode(true)` is called. If it is called from a foreground Service, the elevated frequencies and usage won't happen.

**Comment by svenoaks** [comment]
After further further testing this behavior seems limited to the S8 Plus, the other devices I have tested on it works as expected. Of course, the device that actually has the problem that SuperpoweredCPU fixes and is the flagship phone from the biggest manufacturer.

Also, the readme claims it works across all cores, but it doesn't seem to work across big/little, only little set gets amped up, at least on S8 Plus and Moto X Pure.

**Comment by superpoweredSDK** [comment]
SuperpoweredCPU does work on big/little. But there is no cure for the Android 7.1.1 bug unfortunately. https://issuetracker.google.com/issues/37324116
