### ISSUE TITLE
How to user jogTick() method?

### ISSUE THREAD

**Issue by liujunhg** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#301]
Hi,

Superpowered is really a great audio engine.

I want to use jogTick(int 	value,bool bendStretch,float bendMaxPercent,unsigned int bendHoldMs,bool 	parameterMode ) for "Virtual jog wheel" ,But I don't know the current position befor jogTick().

How to  precise seeking position(ms) use of jogTick()'s Parameters?

Can you post a example how you did that?

Please help me! thanks!

**Comment by superpoweredSDK** [comment]
This is for jog wheel handling on DJ controllers. MIDI jog wheels are sending "ticks" when the user moves the jog wheel.

**Comment by liujunhg** [comment]
I use jogTick()  for jog wheel handling on DJ controllers.
And how to set the value that Parameter "int value"?

**Comment by superpoweredSDK** [comment]
DJ controllers send a predefined number of "ticks" for every turn (360 degrees). Budget controllers send less (such as 100), high quality jog wheels send more (such as 2000). This is the "resolution" of a jog wheel.
These ticks are typically sent in the jog move MIDI CC (Control Change) message.

**Comment by liujunhg** [comment]
The current positionMs of SuperpoweredAdvancedAudioPlayer  is changing when DJ controllers send a predefined number of "ticks",and How to precise seeking position(ms)  when DJ controllers send a predefined number of "ticks"?

I can do it?

**Comment by superpoweredSDK** [comment]
DJ controller jog wheels are not sending position information at all, just the relative movement as "ticks". You can seek using the setPosition() or seek() methods.
