### ISSUE TITLE
High CPU Load with Android CrossExample

### ISSUE THREAD

**Issue by qstuff** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#303]
I downloaded the latest SDK and built the Android CrossExample without any code changes.
When playing a track the CPU monitor of Android Studio shows a CPU load of around 35%.
This seems quite high to me.
My device is a Nexus 5x.

In comparison: Playing an audio mp3 track with exoplayer2 causes a CPU load of 3%.

Is there a chance to reduce the load ?

**Comment by superpoweredSDK** [comment]
It's not a "real" CPU load. 
It's the Superpowered CPU class keeping the CPU frequency at level with NOP (No Operation) instructions.
CPU frequency scaling on Android is broken for low latency, high performance audio. The Superpowered CPU class fixes this with minimal impact (less than 5%) on battery load.
More information: http://superpowered.com/cpu-frequency-scaling-android
