### ISSUE TITLE
Sound glitch when starting new player while another one is already playing

### ISSUE THREAD

**Issue by asintu** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#304]
Hi, starting from the initial Android CrossExample sample application I have further simplified the code in order to test the following simple scenario: starting playerB while playerA is already playing. As soon as playerB starts playing there is a very noticeable sound glitch/clipping happening.

I have attached all modified files for your convenience.

To reproduce the issue: 
 - press "PLAY" button to start the first player
 - wait 10sec (this is because I have found that the louder playerA gets the more noticeable the glitch)
 - press "PLAY 2ND" button to start the second player (here you will notice the glitch)
[two players_sound_glitch.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/1025826/two.players_sound_glitch.zip)

**Comment by superpoweredSDK** [comment]
You should always call both player's process() methods, as they drive some internal message queue. Stick to how the example did implement it.
You can call play() from any thread at any time.
