### ISSUE TITLE
Can you create example for cocos2d-x ?

### ISSUE THREAD

**Issue by KAMIKAZEUA** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#305]
Most popular open-source 2D game engine in a world https://github.com/cocos2d/cocos2d-x

Why there is no any simple 2d example from you? 
Something like: https://github.com/wwisesamples/cocos2dx-IntegrationDemo

**Comment by superpoweredSDK** [comment]
We are not able to provide an example for every popular platform, sorry. The SDK has 18 examples already.

**Comment by KAMIKAZEUA** [comment]
Lol, and I was thinking to use it) but nope.
