### ISSUE TITLE
Can't use libSuperpoweredLinuxX86_64.a with GCC 4

### ISSUE THREAD

**Issue by 0joshuaolson1** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#306]
When compiling Examples_Linux/src/hls.cpp with a modified buildX86.sh (to use 64-bit):
```
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: ../Superpowered/libSuperpoweredLinuxX86_64.a(SuperpoweredAdvancedAudioPlayer.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
../Superpowered/libSuperpoweredLinuxX86_64.a: error adding symbols: Bad value
```

**Comment by superpoweredSDK** [comment]
Perhaps recompile with -fPIC as it suggests?

**Comment by 0joshuaolson1** [comment]
That didn't change the error.

**Comment by superpoweredSDK** [comment]
We were using GC 4.9.2 on Debian to compile our library.
How did you modify the buildX86.sh to support 64-bit?

**Comment by 0joshuaolson1** [comment]
I commented out the lines to compile `offline*` and changed `libSuperpoweredLinuxX86.a` to `libSuperpoweredLinuxX86_64.a`.

**Comment by 0joshuaolson1** [comment]
I'm on Sabayon (Gentoo-based).

**Comment by superpoweredSDK** [comment]
Can you try with clang? Like this:

clang-3.5 ... -target x86_64-linux-gnueabi

**Comment by 0joshuaolson1** [comment]
No, but I can install clang 4, and that works for me.
