### ISSUE TITLE
How to get decibel value from SuperpoweredAndroidAudioIO recorded data

### ISSUE THREAD

**Issue by falll2000** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#307]
My decibel caculate function on below, I pass SuperpoweredAndroidAudioIO recorded data called audioInput into caculateDecibels function.

But, I get weird result. Even I don't speak, result value still move up and down.

Is any function can get decibel from SuperpoweredAndroidAudioIO recorded data use Superpowered SDK? 
or How to modify below function to get proper decibel value? 

Sorry my poor English, and thanks for your reply.

```c++
//    get mic data from SuperpoweredAndroidAudioIO called audioInput
calculateDecibels(audioInput, sizeof(audioInput) / sizeof(audioInput[0]));

//    caculate mic decibel
void LowLevelMusicRecorder::calculateDecibels(short int *mBuffer, int readSize) {
    int result = 0;
    int sum = 0;
    double amplitude;
    for (int i = 0; i < readSize; i++) {
        sum += mBuffer[i] * mBuffer[i];
    }
    if (readSize > 0) {
        amplitude = (double) ((double) sum / (double)readSize);
        result = (int) sqrt(amplitude);
    }
}
```

**Comment by superpoweredSDK** [comment]
Check the value of readSize if it really contains the number of samples you'd like to process. With memory allocated on heap it will not be correct.
sum will easily overflow, as you are multiplying numbers up to 32768. You need to convert to float in the range of -1 to 1 first.
This is not an issue of the SDK, i close this now. StackOverflow might be a better place for such posts.
