### ISSUE TITLE
.AAR prebuilt file to be used

### ISSUE THREAD

**Issue by 0xRumple** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#308]
Hello,

I'm using Xamarin Android... I wanna bind superpowered in my project.
Would you mind make an aar prebuilt release to be used ?

If it works, I will make a pull request with the binding project and the dll :)

**Comment by superpoweredSDK** [comment]
Hello,

sorry, but we've no plans for such builds currently.
