### ISSUE TITLE
Multiple SuperpoweredAdvancedAudioPlayer player objects and timing manipulation with counter 

### ISSUE THREAD

**Issue by uc3po** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#309]
Hi,
I have an issue, try to implementing an android simple daw.
I've have a c++ vector object includes SuperpoweredAdvancedAudioPlayer.
I played lots of player objects at the same time, it works perfectly. 
But the problem is lots of player objects starting at different times. 
E.g:  Counter starts when user click play button. 
Counter range 0...n (minute, seconds and miliseconds)
     Track1 start at 5th - end At 18th (second)
     Track2 start at 16th- end At 199th
     Track3 start at 19th- end At 112th
      ....
Is there any suggestion how can i configure players time dynamically according to the counter?
And How can i sync in process function?

**Comment by superpoweredSDK** [comment]
SuperpoweredAdvancedAudioPlayer is not really good for DAW application.
For syncing to a virtual beatgrid check the mastermselapsedsincelastbeat and bpm parameters.
play(true) for synchronized play start.
