### ISSUE TITLE
FFT magnitude is zero at bin zero

### ISSUE THREAD

**Issue by williehwc** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#312]
Hi,

I am getting an FFT magnitude of zero at bin zero. Here's the code I'm using, which should be similar if not identical to the Superpowered sample:

```
SuperpoweredInterleave(buffers[0], buffers[1], stereoInputLocalMicBuffer, numberOfSamples);
frequencyDomain->addInput(stereoInputLocalMicBuffer, numberOfSamples);
while (frequencyDomain->timeDomainToFrequencyDomain(magnitudeLeft, magnitudeRight, phaseLeft, phaseRight)) {
    // do something with magnitudeLeft
    frequencyDomain->advance(frequencyDomain->fftSize);
}
```

Here are plots comparing FFT magnitudes outputted by Superpowered (blue) compared to numpy (red), computed on the same audio file. This difference affects the calculation of spectral flatness, for example (I would have to start from bin 1 to avoid zeroing out the result).

Note: bin 1 on the plot corresponds to bin 0 in Superpowered and numpy, bin 2 on the plot corresponds to bin 1, and so on.

![fft-comparison](https://cloud.githubusercontent.com/assets/2502398/26794484/d7a9e9ea-49ef-11e7-8dd8-d94c78234952.jpg)
![fft-comparison-log](https://cloud.githubusercontent.com/assets/2502398/26794507/e8d3eda6-49ef-11e7-892c-a68abab3c0cd.jpg)

Is this intended behavior? Do you know what is the cause of this issue (if it's actually an issue)?

Thank you for your assistance!

**Comment by superpoweredSDK** [comment]
Data packing with Superpowered is different. The first bin is not a true frequency bin at all, it has Nyquist and DC Offset values only. Check "Data Packing" here: https://developer.apple.com/library/content/documentation/Performance/Conceptual/vDSP_Programming_Guide/UsingFourierTransforms/UsingFourierTransforms.html
