### ISSUE TITLE
Bluetooth latency

### ISSUE THREAD

**Issue by kubatatami** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#313]
I write simple app with few buttons. Each button plays a sound. I use Superpowered for best latency. I create few instance of SuperpoweredAdvancedAudioPlayer and one SuperpoweredAndroidAudioIO. Unfortunately when I connect bluetooth speaker or headphones output latency on Superpowered is ~200ms **higher** than on AudioTrack and SoundPool. Is there any way to improve that latency to SoundPool level?

Tested on Google Pixel XL (Android 7.1.2) and Nexus 6P (Android O preview)

**Comment by superpoweredSDK** [comment]
Try with larger buffer sizes for Bluetooth perhaps. Please note that we have zero focus on Bluetooth audio, as Bluetooth transmission itself starts from 100 ms, so it's not usable for low latency audio at all.
