### ISSUE TITLE
Missing malloc declaration

### ISSUE THREAD

**Issue by marafat** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#314]
Hi, 

I upgraded to NDK 15 and I started getting the following issue in `SuperpoweredAndroidAudioIO.cpp`:
`Error:(118, 39) error: use of undeclared identifier 'malloc'`. Adding `#include <stdlib.h>` fixed the error.

Tested on v1.0.4

**Comment by theyonibomber** [comment]
Didn't see this... Created a pull request #315 (used new and delete[] instead of importing <stdlib.h>, I'm not sure which solution is better)

**Comment by superpoweredSDK** [comment]
Thank you very much for your contribution. The SDK is now updated for NDK 25.
