### ISSUE TITLE
Frequent crash in SuperpoweredIOSAudioIO

### ISSUE THREAD

**Issue by bhavinpankanis** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#317]
I've implemented SuperpoweredIOSAudioIO in my project.
While testing I encounter a crash at the following line whenever I play the audio file.

 silence = !self->processingCallback(self->processingClientdata, bufs, inputChannels, self->numChannels, inNumberFrames, self->samplerate, inTimeStamp->mHostTime);

The crash log prints as follows : 
0  Tyunami_POC                    0x10018d488 processAUTHREAD(float**, bool*, unsigned int, float*, double, double, SuperpoweredAdvancedAudioPlayerInternals*, bool) (SuperpoweredAdvancedAudioPlayer.cpp:1994)

There seems to be an issue with the buffer size as per this https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/issues/15#issuecomment-113447266, but I'm unable to fix it as none of the solution mentioned on this link works.

Please provide inputs so that I can get it working without the crash.

Any inputs will be appreciated.

**Comment by superpoweredSDK** [comment]
Your "processingCallback" is a custom code you wrote. According to the crash log something crashes _inside_ your processingCallback. What happens on that line?

**Comment by bhavinpankanis** [comment]
Hello,

Many thanks for the prompt reply.

Rite now my stereoBuffer size is (4096 + 128) based on the observations made from SuperpoweredPerformance sample code and the link 
https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/issues/15#issuecomment-113447266

Could you please tell me what size should be ideal. 

Also I need to understand the relation between framesPerBuffer & SampleRate , as I intent to calculate the buffer-sizes based on these values

**Comment by superpoweredSDK** [comment]
My recommendations for iOS buffer sizes:
3 ms for low latency (that will bring 128 samples typically)
11 ms for normal use (that will bring 512 samples typically)
