### ISSUE TITLE
SuperpoweredAdvancedAudioPlayer in streaming mode.

### ISSUE THREAD

**Issue by rahulnikose** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#319]
I want to let user preview audio effect before they apply. ( for example preview flanger/reverb for different parameters unless user is sure about them before he apply them).
I played around  SuperpoweredAdvancedAudioPlayer to check possibility of providing data after
effect->process(..) call, but it play only for few seconds. 
I am expecting similar behavior as in Android AudioTrack in streaming mode, where audio track is configured first and data is fed at regular interval. 

NB: Please note, I don't have complete file for playback, just few KB of process data. 
Any suggestion /help is appreciated. 

--
Thanks

**Comment by superpoweredSDK** [comment]
You can place the player and effects in any place in any order. I don't understand the question.

**Comment by rahulnikose** [comment]
Hi,
   Thanks for quick reply. I am able to make following code flow working.

* Init decoder
* Init configure effect (e.q flanger, reverb)
* Init output wav file
* loop
      decode
      apply effects
      write processed buffer to wav file
* Deinit

Above pipe line is working great. I am struggling with following code flow

* Init decoder
* Init configure effect (e.q flanger, reverb)
* init player
* loop
      decode
      apply effects
      play out processed buffer --> This playback will be used as preview
* Deinit

I am not sure if SuperpoweredAdvancedAudioPlayer  support such streaming mode. 
SuperpoweredAdvancedAudioPlayer :: open() need file name (which i don't have )
My current need want feature as below
* Init AudioPlayer with sample rate, min buffersize, format (8/16bit) 
* AudioPlayer :: write (buffer ) --> play out this buffer data.

I hope it give clear idea. Please let us know if this is possible.Please refer if there are example. I tried some of them. 

---
Thanks

**Comment by superpoweredSDK** [comment]
The offline example shows how to do your first pipeline. The cross example shows how to do your second pipeline.

**Comment by rahulnikose** [comment]
Thanks. It was helpful.
