### ISSUE TITLE
Request: Add in-memory option for SuperpoweredAdvancedAudioPlayer

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#32]
Being able to play from an in-memory array would make many apps possible/easier, and seems like it would not be too hard to implement.

**Comment by superpoweredSDK** [comment]
Not too hard, but our focus is elsewhere currently. Please note that the advanced audio player is probably not the best option to play quick short samples from memory.
