### ISSUE TITLE
Synchronous stop() for SuperpoweredRecorder

### ISSUE THREAD

**Issue by romanbsd** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#320]
The SuperpoweredRecorder is doing its I/O in a background thread, and it's currently impossible to know when the file was fully written to disk. This leads to unpredicted behavior. The current <s>hack</s> workaround is to read the header and to compare the size on disk to the size in header, sleep, retry.
It's desired to have either a synchronous stopSynchronously() method or a method with a callback, which will be called when the file is fully written to disk.

**Comment by superpoweredSDK** [comment]
Thank you for the feature request. We'll implement a callback soon.

**Comment by weepy** [comment]
I see this ticket is closed. Does that mean it has been implemented?

**Comment by superpoweredSDK** [comment]
yes, there is a callback mechanism

**Comment by weepy** [comment]
Awesome thanks.
