### ISSUE TITLE
SuperpoweredAdvancedAudioPlayer crash with tempo is below 0.25

### ISSUE THREAD

**Issue by felart** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#321]
Hi,

I noticed a crash when tempo  is below 0.25.

With SupoerpoweredPerformance example:

player->setTempo(enabled ? 1.0f : 0.26f, true);==>OK

player->setTempo(enabled ? 1.0f : 0.25f, true);==>crash

Thanks.
Erick

**Comment by superpoweredSDK** [comment]
Hi,

can't reproduce with the current version of Superpowered, sorry. Can you send a crash log?

**Comment by felart** [comment]
Hi, I test again. Problem occurs only in iOS simulator. On real device it's ok.
Maybe you can close the defect.

Thanks.

**Comment by superpoweredSDK** [comment]
I found a bug in the iOS Simulator implementation. Fix is coming with the next update.
