### ISSUE TITLE
Bpm detection fails using SuperpoweredOfflineAnalyzer

### ISSUE THREAD

**Issue by anjovis** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#323]
Hi,
I tested the offlineAnalyzer using a slightly modified offline3.cpp example for Linux and noticed that the bpm detection fails in some cases. The samples were generated using Pysynth library: https://github.com/mdoege/PySynth.

The cases when the detection didn't work. The correct bpm value is at the beginning of the file. The "bars"-value indicates the length in bars.
![bpm_detector_log](https://user-images.githubusercontent.com/16133618/27763932-ff2e74bc-5e95-11e7-834b-cf60cd8941ec.PNG)

However, the detection succeeded for a bit longer samples:
![bpm_detector_working](https://user-images.githubusercontent.com/16133618/27763939-3ea91156-5e96-11e7-81b5-4dbd10de652a.PNG)

I couldn't find specs about the beat detection algorithm in the docs, but it probably works better with longer samples.  Are there other general rules when the bpm detection works and when it doesn't? 

Thanks,
Eemeli

[offline3.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/1117264/offline3.zip)
[test_samples.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/1117279/test_samples.zip)

**Comment by superpoweredSDK** [comment]
Hello,

there is no hard minimum or maximum, but bpm detection needs at least 20 seconds of data to provide a good estimate, and the more the better.
