### ISSUE TITLE
setReverse in looping mode doesn't work with certains files

### ISSUE THREAD

**Issue by felart** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#324]
Hi,

setReverse in looping mode doesn't work with certains files.

With this files playing stop at the beginning after setReverse.

[101_bleephop.aif.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/1126137/101_bleephop.aif.zip)

With other files  there's no problem.

Thanks.
Erick.

**Comment by superpoweredSDK** [comment]
Hi,

i can't reproduce this problem with the upcoming version of the Superpowered SDK. Are you looping between 0 and 4749 milliseconds for this track? (The player reports that length.)
