### ISSUE TITLE
SuperpoweredAdvancedAudioPlayer - error loading specific m4a file (1.0.5 regression)

### ISSUE THREAD

**Issue by amitayd** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#325]
Trying to load a specific m4a file in version 1.0.5 results in SuperpoweredAdvancedAudioPlayerEvent_LoadError event in the player callback.

The same file worked on previous versions of superpowered, and also with @theyonibomber ndk 15 patch  - https://github.com/theyonibomber/Low-Latency-Android-Audio-iOS-Audio-Engine/tree/patch-1 .

The file which causes the issue:
[tick.m4a.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/1133623/tick.m4a.zip)

This was easily reproduced in Android CrossExample as well: 
1) Added tick.m4a to the res/raw directory.
2) Replaced `R.raw.lycka` with `R.raw.tick` in MainActivity
3) For logging, added the following in SuperPoweredExample.cpp:
```
static void playerEventCallbackA(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event, void * __unused value) {
    __android_log_print(ANDROID_LOG_INFO, "SuperpoweredExample",
                        "Player event: %d, in playerEventCallbackA", event);

...

static void playerEventCallbackB(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event, void * __unused value) {
    __android_log_print(ANDROID_LOG_INFO, "SuperpoweredExample",
                        "Player event: %d, in playerEventCallbackB", event);
```

We get this at the log:
```
07-17 11:57:25.881 15916-15937/? I/SuperpoweredExample: Player event: 1, in playerEventCallbackA
07-17 11:57:25.882 15916-15938/? I/SuperpoweredExample: Player event: 6, in playerEventCallbackB
07-17 11:57:25.902 15916-15938/? I/SuperpoweredExample: Player event: 0, in playerEventCallbackB
````

This was reproduced consistently on several devices.

**Comment by superpoweredSDK** [comment]
This file has only 3 AAC frames, making it less than 70 ms long. 
The decoder thinks it's corrupted under 4 frames. Make it 4 frames long at least.
