### ISSUE TITLE
fullyDownloadedFilePath null for progressive downloads?

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#326]
According to the header file it should be considered read-only and used to get the path to the temporary file for permanent saving. Correct? No-matter what, it seems to always be null. Am I missing something?

iOS

**Comment by superpoweredSDK** [comment]
It should become non-null when the file has been fully downloaded (not downloading anymore, every byte is on disk).

**Comment by flagoworld** [comment]
Right. It doesn't seem to become non-null. Tested by repeatedly logging its value to the console while monitoring network activity. Network activity went back down to 0 and it was still null. This is on iOS.

**Comment by superpoweredSDK** [comment]
Will test and report back next week.

**Comment by superpoweredSDK** [comment]
Will be fixed in the next update. It was updated only when the player was playing and the decoder was decoding new samples.
