### ISSUE TITLE
Segmentation fault with some MP3's

### ISSUE THREAD

**Issue by c0dehunter** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#327]
Affects versions 1.0.5 and 1.0.6 (did not check others).

Some MP3 files (nothing special) cause segfault when trying to load with SuperPoweredAdvancedAudioPlayer's `open()`. This is the error from Logcat (running on Android 7.0, also tried with Android 4.1):

```
07-18 11:45:30.212 2365-2683/? A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 2683 (AudioFile Read)
07-18 11:45:30.322 1159-1159/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-18 11:45:30.322 1159-1159/? I/DEBUG: Build fingerprint: 'generic_x86/google_sdk_x86/generic_x86:4.1.2/MASTER/3093084:eng/test-keys'
07-18 11:45:30.322 1159-1159/? I/DEBUG: pid: 2365, tid: 2683, name: AudioFile Read  >>> com.something.appname <<<
07-18 11:45:30.322 1159-1159/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
07-18 11:45:30.472 1159-1159/? I/DEBUG:     eax 00000000  ebx 00000000  ecx 0000000d  edx 00000240
07-18 11:45:30.472 1159-1159/? I/DEBUG:     esi 00000042  edi 00000108
07-18 11:45:30.472 1159-1159/? I/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
07-18 11:45:30.472 1159-1159/? I/DEBUG:     eip a48865ef  ebp 9facdb08  esp 9facd710  flags 00210202
07-18 11:45:30.472 1159-1159/? I/DEBUG: backtrace:
07-18 11:45:30.472 1159-1159/? I/DEBUG:     #00  pc 0003b5ef  /data/data/com.something.appname/lib/libSuperpoweredAudio.so (MP3DequantChannel(int*, int*, MP3DecInfo*, SideInfoSub*, ScaleFactorInfoSub*, CriticalBandInfo*)+1231)
07-18 11:45:30.472 1159-1159/? I/DEBUG: stack:
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd6d0  00000000  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd6d4  00000000  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd6d8  00000000  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd6dc  00000000  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd6e0  00000000  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd6e4  00000000  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd6e8  00000000  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd6ec  00000000  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd6f0  00000000  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd6f4  00000000  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd6f8  00000000  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd6fc  00000000  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd700  00000042  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd704  00000030  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd708  00000000  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd70c  a4886134  /data/data/com.something.appname/lib/libSuperpoweredAudio.so (MP3DequantChannel(int*, int*, MP3DecInfo*, SideInfoSub*, ScaleFactorInfoSub*, CriticalBandInfo*)+20)
07-18 11:45:30.472 1159-1159/? I/DEBUG:     #00  9facd710  00000000  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd714  00000042  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd718  000000c6  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd71c  0005ffff  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd720  0000000c  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd724  b7e429c0  [heap]
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd728  00000240  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd72c  00000002  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd730  00000030  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd734  a4906974  /data/data/com.something.appname/lib/libSuperpoweredAudio.so
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd738  0000000c  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd73c  0000000c  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd740  0000000c  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd744  0005ffff  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd748  00000024  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          9facd74c  0000007e  
07-18 11:45:30.472 1159-1159/? I/DEBUG:          ........  ........
07-18 11:45:30.632 1162-1162/? D/Zygote: Process 2365 terminated by signal (11)
```

Reproducible with [this file](https://freesound.org/data/previews/176/176362_522346-hq.mp3).

**Comment by superpoweredSDK** [comment]
The attached file works okay here in our apps. Perhaps you are opening it from your raw folder and the offset and length properties are not correct?

**Comment by c0dehunter** [comment]
I tested this again with 4 different Android SDKs on emulator, once on Genymotion emulator, and on 1 physical device. On a physical device the file plays fine indeed. But on emulator (Android 4.1, 5.0, 6.0, 7.0) the error is always there with this file, crashing whole application. I am loading other mp3 files too and have specifically pinpointed this exact file to be the cause of the SegFault. All files are loaded from internal storage. 

Have you tried it out on the emulator too?

**Comment by fatihm85** [comment]
I get the same SIGSEV error for some MP3 files for version 1.04, 1.05 and 1.06. 
1.03 is working great but something is wrong for later versions. So I am currently using 1.03 on my apps. Could you please solve this issue?

07-20 13:01:44.759 10436-11660/com.fsm.audiodroid A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 11660 (Thread-2935)

SIGSEGV (signal SIGSEGV: invalid address (fault address: 0x0))
![superpowered_mp3](https://user-images.githubusercontent.com/7520300/28411796-a08296be-6d4a-11e7-856e-f68114e3977b.png)

**Comment by c0dehunter** [comment]
Where can you ownload Superpowered 1.0.3? Can't find it anywhere.

**Comment by c0dehunter** [comment]
I tried 1.0.3, and I it seems that stdlib.h include is missing:
![capture](https://user-images.githubusercontent.com/1484658/28414325-6d869642-6d4b-11e7-89c5-f9b71177b29c.PNG)

**Comment by fatihm85** [comment]
I had also added #include <stdlib.h> Version 1.03 works for all MP3 files.

Could you please solve the MP3 files issue for Versions >= 1.04? Version <= 1.03 is OK.

**Comment by superpoweredSDK** [comment]
We don't support the Android emulator at all. Are all your issues are on the emulator?

**Comment by fatihm85** [comment]
It is not an emulator issue. 

I get the same SIGSEV error for some MP3 files on version 1.04, 1.05 and 1.06.
1.03 is working great but something is wrong onlater versions. So I am currently using 1.03 on my apps on real devices. Could you please solve this issue?

**Comment by superpoweredSDK** [comment]
We found a bug in our mp3 implementation, sorry for that. Emulator will not be supported still. Expect an update in 2 weeks.

**Comment by c0dehunter** [comment]
I can verify this was fixed. Thanks!
