### ISSUE TITLE
Parameter definition in setBandlimitedParameters

### ISSUE THREAD

**Issue by nevosegal** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#328]
Hi,

`setBandlimitedParameters` accepts two arguments, `frequency` and `octaveWidth`. Is the `frequency` the lower cutoff frequency? And does the `octaveWidth` represent the number of octaves in the pass-band? So for example `frequency = 440` and `octaveWidth = 2.0` will result in a band-pass filter with a lower cutoff of 440Hz and upper cutoff of 1760Hz? The documentation is a bit unclear.

Thanks.

**Comment by superpoweredSDK** [comment]
Hi,

frequency is center frequency. Frequency = 440 and octaveWidth = 2.0 will result in 220-880 Hz.
We'll modify our header and documentation to be more precise.

**Comment by nevosegal** [comment]
Thanks
