### ISSUE TITLE
AudioPlayer Read thread crash

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#329]
When allocating many players repeatedly, there is a crash. Attached is the example project that I modified to repro the issue. Load it up in the simulator or device and tap/click "PLAY NEXT" repeatedly very fast. You'll get a couple different crashes.

File was too big to upload so I removed the 2 song files... use the ones that come with iOS Cross Example

lycka.mp3
nuyorica.m4a

[SuperpoweredCrossExample.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/1164005/SuperpoweredCrossExample.zip)

**Comment by superpoweredSDK** [comment]
The audio processing callback doesn't stop immediately, but the code releases all resources as quick as possible.
The design of the code should be changed to use one I/O object, one player, and just call the open() method of the player to replace with a new file ("play next").

**Comment by flagoworld** [comment]
I have changed to code to keep around a single instance of the player and io object, and just call open() when changing songs. It's much more stable, but there are still some issues when quickly changing songs:

1.) mp3Decoder::getFrameLength crash
2.) occasionally all the superpowered threads get blocked when calling open() (i/o was started and never stopped)

<img width="547" alt="crash1" src="https://user-images.githubusercontent.com/263509/28587191-2732dd2a-712b-11e7-87c0-a676303e1293.png">
<img width="837" alt="crash2" src="https://user-images.githubusercontent.com/263509/28587190-2731f6da-712b-11e7-9649-4aca22f74de8.png">
<img width="315" alt="wait1" src="https://user-images.githubusercontent.com/263509/28587192-27330aac-712b-11e7-93e1-b5ed52fe2f80.png">
<img width="329" alt="wait2" src="https://user-images.githubusercontent.com/263509/28587194-27462a9c-712b-11e7-9329-2fbf04e51391.png">

**Comment by flagoworld** [comment]
The mp3Decoder crash can be repro'd quite consistently when open is called on an http path.

open() url1
open() url2 (before url1 is completely downloaded?)
open() url1 again (before url2 is completely downloaded?)
crash
