### ISSUE TITLE
How can you sync both tracks to 80 bpm in the CrossExample?

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#33]
I tried calling: 
    playerA->setTempo(80.0f/126.0f, true);
by itself, and:
    playerA->setTempo(80.0f/126.0f, true);
    playerB->setTempo(80.0f/123.0f, true);

I also set both to 80.0f/123.0f or both to 80.0f/126.0f.

They both slow down but they are no longer in sync. How can I sync them to a bpm that isn't the original bpm of one of the tracks?

**Comment by svenoaks** [comment]
Never mind I figured out all my problem! It working great now!

**Comment by bdauria** [comment]
@svenoaks I also need to make the sync working. How did you end up make it working?

Thanks.
