### ISSUE TITLE
Segmentation fault with some MP3's for SDK Version >= 1.04

### ISSUE THREAD

**Issue by fatihm85** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#330]
I get SIGSEV error for some MP3 files on version 1.04, 1.05 and 1.06.
1.03 is working great but something is wrong on later versions (1.04, 1.05, 1.06). So I am currently using 1.03 on my apps. Could you please solve this issue?

07-20 13:01:44.759 10436-11660/com.fsm.audiodroid A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 11660 (Thread-2935)

SIGSEGV (signal SIGSEGV: invalid address (fault address: 0x0))

![superpowered_mp3](https://user-images.githubusercontent.com/7520300/28452804-025f03ce-6dfd-11e7-9b81-260e7bc56d31.png)

**Comment by superpoweredSDK** [comment]
Please send an example file, which crashes every time.

**Comment by fatihm85** [comment]
Hi,

This attached mp3 file crashes every time on SDK versions >= 1.04. It is OK
for versions <= 1.03. On my app, this file is loaded from device storage
not loaded from res/raw folder.Thanks.

Kind Regards,
Fatih.

2017-07-21 10:16 GMT+03:00 Super Powered <notifications@github.com>:

**Comment by fatihm85** [comment]
Hi,

This attached mp3 file crashes every time on SDK versions >= 1.04. It is OK
for versions <= 1.03. When I import 1.03 SDK files it is loaded without any
error, but when I import SDK 1.04, 1.05 and 1.05 files, it crashes.

On my app, this file is loaded from device storage not loaded from res/raw
folder. Thanks for your support. I hope this issue is solved.

Kind Regards,
Fatih.

2017-07-21 10:16 GMT+03:00 Super Powered <notifications@github.com>:

**Comment by superpoweredSDK** [comment]
Thank you for this file. It plays without any error on our latest production build. Expect an update in 2 weeks.
