### ISSUE TITLE
libSuperpoweredLinuxX86_64.a need to be compiled with -fPIC

### ISSUE THREAD

**Issue by loki666** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#331]
when trying to build a shared lib for linux which depends on libSuperpoweredLinuxX86_64.a, i get this

/usr/bin/ld: libs/Superpowered/libSuperpoweredLinuxX86_64.a(SuperpoweredMixer.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: libs/Superpowered/libSuperpoweredLinuxX86_64.a(SuperpoweredHome.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC

this is my link cmd
g++  obj/midiplay.o obj/adldata.o obj/nukedopl3.o libs/Superpowered/libSuperpoweredLinuxX86_64.a  -O0 -fno-inline -D_GLIBCXX_DEBUG -g -fstack-protector-all -fdata-sections libs/Superpowered/libSuperpoweredLinuxX86_64.a -shared -o bin/libadlmidi-lite.so

**Comment by superpoweredSDK** [comment]
We'll compile the next update with fPIC then!
