### ISSUE TITLE
Record internal audio from Android App

### ISSUE THREAD

**Issue by pratikrao** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#332]
Need to record internal audio from android app for instance as of Music  Maker Jam to allow user to create beats of their own and record....Need some example like that using Superpowered sdk..

**Comment by superpoweredSDK** [comment]
This is not an issue (bug or similar) with the Superpowered SDK. Please contact us at hello@superpowered.com .
Please note that recording other app's audio is not possible on Android, only with system hacks.

**Comment by pratikrao** [comment]
I don't need to record other app audio....Need to record my own app audio....is it possible through superpowered sdk
