### ISSUE TITLE
MP3 Decoding and Playback Issue With This MP3

### ISSUE THREAD

**Issue by fatihm85** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#334]
Hi,

The attached MP3 file was sent by one of my app users and it cannot be played with Superpowered SDK. Could you please resolve this issue? Thank you.
[night 1.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/1185585/night.1.zip)

Edit : It cannot be opened because it is a mono MP3, when I convert it to stereo it can be opened. Could you please provide a solution or fix this issue?

**Comment by superpoweredSDK** [comment]
Hi,

the linked file is not an mp3 file. It's a corrupted AAC file in a corrupted MPEG container, missing important chunks for decoding.
