### ISSUE TITLE
SuperpoweredRecorder setting tempath and Destination Path

### ISSUE THREAD

**Issue by pratikrao** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#335]
How to set the temp path and destination path in android for Superpowered Recorder....
Also which class to be used to record sound played by mediaplayer..

**Comment by superpoweredSDK** [comment]
This is not an issue of the Superpowered Audio SDK. Please use a Q&A platform for your questions or email at hello@superpowered.com
