### ISSUE TITLE
No Sound With new SDK version 1.07

### ISSUE THREAD

**Issue by fatihm85** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#336]
Hi,

When I update to the latest SDK 1.07, I get no sound while playback. The playback position progress but I get no sound. Could you please resolve this issue?

Thanks.
Kind Regards,
Fatih.

**Comment by superpoweredSDK** [comment]
Hi,

we are using the very same SDK in many example projects and all of them has sound where it should have sound. Please be more specific.

**Comment by superpoweredSDK** [comment]
I'll close this issue soon, if you don't reply.

**Comment by fatihm85** [comment]
I see that the reason of this issue is, SuperpoweredAdvancedAudioPlayer playing property does not return true value while playing.

**Comment by superpoweredSDK** [comment]
Under which circumstances does playing equal to false, when the player is playing (audio moves forwards) otherwise?
