### ISSUE TITLE
Empty Zendesk

### ISSUE THREAD

**Issue by 0joshuaolson1** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#337]
https://superpowered.zendesk.com/hc/en-us has no content or recent activity.

**Comment by superpoweredSDK** [comment]
We do respond on Zendesk for every enquiry, we receive 10+ every day typically. We have an older Zendesk plan where populating that page is not possible.

**Comment by 0joshuaolson1** [comment]
Why is this already closed? The link is still valid, and there's no article explaining that its only purpose is the 'Submit a request' feature.

**Comment by superpoweredSDK** [comment]
Hi Joshua, the ZenDesk is being populated as we write. Hopefully, it will be done and public in two weeks. If you have any questions, in the meantime, please email patrick@superpowered.com
