### ISSUE TITLE
Unknown file format

### ISSUE THREAD

**Issue by kubatatami** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#339]
I get SuperpoweredAdvancedAudioPlayerEvent_LoadError with message "Unknown file format" when I'm trying to load:
https://s3.amazonaws.com/vamp-files-v2/77/fa8df0-706a-4f1c-b818-d2225d6c24b7.mp4
on android from local storage. 
Other files like 
https://s3.amazonaws.com/vamp-files-v2/c0/29376b-96fa-43c3-bdb2-eec5a3dd7368.mp4
works great.

**Comment by superpoweredSDK** [comment]
The first file is too short, less than 4 frames long. The decoder consider it as incomplete.

**Comment by kubatatami** [comment]
@superpoweredSDK Is there any way to play that file on Superpowered?

**Comment by kubatatami** [comment]
@superpoweredSDK I check the frame count using this command:
`ffprobe -select_streams a -show_streams fa8df0-706a-4f1c-b818-d2225d6c24b7.mp4 2>/dev/null | grep nb_frames | sed -e 's/nb_frames=//'`
and it shows that a file has **35** frames.

**Comment by superpoweredSDK** [comment]
After giving this file a more thorough test, it shows that the stts table is too short (because the file is too short), and the decoder thinks it doesn't contain valid data. Just make the file longer.

**Comment by kubatatami** [comment]
@superpoweredSDK  I can't make it longer because files are downloaded from external source in runtime. I am creating an android app. Converting a file to add some silence on the end in android app will be difficult and makes app much bigger(ffmpeg) and processing significantly longer. I choose Superpowered because I need low latency and high performace. Is there any chance that you will fix that bug in the near future?

**Comment by superpoweredSDK** [comment]
The file is corrupted as the stts table is too short and provides data which the decoder thinks is not valid. The average number of samples is at 1003 according to the stts table, which is too low for AAC (where it's fixed at 1024). We can lower the bar for such correctness check in the future, but we don't know where to draw the line.

**Comment by kubatatami** [comment]
@superpoweredSDK Maybe you can add that frame limit as a parameter with some default value in SuperpoweredAdvancedAudioPlayer? So I will be able to set very low limit in my specific case.

**Comment by superpoweredSDK** [comment]
We'll just lower the bar for the next release.
