### ISSUE TITLE
How to Prevent Audio Clicks and Pops For Multiple Players

### ISSUE THREAD

**Issue by fatihm85** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#340]
I have a piano app which uses 84 SuperpoweredAdvancedAudioPlayers. I hear clicks, pops and noise when I play fast by moving fingers continuously on the keys. I cannot eliminate this although I use SuperpoweredCPU::setSustainedPerformanceMode(true);

I process player sounds like this:
    for (int i = 0; i < PLAYER_COUNT; i++) {
        if (player[i]->process(stereoBuffer, !silence, numberOfSamples, volume,0, -1.0)) {
            if (volume > 0) {
                silence = false;
            }
       }
  Could you please provide a solution to eliminate this issue? I have tried Stereo Mixer but nothing changed. I see that some other piano apps generate clear sound without clicks and pop. Thanks.

**Comment by superpoweredSDK** [comment]
The SuperpoweredAdvancedAudioPlayer is not the best solution to play short samples. It's like a "DJ hardware tabletop player", not a "sampler". I recommend to simply play back your samples from memory.

**Comment by fatihm85** [comment]
I use Superpowered SDK because Superpowered has better performance and audio effects than Android MediaPlayer and SoundPool classes. Android has too much audio latency. Could you please provide or develop an optimized solution for short samples to eliminate pops/clicks, dropouts and latency? I open all samples before playing in order to prevent latency. Could you please provide a caching for audio files in order to prevent latency while opening files? Maybe I can use reduce the number of players by instantly opening and playing samples.   How can I simply playback my samples from memory, is there any way to do this on OpenSL ES or in Superpowered SDK? Android SDK have too much latency for this task.  I also need great audio effects of Superpowered. Thanks for your support.

**Comment by superpoweredSDK** [comment]
We have no plans to implement such sample player yet, sorry.

**Comment by fatihm85** [comment]
It would be great to make some enhancements for shorter files. Thanks for your support.
