### ISSUE TITLE
Dear Superpowered SDK

### ISSUE THREAD

**Issue by nvThanh** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#341]
I'm now working on karaoke porject, i'm using SuperpoweredAndroidIO to let user input from mic and output to speaker. but it have a little bit delay especially when i sing a long senctence lyric. Could you please explain why and how do i minimize lacenty to 0, i have check the other app they can do with 0 lacenty
Thanks and best regard

**Comment by superpoweredSDK** [comment]
Please check the frequency domain example or the cross example projects on how to set up IO for low latency. Also don't 2x the buffer sizes like you see in the example projects.
