### ISSUE TITLE
"Unknown File Format", plays in all other players. Reencoding throws exceptions.

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#343]
Hello,

I have this file that plays in all other player's I've tried. It errors with Superpowered. Re-encoding it using ffmpeg causes superpowered to work, but it throws tons of exceptions when decoding/reading id3 tags. See attached files.

[superpowered-unknownfileformat.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/1249987/superpowered-unknownfileformat.zip)

**Comment by superpoweredSDK** [comment]
Superpowered doesn't work with this file format, because it's not an mp3, but an mp2 (mpeg-2 layer I or III). Will test the crash next week.

**Comment by superpoweredSDK** [comment]
Tested the "crashing" file with the upcoming version of Superpowered, no crash. Update in a few weeks.

**Comment by flagoworld** [comment]
I am having a similar issue with a different file. I re-encoded the original, forcing mp3 in ffmpeg, and in both cases I get "Unknown File Format". Obviously some kind of format issue going on here... Maybe you can help me figure out what's wrong with the file?

Could be a bug in Superpowered since re-encoding explicitly as mp3 doesn't fix it... but probably not. :)

ffprobe and ffmpeg reports that both the original and reencoded files are mp3 to begin with, but I am starting not to trust that very much...

[unknown-file-format.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/1350329/unknown-file-format.zip)

**Comment by svenoaks** [comment]
It's the same as #78, claim is that MPEG-2 Layer III isn't MP3 (??)

**Comment by flagoworld** [comment]
Just read through your ticket. Looks like my file is 22050 Hz, "mp3" as claimed by ffmpeg/ffprobe, VLC, wikipedia, etc.

https://en.wikipedia.org/wiki/MP3#Standardization
https://www.iso.org/standard/26797.html

It's been in the mp3 standard since 1995? It would be nice if Superpowered supported this version of mp3 as well.

Changing my file to 44100 did indeed fix it, but that is not an ideal solution for me.

**Comment by DanNi0130** [comment]
Struggling with this issue also, being able to play a 22050 hz file would be great.
