### ISSUE TITLE
SuperpoweredUSBSystem::onConnect returns 0 for Yamaha Keyboard

### ISSUE THREAD

**Issue by MatheusFSValin** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#344]
Hi!

When using the simpleusb example project, my Yamaha MOX 8 keyboard always return 0 on
SuperpoweredUSBSystem::onConnect call, so I can't get midi from it in the example

other apps can read audio and midi from the keyboard, so it's not a problem with the keyboard or my android device

What is wrong? 

thanks in advance

**Comment by superpoweredSDK** [comment]
Hello,

is that device USB MIDI Class Compliant? Unfortunately we don't have such device, so can't debug/test.

**Comment by MatheusFSValin** [comment]
Yeah , turns out it isn't MIDI Class Compliant :/
That means I can't use Superpowered with it?
Do you know of any other resource I could use to record audio from it? since there are apps that are capable of that, it's still possible

**Comment by superpoweredSDK** [comment]
USB Audio Class and USB MIDI Class means "driverless" operation. Seems like your device requires a driver, which you can't install on Android. Superpowered supports USB Audio Class and USB MIDI Class compliant devices only.
Does Superpowered recognise the audio part of your device? Which apps are capable to record audio from your keyboard on Android?

**Comment by MatheusFSValin** [comment]
How can I test if it recognises the audio part?
USB Midi Monitor (https://play.google.com/store/apps/details?id=com.extreamsd.usbmidimonitor) was able to get the midi inputs and 
Audio Evolution Mobile DEMO (https://play.google.com/store/apps/details?id=com.extreamsd.aemobiledemo) was able to record audio from it

**Comment by superpoweredSDK** [comment]
Can you please send the full USB descriptor of this device? That's the only way I can figure something out.

**Comment by MatheusFSValin** [comment]
Sure!
Not sure what you mean by USB Descriptor, so here is the device.toString() and the descriptor functions from a UsbConnection from it
If this is not what you asked, please let me know!

```
UsbDevice[mName=/dev/bus/usb/001/002,mVendorId=1177,mProductId=5379,mClass=239,mSubclass=2,mProtocol=1,mManufacturerName=Yamaha Corporation,mProductName=Yamaha MOX6/MOX8,mSerialNumber=null,mConfigurations=[
                                                                 UsbConfiguration[mId=1,mName=null,mAttributes=192,mMaxPower=1,mInterfaces=[
                                                                 UsbInterface[mId=0,mAlternateSetting=0,mName=null,mClass=255,mSubclass=1,mProtocol=0,mEndpoints=[]
                                                                 UsbInterface[mId=1,mAlternateSetting=0,mName=null,mClass=255,mSubclass=2,mProtocol=0,mEndpoints=[]
                                                                 UsbInterface[mId=1,mAlternateSetting=1,mName=null,mClass=255,mSubclass=2,mProtocol=0,mEndpoints=[
                                                                 UsbEndpoint[mAddress=1,mAttributes=5,mMaxPacketSize=288,mInterval=1]]
                                                                 UsbInterface[mId=2,mAlternateSetting=0,mName=null,mClass=255,mSubclass=2,mProtocol=0,mEndpoints=[]
                                                                 UsbInterface[mId=2,mAlternateSetting=1,mName=null,mClass=255,mSubclass=2,mProtocol=0,mEndpoints=[
                                                                 UsbEndpoint[mAddress=130,mAttributes=5,mMaxPacketSize=288,mInterval=1]]
                                                                 UsbInterface[mId=3,mAlternateSetting=0,mName=null,mClass=255,mSubclass=3,mProtocol=0,mEndpoints=[
                                                                 UsbEndpoint[mAddress=3,mAttributes=2,mMaxPacketSize=32,mInterval=1]
                                                                 UsbEndpoint[mAddress=132,mAttributes=2,mMaxPacketSize=32,mInterval=1]]
                                                                 UsbInterface[mId=4,mAlternateSetting=0,mName=null,mClass=3,mSubclass=0,mProtocol=1,mEndpoints=[
                                                                 UsbEndpoint[mAddress=133,mAttributes=3,mMaxPacketSize=8,mInterval=16]]]]
```

File Descriptor: 41
Raw Device Descriptors:
18,1,0,2,-17,2,1,8,-103,4,3,21,0,1,1,2,0,1,9,2,52,1,5,1,0,-64,1,8,11,0,4,-1,0,0,0,9,4,0,0,0,-1,1,0,0,10,36,1,0,1,52,0,2,1,2,12,36,2,1,1,1,0,2,3,0,0,0,9,36,3,2,1,3,0,1,0,12,36,2,3,3,6,0,2,3,0,0,0,9,36,3,4,1,1,0,3,0,9,4,1,0,0,-1,2,0,0,9,4,1,1,1,-1,2,0,0,7,36,1,1,1,1,0,11,36,2,1,2,3,24,1,68,-84,0,7,5,1,5,32,1,1,7,37,1,1,0,0,0,9,4,2,0,0,-1,2,0,0,9,4,2,1,1,-1,2,0,0,7,36,1,4,1,1,0,11,36,2,1,2,3,24,1,68,-84,0,7,5,-126,5,32,1,1,7,37,1,1,0,0,0,9,4,3,0,2,-1,3,0,0,7,36,1,0,1,96,0,6,36,2,1,1,0,6,36,2,1,2,0,6,36,2,1,3,0,6,36,2,1,4,0,6,36,2,1,5,0,9,36,3,1,6,1,1,1,0,9,36,3,1,7,1,1,1,0,9,36,3,1,8,1,1,1,0,9,36,3,1,9,1,1,1,0,9,36,3,1,10,1,1,1,0,7,5,3,2,32,0,1,7,5,-124,2,32,0,1,9,4,4,0,1,3,0,1,0,9,33,0,1,0,1,34,45,0,7,5,-123,3,8,0,16

**Comment by superpoweredSDK** [comment]
According to this USB Descriptor, this device has 6 vendor-specific interfaces and a HID interface.
The USB Class defines 1 as the audio class and 3 as the MIDI class.
This means that the device is not USB Audio or USB MIDI class compliant.

**Comment by superpoweredSDK** [comment]
http://www.usb.org/developers/defined_class
Could the Audio Evolution Mobile DEMO utilise all channels of the device, or just the first 2 one?
