### ISSUE TITLE
Multiple iOS crashes on onAudioSessionInterrupted (v1.0.7)

### ISSUE THREAD

**Issue by willocdev** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#345]
Getting multiple crash reports from line 179 of SuperpoweredIOSAudioIO.mm.

Line 179:
`NSNumber *wasSuspended = [notification.userInfo objectForKey:AVAudioSessionInterruptionWasSuspendedKey];
`

**Comment by superpoweredSDK** [comment]
Will be fixed in the next release (coming in a few weeks). Happens for older iOS versions without that key available. Workaround: if (&AVAudioSessionInterruptionWasSuspendedKey != NULL) {

**Comment by willocdev** [comment]
All crashes were from devices running iOS 10.2.1

**Comment by flagoworld** [comment]
Yes. Docs say this key is 10.3+

https://developer.apple.com/documentation/avfoundation/avaudiosessioninterruptionwassuspendedkey
