### ISSUE TITLE
Android Recorder Example?

### ISSUE THREAD

**Issue by josefkorbel** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#346]
Hello, 
Thanks for creating this awesome SDK because I've been struggling with USB audio recording for very long time, however, I cannot find any examples of SuperpoweredRecorder's method from its header file, is there any example out there for android with basic usb audio recording funcionality?

**Comment by superpoweredSDK** [comment]
Hello,

no, sorry, we are not able to create an example for every Superpowered feature yet.

**Comment by josefkorbel** [comment]
Hello,
Came across this one year after, is any example available?
