### ISSUE TITLE
Noise suppression and gain control?

### ISSUE THREAD

**Issue by leonylcatwork** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#347]
Does it has noise suppression and gain control functions? Cheers

**Comment by superpoweredSDK** [comment]
If you mean noise suppression and automatic gain control for the audio input, then the answer is no. Audio I/O is not strictly part of the SDK, although we offer helper classes to set up audio I/O. Device dependent noise suppression and AGC may be present.
