### ISSUE TITLE
Advanced Audio Player sample project

### ISSUE THREAD

**Issue by aChase55** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#349]
Please add a simplified advanced audio player sample project. Currently none of the sample projects show how to play an individual track with an advanced audio player.  All of the examples have other capabilities/dependancies. In other words, you should include a sample project that simply plays a local audio file via AdvancedAudioPlayer.  Also please consider supporting cocoapods.

**Comment by superpoweredSDK** [comment]
The cross example project shows two audio players and some effects. If you remove all code related to effects and player B, you get an example project of showing one player. This is around 5 minutes work for you to do.
Regarding cocoapods, please let us know the benefit. The current solution of drag&drop the .a file and the header files is quite quick.

**Comment by aChase55** [comment]
@superpoweredSDK I initially did what you suggested, remove all code related to fx and player b, which did take about five minutes. But still no dice. I think my issue has to do with the `audioProcessing` callback.  The `process` call on the player is always returning false, and I have no idea why.  I have called `play(true)` on the player but haven't gotten the player to produce any sound.  I'm thinking maybe it could have something to do with allocating the stereo buffer? But I'm not really sure.

I've even cleared out all the code in the cross example so that just PlayerA would play.  Verified it would work, and copied it into my own project.  In my project it does not play.  It may have something to do with the players being owned by the view controller in the cross example. I'm using swift and would like to have the player inside its own SuperPowered.mm file, similar to the `SuperpoweredFrequencies` example project. It may have something to do with my project configuration, which is why cocoapods would be helpful.

I filed this issue in relation:
https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/issues/348

I have no idea why audio isn't playing and I am completely stuck. **Please help**.

It's rather discouraging that both of these issues were closed off as "user error" off _so_ quickly. I think one advantage of cocoapods implementation is that a user can install the project correctly and get up and running quickly. Another benefit of cocoa pods is that there is less room for user error upon installation.  In addition to that you will have less issues to respond to regarding installation and cocoapods requests.
