### ISSUE TITLE
Needs more example for offline processing

### ISSUE THREAD

**Issue by jiayuzhang** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#35]
I try to process audio files by applying both SuperpoweredTimeStretching and other filters (i.e SuperpoweredWhoosh) and finally save to a file. However, the offline-processing example only tutors about SuperpoweredTimeStretching and the interface between SuperpoweredFX and SuperpoweredTimeStretching is quite different.

process (float *input, float *output, unsigned int numberOfSamples)
process (SuperpoweredAudiobufferlistElement *input, SuperpoweredAudiopointerList *outputList)

I'm not expert in c/c++, plz shed me some light and sample codes, that will save my life. Appreciate!

**Comment by superpoweredSDK** [comment]
At line 98 you get 32-bit floating point interleaved stereo audio in the buffer "timeStretchedAudio". You can process that between line 98-101.

**Comment by myrunrun** [comment]
I try it ,but failed.Please show me some light and sample codes!

**Comment by myrunrun** [comment]
@jiayuzhang Have you sloved your problem?

**Comment by chintan100** [comment]
I have the same question as @myrunrun and your code samples and explanation above seem to be geared towards experienced developers and not beginners in audio processing. 

It will be great if you can provide an example or code snippet here about how to save audio to file after applying SuperpoweredFX effect.

Thanks!
