### ISSUE TITLE
SuperpoweredAdvancedAudioPlayer playing property not returning true

### ISSUE THREAD

**Issue by fatihm85** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#350]
SuperpoweredAdvancedAudioPlayer playing property not returning true although the player is playing and positionMS progresses on Android.  There is no sound when the player progresses. This issue occurs on version 1.0.7 SDK and it does not appear on versions < 1.0.7. I see that it does not returns true and also there is no sound when I use player->play(true) for syncing players. Could you please resolve this issue? I need to use version 1.0.3 because later versions are not stable.  Thanks for your support.

   if (player[i]->playing)  // always false

**Comment by fatihm85** [comment]
I see that the player->play(true) does not play on version 1.0.7. The same syncing code was working on 1.0.3

**Comment by superpoweredSDK** [comment]
Do you always call the player's process() method in the audio processing callback?

**Comment by fatihm85** [comment]
Yes, I always call the process() method. It is working when I start playing by player->pause(false); but it does not play when I call player->pause(true) for syncing. The same code was working on 1.0.3.

**Comment by superpoweredSDK** [comment]
It waits to the perfect moment to start playback (you ask for a synchronised playback start). playing will be true as soon as the player starts playing. I'm guessing that your player has nothing to synchronise with, so it waits indefinitely.

**Comment by fatihm85** [comment]
Thanks for info.

**Comment by craftbox2245** [comment]
Error while executing process E:\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build E:\Test_project_android\superpowered-ndk-example-master\app\.externalNativeBuild\cmake\debug\armeabi-v7a --target SuperpoweredExample}
[1/2] Building CXX object CMakeFiles/SuperpoweredExample.dir/src/main/cpp/SuperpoweredExample.cpp.o
[2/2] Linking CXX shared library ..\..\..\..\build\intermediates\cmake\debug\obj\armeabi-v7a\libSuperpoweredExample.so
FAILED: cmd.exe /C "cd . && E:\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=armv7-none-linux-androideabi --gcc-toolchain=E:/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=E:/sdk/ndk-bundle/sysroot -fPIC -isystem E:/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=16 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security  -frtti -fexceptions -fsigned-char -Inull -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot E:/sdk/ndk-bundle/platforms/android-16/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libSuperpoweredExample.so -o ..\..\..\..\build\intermediates\cmake\debug\obj\armeabi-v7a\libSuperpoweredExample.so CMakeFiles/SuperpoweredExample.dir/src/main/cpp/SuperpoweredExample.cpp.o  -latomic -lm "E:/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_static.a" && cd ."
E:\Test_project_android\superpowered-ndk-example-master\app\src\main\cpp/SuperpoweredExample.cpp:18: error: undefined reference to 'SuperpoweredAdvancedAudioPlayer::SuperpoweredAdvancedAudioPlayer(void*, void (*)(void*, SuperpoweredAdvancedAudioPlayerEvent, void*), unsigned int, unsigned int)'
E:\Test_project_android\superpowered-ndk-example-master\app\src\main\cpp/SuperpoweredExample.cpp:19: error: undefined reference to 'SuperpoweredAdvancedAudioPlayer::open(char const*, int, int, char**)'
E:\Test_project_android\superpowered-ndk-example-master\app\src\main\cpp/SuperpoweredExample.cpp:21: error: undefined reference to 'SuperpoweredAndroidAudioIO::SuperpoweredAndroidAudioIO(int, int, bool, bool, bool (*)(void*, short*, int, int), void*, int)'
E:\Test_project_android\superpowered-ndk-example-master\app\src\main\cpp/SuperpoweredExample.cpp:27: error: undefined reference to 'SuperpoweredAndroidAudioIO::~SuperpoweredAndroidAudioIO()'
E:\Test_project_android\superpowered-ndk-example-master\app\src\main\cpp/SuperpoweredExample.cpp:28: error: undefined reference to 'SuperpoweredAdvancedAudioPlayer::~SuperpoweredAdvancedAudioPlayer()'
E:\Test_project_android\superpowered-ndk-example-master\app\src\main\cpp/SuperpoweredExample.cpp:34: error: undefined reference to 'SuperpoweredAdvancedAudioPlayer::play(bool)'
E:\Test_project_android\superpowered-ndk-example-master\app\src\main\cpp/SuperpoweredExample.cpp:36: error: undefined reference to 'SuperpoweredAdvancedAudioPlayer::pause(float, unsigned int)'
E:\Test_project_android\superpowered-ndk-example-master\app\src\main\cpp/SuperpoweredExample.cpp:41: error: undefined reference to '__android_log_print'
E:\Test_project_android\superpowered-ndk-example-master\app\src\main\cpp/SuperpoweredExample.cpp:45: error: undefined reference to 'SuperpoweredAdvancedAudioPlayer::setTempo(double, bool)'
E:\Test_project_android\superpowered-ndk-example-master\app\src\main\cpp/SuperpoweredExample.cpp:48: error: undefined reference to 'SuperpoweredAdvancedAudioPlayer::setTempo(double, bool)'
E:\Test_project_android\superpowered-ndk-example-master\app\src\main\cpp/SuperpoweredExample.cpp:51: error: undefined reference to 'SuperpoweredAdvancedAudioPlayer::setTempo(double, bool)'
E:\Test_project_android\superpowered-ndk-example-master\app\src\main\cpp/SuperpoweredExample.cpp:54: error: undefined reference to 'SuperpoweredAdvancedAudioPlayer::setTempo(double, bool)'
E:\Test_project_android\superpowered-ndk-example-master\app\src\main\cpp/SuperpoweredExample.cpp:60: error: undefined reference to '__android_log_print'
E:\Test_project_android\superpowered-ndk-example-master\app\src\main\cpp/SuperpoweredExample.cpp:62: error: undefined reference to 'SuperpoweredAdvancedAudioPlayer::setPitchShift(int)'
E:\Test_project_android\superpowered-ndk-example-master\app\src\main\cpp/SuperpoweredExample.cpp:67: error: undefined reference to 'SuperpoweredAdvancedAudioPlayer::seek(double)'
E:\Test_project_android\superpowered-ndk-example-master\app\src\main\cpp/SuperpoweredExample.cpp:71: error: undefined reference to 'SuperpoweredAdvancedAudioPlayer::process(float*, bool, unsigned int, float, double, double)'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

please help me my issue
