### ISSUE TITLE
Resampling @ 48khz

### ISSUE THREAD

**Issue by weepy** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#351]
Hi, I have an audio engine which needs to run at 44.1k, but of course on iOS you cannot guarantee that the main graph runs at this rate.  Can superpowered resample a stream ? Or any suggestions ?

**Comment by superpoweredSDK** [comment]
Yes, Superpowered has a resampler: http://superpowered.com/docs/class_superpowered_resampler.html

**Comment by weepy** [comment]
Ah I see - great thanks! ... I'm a bit unsure where to specify the rate change ? there's rateAdd, but that seems to imply a glide ?

**Comment by superpoweredSDK** [comment]
Yes, rateAdd is for smooth changes. Just set "rate".
