### ISSUE TITLE
Pitch Shifting on Live audio from mic

### ISSUE THREAD

**Issue by PavanKumarGAP** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#352]
Hi, 
I am trying to implement Pitch Shifting on Live audio from mic.
I am trying to use SuperpoweredTimeStretching.
 Is there any example for that or can you help with some sudo code so that i can try it out?

Thanks

**Comment by superpoweredSDK** [comment]
Sorry, but we're not able to create more example projects at this moment.
