### ISSUE TITLE
SuperpoweredAndroidAudioIO crashes whiles creating instance with input enabled

### ISSUE THREAD

**Issue by fatihm85** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#355]
I get the following crash log on Google Play Developer console. Could you please resolve this issue?  RECORD_AUDIO permission is checked before creating SuperpoweredAndroidAudioIO instance. The instance is created like this:

audioInput = new SuperpoweredAndroidAudioIO(samplerate, buffersize, true, false,
                                                    audioProcessing, this, -1,
                                                    SL_ANDROID_STREAM_MEDIA, buffersize * 2);       //crash

Thanks for your support.

********** Crash dump: **********
Build fingerprint: 'samsung/grandpplteser/grandpplte:6.0.1/MMB29T/G532FXWU1AQG5:user/release-keys'
pid: 32083, tid: 32083, name:****  >>> **** <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Stack frame     #00 pc 0003402e  /data/app/****/lib/arm/libSuperpoweredAudioIO.so (_ZN26SuperpoweredAndroidAudioIOC1EiibbPFbPvPsiiES0_iii+701): Routine SuperpoweredAndroidAudioIO at SuperpoweredSDK\Superpowered\AndroidIO/SuperpoweredAndroidAudioIO.cpp:185
Stack frame     #01 pc 00017a9f  /data/app/****/lib/arm/libSuperpoweredAudioIO.so (_ZN19SuperpoweredAudioIOC2EiPKcPi+1010): Routine SuperpoweredAudioIO at \src\main\jni/SuperpoweredAudioIO.cpp:494
Stack frame     #02 pc 0001a247  /data/app/****/lib/arm/libSuperpoweredAudioIO.so (Java_****_SuperpoweredAudioIO+154): Routine at \src\main\jni/SuperpoweredAudioIO.cpp:1840
Stack frame     #03 pc 01234651  /data/app/****/oat/arm/base.odex (offset 0xcd8000)

**Comment by superpoweredSDK** [comment]
SuperpoweredAndroidAudioIO is open source, you can check what happen there.
I'm guessing that the device you're trying to open an input on has no audio input available for some reason, and it also has a buggy implementation for Open SL ES to handle this. There is nothing we can do here.
