### ISSUE TITLE
memcpy Error Handling Request on Decoder

### ISSUE THREAD

**Issue by fatihm85** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#356]
I see that memcpy function called within pcmDecodeLittleEndian function at pcmreader.h file. The app crashes because of out of memory or the file is deleted. Could you please add error handling on memcpy?

I see that the app crashes on this line of code:
if (decoder->decode(intBuffer, &samplesDecoded) == SUPERPOWEREDDECODER_ERROR) break;

Could you please return SUPERPOWEREDDECODER_ERROR when the memcpy failed without crashing by error handling? Thank you.

Thanks.

**Comment by superpoweredSDK** [comment]
LOL, there is no error handling on memcpy. Memcpy is a low level memory copy API. It crashes only if the memory region it tries to read or write is invalid.
If this happens in relation to pcmreader, then the only thing crashing this can be an invalid or too small samplesDecoded.
