### ISSUE TITLE
Feature request - Add option to open the SuperpoweredAdvancedAudioPlayer directly from byte array

### ISSUE THREAD

**Issue by LainCoubrt** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#357]
At the moment the only option to **open** the **SuperpoweredAdvancedAudioPlaye**r and the **SuperpoweredDecoder** is from a file path. I think it would be great if there was a option to send the bytes directly to this open function. Is this possible in the near future?

**Comment by superpoweredSDK** [comment]
We don't have such plans for the near future, sorry.
Please use hello@superpowered.com for feature requests, since those are not "issues".
