### ISSUE TITLE
SuperpoweredRecorder in mono (using one channel)

### ISSUE THREAD

**Issue by drusak** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#359]
In 1.0.7.1 SuperpoweredRecorder supports any number of input channels. I'm trying to record with 1 channel (mono). But using same technic as for stereo Result sounds like robot. Should this new feature be used in some other way?
I guess clue is somewhere here in method process(short int *input, unsigned int numberOfSamples):
```
SuperpoweredShortIntToFloat(input, stereoBufferRecording, numberOfSamples, stereo ? 2 : 1);
data = recorder->process(stereoBufferRecording, NULL, numberOfSamples);
```
Could you help with it?
My goal is to record audio in Mono (because not all Android devices support Stereo).

Thanks in advance!

**Comment by superpoweredSDK** [comment]
Submit just 1 channel of audio in "stereoBufferRecording" (not the best name for this). Are you sure your "input" holds just 1 channel of audio?

**Comment by drusak** [comment]
I thought if I put channel number 1 to Recorder it will pass 'input' as mono, or I should handle it in some other way?

```
audioSystemRecording = new SuperpoweredAndroidAudioIO(sampleRate, bufferSize, true, false, audioProcessingRecording, this);
recorder = new SuperpoweredRecorder(tempPath, sampleRate, 1, stereo ? 2 : 1);
```

**Comment by superpoweredSDK** [comment]
You need to submit mono audio to the recorder if you want to record in mono. SuperpoweredSimple.h has various functions for mono conversion.
