### ISSUE TITLE
SuperpoweredAndroidIO and different samplerates

### ISSUE THREAD

**Issue by JMDidon** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#36]
Hello,

I would to know if it is possible to have different sample rates when using the AndroidIO class ? In my case, my input sample rate will be lower than the output. How could I do that, or what can I do to make it compatible ?

**Comment by superpoweredSDK** [comment]
Hi,

low latency audio on Android works with the device's native sample rate and buffer size only, this is a limitation by Android's audio stack. You can "convert" between sample rates using a resampler, such as the SuperpoweredResampler.

**Comment by JMDidon** [comment]
How can I use the SuperpoweredResampler class with the SuperpoweredAndroidAudioIO class ? It seems to me that the detection of the Android input is handled by OpenSL ES, so this should be where I should use the resampler, right ?

**Comment by JMDidon** [comment]
How does the resampler work ? I tried this in `SuperpoweredAndroidAudioIO` in the input callback, but to no avail:
```
float *output;
internals->resampler->process(input, output, 16000, false, false, internals->samplerate);
```
Thank you in advance !

**Comment by superpoweredSDK** [comment]
The samplerate for rateAdd is not good. It's a rate step function, stepping by a high value (such as a sample rate) is way too much. Leave that at 0 if you don't know what you do. :-)
Set the rate purely on the instance, like this: internals->resampler->rate = 1.1f;

**Comment by JMDidon** [comment]
Thanks for your response. However, it doesn't seem to solve my problem =/. I have a Nexus 5 with Android 5.1.1, and it seems that the input is all "scrambled": there is only static noise coming from the speakers when I speak or blow in the micro. Did you also had this problem ? I have not modified a lot the SuperpowredAndroidAudioIO class, I just tried the resampler with the value you advised me.

**Comment by superpoweredSDK** [comment]
No, we don't have such problem. Did you notice the resampler outputs floating point samples? Did you take care of that?

**Comment by JMDidon** [comment]
Yes I did. That's strange because I redone my app from the ground up with only the input and it worked. I will try to apply the effects on the input now :) Thank you very much for your help !
