### ISSUE TITLE
Clicks (buffer underruns?) when using macOS library

### ISSUE THREAD

**Issue by nevosegal** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#360]
Hi,

I am using the macOS library, and experiencing some clicks and pops, even when my audio callback is a simple passthrough.

What's interesting is that often the app starts up ok (not always), but then if I place a breakpoint and then release it, the clicks suddenly appear. Sometimes doing this several times eventually fixes the issue as well.

I looked through the macOS `.mm` file and saw that you keep track of even/odd inputs and outputs. Could this issue be related to that? I was also wondering why you keep track of this?

Thanks!
Nevo

**Comment by superpoweredSDK** [comment]
Hi,

the even/odd is there because we are using a pair of input and output buffers. Placing a breakpoint in a debugging session can introduce buffer underruns, this is how Xcode works, but it's not related to production code. Please check that even if your audio callback is doing passthrough only, it doesn't block somehow on a mutex or a static variable.

**Comment by nevosegal** [comment]
Hi @superpoweredSDK, thanks for the quick reply. I don't think it does, as the same code works fine on iOS - no clicks at all.

**Comment by superpoweredSDK** [comment]
iOS has a different audio stack. The effects of a block might be very different.

**Comment by nevosegal** [comment]
Alright, in any case there isn't any block in my code. Anything else I should check?

**Comment by nevosegal** [comment]
Do you have example code for macOS that I can try running on my machine and check if I can reproduce?

**Comment by superpoweredSDK** [comment]
Please try the ambi example project in the SuperpoweredSpatializer folder.

**Comment by nevosegal** [comment]
OK so I tried the ambi example project, and couldn't reproduce. However, this example doesn't accept microphone input, so it's not the same. Do you have an example that does both?

**Comment by superpoweredSDK** [comment]
In the ambi example project, just enable input.

**Comment by superpoweredSDK** [comment]
Still clicks?

**Comment by nevosegal** [comment]
I actually did experience some clicks on the ambi project as well. I'm still investigating so I'll comment here once I have more information.
