### ISSUE TITLE
Using kAudioUnitSubType_VoiceProcessingIO audio unit in macOS

### ISSUE THREAD

**Issue by nevosegal** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#362]
Hi,

I would like to use Apple's built-in echo canceller in a macOS app, with Superpowered.

I saw that you are using one audio unit for input, and one for output. As far as I understand, the echo canceller audio unit must do both input and output, which means I will need to replace the two audio units with one (`kAudioUnitSubType_VoiceProcessingIO`) that does both. Is there a reason to why you separated it to two? Why not have one that does both like you do in iOS?

Thanks!

**Comment by superpoweredSDK** [comment]
Hi,

having just one audio unit for both input and output didn't work on many MacBooks and USB audio devices.
Our OSX audio I/O class is fully open source and it's just an easy way to set up audio I/O, it's not strictly part of our SDK. It's just a helper. If you need advanced functionality, please modify our class or implement your own.

**Comment by rfistman** [comment]
`kAudioUnitSubType_VoiceProcessingIO` doesn't require you to use just one audio unit, but it does require your output unit to have `kAudioOutputUnitProperty_CurrentDevice` of the input device set on the input bus.
