### ISSUE TITLE
BPM is multiply by 2 for some files 

### ISSUE THREAD

**Issue by oazya500** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#363]
BPM is multiply by 2 for some files 

file in the link is multiplay by 2 . the lib show 173 BPM and the correct is 85 

[http://mesbahey.com/_0_0.wav](url)

void Player::detectFileBPM(const char *path) {
    SuperpoweredDecoder *decoder = new SuperpoweredDecoder();
    const char *openError = decoder->open(path);
    if (openError != NULL) {
        __android_log_print(ANDROID_LOG_VERBOSE, "SuperpoweredExample", "error %s", openError);

        delete decoder;
        return;
    }
    SuperpoweredOfflineAnalyzer *analyzer = new SuperpoweredOfflineAnalyzer(decoder->samplerate, 0, (int) decoder->durationSeconds);

    // Create a buffer for the 16-bit integer samples coming from the decoder.

    short int *intBuffer = (short int *)malloc(decoder->samplesPerFrame *2 * sizeof(short int) + 32768);
    // Create a buffer for the 32-bit floating point samples required by the effect.
    float *floatBuffer = (float *)malloc(decoder->samplesPerFrame *2 * sizeof(float) + 32768);

    // Processing.
    while (true) {
        // Decode one frame. samplesDecoded will be overwritten with the actual decoded number of samples.
        unsigned int samplesDecoded = decoder->samplesPerFrame;
        if (decoder->decode(intBuffer, &samplesDecoded) == SUPERPOWEREDDECODER_ERROR) break;
        if (samplesDecoded < 1) break;

        // Convert the decoded PCM samples from 16-bit integer to 32-bit floating point.
        SuperpoweredShortIntToFloat(intBuffer, floatBuffer, samplesDecoded);

        // Submit samples to the analyzer.
        analyzer->process(floatBuffer, samplesDecoded);
    };

    // Get the result.
    unsigned char *averageWaveform = NULL, *lowWaveform = NULL, *midWaveform = NULL, *highWaveform = NULL, *peakWaveform = NULL, *notes = NULL;
    int waveformSize, overviewSize, keyIndex;
    char *overviewWaveform = NULL;
    float loudpartsAverageDecibel, peakDecibel, bpm, averageDecibel, beatgridStartMs = 0;
    analyzer->getresults(&averageWaveform, &peakWaveform, &lowWaveform, &midWaveform, &highWaveform, &notes, &waveformSize, &overviewWaveform, &overviewSize, &averageDecibel, &loudpartsAverageDecibel, &peakDecibel, &bpm, &beatgridStartMs, &keyIndex);

    // Cleanup.
    delete decoder;
    delete analyzer;
    free(intBuffer);
    free(floatBuffer);

    playerA->setBpm(bpm);

    if (averageWaveform) free(averageWaveform);
    if (lowWaveform) free(lowWaveform);
    if (midWaveform) free(midWaveform);
    if (highWaveform) free(highWaveform);
    if (peakWaveform) free(peakWaveform);
    if (notes) free(notes);
    if (overviewWaveform) free(overviewWaveform);

}

**Comment by superpoweredSDK** [comment]
This is normal. Every bpm detection class has this problem, as it's very hard to decide the correct value in this range. You can narrow the bpm range in the constructor of SuperpoweredOfflineAnalyzer. If you set the maximum bpm to 160, it will return the correct value.
