### ISSUE TITLE
Superpowered in Service Best Practice

### ISSUE THREAD

**Issue by sam-murphy55** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#364]
This is not an issue, I just want a clarification on the best practice regarding using Superpowered Player as part of a Music Service. I have tried to initialize the Superpowered Player in a Service (as shown below) and the App is having an issue with battery drain due to Stuck Wake Locks. I guess I need to utilize SuperpoweredAdvancedAudioPlayer's onBackground and onForeground or onStop and onStart functions. However what I found in your documentation is comments regarding Activity.

So can you please let me know what is the best practice in order to avoid having Stuck Wake Locks (Battery drain) when using Superpowered as part of a Service? 

Thanks for your help and for this great Audio Engine!

```
SuperpoweredPlayer::SuperpoweredPlayer(unsigned int samplerate, unsigned int buffersize) {
    stereoBuffer = (float *) memalign(16, (buffersize + 16) * sizeof(float) * 2);
    outputBuffer = (float *) memalign(16, (buffersize + 16) * sizeof(float) * 2);

    // Allow one cached point, and set the buffer size to 15s.
    audioPlayer = new SuperpoweredAdvancedAudioPlayer(&audioPlayer, audioPlayerCallback,
                                                      samplerate, 1, 15);
    //audioPlayer->open(path);

    audioSystem = new SuperpoweredAndroidAudioIO(samplerate, buffersize, false, true,
                                                 audioProcessing, this, -1, SL_ANDROID_STREAM_MEDIA,
                                                 buffersize * 2);
    
    clipper = new SuperpoweredClipper();
    clipper->thresholdDb = -1.0f;
    eq = new Superpowered3BandEQ(samplerate);
    eq->enable(true);

}
```

**Comment by svenoaks** [comment]
You want to call SuperpoweredAndroidAudioIO.onBackground() or stop() to release the `AudioMix `wakelock and stop the OpenSL callback when you're paused. It's irrelevant if its done through Service or Activity. You don't want to leave the Service running with the callback/wakelock going for long periods of time when you're not playing, that's what causes the battery drain.

I'm not sure of the exact difference between `onBackground()` and `stop()` (perhaps Superpowered can say for sure, `onBackground()` ends up doing the same `stopQueues()` function anyway), but I simply call `onForeground()` when play and `onBackground()` and have no wakelock/battery drain issues anymore.

**Comment by superpoweredSDK** [comment]
onBackground and onForeground are there to automatically save battery when nothing is playing.

start and stop are there for programmatic/manual control.
