### ISSUE TITLE
Forced USB audio output (Android)

### ISSUE THREAD

**Issue by ifyousleep** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#365]
Tell me, please, how to forcibly output audio to a connected USB audio card using Superpowered? 
Is this possible?

**Comment by superpoweredSDK** [comment]
Check our USB example project in the Examples_Android folder. That's the only way to do it.

**Comment by ifyousleep** [comment]
Ok. Thank. 
I did not ask the right question. Excuse me.
Can I play audio use android.media.AudioTrack to a connected USB audio card using Superpowered?
I ask, if possible, to help with the code.
