### ISSUE TITLE
Compiler Warning

### ISSUE THREAD

**Issue by mlostekk** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#366]
Hey there, i just downloaded the latest SDK and found one warning in "SuperpoweredIOSAudioio.mm" in line number 180

```if (&AVAudioSessionInterruptionWasSuspendedKey != NULL) {```

it says

``` Superpowered/SuperpoweredIOSAudioIO.mm:180:18: Comparison of address of 'AVAudioSessionInterruptionWasSuspendedKey' not equal to a null pointer is always true```

just FYI

**Comment by superpoweredSDK** [comment]
Hi,

this doesn't appear in our Xcode. We are using Xcode 9.0. Perhaps you're not targeting iOS versions where this key is not present? Such as iOS 9?

**Comment by mlostekk** [comment]
Happening here with Xcode 9.0 (9A235) and Target with Deployment Target 11.0

**Comment by superpoweredSDK** [comment]
Yes. If you target iOS 11 exclusively, then this key is always present. But it's not present in iOS 9 for example. If it hurts your eye, surround it like this:

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wtautological-pointer-compare"
            if (&AVAudioSessionInterruptionWasSuspendedKey != NULL) {
#pragma clang diagnostic pop
