### ISSUE TITLE
On some songs the reported BPM rate is approximately twice as high as in online databases

### ISSUE THREAD

**Issue by o1exij** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#367]
I was using the swift wrapper https://github.com/Luccifer/BPM-Analyser. The reported BPM rate was significantly different to what is reported in online sources. Examples:

IN EXTREMO 'Lebensbeichte'
REPORTED BPM: 178
https://songbpm.com/in-extremo-lebensbeichte?q=In%20Extremo%20-%20Lebensbeichte: 89

DEPECHE MODE 'A question of lust'
REPORTED BPM: 187.5
https://songbpm.com/depeche-mode-a-question-of-lust?q=depeche%20mode%20-%20a%20question%20of%20lust: 96

the other songs however are (almost) identical:
Archive - 'You make me feel'
REPORTED BPM: 167
https://songbpm.com/archive-you-make-me-feel?q=Archive%20-%20You%20make%20me%20feel: 167

**Comment by superpoweredSDK** [comment]
This is a known problem of any bpm detection library. It's very hard to decide the correct value where a double or half bpm could be plausible. Our detector library can receive a maximum and minimum bpm value, so if you know the ballpark range for these, you can help finding the correct value.

**Comment by o1exij** [comment]
Thanks, I found exactly what you're describing in an other tool: https://support.native-instruments.com/hc/en-us/articles/209550849-The-Track-BPM-Detected-by-TRAKTOR-is-Half-or-Twice-the-Original-BPM-of-the-Track

**Comment by o1exij** [comment]
However, how can we as humans tell, what's the correct bpm?

**Comment by superpoweredSDK** [comment]
Most humans can't tap precisely on the beats, despite of they feel otherwise. Tapping is typically happening in a 20 bpm wide range...
Humans can separate most instruments and lyrics, technology can't do that yet. Those help deciding if the tempo is double or half.
