### ISSUE TITLE
how to estimate latency of an android device ?

### ISSUE THREAD

**Issue by b2renger** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#37]
Hello,

I have notice the /SuperpoweredPerformance (iOS) and the  android app to test latency http://superpowered.com/latency/#axzz3bpJmBZ7c

I was wondering if there was a sample code to get estimated latency on android somewhere ?

I am considering using superpoweredSDK to build an app that will let people tap on their screen to create cued annotation (maybe in csv format), and I could highly benefit from knowing the latency of the device I'm on, and I should also probably worry about touch screen latency.

I'm not really used to C and C++ and I have a relatively low amount of time so I need to carefully consider before diving in. This sdk seems to be what I'm looking for any advice on the subject would be greatly appreciated.

**Comment by superpoweredSDK** [comment]
Hello,

the latency app is totally open source: https://github.com/superpoweredSDK/SuperpoweredLatency
You don't need the Superpowered Audio SDK to build it, we did not use any closed source code for this particular project for full transparency.
