### ISSUE TITLE
Partial support for Windows?

### ISSUE THREAD

**Issue by swan488** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#370]
Love the superpoweredSDK, I wonder if it's possible for you guys to provide static lib for only SuperpoweredAdvancedAudioPlayer and utilities in SuperpoweredSimple for Windows? I imagine the AudioIO part is a big chunk of platform specific work, but it may be easier to provide partial support? For users who wants to use another layer for audio IO, this would be amazing!

**Comment by superpoweredSDK** [comment]
Windows support needs examples and tests too, so audio IO is not the big problem here. Thank you for the feature request!
