### ISSUE TITLE
Distortion on Samsung s8 phones

### ISSUE THREAD

**Issue by palad1** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#371]
Hello, users are complaining about distorted bass on Samsung s8 phones, with and without UHD, both on headphones and speaker. Did you have other reports of this issue?

**Comment by svenoaks** [comment]
@palad1 See my #298. There really should be two buffers always with Android 7+. Even so, I think there is a problem with OpenSL on these phones and you need to use performance mode when app is in background otherwise there are still dropouts

**Comment by superpoweredSDK** [comment]
Update to the latest version of Superpowered and let me know your results.

**Comment by superpoweredSDK** [comment]
Any feedback?
