### ISSUE TITLE
When is the right time to set player->loop ?

### ISSUE THREAD

**Issue by alexfoxy** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#372]
I'm having an issue setting a loop using the SuperpoweredAdvancedAudioPlayer. I'm running:

```
player->open(filepath);
player->loop(0, 20, false, 255, false);

```

But the loop is ignored. If I run the player->loop code later, for example when I'm about to start the player it works as expected. 

Also, is the SuperpoweredAdvancedAudioPlayer set to loop by default ?

Thanks!

**Comment by superpoweredSDK** [comment]
Check the player callback. When open is successful, you can call ->loop(). The player is not set to looping by default. Check how the EOF event is handled in your player callback.
