### ISSUE TITLE
audioCallback not being called

### ISSUE THREAD

**Issue by josefkorbel** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#373]
Greetings,

Im struggling with a little problem right now, Im using `SuperpoweredAndroidAudioIO` and `SuperpoweredRecorder` classes to record audio from USB microphone connected via OTG. However, the callback `bool audioCallback(void *clientdata, short int *audioIO, int numberOfSamples, int samplerate)` is never called (I have log inside that function that is never called, it was actually outputing something before I've approved `RECORD_SOUND` permission, really strange. Here is my code:

startIO function
```c++
JNI(void, startIO, PID)(JNIEnv *env, jobject __unused obj) {
    // Create Recording buffer
    stereoBuffer = (float *)memalign(16, (stereoBufferSize + 16) * sizeof(float) * 2);
    ALOG("Before init");
    audioSystem = new SuperpoweredAndroidAudioIO(44100, stereoBufferSize, true, false, audioCallback, 0, -1, 0, 0);
    ALOG("After init");
}
```

audioCallback - ALOG is never called
```c++
bool audioCallback(void *clientdata, short int *audioIO, int numberOfSamples, int samplerate) {
	ALOG("Data %d", audioIO);
	SuperpoweredShortIntToFloat(audioIO, stereoBuffer, numberOfSamples);
        return recorder->process(stereoBuffer, NULL, numberOfSamples);
}
```

startRecording
```c++
JNI(bool, startRecording, PID)(JNIEnv *env, jobject __unused obj, jstring tempPath, jstring destPath) {

    const char* tpath = env->GetStringUTFChars(tempPath, NULL);
    const char* dpath = env->GetStringUTFChars(destPath, NULL);
    bool status;

    recorder = new SuperpoweredRecorder(tpath, 44100);
    if (!recording) {
        status = recorder->start(dpath);
        recording = true;
        ALOG("Recorder initialized and started");
    }

    env->ReleaseStringUTFChars(tempPath, tpath);
    env->ReleaseStringUTFChars(destPath, dpath);
    return status;

}
```

I can locate the file, it is created, but it has (obviously) 0 bytes because of the missing data from the callback, what am I missing please? Im staring into this for hours without luck.

**Comment by josefkorbel** [comment]
EDIT:

I just found out if i edit `audioCallback` method like this:
```c++
bool audioCallback(void *clientdata, short int *audioIO, int numberOfSamples, int samplerate) {
	ALOG("Data %d", audioIO);
	return true;
	//return processRecording(audioIO, numberOfSamples);
}
```
I can now see the data output, but it is not piped to the next processing thus making it useless.
```
10-18 16:14:40.771 23818-24825/? I/C USB Class: Data 218609472
10-18 16:14:40.771 23818-24825/? I/C USB Class: Data 218609792
10-18 16:14:40.771 23818-24825/? I/C USB Class: Data 218610112
10-18 16:14:40.771 23818-24825/? I/C USB Class: Data 218610432
10-18 16:14:40.771 23818-24825/? I/C USB Class: Data 218610752
10-18 16:14:40.771 23818-24825/? I/C USB Class: Data 218611072
10-18 16:14:40.771 23818-24825/? I/C USB Class: Data 218611392
10-18 16:14:40.788 23818-24825/? I/C USB Class: Data 218606592
10-18 16:14:40.788 23818-24825/? I/C USB Class: Data 218606912
10-18 16:14:40.788 23818-24825/? I/C USB Class: Data 218607232
10-18 16:14:40.788 23818-24825/? I/C USB Class: Data 218607552
10-18 16:14:40.789 23818-24825/? I/C USB Class: Data 218607872
10-18 16:14:40.789 23818-24825/? I/C USB Class: Data 218608192
10-18 16:14:40.789 23818-24825/? I/C USB Class: Data 218608512
10-18 16:14:40.789 23818-24825/? I/C USB Class: Data 218608832
10-18 16:14:40.789 23818-24825/? I/C USB Class: Data 218609152
```

Any ideas? Thanks ~

**Comment by superpoweredSDK** [comment]
You're returning with "recorder->process".  It returns with the number of seconds recorded so far. Just always return with true, and uncomment the other stuff.

**Comment by josefkorbel** [comment]
Hello, thanks for fast response, however, it doesnt changed anything.
audioCallback now looks like this
```c++
bool audioCallback(void *clientdata, short int *audioIO, int numberOfSamples, int samplerate) {
	ALOG("Data %d", audioIO);
	SuperpoweredShortIntToFloat(audioIO, stereoBuffer, numberOfSamples);
        recorder->process(stereoBuffer, NULL, numberOfSamples);
        return true;
}
```

However i still dont see the data log.

DISCOVERY:
I just found out that if i unplug the USB microphone from phone, it start to spit out the data from the ALOG function, it is possible that `SuperpoweredAndroidAudioIO` is using built-in microphone instead of the USB OTG one? Thanks~

**Comment by superpoweredSDK** [comment]
Android has very bad support for USB devices. Are you able to record audio with the USB microphone with other apps?

**Comment by josefkorbel** [comment]
@superpoweredSDK Yes, it is working with every USB recording app on Google Play but al them are using messy lib-usb implementations., I've tested 3 different microphones.

**Comment by superpoweredSDK** [comment]
Is it working with a non-specialised USB recording app? A simple recorder?

**Comment by josefkorbel** [comment]
I dont know how you mean that, it is not - Android doesnt support USB audio out of the box. It is working with USB recording apps, but most of them are using lib-usb. Im starting to feel desperate.

**Comment by superpoweredSDK** [comment]
SuperpoweredAndroidAudioIO is using the default audio stack of Android (and configuring it to low latency if that's available). For USB audio I/O you need to check SuperpoweredUSBAudio.
