### ISSUE TITLE
Can't open track with space in path or unicode using SuperpoweredAdvancedAudioPlayer

### ISSUE THREAD

**Issue by swan488** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#374]
Hi There,

I can't find much details on whether unicode is supported, and it doesn't seem to work. Also i get SuperpoweredAdvancedAudioPlayerEvent_LoadError when calling open with a file path that contains a space.

I'm wondering if I'm doing something wrong or if this isn't supported, if so, any plan to support this?

Cheers

**Comment by superpoweredSDK** [comment]
Superpowered is a low-level C++ API. It needs the low-level "file system representation" path.

**Comment by swan488** [comment]
Thanks for answering, i'll see what I'm doing wrong..

**Comment by swan488** [comment]
Hi Owner, I just went back and tried again, opening files with space in name still doesn't seem to work with SuperpoweredAdvancedAudioPlayer. Could you please test and let me know if this is expected? I checked in the debugger, the char for space is 0x20. My knowledge on strings and encoding is a bit limited, please enlighten me on how to do this, for example what encoding is expected if that is a valid question?

**Comment by superpoweredSDK** [comment]
If you are on iOS, then the path will be [path fileSystemRepresentation]. Try that (and NSLog it to see how such paths really look like).

**Comment by swan488** [comment]
Hi thanks! Tried with cross example and verified that paths with space does work, I will check my code. Cheers!
