### ISSUE TITLE
record using SuperpoweredRecorder not working on iOS

### ISSUE THREAD

**Issue by quangbachit** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#375]
I want to record audio on iOS:
- First, i create new Recorder 
` NSDate *date = [NSDate date];
    NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
    [formatter setDateFormat:@"YYMMDD-hhmmss"];
    NSString *timeString = [formatter stringFromDate:date];
    
    NSString *fileNameAudio = [@"Audio-" stringByAppendingString:timeString];
    _audioFilePath = [NSTemporaryDirectory() stringByAppendingString:fileNameAudio];
    NSString *temp = [NSTemporaryDirectory() stringByAppendingString:@"temp"];
    recorder = new SuperpoweredRecorder([temp UTF8String], 44100);`

- I start record with: `recorder->start([_audioFilePath UTF8String]);`
-process in callBack: `if (!self->isPauseRecord) {
        self->recorder->process(interleaved, numberOfSamples);
    }`.

problem, it isn't working, Why?

**Comment by superpoweredSDK** [comment]
Are you sure you're passing a valid path in _audioFilePath?

**Comment by quangbachit** [comment]
_audioFilePath: /private/var/mobile/Containers/Data/Application/tmp/Audio-20171019
is it true?

**Comment by superpoweredSDK** [comment]
[NSTemporaryDirectory() fileSystemRepresentation] is the true path

**Comment by quangbachit** [comment]
I have fixed it.
Thank you very much
