### ISSUE TITLE
Unreal Engine 4 support

### ISSUE THREAD

**Issue by JamesMugford** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#377]
I'm embarking on making an Unreal Engine integration for the Superpowered SDK.

Is there any existing code or tips you can throw my way in order to get started on this?

Happy to provide pull requests, if you think this would be of value.

Best Regards,
James

**Comment by superpoweredSDK** [comment]
We have 0 experience with Unreal. But Unreal's documentation reveals a starting point, the BlankPlugin, here: https://docs.unrealengine.com/latest/INT/Programming/Plugins/

**Comment by rdthompson2020** [comment]
Has this changed any (Superpowered SDK for Unreal Engine) since this was posted?
