### ISSUE TITLE
Change the tempo with different IO

### ISSUE THREAD

**Issue by ifyousleep** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#378]
When I use
 ```
audioPlayer->open(path, 0, fileLength);
SuperpoweredAndroidAudioIO(samplerate, buffersize, false, true, 
audioProcessingDefault, this, -1, SL_ANDROID_STREAM_MEDIA, buffersize * 2);
```
and while playing music use
`audioPlayer->setTempo(tempo, true);`
tempo of music is changing

But if there is a connection to the audio usb and I'm using
```
audioPlayer->open(path, 0, fileLength);
SuperpoweredUSBAudio::easyIO(devID, samplerate, 
16, 0, 1, SuperpoweredUSBLatency_High, this, audioProcessingUsb) 
```
and while playing music use
`audioPlayer->setTempo(tempo, true);`
tempo of music is not changing

Why?

**Comment by ifyousleep** [comment]
Strangely enough, I checked now, I connected the hdmi output, and the tempo does not change again. And when I run the code on the phone, everything is ok.
Can someone suggest how to change the tempo of music when a device with an audio output is connected?

**Comment by superpoweredSDK** [comment]
A SuperpoweredAdvancedAudioPlayer's tempo has nothing to do with the IO. audioPlayer is not a Superpowered class, it's a custom code written by you? Check the bug there please.
