### ISSUE TITLE
SuperpoweredAdvancedAudioPlayerEvent_LoopEnd for loop end in reverse mode

### ISSUE THREAD

**Issue by mlostekk** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#379]
Hey there,

is it possible to get an event if a loop was done playing backwards? Something like `SuperpoweredAdvancedAudioPlayerEvent_LoopEnd` but in reverse playing mode?

**Comment by superpoweredSDK** [comment]
I put this onto our list as a feature request.

**Comment by mlostekk** [comment]
Do you have some compact release notes somewhere in order for me to follow them and see when this will be implemented?

**Comment by superpoweredSDK** [comment]
We always put the modifications into the GitHub commits.
The next update will have the SuperpoweredAdvancedAudioPlayerEvent_LoopStartReverse event.
I don't have an ETA for the next update. Perhaps before Christmas, but if not, then in January.
