### ISSUE TITLE
Not found shortIntToFloat in SuperpoweredStereoMixer

### ISSUE THREAD

**Issue by smbitz** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#38]
From this https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/issues/24

In while loop, He used function named SuperpoweredStereoMixer::shortIntToFloat.
But in SuperpoweredMixer.h don't have it.

How I do to use this function ?

Thank You.

**Comment by superpoweredSDK** [comment]
That API is moved into the SuperpoweredSimple.h
