### ISSUE TITLE
recording from USB microphone Android

### ISSUE THREAD

**Issue by ifyousleep** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#380]
I have Input and Output in USB
```
SuperpoweredUSBAudio::easyIO(devID, samplerate, 16, 2, 2, SuperpoweredUSBLatency_High, this,
                                     audioProcessingUsb);
```
And in my callback 
```
static bool audioProcessingUsb(void *clientdata, int __unused deviceID, float *audioIO, int numberOfSamples,
                   int samplerate, int __unused numInputChannels, int numOutputChannels) { .....
```
i have float *audioIO
How to split the float * audioIO into the input and output to record only the sound from the microphone to the file?

**Comment by superpoweredSDK** [comment]
audioIO will have the microphone input as floating point data. What exactly would you like to "split"?

**Comment by ifyousleep** [comment]
I have a synchronous and simultaneous audio input and audio output via usb. I need to split the audio input from the microphone and the audio output from the player.

**Comment by superpoweredSDK** [comment]
audioIO will have the microphone input as floating point data. Process that first, then overwrite it with the audio output from your player.

**Comment by ifyousleep** [comment]
Hmm, when I in callback with float *output do the following
```
audioRecorder->process(output, NULL, numberOfSamples);
```
a voice from the microphone and music are written to the file. Is it possible to record only the input from the microphone? And do not record music that
```
bool silence = audioPlayer->process(output, false, numberOfSamples);
return silence;
```

**Comment by superpoweredSDK** [comment]
If you call audioRecorder->process before audioPlayer->process, then the recorder will "record" the microphone input only.

**Comment by ifyousleep** [comment]
I'm doing it. Here is my code.
 ```
audioRecorder->process(output, NULL, numberOfSamples);
bool silence = audioPlayer->process(stereoBuffer, false, numberOfSamples);
stereoBuffer = output;
return silence;
```
but a voice from the microphone and music are written to the file (

**Comment by superpoweredSDK** [comment]
I don't understand what you do with "stereoBuffer". What does stereoBuffer = output do?
Are you sure you are recording the player's output, and not the player's output going to the speakers, then traveling back to the microphone over the air?

**Comment by ifyousleep** [comment]
Big thanks!
