### ISSUE TITLE
play(true) - stuck on buffering

### ISSUE THREAD

**Issue by weepy** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#381]
Hi I'm trying to use the Advanced Audio Player and finding that it works fine with play(false) but not with play(true) --- (i.e. synchronised).

If I do `superpoweredPlayer->play(true);` the player is always "waitingForBuffering"

This isn't the case with `superpoweredPlayer->play(false);`

Any thoughts ?

**Comment by superpoweredSDK** [comment]
The player is waiting for something to "sync" to. Are you submitting continuous master beat grid information in masterBpm and masterMsElapsedSinceLastBeat?

**Comment by weepy** [comment]
Yes. So I’m passing in the masterbpm and the masterMsElapsedSinceLastBeat
is essentially fmod(samplesPulled/sampleRate, beatDuration)

Is that right ?

**Comment by superpoweredSDK** [comment]
No, that doesn't look right. Let's expand what masterMsElapsedSinceLastBeat means: MILLISECONDS elapsed since the last beat. Let's say the masterBpm is 120, then one beat is 500 milliseconds, therefore the masterMsElapsedSinceLastBeat should have the values between 0..500.

**Comment by weepy** [comment]
OK - so I tried to implement similar "master grid" into SuperpoweredCrossExample : 

```

static double numSamplesPulled = 0.0;

// This is where the Superpowered magic happens.
static bool audioProcessing(void *clientdata, float **buffers, unsigned int inputChannels, unsigned int outputChannels, unsigned int numberOfSamples, unsigned int samplerate, uint64_t hostTime) {
    __unsafe_unretained ViewController *self = (__bridge ViewController *)clientdata;


    float masterBpm = 80;
    double beatDurationMs = 60000.0 / masterBpm;
//    double msElapsedSinceLastBeat = 0; // sync
    double msElapsedSinceLastBeat = fmod(numSamplesPulled/samplerate*1000.0, beatDurationMs); // NO sync
    
    numSamplesPulled += numberOfSamples;

    bool silence = !self->playerA->process(self->stereoBuffer, false, numberOfSamples, self->volA, masterBpm, msElapsedSinceLastBeat);
    if (self->playerB->process(self->stereoBuffer, !silence, numberOfSamples, self->volB, masterBpm, msElapsedSinceLastBeat)) silence = false;

    if (!silence) SuperpoweredDeInterleave(self->stereoBuffer, buffers[0], buffers[1], numberOfSamples);
    return !silence;
}
```

So I get the tracks playing back, but they are not synced. However if I set msElapsedSinceLastBeat to 0 always - it works. 

I think I'm not quite understanding what it should be going on!

**Comment by weepy** [comment]
I am getting the values ~ between 0-500 from the above code.

**Comment by superpoweredSDK** [comment]
You start both tracks with play(true)?

**Comment by weepy** [comment]
I've not changed anything from the repo version other than the function
above.

The play code is =>

```

- (IBAction)onPlayPause:(id)sender {

    UIButton *button = (UIButton *)sender;

    if (playerA->playing) {

        playerA->pause();

        playerB->pause();

    } else {

        bool masterIsA = (crossValue <= 0.5f);

        playerA->play(!masterIsA);

        playerB->play(masterIsA);

    };

    button.selected = playerA->playing;

}

```


I'll try to both true as I can see why maybe there's an issue

**Comment by weepy** [comment]
OK that worked !

But why did it work if `double msElapsedSinceLastBeat = 0;`  ?

**Comment by superpoweredSDK** [comment]
The sync moment is when msElapsedSinceLastBeat crosses 0, which indicates a "beat". Telling 0 indicated "now is the time".

**Comment by weepy** [comment]
Right. So it’s saying there’s always a beat. But what does that mean the
the Superpowered player ?

**Comment by weepy** [comment]
Do you mind explaining a little more ?
