### ISSUE TITLE
Please document the WakeLocks aquired by SuperPowered on Android

### ISSUE THREAD

**Issue by palad1** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#382]
Hi, I am troubleshooting issues where I am using SuperpoweredDecoder in a service. As my application has a complex lifecycle that involves several different wake-locks at different levels, I would prefer to manually handle wake locks, could you let me know when Superpowered takes a wake lock named "audioWakeLock" and how I can disable this behaviour if possible.

Thanks!

**Comment by superpoweredSDK** [comment]
We don't use any wake locks in Superpowered.

**Comment by palad1** [comment]
What about the background and foreground calls then?

**Comment by superpoweredSDK** [comment]
SuperpoweredAndroidAudioIO is an open-source helper to setup audio I/O on Android. You can check it's source. Wake locks are not handled there either.
