### ISSUE TITLE
Midi note and SuperpoweredAdvancedAudioPlayer

### ISSUE THREAD

**Issue by ifyousleep** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#383]
Is it possible to play note from midi with the help of the Superpowered player?

**Comment by superpoweredSDK** [comment]
MIDI notes are just... notes. Like "C3". The Superpowered player plays audio.

**Comment by ifyousleep** [comment]
I understand completely. But I thought maybe you were faced with the transformation of notes into sound.

**Comment by superpoweredSDK** [comment]
That would involve shipping a full instrument library. It doesn't fit into the purpose of Superpowered, sorry.
