### ISSUE TITLE
Audio glitches and dropouts

### ISSUE THREAD

**Issue by drusak** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#385]
Hi,

Some users of my Android app complain about many glitches and dropouts of audio playback on some devices. 
Here is the code snippets I use to play and record:
- getting audio params from system (sampleRate and bufferSize):

```
AudioManager audioManager = (AudioManager) BattleMeApplication.getInstance().getSystemService(Context.AUDIO_SERVICE);
String samplerateString = audioManager.getProperty(AudioManager.PROPERTY_OUTPUT_SAMPLE_RATE);
String buffersizeString = audioManager.getProperty(AudioManager.PROPERTY_OUTPUT_FRAMES_PER_BUFFER);
sampleRate = !TextUtils.isEmpty(samplerateString) ? Integer.parseInt(samplerateString) : 44100;
bufferSize = !TextUtils.isEmpty(buffersizeString) ? Integer.parseInt(buffersizeString) : 512;
```

- Init audioIO (C code) it should support playback and recording so it is created with both Input and Output:

```
audioSystem =
                new SuperpoweredAndroidAudioIO(
                        sampleRate,
                        bufferSize,
                        true,
                        true,
                        audioProcessing,
                        this,
                        SL_ANDROID_RECORDING_PRESET_GENERIC,
                        SL_ANDROID_STREAM_MEDIA,
                        bufferSize * 2);
```
- player creation (there are can be several players playing simultaneously, but problem occurs even with one player!):
```
SuperpoweredAdvancedAudioPlayer *player =
            new SuperpoweredAdvancedAudioPlayer(this,
                                                playerEventCallback,
                                                (unsigned int) sampleRate,
                                                0);
players[playerIndexCounter++] = player;

player->open(path, fileOffset, fileSize);

player->syncMode = SuperpoweredAdvancedAudioPlayerSyncMode_TempoAndBeat;
```

- and process() method, (there are can be several players playing simultaneously, but problem occurs even with one player!)
```
bool AudioEngine::process(short int *audioIO, unsigned int numberOfSamples) {
    bool silence = playersCount > 0;
    for (int i = 0; i < playersCount; i++) {
        bool processed = players[i]->process(stereoBufferPlayback, !silence, numberOfSamples, volume);
        if (processed) {
            silence = false;
        }
    }

    if (recording) {
        if (silence) {
            // silence
            recorder->process(NULL, numberOfSamples);
        } else {
            SuperpoweredShortIntToFloat(audioIO, stereoBufferRecording, numberOfSamples);
            recorder->process(stereoBufferRecording, NULL, numberOfSamples);
        }
    }
    bool playbackProcessed = playersCount > 0 && !silence;
    if (playbackProcessed) {
        // write playback buffer to io stream audio
        SuperpoweredFloatToShortInt(stereoBufferPlayback, audioIO, numberOfSamples);
    }
    return playbackProcessed;
}
```

What can be wrong here? Is it possible that bufferSize is too small?
I tested on my devices and it seems fine.
SuperpoweredSDK version is 1.1.0
Appreciate any help or ideas how to solve it! Thanks

**Comment by superpoweredSDK** [comment]
Your code looks good. Please get the Android version and device model of those users.

**Comment by drusak** [comment]
Thank you.
I'm trying to collect reviews with such problems. Here are some of known already:
-  Redmi 4X (santoni), 7.1.2
- ZTE Blade Zmax Z982
- LG Stylus2 Plus, 6.0.1
- Galaxy Note5, 6.0.1

After recording I play two players in parallel (music and voice). And some of users say that music not playing but voice sounds good.
Also some of users say that voice is too quiet (I guess the problem of the microphone of the device or headset), but probably it depends on PRESET of audio IO used.
I'll try to get more feedback (devices, os).
Thanks is advance.

**Comment by superpoweredSDK** [comment]
Did you use the SuperpoweredCPU class to enable sustained performance mode?

**Comment by drusak** [comment]
Yes, I did.
```
void AudioEngine::setPlay(bool shouldPlay) {
    for (int i = 0; i < playersCount; i++) {
            if (shouldPlay) {
                players[i]->play(false);
            } else {
                players[i]->pause();
            }
    }
    playing = shouldPlay;
    SuperpoweredCPU::setSustainedPerformanceMode(shouldPlay); // <-- Important to prevent audio dropouts.
}
```

**Comment by drusak** [comment]
From logs I see 
sampleRate is 44100 and bufferSize 960
I guess it depends on something, not sure what exactly (like some device's state or something else).
I think I heard small glitches on my test device several times (even if it works perfectly all the time).
I know that it is difficult to say the cause, but it would be very helpful to have some ideas what may be cause of that.

**Comment by superpoweredSDK** [comment]
44100 sample rate with 960 buffer size looks off. The 960 buffer size goes with 48000 Hz typically. Can you try a 48000/960 combination please?

**Comment by drusak** [comment]
I will try to put this change into next build.
Meanwhile I got one more feedback from Galaxy s7 (android 7.0) sampleRate 48000 and bufferSize 240. User wrote about "robotic noises".
About combination of audio params is there any rule how to optimize it? I thought using of audioManager.getProperty is optimal.
 
Wondering if it can be a problem that in my implementation when user starts recording I delete all players and create a new one (to play with recording in parallel). User may cancel it and I again recreate all players (in my case it is max two players). So somehow system audio engine becomes "dirty"!? I create SuperpoweredAndroidAudioIO once and then ask to start() when need playback/recording or stop() when no playback/recording needed.

**Comment by drusak** [comment]
just found Redmi 4X device:
I'm able to reproduce the audio distortions. It Appears when trying to record while music playing in Player. So one player one recorder.
Tomorrow will make more tests and get back to you with more details.

**Comment by drusak** [comment]
Seems problem is in recording Preset:
There was SL_ANDROID_RECORDING_PRESET_GENERIC, I changed it to SL_ANDROID_RECORDING_PRESET_VOICE_RECOGNITION and now it sounds without distortions... 
I'll put this change in next build of app and will analyze reports and comments.
