### ISSUE TITLE
Manual control USB IO (android)

### ISSUE THREAD

**Issue by ifyousleep** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#386]
Such a question, in my application I monitor the background and foregraund state (onPause and onResume).
Is it possible to manually connect to audio card (SuperpoweredUSBAudio :: easyIO) when foregraund and disconnect, when background, to give access to the audio card to other applications? I tried SuperpoweredUSBAudio :: stopIO, but after that other applications could not play sound through usb.

**Comment by superpoweredSDK** [comment]
Unfortunately this is how Android works. If a user app "takes over" a USB device with custom I/O, then Android "releases" it.

**Comment by superpoweredSDK** [comment]
SuperpoweredUSBAudio "releases" it, however the Android system doesn't "pick it up" after the release.

**Comment by ifyousleep** [comment]
Oh, it's very unfortunate. Thank you.
