### ISSUE TITLE
Crash in the AACDecodeNextElement

### ISSUE THREAD

**Issue by romanbsd** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#387]
Crashed: 
0  libAudioAPI.so                 0x57e6e118 AACDecodeNextElement(_AACDecInfo*, unsigned char**, int*, int*)
1  libAudioAPI.so                 0x57e34a04 aacDecoder::decodeFrame(int*, unsigned char**, int, short*)
2  libAudioAPI.so                 0x57e3624c aacFile::decodeFrame(short*, unsigned int, bool*, bool*)
3  libAudioAPI.so                 0x57e343bc aacFile::decode(short*, unsigned int*)
4  libAudioAPI.so                 0x57e31748 SuperpoweredDecoder::decode(short*, unsigned int*)
5  libAudioAPI.so                 0x57e63558 (Missing)
6  libc.so                        0x400615b0 __thread_entry

Unfortunately I don't have more info. I just know that the user did some seeking forward/back before the crash.

**Comment by superpoweredSDK** [comment]
Can't help with this, sorry. This may happen for some rarely corrupted files. If you have the file, please send it to us. Was the app built with the latest version of Superpowered?
