### ISSUE TITLE
Syncing between Android MediaPlayer and SuperpoweredAdvancedAudioPlayer

### ISSUE THREAD

**Issue by skopintsevDima** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#389]
Hi
I need to develop an app, where user can pick video and have an ability to do real-time pitch shifting(without speed changing) of audio with SeekBar. I have chosen Superpowered.
I am separating video for two independent files: video(no sound) and audio(no video).
So, video(no sound) is processing by MediaPlayer, and audio(from current video) is processing by SuperpoweredAdvancedAudioPlayer. 

### But I have problem: audio plays little faster then video. 

I am using seekTo() method of MediaController.MediaPlayerControl interface to react of video position changing and to change position of SuperpoweredAdvancedAudioPlayer by seek() method.

### My question: How I can to implement more quality syncing between Android MediaPlayer and SuperpoweredAdvancedAudioPlayer?

**Comment by superpoweredSDK** [comment]
I'm not able to provide support for Android MediaPlayer, sorry. What do you mean little faster? The phase is not perfect or the actual tempo is faster, so the audio slowly phases out?

**Comment by skopintsevDima** [comment]
Audio actual tempo is faster then video tempo.

**Comment by superpoweredSDK** [comment]
By how much?

**Comment by skopintsevDima** [comment]
By 0.5 s

**Comment by superpoweredSDK** [comment]
By how much percent? Or how long is the video then?

**Comment by superpoweredSDK** [comment]
I need to close this issue if you don't respond.

**Comment by skopintsevDima** [comment]
By 2-3 %

**Comment by superpoweredSDK** [comment]
Is it possible that the time stretcher object wasn't set up with the correct audio sample rate?

**Comment by skopintsevDima** [comment]
I am not using TimeStretcher. 
I implemented real-time pitch shifting without TimeStretcher. 
When user change progress of SeekBar I change pitch by setPitchShiftCents method of SuperpoweredAdvancedAudioPlayer class.

**Comment by superpoweredSDK** [comment]
Is it possible that the player object was set up with a different sample rate than the video's sample rate was?

**Comment by superpoweredSDK** [comment]
I need to close this without any response.

**Comment by skopintsevDima** [comment]
Sorry for the late response

**Comment by skopintsevDima** [comment]
I have realized, that audio track starts from 353 ms position. Independently what video file I will pick.

**Comment by skopintsevDima** [comment]
I am monitoring audio player position. Every two seconds I am getting SuperpoweredAdvancedAudioPlayer  positionMs and sometimes it's I got: last positionMs + 2000 ms + delta. This delta may be and positive. and negative. 
So, current position of player after two seconds, farther or closer then expected.

**Comment by superpoweredSDK** [comment]
SuperpoweredAdvancedAudioPlayer is used in many professional DJ applications, meaning it follows time very very precisely, to plus-minus 1 audio sample!

What is the range of that delta you get every two seconds?

**Comment by skopintsevDima** [comment]
+-40 ms

**Comment by skopintsevDima** [comment]
But error accumulates and I have 0.5-0.7 s difference between audio and video(audio plays faster)

**Comment by superpoweredSDK** [comment]
How fast does it accumulate?

How do you pitch shift? Using the SuperpoweredAdvancedAudioPlayer's pitch shifting, or by separately utilising SuperpoweredTimeStretching?
