### ISSUE TITLE
bufferEndPercent not updated while paused

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#390]
• open() a network file
• pause() playback
• poll player->bufferEndPercent

Bug: bufferEndPercent is not updated while audio is paused, even though the file is still being downloaded. Once you play() again, it will immediately update bufferEndPercent with the correct value. Same with fullyDownloadedFilePath, I think?

**Comment by superpoweredSDK** [comment]
No, fullyDownloadedFilePath is updated even when the player is not playing.
This behaviour is handled by the internal SuperpoweredDecoder, which is never called when the player is not playing, so yes, bufferEndPercent is not updated. We have no plans yet to change this behaviour.
When fullyDownloadedFilePath becomes non-NULL, you can update your user interface for 100% downloaded status.
