### ISSUE TITLE
[Quesiton] Merge or trim audio possible ?

### ISSUE THREAD

**Issue by Herz3h** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#391]
Hello,

I would like to know if this SDK allows for audio merging (joining two m4a together) and trim an audio from startTime to endTime.

Note: I currently do this with ffmpeg, but it's licensed under GPL/LGPL and i need merge/trim feature in a commercial app without having to release source code.

Thanks

**Comment by superpoweredSDK** [comment]
Yes, this is possible. You can decode both files to PCM using the SuperpoweredDecoder, then use one of the functions in SuperpoweredSimple.h to mix them together.

**Comment by Herz3h** [comment]
Thnaks for the reply,

I checked SuperpoweredSimple, and looks like i see SuperpoweredAdd1 as the function to merge an audio into output. But how about the trimming ? i don't see any function that seems to be doing that.

**Comment by superpoweredSDK** [comment]
You need to decode both files to PCM using the SuperpoweredDecoder. Then you have the raw audio data, so trimming is easy to do.

**Comment by Herz3h** [comment]
I'm trying to get the merge to work, but i realized that i don't know how to get all the samples from a file. 

When looking https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/blob/00827a29a78630c10ea8bc121d42ce0ab4bd7943/Examples_Linux/src/offline1.cpp 

I used decoder->samplesPerFrame but i soon realized its not giving me all the samples in the audio, but then how do i get the number of frame in an audio (so then i can samplesPerFrame * nbFrames) to decode the audio fully.

Thanks in advance.

**Comment by Herz3h** [comment]
I tried to implement merge and here is the code i wrote, but i end up with a file thats too big.

For instance say i want to merge these two files : 

firstM4A : 5000 bytes
secondM4A : 11000 bytes

the resultBuffer after merge : 670000+ bytes

```
jint throwRuntimeException(JNIEnv *env, const char *message)
{
    jclass exClass;
    const char *className = "java/lang/RuntimeException" ;

    exClass = env->FindClass(className);

    return env->ThrowNew(exClass, message);
}

AudioProcessing::AudioProcessing(JNIEnv *javaEnv, jstring filePath)
{
    const char *filePathChar = javaEnv->GetStringUTFChars(filePath, 0);
    this->filePath = filePathChar;
    this->javaEnv = javaEnv;

    decoder = new SuperpoweredDecoder();
    const char* openError = decoder->open(filePathChar, false, 0, 0);

    if (openError)
    {
        printf("Open error: %s\n", openError);
        char *errorMessage = "";

        sprintf(errorMessage, "Error opening file %s", filePathChar);
        throwRuntimeException(javaEnv, errorMessage);
        delete decoder;


        // Throw exception here
    };
}

void AudioProcessing::decode()
{
    // Create a buffer for the 16-bit integer samples coming from the decoder.
    intBuffer = (short int *)malloc(decoder->durationSamples * 2 * sizeof(short int) + 32768);

    samplesDecoded = (unsigned int) decoder->durationSamples;
    double duration = decoder->durationSeconds;
    int64_t durationSamples = decoder->durationSamples;
    SuperpoweredDecoder_Kind kind = decoder->kind;

    int res = decoder->decode(intBuffer, &samplesDecoded);
    if (res == SUPERPOWEREDDECODER_ERROR)
    {
        // Throw exception here
        char *errorMessage = "";
        sprintf(errorMessage, "Error decoding file %s", filePath);
        throwRuntimeException(javaEnv, errorMessage);

        return;
    }
}

int AudioProcessing::getSamplesDecoded()
{
    return samplesDecoded;
}

float* AudioProcessing::getFloatBuffer()
{
    floatBuffer = (float *)malloc(decoder->durationSamples * 2 * sizeof(float) + 32768);
    SuperpoweredShortIntToFloat(intBuffer, floatBuffer, samplesDecoded);
    return floatBuffer;
}

unsigned int AudioProcessing::getFloatBufferSize() {
    return decoder->durationSamples * 2 * sizeof(float) + 32768;
}

AudioProcessing::~AudioProcessing()
{
    delete intBuffer;
    delete floatBuffer;
    delete decoder;
}


extern "C" JNIEXPORT jbyteArray Java_com_my_package_mergesFilesInto(JNIEnv *javaEnv,
                                                                                                   jobject thiz,
                                                                                                   jobjectArray filesToMerge,
                                                                                                   jstring inputFilePath,
                                                                                                   jstring outputFilePath)
{

    int totalSamplesDecoded = 0;

    AudioProcessing *inputFile = new AudioProcessing(javaEnv, inputFilePath);
    inputFile->decode();
    float *floatInputBuffer = inputFile->getFloatBuffer();

    totalSamplesDecoded = inputFile->getSamplesDecoded();

    // Files to merge
    int nbFiles = (*javaEnv).GetArrayLength(filesToMerge);
    for(int i = 0; i < nbFiles; i++)
    {
        jstring file = (jstring) javaEnv->GetObjectArrayElement(filesToMerge, i);

        AudioProcessing *tempFile = new AudioProcessing(javaEnv, file);
        tempFile->decode();
        float *floatTempBuffer = tempFile->getFloatBuffer();

        SuperpoweredAdd1(floatTempBuffer, floatInputBuffer, tempFile->getFloatBufferSize());
        totalSamplesDecoded += tempFile->getSamplesDecoded();

        delete tempFile;
    }

    signed char *charOutputBuffer = (signed char *)malloc(totalSamplesDecoded);
    SuperpoweredFloatToChar(floatInputBuffer, charOutputBuffer, totalSamplesDecoded, 1);

    delete inputFile;

    jbyteArray resultBuffer;
    resultBuffer = javaEnv->NewByteArray(totalSamplesDecoded * 4);
    if (resultBuffer == NULL)
    {
        throwRuntimeException(javaEnv, "Out of memory");
    }


    jbyte fill[totalSamplesDecoded * 4];
    for(int i = 0; i < totalSamplesDecoded * 4;i++)
    {
        fill[i] = charOutputBuffer[i];
    }

    javaEnv->SetByteArrayRegion(resultBuffer, 0, totalSamplesDecoded * 4, fill);

    return resultBuffer;
}
```

Am i doing this right, i'm confused.

Note : The reason i return a buffer instead of using fwrite is because Android fails to fopen a file path for some reasons (file is valid : /data/data/{mypackagehere}/cache/tempfile.m4a)

**Comment by superpoweredSDK** [comment]
This code has multiple errors, sorry. Please stop decoding when the decoder tells you to, not based on "nbFiles". I'm not able to provide custom code review.

**Comment by Herz3h** [comment]
The thing is decode doesn't throw any error. I try to decode the audio fully and it seems to not return SUPERPOWEREDDECODER_ERROR, so i assume it has decoded entire file.

nbFiles is the number of files i want to merge (so i decode them first to get samples, then i SuperpoweredAdd1 to the output file)

There are not many examples out there, that's why i'm asking help here :/

**Comment by Herz3h** [comment]
Well,

I just went and compiled FFmpeg with LGPL2.1 license, not ideal but it does the job and there is lot of documentation out there.

Thanks for the attempts to help.

**Comment by superpoweredSDK** [comment]
The Linux offline example you are referring to shows a complete solution to fully decode an audio file. In your code you missed one critical line:

if (samplesDecoded < 1) break;

That's the point when decoding ends.
