### ISSUE TITLE
OfflineTimeStretching example audio quality

### ISSUE THREAD

**Issue by skopintsevDima** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#392]
I have developed an app, where I am using SuperpoweredAdvancedAudioPlayer for real-time pitch shifting of audio track from video file with SeekBar. I have implement it with help of setPitchShiftCents method of SuperpoweredAdvancedAudioPlayer class, that I using everytime when user change progress of SeekBar. Also I need to save pitch-shifted audio into file. I am using OfflineTimeStretching example for it, but quality of result .wav file is more worse then quality of SuperpoweredAdvancedAudioPlayer while playing audio track.

### 2) How I can save pitch shifted audio into file with another format( .aac ). Maybe this can increase a quality?

**Comment by superpoweredSDK** [comment]
The quality should be exactly the same. Can you show an A/B example?

Because wav is an uncompressed format, it will always sound better than a compressed format (such as aac).

**Comment by skopintsevDima** [comment]
The quality of audio without pitch shifting is the same, but quality of pitch shifted audio, produced by OfflineTimeStretching example, is worse then quality of audio that produced by SuperpoweredAdvancedAudioPlayer with cents parameter >0 or <0.
There are you can find two pairs of samples of audio: the first pair(tempo = 1.00f, cents = 0) have the same quality and the second pair: 1)is the recorded audio from Superpowe
[samples.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/1488112/samples.zip)
redAdvancedAudioPlayer with cents = 600, tempo = 1.00f, and 2) is the .wav file, produced by OfflineTimeStretching example with cents = 600, tempo = 1.00f. The difference between quality of the second pair is very sensible.

**Comment by skopintsevDima** [comment]
Sorry, this is my inattention. I used setRateAndPitchShift method instead of setRateAndPitchShiftCents and pass cents parameter instead of pitch. 
All is ok, if I am using setRateAndPitchShiftCents method.
