### ISSUE TITLE
Mixing use of AdvancedAudioPlayer, Recorder and Decoder

### ISSUE THREAD

**Issue by sigmadeltasoftware** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#393]
Hey guys, 

We currently have a use case where we want to have the AdvancedAudioPlayer, Recorder and Decoder all working at the same time. So when we only make use of the AdvancedAudioPlayer and the recorder (simultaneously), everything goes fine. In this case we can basically play back an audio file and record on top of it. 

But now, we also want to be able to play back previous recordings, on top of the original audio-file played by the AdvancedAudioPlayer while recording a new file on top of that. For this we figured that it would be best to use the SuperPoweredDecoder to read in chunks of the file and passing those chunks on to the Mixer, while the AdvancedAudioPlayer keeps playing and the Recoder keeps recording. 

The issue we're currently experiencing, is that during the design of our algorithm, we assumed that SuperpoweredDecoder::samplesPerFrame would remain constant. We pass the samplesPerFrame as an argument to the SuperpoweredDecoder::decode() method to retrieve #samplePerFrame samples from the recording. And the first few times it returns a normal value of 1024 (for m4a) but after 1-2 times it suddenly only returns 64 for some reason. Even if we set samplesPerFrame explicitly to 1024 before calling the decode again, it still only reads 64 samples.

Can anyone provide some more information about what could be going wrong with the context given? Please let us know whether you require more information and/or if we're doing something terribly wrong here.

**Comment by superpoweredSDK** [comment]
Don't use the SuperpoweredDecoder in a live audio processing callback, since the decoder may read directly from disk, which is a slow and blocking operation. Use another instance of the advanced audio player to play another piece of audio.
