### ISSUE TITLE
Effect Superpowered Spatializer Reverb could not be found.

### ISSUE THREAD

**Issue by mbariola** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#394]
Hi,

I am a total noob at Unity, but I wanted to try your spatializer examples - either to compile for Windows  , or Android.

I download and unpack this repo, then Open a new Unity project with root folder SuperpoweredSpatializer\SuperpoweredUnity . I let Unity import it, but I cannot compile as I get the error "Effect Superpowered Spatializer Reverb could not be found. Check that the project contains the correct native audio plugin libraries and that the importer settings are set up correctly.
"

It might be something really simple to fix but couldn't google anything relevant. Could you point me in the right direction with the detailed steps to get the demo running either on windows or android please?

**Comment by superpoweredSDK** [comment]
Hi,

the Unity example is made for Mac OSX. Superpowered doesn't support Windows yet. Building for Android on Mac OSX works, but I'm not sure with Windows, since we doesn't support Windows yet.

**Comment by mbariola** [comment]
Hi,
actually I was able to make the simple example run on Windows (the one with just a ball and a wall) and on android (even though I wasn't sure of the controls there). It was an import problem and reimporting the effect allowed it to build. (a much more expert in unity friend found how to reimport it, apparently the project conversion between unity version is not watertight). I hear it looping the eponymous phrase from the Half Life intro. I'll see if it works with other suitable examples too.

Would you also have available the source of the demo that you showcase on youtube here? https://www.youtube.com/watch?v=kkgdfJenEHo

I'd really like to hear how it sounds on my android ....

Many thanks

**Comment by superpoweredSDK** [comment]
The link is in the video... http://bit.ly/2iJKt8B

**Comment by mbariola** [comment]
Ouch. Sorry, must have missed it. thanks!
