### ISSUE TITLE
Looking for Linux equivalent of SuperpoweredAndroidAudioIO/SuperpoweredOSXAudioIO

### ISSUE THREAD

**Issue by sgowen** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#395]
I'm looking for the Linux equivalent of the SuperpoweredAndroidAudioIO/SuperpoweredOSXAudioIO class.

It seems to be missing. Thoughts?

**Comment by superpoweredSDK** [comment]
Thank you for the feature request. I wonder on which condition should I close this ticket?

**Comment by sgowen** [comment]
Thanks for the quick response!

To elaborate, it would be nice if we had the equivalent of Android's CrossExample, particularly the usage of SuperpoweredAndroidAudioIO demonstrated inside SuperpoweredExample.cpp: https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/blob/master/Examples_Android/CrossExample/app/src/main/jni/SuperpoweredExample.cpp

And of course, to do this properly, there would need to be a SuperpoweredLinuxAudioIO.cpp added to the SDK.

**Comment by superpoweredSDK** [comment]
Please note that this will be unlikely to happen anytime soon.

**Comment by sgowen** [comment]
Okay, its just a shame, because I am using Superpowered for my game engine now, powering Android, iOS, and Mac OS X. If I have to use something like PortAudio for Linux, then I'll probably just use PortAudio for all of my platforms, just for the sake of having a single interface.

**Comment by superpoweredSDK** [comment]
PortAudio is an audio I/O library. 
Superpowered is an audio SDK to play and process audio (DSP). Superpowered has some open-source I/O components as well, but those are not in our main focus.
If you are using Superpowered for I/O only, then switching to PortAudio can be a good idea.

**Comment by sgowen** [comment]
Yeah, that's all I'm using it for on Android, iOS, and macOS.

So I'm just going to remove my dependency on Superpowered and switch to OpenAL. I've already gotten it working on Linux.

Thank you for being so responsive.
I'm going to close this out now.
