### ISSUE TITLE
How to use SuperpoweredWaveform in real-time ?

### ISSUE THREAD

**Issue by temkich** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#397]
Is this possible? If so, then I have a question, when creating an object, what value should I set for **lengthSeconds** if I receive data from a microphone?
`SuperpoweredWaveform(unsigned int samplerate, int lengthSeconds);`

How to call the **getresult** method? I get empty data for waveform =(
any suggestions?

**Comment by superpoweredSDK** [comment]
The SuperpoweredWaveform class is not designed for real-time use. It's designed to collect data with its process() method real-time, but getresult() is not good as it has memory allocation inside.
