### ISSUE TITLE
Question about  squeaking in phone speaker if i use player and mic in mixer

### ISSUE THREAD

**Issue by temkich** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#399]
If I use the player in the real-time and the sound from the microphone, I impose on the sound from the microphone the effects and combine it all in the mixer, sometimes when I turn on, there is a squeak in the loudspeaker. In headphones, everything is working fine. This sometimes happens if the microphone is near the speakers. How can I set it up and get rid of the squeak?
In which direction to move? how to lower the sensitivity of the microphone?

**Comment by superpoweredSDK** [comment]
This is physics. The typical example of audio feedback.

**Comment by temkich** [comment]
What to do? How to lower the sensitivity of a signal from a microphone? Or do something that worked only with headphones? Autotune does not have such a problem, without headphones they work well. How could they do that?

**Comment by superpoweredSDK** [comment]
Perhaps Autotune outputs a very different audio signal to the input, or it uses Acoustic Echo Cancellation.

**Comment by temkich** [comment]
Acoustic Echo Cancellation as part of Superpowered? if not, how to integrate it with Superpowered? And about the different signals, I did not understand, how can I change the signal before entering the SuperpoweredIOSAudioIO?

**Comment by superpoweredSDK** [comment]
We don't offer an Acoustic Echo Cancellation feature, but as Superpowered operates on raw audio data, you can integrate an open-source AEC.
Autotune changes the incoming audio signal significantly, the output is very different to the input, so it's less sensitive to feedback.
