### ISSUE TITLE
Need help and examples

### ISSUE THREAD

**Issue by ryghar1** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#4]
Hi! Iam very exited with the features of this SDK!! 
Im relativity new to android programming and need some help to get this work.
I have the android example working ok but i dont know if the library compiled with all classes. If i try to use ie SuperpoweredRecorder eclipse said that the class dont exist.

With the SDK downloaded, wich are the steps to get an empty project ready to use with all the superpowered sdk features?
Can you give me some examples to implement recording and playback with timestreching using the sdk in android?

Thanks!!!

**Comment by danbaryak** [comment]
Hi

Although the recorder is "easy to use" as you state, we've been fighting the superpowered SDK to be able to get a sample accurate recording on top of an existing track (beat or something similar). I would very much appreciate a working example for a recorder if it's possible for you guys to post one.

Thanks

**Comment by superpoweredSDK** [comment]
Please explain in more detail, what do you mean under "sample accurate recording"? The Superpowered Recorder does sample accurate recording, it does not really do any transformation on the incoming buffer.

**Comment by danbaryak** [comment]
Well, we are building an application that needs basic multitrack recording support (only two channels at a time). The flow is like this: 
- User records one track.
- User plays that track back and records something on top of it.

Naturally the recording should be perfectly in sync. I could not find any concrete example on how to record using your SDK, only the recorder documentation which we found difficult to understand. We've been playing around with it for several months now but couldn't get a synchronised recording to work properly. 
A simple example of how to record something in sync to a playing track and then mix it down to a new file would be very valuable to us.
Thanks

**Comment by superpoweredSDK** [comment]
You are building a looper then. You need to implement recording to memory yourself, then cut the next recording to the length of the first track. There are no existing solutions for this, not in Superpowered, Core Audio or else, because this is a quite special case. 
But it's not that difficult to store audio data in raw memory buffers and play back from there. You can use the SuperpoweredStereoMixer or VolumeAdd APIs for mixing.

**Comment by J-DJadav** [comment]
@superpoweredSDK is there any update to Record Audio & Playback togather & then saving into file?

**Comment by op27no2** [comment]
I don't think this is really a "special case," as looping/overdub is present in pretty much any audio production application. Any further guidance on how to implement this on the ndk side with superpowered would be appreciated. Do you mean you can play back the audio with Superpowered from raw memory buffers?
