### ISSUE TITLE
seekTo value not working while playing multiple music together. The seek value is setting after some delay.

### ISSUE THREAD

**Issue by kkarthikdr** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#40]
I am playing more than 1 superpowered music simultaneously. My requirement is, If user is adding a new music along with the music which are playing already, it must start from the same seek position as of 1st music, but it is not happening so. I tried with the function seekTo but it is not working. Can anyone please let me know how to keep all the music in sync using superpoweredSDK.

**Comment by superpoweredSDK** [comment]
Opening and seeking can't happen immediately. Please check the cross example project how to sync two tracks together (using the same bpm value and a beatgrid).

**Comment by kkarthikdr** [comment]
When I am trying to open a new audio file using open(), with existing SuperpoweredAdvancedAudioPlayer player, which has an audio file playing already. Then it’s duration property is getting set to nil or 0. Is there a way to get duration value for the audio file after it’s being opened using open().

**Comment by superpoweredSDK** [comment]
Yes, duration is updated after open finishes successfully (you receive an event in a callback).

**Comment by kkarthikdr** [comment]
Callback function is getting fired after the opening the player.
Inside the call back function we are setting the postion with setPosition A.P.I.
Just after setting the position we are trying to display the position to which player is set.
But it is displaying the value as zero. Below is the piece of code in the callback function
```
void playerEventCallbackA(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event, void *value) {
    if (event == SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess) {
        ViewController *self = (__bridge ViewController *)clientData;
        self->playerA->setBpm(126.0f);
        self->playerA->setFirstBeatMs(353);
        self->playerA->play(false);
        self->playerA->setPosition(self->playerA->firstBeatMs, false, false);
        NSLog(@"position = %d duration = %d",self->playerA->positionSeconds,self->playerA->durationSeconds);
    };
}
```
We are getting the output as given below
```
2015-06-17 09:46:00.917 SuperpoweredCrossExample[12970:1940569] position = 0 duration = 409
```
Please advice us, whether we are in the right direction.

**Comment by superpoweredSDK** [comment]
Please let me know what's the problem here, as you are reporting: duration = 409
So the duration is reported.

**Comment by kkarthikdr** [comment]
I’m playing multiple players and when a new player is added,It should be in sync with the first player’s position which I’m setting in call back method. While retrieving the position of newly added player it is returning value 0. Please help us to get the proper position value.

**Comment by kkarthikdr** [comment]
I’m playing multiple players and when a new player is added open() function is called to open new audio file,Then I’m making newly added player to be in sync with the first player’s position which I’m setting in open() method’s callback. While retrieving the position of newly added player it is returning value 0. Please help us to get the proper position value.

**Comment by kkarthikdr** [comment]
I’m playing 2 players simultaneously.I’m changing the audio file of second player using open() function while both are playing. I’m trying to sync 2nd player with 1st player by setting the position property in callback function of 2nd player. But when I try to display the position of 2nd player in the call back function after setting the position it is displaying the value 0. Duration is set properly. I would like to know whether this scenario is possible.

**Comment by superpoweredSDK** [comment]
Changing position happens in the audio processing callback, so there is 99.99999% chance you will not see the position changing right after you asked for it.
