### ISSUE TITLE
How to get musical keys from SuperpoweredAnalyzer class?

### ISSUE THREAD

**Issue by hirokimoto** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#401]
This class has several member functions and I'd like to get more cleared for getresults function.

analyzer->getresults(&averageWaveform, &peakWaveform, &lowWaveform, &midWaveform, &highWaveform, &notes, &waveformSize, &overviewWaveform, &overviewSize, &averageDecibel, &loudpartsAverageDecibel, &peakDecibel, &bpm, &beatgridStartMs, &keyIndex);

I have analyzed a music file from this function and get the following notes.

M-A\M-A\M-A\M-A\M-A\^QAQQaQa\M-A\M-A\M-A\M-A\M-A\M-A\M-A\M-A\M-A\M-A\M-A\M-A\M-A\M-A\301\201\M^AQQQVQVQfQaaaQaa\M-A\M-A\M-A\M-A\M-A\M-A\M-FV\M^FVVVVVVVfVVVfVfVVffVVfVVV[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[V[VVVVV\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-AQQVYYYYYYYYYYY\M-I\M-I\M-I\M-I\M-I\M-I\M-F\M-F\M-FVVVVVYVYYYYYYYY\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-IYYYYYYYYYYY\M-IY\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-IYVYYY\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\301\206Vvfffff\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-FƆ\M^F[[[[[[kkk[k\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K[[[[[VV[[[\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K[[[[[VVVfVV\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-FVVQQQQQVaQQffVQaVa\M-F\M-A\M-F\M-A\M-FQQQQQQQQVVVVVfVVfVfffVfVVVQQQQQQQQQQQQQQfVVVVVfQQVQQQQQQQQQQQQQQQQQQQQ\M-AQVVVVVVVVVVV\M-FV\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F[[[[[[[[[\M-K[\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K[[[[[[[[[[[[[\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K\M-K[[[[[[VVVVV\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-FVVVY\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-IV\M^IYYiYiiiii\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-IY\M^IVVVVVVVfVffi\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-IYYYYYYYYYYYYY\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-I\M-F\M-A\M-FVVVVVVVVVVVVV\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-F\M-FV[[[[[[[[k[kkk[k[k\M-K\M-K\M-K\M-K\M-K[[[[[[[[[[k[k[k[k[kkk[kk[[[VVVVVVVVVVVVVVVVVVVVVVYTTTTTTTTTTTTTTTTT\M-D\M-D\M-D\M-DTTTTTTTYV\M-I

But I can't understand what it does mean.
Can you please explain about it in more detail?

**Comment by superpoweredSDK** [comment]
150 points/sec data displaying the bass and mid keys.
Each unsigned char (8-bit byte) represents one point.
Upper 4 bits are the bass notes 0 to 11, lower 4 bits are the mid notes 0 to 11.
(C, C#, D, D#, E, F, F#, G, G#, A, A#, B). 
The note value is 12 means "unknown note due low volume".

**Comment by shreyanshbangar** [comment]
Copy the Values from Notes(which is unsigned char pointer) to a int array. And print the integers in that int array.
