### ISSUE TITLE
How to calculate tempo?

### ISSUE THREAD

**Issue by hirokimoto** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#403]
Thanks for taking a look at my issue.

You know, SuperpoweredOfflineAnalyzer class has a function called getresults, and it returns bpm.
I am not sure how to calculate tempo based on this bpm.

**Comment by superpoweredSDK** [comment]
BPM = Beats Per Minute
I don't understand the question, sorry.
