### ISSUE TITLE
No voice recorded on some devices with headset while playing another track

### ISSUE THREAD

**Issue by drusak** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#405]
I've been reported by some users that they can't hear voice when recording with headset.
Our App records voice with beat playing, and instead of recorded voice there is a silence file. Our app allows to record second voice and strange thing that second voice together with beat and voice 1 records correctly! Also recording works fine without headset (using just phone's mic).
So the problem seems in recording one track while player playing another track (beat) in headset.

I'm wondering if you observed such an issue on your side. Any idea will be helpful!

One device that is known is Lenovo a2016 with android 6.0. I asked user to try another headset and the problem still exists... There are not many reports about that problem (in general everything works fine) but it exists and I want to figure out the cause of it.

Thanks!

**Comment by drusak** [comment]
Also it probably appeared after upgrading Superpowered SDK to 1.1.0, but not sure. Just possible case

**Comment by superpoweredSDK** [comment]
Because the second voice works records correctly, it sounds like you have a very hard to find bug in your own code. We received no such reports in the 4 years of Superpowered so far.

**Comment by drusak** [comment]
Yes, I'm thinking about that and starting exploring the code. But strange thing that without headset it works fine as well with voice 1... I'll take some time to investigate it and get back to you if found anything

**Comment by superpoweredSDK** [comment]
Perhaps it's a concurrency problem then.

**Comment by drusak** [comment]
Not sure, this issue is 100% reproducible on one phone for sure. Unfortunately it is not near me and I cannot do as many test as I wish to...

**Comment by superpoweredSDK** [comment]
Also check if you have only one audio I/O open at a time. Always.

**Comment by drusak** [comment]
Yes, I had one audioIO. Just for test I created one audioIO(just input true) for recorder and two audioIO(just output true) for players sent to the user and it works... Do you know what can be the cause and is that workable solution?
Thank you

**Comment by superpoweredSDK** [comment]
I have no idea.

**Comment by deepakrokz** [comment]
Hi @drusak ,
Can you help me with these issues: [1](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/issues/458) and [2](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/issues/462)
