### ISSUE TITLE
Cant sync gradle due to this error

### ISSUE THREAD

**Issue by student-cwb** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#406]
I had added this `superpowered.dir=C:\\Users\\chiu\\Desktop\\Low-Latency-Android-Audio-iOS-Audio-Engine-master\\Low-Latency-Android-Audio-iOS-Audio-Engine-master\\Superpowered` to local.properties

and installed the necessary sdk tools such as "Cmake, LLDB and NDK". 

When i try to sync the gradles of your example project "CrossExample"

This error was shown :
`External Native Build Issues
Build command failed.
Error while executing 'C:\Users\chiu\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe' with arguments {-HC:\Users\chiu\Desktop\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Examples_Android\CrossExample\app\src\main\jni -BC:\Users\chiu\Desktop\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Examples_Android\CrossExample\app\.externalNativeBuild\cmake\debug\armeabi-v7a -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi-v7a -DANDROID_NDK=C:\Users\chiu\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\chiu\Desktop\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Examples_Android\CrossExample\app\build\intermediates\cmake\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=C:\Users\chiu\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -DCMAKE_TOOLCHAIN_FILE=C:\Users\chiu\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=16 -DCMAKE_C_FLAGS=-O3 -fsigned-char -DCMAKE_CXX_FLAGS=-fsigned-char -IC:\Users\chiu\Desktop\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Superpowered -DANDROID_PLATFORM=android-16 -DANDROID_TOOLCHAIN=clang -DANDROID_ARM_NEON=TRUE -DANDROID_STL=gnustl_static -DPATH_TO_SUPERPOWERED:STRING=C:\Users\chiu\Desktop\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Superpowered}
-- Check for working C compiler: C:/Users/chiu/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Users/chiu/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- broken
-- Configuring incomplete, errors occurred!
See also "C:/Users/chiu/Desktop/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Examples_Android/CrossExample/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeOutput.log".
See also "C:/Users/chiu/Desktop/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Examples_Android/CrossExample/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeError.log".
CMake Warning in C:/Users/chiu/Desktop/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Examples_Android/CrossExample/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Users/chiu/Desktop/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Examples_Android/CrossExample/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_fa3b7.dir/
  has 247 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    testCCompiler.c.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
  It fails with the following output:
   Change Dir: C:/Users/chiu/Desktop/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Examples_Android/CrossExample/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp
  Run Build
  Command:"C:\Users\chiu\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe"
  "cmTC_fa3b7"
  [1/2] Building C object CMakeFiles/cmTC_fa3b7.dir/testCCompiler.c.o
  FAILED:
  C:\Users\chiu\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe
  --target=armv7-none-linux-androideabi
  --gcc-toolchain=C:/Users/chiu/AppData/Local/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64
  --sysroot=C:/Users/chiu/AppData/Local/Android/Sdk/ndk-bundle/sysroot
  -isystem
  C:/Users/chiu/AppData/Local/Android/Sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi
  -D__ANDROID_API__=16 -g -DANDROID -ffunction-sections -funwind-tables
  -fstack-protector-strong -no-canonical-prefixes -march=armv7-a
  -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -mfpu=neon
  -Wa,--noexecstack -Wformat -Werror=format-security -O3 -fsigned-char -fPIE
  -o CMakeFiles/cmTC_fa3b7.dir/testCCompiler.c.o -c
  C:\Users\chiu\Desktop\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Examples_Android\CrossExample\app\.externalNativeBuild\cmake\debug\armeabi-v7a\CMakeFiles\CMakeTmp\testCCompiler.c
  Assembler messages:
  Fatal error: can't create CMakeFiles/cmTC_fa3b7.dir/testCCompiler.c.o: No
  such file or directory
Error:error: assembler command failed with exit code 1 (use -v to see
  invocation)
  ninja: build stopped: subcommand failed.
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt
Build command failed.
Error while executing 'C:\Users\chiu\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe' with arguments {-HC:\Users\chiu\Desktop\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Examples_Android\CrossExample\app\src\main\jni -BC:\Users\chiu\Desktop\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Examples_Android\CrossExample\app\.externalNativeBuild\cmake\release\armeabi-v7a -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi-v7a -DANDROID_NDK=C:\Users\chiu\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\chiu\Desktop\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Examples_Android\CrossExample\app\build\intermediates\cmake\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=C:\Users\chiu\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -DCMAKE_TOOLCHAIN_FILE=C:\Users\chiu\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=16 -DCMAKE_C_FLAGS=-O3 -fsigned-char -DCMAKE_CXX_FLAGS=-fsigned-char -IC:\Users\chiu\Desktop\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Superpowered -DANDROID_PLATFORM=android-16 -DANDROID_TOOLCHAIN=clang -DANDROID_ARM_NEON=TRUE -DANDROID_STL=gnustl_static -DPATH_TO_SUPERPOWERED:STRING=C:\Users\chiu\Desktop\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Superpowered}
-- Check for working C compiler: C:/Users/chiu/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Users/chiu/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- broken
-- Configuring incomplete, errors occurred!
See also "C:/Users/chiu/Desktop/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Examples_Android/CrossExample/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeOutput.log".
See also "C:/Users/chiu/Desktop/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Examples_Android/CrossExample/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeError.log".
CMake Warning in C:/Users/chiu/Desktop/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Examples_Android/CrossExample/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:
  The object file directory
    C:/Users/chiu/Desktop/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Examples_Android/CrossExample/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_c1adc.dir/
  has 249 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    testCCompiler.c.o
  cannot be safely placed under this directory.  The build may not work
  correctly.
  It fails with the following output:
   Change Dir: C:/Users/chiu/Desktop/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Examples_Android/CrossExample/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp
  Run Build
  Command:"C:\Users\chiu\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe"
  "cmTC_c1adc"
  [1/2] Building C object CMakeFiles/cmTC_c1adc.dir/testCCompiler.c.o
  FAILED:
  C:\Users\chiu\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe
  --target=armv7-none-linux-androideabi
  --gcc-toolchain=C:/Users/chiu/AppData/Local/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64
  --sysroot=C:/Users/chiu/AppData/Local/Android/Sdk/ndk-bundle/sysroot
  -isystem
  C:/Users/chiu/AppData/Local/Android/Sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi
  -D__ANDROID_API__=16 -g -DANDROID -ffunction-sections -funwind-tables
  -fstack-protector-strong -no-canonical-prefixes -march=armv7-a
  -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -mfpu=neon
  -Wa,--noexecstack -Wformat -Werror=format-security -O3 -fsigned-char -fPIE
  -o CMakeFiles/cmTC_c1adc.dir/testCCompiler.c.o -c
  C:\Users\chiu\Desktop\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Examples_Android\CrossExample\app\.externalNativeBuild\cmake\release\armeabi-v7a\CMakeFiles\CMakeTmp\testCCompiler.c
  Assembler messages:
  Fatal error: can't create CMakeFiles/cmTC_c1adc.dir/testCCompiler.c.o: No
  such file or directory
Error:error: assembler command failed with exit code 1 (use -v to see
  invocation)
  ninja: build stopped: subcommand failed.
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt
C:\Users\chiu\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake
Warning:(63, 98)  (include)   CMakeLists.txt 
Warning:(63, 98)  (include)   CMakeLists.txt 
C:\Users\chiu\AppData\Local\Android\Sdk\cmake\3.6.4111459\share\cmake-3.6\Modules\CMakeTestCCompiler.cmake
Error:(61, 0) /Users/chiu/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"   is not able to compile a simple test program. 
<a href="openFile:C:\Users\chiu\AppData\Local\Android\Sdk\cmake\3.6.4111459\share\cmake-3.6\Modules\CMakeTestCCompiler.cmake">Open File</a>
Error:(61, 0) /Users/chiu/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"   is not able to compile a simple test program. 
<a href="openFile:C:\Users\chiu\AppData\Local\Android\Sdk\cmake\3.6.4111459\share\cmake-3.6\Modules\CMakeTestCCompiler.cmake">Open File</a>`

**Comment by superpoweredSDK** [comment]
Please do as the log advises: check the error log here:
 C:/Users/chiu/Desktop/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master/Examples_Android/CrossExample/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeError.log

**Comment by student-cwb** [comment]
![image](https://user-images.githubusercontent.com/30753381/33694815-2091bd3c-db35-11e7-82f7-7e7c5121fd48.png)

**Comment by HitRoxxx** [comment]
I think you're local.properties superpowered.dir is wrong Use like this it will work

superpowered.dir= C\:/hitro/SuperpoweredSDK/Superpowered

**Comment by superpoweredSDK** [comment]
Or in Windows using double slashes is good too, like this: C:\\folder\\subfolder

**Comment by student-cwb** [comment]
Still cant work. I had reinstalled my android studio and applied necessary sdk tools such as "Cmake, LLDB and NDK" again. 
![image](https://user-images.githubusercontent.com/30753381/33797263-cfc70a12-dd3f-11e7-960a-908bd50df266.png)

![image](https://user-images.githubusercontent.com/30753381/33797275-0cea4dc8-dd40-11e7-80bf-9fe50062c774.png)

**Comment by HitRoxxx** [comment]
This is not problem of studio, Its an address problem, in Window I use like this and  it is running successfully.
ndk.dir=C\:\\Users\\HITRO\\AppData\\Local\\Android\\Sdk\\ndk-bundle
sdk.dir=C\:\\Users\\HITRO\\AppData\\Local\\Android\\Sdk
superpowered.dir= C\:/hitro_projects/SuperpoweredSDK/Superpowered

**Comment by student-cwb** [comment]
![image](https://user-images.githubusercontent.com/30753381/33797370-94cea6fc-dd41-11e7-81ef-bc0ce3d7c2aa.png)

**Comment by HitRoxxx** [comment]
Give The format I gave u a try

**Comment by student-cwb** [comment]
C:\Users\chiu\Desktop\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Low-Latency-Android-Audio-iOS-Audio-Engine-master\Superpowered

u mean this 1? what format u mean?

**Comment by HitRoxxx** [comment]
![temp](https://user-images.githubusercontent.com/22116622/33797434-cd577fb2-dd2d-11e7-8d2f-a7630feec851.PNG)

**Comment by student-cwb** [comment]
![image](https://user-images.githubusercontent.com/30753381/33797505-00764f84-dd44-11e7-9db8-0c8e82ca7532.png)

**Comment by HitRoxxx** [comment]
Change your Superpowered SDK path, remove unnecessary name like Low-Latency-Android-Audio-iOS-Audio-Engine-master/Low-Latency-Android-Audio-iOS-Audio-Engine-master

**Comment by student-cwb** [comment]
oh finally it works. Thank you sir. 
![image](https://user-images.githubusercontent.com/30753381/33797767-8ef3cd14-dd48-11e7-8e59-faf8c2be743b.png)

**Comment by Edison4mobile** [comment]
It is perfect
