### ISSUE TITLE
positionMs dose not follow correctly the tempo change

### ISSUE THREAD

**Issue by mehdisam** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#409]
First of all, thank you for this great job. I am working on a project and there is this issue with the **positonMs** that does not reflect the actual position of the song. 

<img width="974" alt="screen shot 1396-09-27 at 4 42 16 pm" src="https://user-images.githubusercontent.com/9934653/34107742-8ff8a7c2-e412-11e7-8de1-878a35e7dad8.png">

Blue area shows the change of the tempo and the red area shows the response of **positionMs**. As you can see for tempo less than 1 the **positonMs** does not change. Note that the sound goes on but the **positionMs** does not reflect the actual position of the song.

**Comment by superpoweredSDK** [comment]
There are several DJ apps using Superpowered and none of them have this problem. DJ apps must have very precise positioning with wildly fluctuating tempo (scratching for example).

What is "normalized position"? There is no such thing in Superpowered. The positionMs property of the SuperpoweredAdvancedAudioPlayer always reflects the actual position regardless the tempo.

I don't see the "position less than 1" on the graph either, looks like the labelling is not correct?

**Comment by mehdisam** [comment]
Normalized position: To put position and tempo at the same diagram I divided position value to the maximum of the range.
Blue area is the **tempo** and the red area is the position in response to change in tempo.
You see at the start of the diagram, **tempo** (Blue Area) is changing while **position** (Red Area) is near zero.
And at the end of the diagram **tempo** (Blue Area) is going down but the **position** stays there.

**Comment by superpoweredSDK** [comment]
What is the "maximum of the range" value the position is divided with?
Why do you expect the two curves to match, since the playback tempo is not directly proportional to the position?

**Comment by mehdisam** [comment]
The diagram is the samples of position and tempo values over time.
position value is in milliseconds so my data is at range (0 ~ 8000 ) and if I want to plot both tempo and position at the same diagram you can't see the tempo area because the tempo is at the range ( 0~ 1). I simply divide position data by their maximum value to make them comparable to tempo data.

<img width="974" alt="screen shot 1396-09-27 at 4 42 16 pm" src="https://user-images.githubusercontent.com/9934653/34119142-56d2d26e-e436-11e7-8799-09c9d73aa5e0.png">

**Comment by superpoweredSDK** [comment]
I can see the position growing in your green rectangle.

**Comment by superpoweredSDK** [comment]
I'm not able to help with this, sorry.

**Comment by CodeJd** [comment]
when using sdk version 1.0.5 and mp3 files, we detect big fluctuations in time, thats why we start using m4a, but width more recent version we dont detect this (just hearing the audio)
