### ISSUE TITLE
The Audio processing effect occurs on all audio players

### ISSUE THREAD

**Issue by abhimanyujindal10** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#41]
I have created 5 audio players. And I have created 5 different equalizer objects. The issue with the equalizer is that the equalizer of the first player works correctly and changes the audio for the first player. But the equalizer of second track changes the value of both first as well as second player. Similarily 3 one for all 3 audio players. Can't I set the equalizer to work only for specific audio player?

**Comment by superpoweredSDK** [comment]
Of course you can. You need to process every player into a distinct buffer (with bufferAdd false), process every eq on the corresponding buffer, then mix them together using the SuperpoweredMixer.

**Comment by abhimanyujindal10** [comment]
SuperpoweredMixer can process maximum 4 buffers at a time. In that case, it will not work for 5 players parallely?

**Comment by superpoweredSDK** [comment]
Yes, you need two SuperpoweredMixer instances, as one instance can process 4 buffers maximum.

**Comment by abhimanyujindal10** [comment]
If I create 2 SuperpoweredMixer instances, then noise is produced. It is not working properly in that case

**Comment by superpoweredSDK** [comment]
There are multiple apps with multi-million downloads using more SuperpoweredMixer instances... If noise is produced, then you are passing the wrong buffers or setting up the parameters wrong.

**Comment by abhimanyujindal10** [comment]
I am sure I might be doing something wrong at my end. 

I have implemented the following delegate method in my class : - 

- (bool)audioProcessingCallback:(float **)buffers inputChannels:(unsigned int)inputChannels outputChannels:(unsigned int)outputChannels numberOfSamples:(unsigned int)numberOfSamples samplerate:(unsigned int)samplerate hostTime:(UInt64)hostTime {
}

Then after creating multiple instances of SuperpoweredMixer, I am passing  buffers (which I am receiving from the above mentioned delegate method) in the second parameter value (i.e outputs). Is this correct or I need to create new output for each instance?

**Comment by superpoweredSDK** [comment]
Please show the mixing part of your code.

**Comment by abhimanyujindal10** [comment]
Here is callback method for processing buffers :-

- (bool)audioProcessingCallback:(float **)buffers inputChannels:(unsigned int)inputChannels outputChannels:(unsigned int)outputChannels numberOfSamples:(unsigned int)numberOfSamples samplerate:(unsigned int)samplerate hostTime:(UInt64)hostTime {
    if (samplerate != lastSamplerate) { // Has samplerate changed?
        [self setCurrentTrackPlayersSampleRate:samplerate];
    }
    
    pthread_mutex_lock(&mutex);
    
//    	float masterBpm = audioPlayer->currentBpm; // Players will sync to this tempo.
//    	double msElapsedSinceLastBeatA = audioPlayer->msElapsedSinceLastBeat; // When playerB needs it, playerA has already stepped this value, so save it now.
//    
    __block bool silence = true;

    if (trackPlayers.count) {
        [trackPlayers enumerateObjectsUsingBlock: ^(TrackPlayer *trackPlayer, NSUInteger idx, BOOL *stop) {
         //   BOOL shouldAddBuffer = [self shouldAddBufferForIndex:idx];
            BOOL currentSilenceValue = ![trackPlayer processBuffer:NULL bufferAdd:false numberOfSamples:numberOfSamples volume:1.0 * headroom masterBpm:[trackPlayer currentBpm] masterMsElapsedSinceLastBeat:[trackPlayer msElapsedSinceLastBeat]];
            [trackPlayer processAudioAdvanceFunctionsWithSamples:numberOfSamples];
            silence = [self systemShouldSilence:silence andCurrentPlayerSilenceValue:currentSilenceValue];
        }];
    }
    if (!silence) {
        outPutBuffers = buffers;
        [self processAudioMixerForTrackPlayers:trackPlayers andSamples:numberOfSamples];
    }
    else {
        float mixerOutputMeter[2] = { 0.0f, 0.0f };
        [self postNotificationWithMixerOutputMeter:mixerOutputMeter];
    }
    pthread_mutex_unlock(&mutex);
    return !silence;
}

This is the method where I am doing the mixing part :-

- (void)processAudioMixerForTrackPlayers:(NSMutableArray *)trackPlayers andSamples:(unsigned int)numberOfSamples {
    
    int numberOfMixerRequired = 0;
    int mixerCount = 0;
    if (trackPlayers.count)
        mixerCount = (int)trackPlayers.count/4;
    if (fmod(trackPlayers.count, 4) > 0)
        numberOfMixerRequired = mixerCount + 1;
    else
        numberOfMixerRequired = mixerCount;
        
    for (int mixerCount = 0; mixerCount <numberOfMixerRequired; mixerCount++) {
        int startTrackRange = mixerCount*4;
        int lastTrackRange = startTrackRange + 3;
        
        if (lastTrackRange>trackPlayers.count) {
            lastTrackRange = (int)trackPlayers.count - 1;
        }
        
        float mixerInputTrack1 = 0.0;
        float mixerInputTrack2 = 0.0;
        float mixerInputTrack3 = 0.0;
        float mixerInputTrack4 = 0.0;
        float mixerInputTrack5 = 0.0;
        float mixerInputTrack6 = 0.0;
        float mixerInputTrack7 = 0.0;
        float mixerInputTrack8 = 0.0;
        
        float * outPutBuffer_1 = NULL;
        float *outPutBuffer_2 = NULL;
        float *outPutBuffer_3 = NULL;
        float *outPutBuffer_4 = NULL;
        
        int counter = 0;
        for (int trackPlayerCount = startTrackRange; trackPlayerCount<= lastTrackRange; trackPlayerCount++) {
            TrackPlayer *player = trackPlayers[trackPlayerCount];
            
            switch (counter) {
                case 0:
                {
                    outPutBuffer_1 = [player trackBuffer];
                    mixerInputTrack1 = [player mixerInputLevel];
                    mixerInputTrack2 = [player mixerInputLevel];
                }
                    break;
                case 1:
                {
                    outPutBuffer_2 = [player trackBuffer];
                    mixerInputTrack3 = [player mixerInputLevel];
                    mixerInputTrack4 = [player mixerInputLevel];
                }
                    break;
                case 2:
                {
                    outPutBuffer_3 = [player trackBuffer];
                    mixerInputTrack5 = [player mixerInputLevel];
                    mixerInputTrack6 = [player mixerInputLevel];
                }
                    break;
                case 3:
                {
                    outPutBuffer_4 = [player trackBuffer];
                    mixerInputTrack7 = [player mixerInputLevel];
                    mixerInputTrack8 = [player mixerInputLevel];
                }
                    break;
                    
                default:
                    break;
            }
            counter++;
        }
        
        float *mixerInputs[4] = { outPutBuffer_1, outPutBuffer_2, outPutBuffer_3, outPutBuffer_4 };
        
        float mixerInputLevels[8] = { mixerInputTrack1, mixerInputTrack2, mixerInputTrack3, mixerInputTrack4, mixerInputTrack5, mixerInputTrack6, mixerInputTrack7, mixerInputTrack8 };

        float mixerOutputLevels[2] = { 1.0f, 1.0f };
        float mixerOutputMeter[2] = { 0.0f, 0.0f };
        audioMixer[mixerCount]->process(mixerInputs, outPutBuffers, mixerInputLevels, mixerOutputLevels, NULL, mixerOutputMeter,  numberOfSamples);
        
        [self postNotificationWithMixerOutputMeter:mixerOutputMeter1];
    }
}

where values of trackBuffer & mixerInputLevel coming from other methods as NULL or buffer depending whether the player is playing or not respectively.

**Comment by abhimanyujindal10** [comment]
I just need to understand, how to process multiple instances of mixers together.

**Comment by Atulth2001** [comment]
Any updates ?
 I am waiting for your reply as the development of the app is stuck up in between due to the issue.

**Comment by superpoweredSDK** [comment]
In your code you mix outputbuffer1..4 together, into "outputbuffers". Mix them into just one buffer, let's name it "outputbuffer1_4". So your outputs parameter for your mixer process function will be { outputbuffer1_4, NULL }.
Let's assume you process your 5th source into outputbuffer5. Then you need to call mixer->process again, with the parameters:
mixerInputs[4] = { outputbuffer1_4, outputbuffer5, NULL, NULL };
And output can finally go into outputbuffers.

**Comment by Atulth2001** [comment]
I have implemented the process as you suggested but its still not working for the 5th song, may be I am still not getting it the right way. Please just have a look on the mixing code once again

- (void)processAudioMixerForTrackPlayers:(NSMutableArray *)trackPlayers andSamples:(unsigned int)numberOfSamples {
    
    int numberOfMixerRequired = 0;
    int mixerCount = 0;
    if (trackPlayers.count)
        mixerCount = (int)trackPlayers.count/4;
    if (fmod(trackPlayers.count, 4) > 0)
        numberOfMixerRequired = mixerCount + 1;
    else
        numberOfMixerRequired = mixerCount;
    
    for (int mixerCount = 0; mixerCount < numberOfMixerRequired; mixerCount++) {
        int startTrackRange = mixerCount*4;
        int lastTrackRange = startTrackRange + 3;
        
        if (lastTrackRange>=trackPlayers.count) {
            lastTrackRange = (int)trackPlayers.count - 1;
        }
        
        float mixerInputTrack1 = 0.0;
        float mixerInputTrack2 = 0.0;
        float mixerInputTrack3 = 0.0;
        float mixerInputTrack4 = 0.0;
        float mixerInputTrack5 = 0.0;
        float mixerInputTrack6 = 0.0;
        float mixerInputTrack7 = 0.0;
        float mixerInputTrack8 = 0.0;
        
        float *outPutBuffer_1 = NULL;
        float *outPutBuffer_2 = NULL;
        float *outPutBuffer_3 = NULL;
        float *outPutBuffer_4 = NULL;
        
        int counter = 0;
        for (int trackPlayerCount = startTrackRange; trackPlayerCount<= lastTrackRange; trackPlayerCount++) {
            TrackPlayer *player = trackPlayers[trackPlayerCount];
            
            switch (counter) {
                case 0:
                {
                    outPutBuffer_1 = [player trackBuffer];
                    mixerInputTrack1 = [player mixerInputLevel];
                    mixerInputTrack2 = [player mixerInputLevel];
                }
                    break;
                case 1:
                {
                    outPutBuffer_2 = [player trackBuffer];
                    mixerInputTrack3 = [player mixerInputLevel];
                    mixerInputTrack4 = [player mixerInputLevel];
                }
                    break;
                case 2:
                {
                    outPutBuffer_3 = [player trackBuffer];
                    mixerInputTrack5 = [player mixerInputLevel];
                    mixerInputTrack6 = [player mixerInputLevel];
                }
                    break;
                case 3:
                {
                    outPutBuffer_4 = [player trackBuffer];
                    mixerInputTrack7 = [player mixerInputLevel];
                    mixerInputTrack8 = [player mixerInputLevel];
                }
                    break;
                    
                default:
                    break;
            }
            counter++;
        }
        
        float *mixerInputs[4];
        if (mixerCount == 0 && numberOfMixerRequired==1) {
            NSLog(@"First four mixing");
            mixerInputs[0] = outPutBuffer_1;
            mixerInputs[1] = outPutBuffer_2;
            mixerInputs[2] = outPutBuffer_3;
            mixerInputs[3] = outPutBuffer_4;
            
            float mixerInputLevels[8] = { 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f };
            float mixerOutputLevels[2] = { 1.0f, 1.0f };
            float mixerOutputMeter[2] = { 0.0f, 0.0f };
            audioMixer->process(mixerInputs, outPutBuffers, mixerInputLevels, mixerOutputLevels, NULL, mixerOutputMeter, numberOfSamples);
            
            [self postNotificationWithMixerOutputMeter:mixerOutputMeter];
        }
        else if (mixerCount == 0 && numberOfMixerRequired==2)
        {
            NSLog(@"First four NOT mixing");
            mixerInputs[0] = outPutBuffer_1;
            mixerInputs[1] = outPutBuffer_2;
            mixerInputs[2] = outPutBuffer_3;
            mixerInputs[3] = outPutBuffer_4;
            
            float mixerInputLevels[8] = { 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f };
            
            float mixerOutputLevels[2] = { 1.0f, 1.0f };
            float mixerOutputMeter[2] = { 0.0f, 0.0f };
            audioMixer->process(mixerInputs, &outPutBufferFinal, mixerInputLevels, mixerOutputLevels, NULL, mixerOutputMeter, numberOfSamples);
        }
        else
        {
            NSLog(@"Last Track Mixing");

            mixerInputs[0] = outPutBufferFinal;
            mixerInputs[1] = outPutBuffer_1;
            mixerInputs[2] = outPutBuffer_2;
            mixerInputs[2] = outPutBuffer_3;
            
            float mixerInputLevels[8] = { 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f };
            
            float mixerOutputLevels[2] = { 1.0f, 1.0f };
            float mixerOutputMeter[2] = { 0.0f, 0.0f };
            audioMixer1->process(mixerInputs, outPutBuffers, mixerInputLevels, mixerOutputLevels, NULL, mixerOutputMeter, numberOfSamples);
            
            [self postNotificationWithMixerOutputMeter:mixerOutputMeter];
        }
    }
}

**Comment by superpoweredSDK** [comment]
You have a branch with 3 different routes, and mixer process() happens just once in each. You need two mixer process() to mix 5 sources together, and follow my recommendation in my previous answer please.

**Comment by Atulth2001** [comment]
I am following your recommendation but could not implement it the right way. Kindly guide me to make this mixing part done.

**Comment by superpoweredSDK** [comment]
You need to use two mixer instances. 
The first mixer should mix 4 interleaved stereo inputs (4 players) to 1 interleaved stereo output.
The second mixer should mix 2 interleaved stereo inputs (1 player + the output of the previous mixer) to 1 non-interleaved stereo output (which will go to the audio system output).

**Comment by Atulth2001** [comment]
I am using two mixers now for processing more than 4 tracks as you suggested :-1
            mixerInputs[0] = outPutBuffer_1;
            mixerInputs[1] = outPutBuffer_2;
            mixerInputs[2] = outPutBuffer_3;
            mixerInputs[3] = outPutBuffer_4;
            
            float mixerInputLevels[8] = { 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f };
            float mixerOutputLevels[2] = { 1.0f, 1.0f };
            float mixerOutputMeter[2] = { 0.0f, 0.0f };
            audioMixer->process(mixerInputs, outPutBuffers, mixerInputLevels, mixerOutputLevels, NULL, mixerOutputMeter, numberOfSamples);
            
            //outPutBuffers2 = outPutBuffers;
            
            mixerInputs1[0] = *outPutBuffers;
            mixerInputs1[1] = outPutBuffer_5;
            mixerInputs1[2] = outPutBuffer_6;
            mixerInputs1[3] = outPutBuffer_7;
            
            audioMixer1->process(mixerInputs1, outPutBuffers, mixerInputLevels, mixerOutputLevels, NULL, mixerOutputMeter, numberOfSamples);

But still I am not getting the desired results. As soon as the 2nd mixer instance starts mixing, it produces distorted sound and the sound of  the 1st mixer instance is gone. Kindly guide me how to do it the right way.

**Comment by Atulth2001** [comment]
Any updates..I am eagerly waiting for your reply. Kindly look up in the code and guide.

**Comment by abhimanyujindal10** [comment]
As per the details added in this thread -->>

"In your code you mix outputbuffer1..4 together, into "outputbuffers". Mix them into just one buffer, let's name it "outputbuffer1_4". So your outputs parameter for your mixer process function will be { outputbuffer1_4, NULL }.
Let's assume you process your 5th source into outputbuffer5. Then you need to call mixer->process again, with the parameters:
mixerInputs[4] = { outputbuffer1_4, outputbuffer5, NULL, NULL };
And output can finally go into outputbuffers."

I understand it that I need to create outputbuffer1..4 buffer. But can you help me how to initialize this buffer? 

Currently, I have done it in this way :-

//1 -> Create a new Buffer
float **outPutBuffers1_4; 

//2 -> Initialize it in constructor
if (posix_memalign((void **)&outPutBuffers1_4, 16, 4096 + 128) != 0) 
abort(); 

//3 -> Initialize Buffers for interleaved stereo 
outPutBuffers1_4[0] = (Float32 *)malloc(sizeof(Float32) * numberOfSamples);
outPutBuffers1_4[1] = (Float32 *)malloc(sizeof(Float32) * numberOfSamples);

//4 -> Process this buffer 			
audioMixer->process(mixerInputs, outPutBuffers1_4, mixerInputLevels, mixerOutputLevels, NULL, mixerOutputMeter, numberOfSamples);

//5 - > Add this buffer in mixer Inputs
mixerInputs1[0] = *outPutBuffers1_4;
mixerInputs1[1] = outPutBuffer_5;
mixerInputs1[2] = outPutBuffer_6;
mixerInputs1[3] = outPutBuffer_7;

//5 - > Process it in outPutBuffer which I am getting from the audioProcessingCallback method
audioMixer->process(mixerInputs1, outPutBuffers, mixerInputLevels, mixerOutputLevels, NULL, mixerOutputMeter, numberOfSamples);

This does not work. I the issue is withe the outputBuffer1_4 allocation and initialization as well as the way it needs to be assigned to mixerInputs1[0]

Please help with this......
