### ISSUE TITLE
song plays endlessly. How can I find the end of the soung?

### ISSUE THREAD

**Issue by mehdisam** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#410]
As I followed your sample code, it plays fine but the song loops endlessly. Are there any flags or variables that shows the end of the song?

Thank you

**Comment by superpoweredSDK** [comment]
Yes, please check the SuperpoweredAdvancedAudioPlayerEvent_EOF event handling in the player callback. It's present in many examples.
