### ISSUE TITLE
CrossExample Memory allocation

### ISSUE THREAD

**Issue by drusak** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#411]
Start profiling my app and found out that during playback memory usage is increasing. 
I checked with CrossExample (android) and for 2 minutes app memory usage increased with 5 MB. When playback is paused memory stoped increasing as well. 
Just wondering if it's a normal behavior?

Thanks!

**Comment by superpoweredSDK** [comment]
If it stops at 20 MB then it's normal. Superpowered has no memory leaks. We support _billions_ of app installs, so this is based on a lot of data.

**Comment by drusak** [comment]
Sorry, I didn't mean that it leads to memory leaks! 
Just asking if that is ok and you know about that. I decided to write to you because I noticed that if same player plays same track in a loop, then on the second playback(loop) memory is not increasing.
