### ISSUE TITLE
How can we create one channel IO class in android?

### ISSUE THREAD

**Issue by SenL1997** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#412]

**Comment by superpoweredSDK** [comment]
Just look at the code, line 10: https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/blob/master/Superpowered/AndroidIO/SuperpoweredAndroidAudioIO.cpp

**Comment by SenL1997** [comment]
But when I changed its value to 1:
#define NUM_CHANNELS 1
I get the following error:
E/libOpenSLES: pAudioSnk: requested 1 channels but mask (0x3) has 2 channel bits set
W/libOpenSLES: Leaving Engine::CreateAudioRecorder (SL_RESULT_PARAMETER_INVALID)
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 27746 (frequencydomain)

        [ 12-20 15:11:28.397   603:  603 W/         ]
        debuggerd: handling request: pid=27746 uid=10372 gid=10372 tid=27746
Application terminated.

**Comment by superpoweredSDK** [comment]
Please do as the error advise: change the channel mask.
From SL_SPEAKER_FRONT_LEFT | SL_SPEAKER_FRONT_RIGHT change to SL_SPEAKER_FRONT_CENTER.

**Comment by SenL1997** [comment]
Ok, I got it. Thanks.
