### ISSUE TITLE
iOS Volume issues using AVAudioSession

### ISSUE THREAD

**Issue by LainCoubrt** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#413]
Hi Everybody,

I’m working with AVCaptureSession to capture video and audio, and AVAudioSession to output audio but im experiencing the following issue:
1 - Open the app and set the phone volume to minimum
2 - Switch from front capture device to back and change volume to maximum
3 - Kill the app
4 - Open the app and the volume is minimum, switch the camera and the volume is at max
5 - multiple camera switching and the volume keeps the back device volume

My question is if there is some kinda of “volume session”?? But I’m not sure if there is because the front device lose his volume to be replaced by the back device
I made a search if I was programmatically changing the volume but there is no API from apple to do this.

Thanks in advance

**Comment by superpoweredSDK** [comment]
Hi,

this is not related to the Superpowered Audio SDK, so I have to close this, sorry. I think you need to post this in the Apple developer forums.
