### ISSUE TITLE
3rd party equalizer apps are not working with this SDK on Android

### ISSUE THREAD

**Issue by zoanthropy** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#414]
I'm using Music Speed Changer that is based on Superpowered SDK. 3rd party equalizer apps and even rooted ones Viper4Android and DSPmanager are not working or blocked/ignored. I'm sure it is blocked for stability reason or custom equalizer.

MSC had build-in equalizer that is working but i prefer Viper4Android that is thousands better than build-in one. Soundtouch SDK fully support 3rd party equalizer and had no problems. Problem for me is they have removed option to switch to Soundtouch SDK because i'm using V4A and usibg this SDK does not work with V4A.

Is it possible to support 3rd party equalizer? If not possible, then why?

**Comment by superpoweredSDK** [comment]
This is not an issue with the Superpowered SDK. Audio I/O is not part of the Superpowered SDK, we only offer some helper classes to do that, such as the SuperpoweredAndroidAudioIO.

SuperpoweredAndroidAudioIO uses standard native Android APIs for audio I/O, there nothing special inside. Please contact your app developer if anything else was used, Superpowered has nothing to do with this issue.

Alternatively, perhaps Viper4Android is not prepared to equalize native Android audio, only Java. In this case, contact Viper4Android.

**Comment by svenoaks** [comment]
Not sure why posted here, but I'm the author of Music Speed Changer and you can now switch to AudioTrack in Settings....Software Library. That should work with 3rd party equalizers.
