### ISSUE TITLE
Is there any way to access temp file of recorder during recording?

### ISSUE THREAD

**Issue by mehdisam** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#415]
Is there any way to access temp file of the recorder during recording? Or if possible a way to set/get offset location of temp file? This will help to control the recording position in the file and better progress report.

Thank you

**Comment by superpoweredSDK** [comment]
This is a bad idea, because the temp file is written on a background thread, and disk I/O is not predictable.
You submit the samples to the recorder, therefore you can count the submitted number of samples for a progress report.
