### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by fatihm85** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#416]
Is there any way to play PCM files with SuperpoweredAdvancedAudioPlayer? This feature would be very useful files since some files contain sound in PCM format. We can input the PCM buffer address and format details. I need to write the PCM as wav file to play but it is not efficient. Could you please add this feature? Thank you for the great audio SDK.

**Comment by superpoweredSDK** [comment]
Most WAV files are having raw PCM audio. Just slap the 54 bytes of WAV header in front of your PCM data and you have it!
Check the SuperpoweredRecorder.h header for helper functions creating your WAV file.

**Comment by fatihm85** [comment]
I am doing this way but I would like to directly input PCM buffer to the SuperpoweredAdvancedAudioPlayer without creating a wav file. I have a soundfont file but I don't want to create separate wav files on storage. I would like to load and play PCM data. Thanks.

**Comment by superpoweredSDK** [comment]
Thank you for the feature request!

**Comment by fatihm85** [comment]
Thanks for your support. Could you please add this feature to the next release? Loading a PCM data with a buffer start and length as well as inputting header properties such as sample rate, channel, etc. would be very useful. Thank you.

**Comment by superpoweredSDK** [comment]
This feature is not on our roadmap currently, sorry for that.

**Comment by fatihm85** [comment]
OK. I will be very glad if you could add this feature to your roadmap. I would like to ask if you could share only the struct: SuperpoweredAdvancedAudioPlayerInternals.  Maybe I can manually load PCM data to buffers in this way.

**Comment by superpoweredSDK** [comment]
SuperpoweredAdvancedAudioPlayerInternals is not the relevant part. The player uses multiple instances of the SuperpoweredDecoder class internally, which is the audio data provider. 

This project would involve developing a custom decoder load, and an example on how to implement the decoder for simple PCM delivery. It is significant amount of work.
