### ISSUE TITLE
customized SuperpoweredFX

### ISSUE THREAD

**Issue by passos** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#417]
I was wondering is it possible to customized a sound effect by extend SuperpoweredFX?

It looks like I can do something with `process` method but there is no document about the details of input/output params. For example, what is the data format of input buffer? `*input` point to input buffer but how can I know the input buffer length? or how to determinate the end of data buffer?

Is it possible to open source one of the subclass of SuperpoweredFX like SuperpoweredEcho to demo how it works?

**Comment by superpoweredSDK** [comment]
SuperpoweredFX is just a header with common methods of the various Superpowered effects. Yes, you can create your own class based on SuperpoweredFX.

The process method has just 3 input parameters and all of them are documented. Read the documentation please.

input: 32-bit interleaved stereo input buffer.
output: 32-bit interleaved stereo output buffer.
numberOfSamples: Number of samples to process.

**Comment by passos** [comment]
:( 
Of course I have read the document but I don't think it's useful and answered my question.
Read my question please.

**Comment by superpoweredSDK** [comment]
I believe i answered your question. Let's try again, organized into Q&A form:

Q: "I was wondering is it possible to customized a sound effect by extend SuperpoweredFX?"
A: Yes, you can create your own class based on SuperpoweredFX. SuperpoweredFX is a header with common methods of the various Superpowered effects.

Q: "It looks like I can do something with process method but there is no document about the details of input/output params. For example, what is the data format of input buffer?"

A: The process method has just 3 input parameters and all of them are documented. As the documentation says, input is a 32-bit interleaved stereo input buffer. In other words, the data format for input is 32-bit interleaved stereo floating point.

Q: "*input point to input buffer but how can I know the input buffer length? or how to determinate the end of data buffer?"
A: The process method has the numberOfSamples parameter, which contains the number of samples to process. That's the size of the input and output buffers.

Q: "Is it possible to open source one of the subclass of SuperpoweredFX like SuperpoweredEcho to demo how it works?"
A: The headers and documentation reveals all the parameters, inputs and outputs.
