### ISSUE TITLE
Time loop problem

### ISSUE THREAD

**Issue by CodeJd** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#418]
Hi,

we are developing a mobile app and using superpoweredSdk. The code is based on SuperpoweredCrossExample, and we are loading 9 tracks, that plays in sync:

player->open()
self->player->setFirstBeatMs(1); (we put 1 for the aiif/wav files)
self->player->setPosition(self->player->firstBeatMs, false, false);

its working, but the problem is the moment when it loops:
if we use aiifs or wav, there is a very small antecipation (we are not shure but we have the feeling the tracks its cutting something ), we also tried with different audio tracks

if we use mp3 there is a delay (we verify in a audio software that there is no gaps : in start and end, in the lenght of the track, the time its correct)

Please could you give some advice for this?
Thanks

**Comment by superpoweredSDK** [comment]
Compressed file formats having frequency domain transformations always start will silence (such as mp3 or aac), regardless of the source audio starts immediately.
The SuperpoweredDecoder has the getAudioStartSample() method to detect the beginning.

**Comment by CodeJd** [comment]
Thanks for the feedback, but the problem is because we are using react native. The same app in objective-c its ok, but not in react-native, there is a gap. Like i said we also are using not compressed files.

Sugestions?

**Comment by superpoweredSDK** [comment]
If you need to do anything in real-time, do it in a real-time capable language. React-native is just JavaScript in an embedded browser view, it's far from being "native".
Do all your audio related code in Objective-C or C++.

**Comment by CodeJd** [comment]
[Solution ]

Thanks for the input. React native isn't " JavaScript in an embedded browser view". Look for performance analysis about this and you will be surprised.

Anyway i found the problem, it was a bug in Superpowered, because im using this project https://github.com/MathieuDebit/react-native-superpowered the lib was older, so when i was debugging:

NSLog(@"EOF %f %d ", sps->playerA->positionMs, sps->playerA->durationMs); the durationMs was getting short some loops, so updated the library for the last Superpowered version, and now its ok.

Thanks for the help

**Comment by superpoweredSDK** [comment]
I hope you don't mean the performance tests for UI (such as a tableview), because those are not real-time data processing tests.

React Native runs JavaScript, more specifically the WebKit JavaScriptCore engine. It is not native and especially not real-time, which is required for audio processing.

I checked the react-native-superpowered repository. It seems like all audio-related code runs in Objective-C++ (and not React Native), which is perfect.
