### ISSUE TITLE
LoopBetween and setTempo

### ISSUE THREAD

**Issue by CodeJd** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#419]
Hi again,

l like to ask you help for another question, that its looks to me is a bug:

im playing mp3 files, using:
playerA->loopBetween(12, 8000, true, 255, true); - its a 8000 milliseconds loop
and it works, loops correctly.

But i also want to change the tempo of the player, without changing the pitch, so:
playerA->setTempo(1.5f, true);

the problem is:
1.  i can control the loop correctly and the tempo change but only the first time, because after that the debug is like this:
NSLog(@"LoopEnd %f %d ", sps->playerA->positionMs, sps->playerA->durationMs);

 ReactNativeSuperpowered[4959:474681] LoadSuccess 0.000000 8071 
2018-01-14 15:48:30.594 ReactNativeSuperpowered[4959:474738] DurationChanged 7029.977324 8045 
2018-01-14 15:48:31.210 ReactNativeSuperpowered[4959:474738] LoopEnd 7953.877551 8045 
2018-01-14 15:48:31.303 ReactNativeSuperpowered[4959:474738] LoopEnd 7940.204082 8045 
2018-01-14 15:48:31.407 ReactNativeSuperpowered[4959:474738] LoopEnd 7948.526077 8045 
2018-01-14 15:48:31.500 ReactNativeSuperpowered[4959:474738] LoopEnd 7936.621315 8045 
2018-01-14 15:48:31.604 ReactNativeSuperpowered[4959:474738] LoopEnd 7946.122449 8045 

 is stuck in the event LoopEnd, there is no sound, even if i put 
    sps->playerA->setBpm(bpm);
    sps->playerA->setFirstBeatMs(firstBeatMs);
    sps->playerA->setPosition(sps->playerA->firstBeatMs, false, true);

its stuck in the "Loop End "
This happens with loopBetween and loop.
 If i change the: playerA->setTempo(1.5f, false); - to change the pitch, then also works fine, but then isnt the objetive.

2. If i change the line:
playerA->loopBetween(12, 8000, true, 255, true);
to 
playerA->play(true);

then time change works correctly , but then i dont have control over the mp3 files, and the loop isn't correct (Isn't generating the LoopEnd event but the EOF);

Using sdk version 1.1.0

Thanks for the help

**Comment by superpoweredSDK** [comment]
loopBetween(12, 8000) is not a 8000 ms long loop, but a 7988 ms long loop.

I see the DurationChanged event is called. Perhaps the file is shorter than 8012 milliseconds long?

**Comment by CodeJd** [comment]
Then lest put apart mp3 files. i tested with wav:

a 5000 ms loop

if i use:

    playerA->loopBetween(0.0f,
                           5000.f,
                           true,
                           255,
                           true);

never leaves the LoopEnd event:

2018-01-15 17:22:37.605 ReactNativeSuperpowered[1298:55224] DurationChanged 0.000000 5000 
2018-01-15 17:22:37.626 ReactNativeSuperpowered[1298:55224] LoadSuccess 0.000000 5000 
2018-01-15 17:22:42.318 ReactNativeSuperpowered[1298:55286] LoopEnd 4946.916100 5000 
2018-01-15 17:22:42.422 ReactNativeSuperpowered[1298:55286] LoopEnd 4948.956916 5000 
2018-01-15 17:22:42.527 ReactNativeSuperpowered[1298:55286] LoopEnd 4950.362812 5000 
2018-01-15 17:22:42.631 ReactNativeSuperpowered[1298:55286] LoopEnd 4951.292517 5000 
2018-01-15 17:22:42.735 ReactNativeSuperpowered[1298:55286] LoopEnd 4951.904762 5000 

only works if i use:
playerA->play(true);
wich i cant use for compressed files ....

note: 
about mp3 in the example above if i use the 8000 milliseconds loop and i put a much higher value then the real loop lenght, for example:
    playerA->loopBetween(12.0f,
                           16000.f,
                           true,
                           255,
                           true);

it works, but i never get the loop correct
16000 is a example i tried with diferent values, but like i said never get a good loop, and in the debug if works i will get like 5 LoopEnd  events repeated at that moment

I tried this in the wav (putting a higher value then the track lenght), but never worked, is stuck in the loopend event

Thanks

**Comment by CodeJd** [comment]
Update: testing with wav files the problem only happens if the tempo is higher then 1.0. if is less its working

**Comment by superpoweredSDK** [comment]
when LoopEnd happens, positionMs is not updated yet, since this event happens inside a loop immediately when audio samples are being produced

i don't understand the other comments, sorry

**Comment by CodeJd** [comment]
when LoopEnd happens, positionMs is not updated yet, since this event happens inside a loop immediately when audio samples are being produced
ok, then how this could be solved?


i don't understand the other comments, sorry
an example using a wav file:
using 9 SuperpoweredAdvancedAudioPlayer players loading the same wav file that have 9000 ms

1.
      playerA->setTempo(1.0f, true);
        playerA->loopBetween(0,
                             10000,
                             true,
                             255,
                             true);

 works fine

2.
      playerA->setTempo(0.5f, true);
        playerA->loopBetween(0,
                             10000,
                             true,
                             255,
                             true);

works fine

3.
      playerA->setTempo(0.9f, true);
        playerA->loopBetween(0,
                             10000,
                             true,
                             255,
                             true);

doesnt work: players stuck in Loop End with sound but wrong loop timming

4.
      playerA->setTempo(1.1f, true);
        playerA->loopBetween(0,
                             10000,
                             true,
                             255,
                             true);

doesnt work: players stuck in Loop End, no sound

2018-01-17 12:08:34.395 ReactNativeSuperpowered[2504:119789] LoopEnd 9953.968254 10000 
2018-01-17 12:08:34.395 ReactNativeSuperpowered[2504:119789] LoopEnd 9953.968254 10000 
2018-01-17 12:08:34.396 ReactNativeSuperpowered[2504:119789] LoopEnd 9953.968254 10000 
2018-01-17 12:08:34.429 ReactNativeSuperpowered[2504:119789] LoopEnd 9953.968254 10000 
2018-01-17 12:08:34.429 ReactNativeSuperpowered[2504:119789] LoopEnd 9953.968254 10000 
2018-01-17 12:08:34.429 ReactNativeSuperpowered[2504:119789] LoopEnd 9953.968254 10000 
2018-01-17 12:08:34.430 ReactNativeSuperpowered[2504:119789] LoopEnd 9953.968254 10000 
2018-01-17 12:08:34.430 ReactNativeSuperpowered[2504:119789] LoopEnd 9953.968254 10000 


4.
      playerA->setTempo(1.5f, true);
        playerA->loopBetween(0,
                             10000,
                             true,
                             255,
                             true);

doesnt work: players stuck in Loop End , no sound

2018-01-17 12:09:52.378 ReactNativeSuperpowered[2534:122703] LoopEnd 9946.303855 10000 
2018-01-17 12:09:52.378 ReactNativeSuperpowered[2534:122703] LoopEnd 9946.303855 10000 
2018-01-17 12:09:52.378 ReactNativeSuperpowered[2534:122703] LoopEnd 9946.303855 10000 
2018-01-17 12:09:52.379 ReactNativeSuperpowered[2534:122703] LoopEnd 9946.303855 10000 
2018-01-17 12:09:52.379 ReactNativeSuperpowered[2534:122703] LoopEnd 9946.303855 10000 
2018-01-17 12:09:52.379 ReactNativeSuperpowered[2534:122703] LoopEnd 9946.303855 10000 
2018-01-17 12:09:52.380 ReactNativeSuperpowered[2534:122703] LoopEnd 9946.303855 10000

**Comment by CodeJd** [comment]
so the above test was with superpowered 1.1.0
with 1.0.7.1, have the same problems 
with 1.0.5 apparently this is working correctly (https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/commit/94ba46952a6bcde3770ca28a19d5dc8c69cb8efd)

**Comment by superpoweredSDK** [comment]
I wonder what is the code in your player callback handler? I never saw the player stuck in the LoopEnd event, and i don't see anything obvious on why this may happen.

**Comment by CodeJd** [comment]
can i send you the code? email?

there is also another problem: now the loop is ok (android and ios) but when the device is connected with audio jack the gap its there again when it loops.... - only happens when device is connected to a output jack. all this problems is gonna make me insane... for each solution we have another problem ...

**Comment by superpoweredSDK** [comment]
How could the looping problem magically fix itself?

**Comment by CodeJd** [comment]
the loop fixed because i changed library version:

so the above test was with superpowered 1.1.0
with 1.0.7.1, have the same problems
with 1.0.5 apparently this **is working correctly** (94ba469)

**Comment by superpoweredSDK** [comment]
I'd like to resolve this looping problem. Rolling back to an older version is not really helpful with this, and i guess you wouldn't like to stuck with an old version either.
Please post what's inside your player callback handler.

**Comment by CodeJd** [comment]
thanks and sorry: its lot of code, but its for a better communication

//
float           bpm           = 120;      // Bpm
unsigned int    startPoint;
NSArray         *fileNames      = [NSArray arrayWithObjects:

                                   @"loop20",
                                  ....

NSString        *fileFormat       = @"m4a"	;   // 
float           firstBeatMs       = 0.0f;       // 
unsigned int    sampleRate        = 44100;      // 
bool            isPlaying         = false;      // 
float           tempoShift        = 1.0f;       // 




@implementation SuperpoweredModule {
  SuperpoweredAdvancedAudioPlayer *playerA, *playerB, *playerC, *playerD, *playerE, *playerF, *playerG, *playerH, *playerI;
  SuperpoweredIOSAudioIO *output;

  //unsigned char activeFx;
  float *stereoBuffer, volA, volB, volC, volD, volE, volF, volG, volH,  volI;
  unsigned int lastSamplerate;
  
  SuperpoweredRecorder *recorder;
  float *stereoBufferRecording;
  //SuperpoweredIOSAudioIO *audioSystemA = NULL, *audioSystemRecording;
  
}


RCT_EXPORT_MODULE();

void playerEventCallbackA(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event, void *value) {
  SuperpoweredModule *sps = (__bridge SuperpoweredModule *)clientData;
  
  if (event == SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess) {
    //SuperpoweredModule *self = (__bridge SuperpoweredModule *)clientData;
    
    sps->playerA->setBpm(bpm);
    sps->playerA->setFirstBeatMs(firstBeatMs);
    sps->playerA->setPosition(sps->playerA->firstBeatMs, false, false);
    
    NSLog(@"LoadSuccess0 %f %d ", sps->playerA->positionMs, sps->playerA->durationMs);
    
  }else if (event == SuperpoweredAdvancedAudioPlayerEvent_EOF) {
    NSLog(@"EOF0 %f %d ", sps->playerA->positionMs, sps->playerA->durationMs);
  }else if (event == SuperpoweredAdvancedAudioPlayerEvent_DurationChanged) {
    NSLog(@"DurationChanged %f %d ", sps->playerA->positionMs, sps->playerA->durationMs);
  
  }else if (event == SuperpoweredAdvancedAudioPlayerEvent_LoopEnd) {
    NSLog(@"LoopEnd %f %d ", sps->playerA->positionMs, sps->playerA->durationMs);
    
    outvar = true;   
  };
}

...



static bool audioProcessing(void *clientdata, float **buffers, unsigned int inputChannels, unsigned int outputChannels, unsigned int numberOfSamples, unsigned int samplerate, uint64_t hostTime) {
  
  __unsafe_unretained SuperpoweredModule *self = (__bridge SuperpoweredModule *)clientdata;
  if (samplerate != self->lastSamplerate) {
    self->lastSamplerate = samplerate;
    self->playerA->setSamplerate(samplerate);
    ....
  };
  
  
  bool masterIsA = true;//(self->crossValue <= 0.5f);
  float masterBpm = self->playerA->currentBpm;
  double msElapsedSinceLastBeatA = self->playerA->msElapsedSinceLastBeat;
  
  bool silence = !self->playerA->process(self->stereoBuffer, false, numberOfSamples, self->volA, masterBpm, msElapsedSinceLastBeatA);
  
  if (self->playerB->process(self->stereoBuffer, !silence, numberOfSamples, self->volB, masterBpm, msElapsedSinceLastBeatA)) silence = false;
  
	...
	
  if (outvar){
    outvar = false;
    NSLog(@"positionMs0 %f %d ", self->playerA->positionMs, self->playerA->durationMs);
   ...

  }
  

  if (!silence) SuperpoweredDeInterleave(self->stereoBuffer, buffers[0], buffers[1], numberOfSamples);
  return !silence;
}


RCT_REMAP_METHOD(init,
                 initResolver:(RCTPromiseResolveBlock)resolve
                 initRejecter:(RCTPromiseRejectBlock)reject)
{
	...
  
  if (posix_memalign((void **)&stereoBuffer, 16, 4096 + 128) != 0) abort(); // Allocating memory, aligned to 16.
  
  
  playerA = new SuperpoweredAdvancedAudioPlayer((__bridge void *)self, playerEventCallbackA, sampleRate, 0);
  playerA->open([[[NSBundle mainBundle] pathForResource:fileNames[0] ofType:fileFormat] fileSystemRepresentation]);
  
	...
  
  
  playerA->syncMode = playerB->syncMode = playerC->syncMode = playerD->syncMode = playerE->syncMode = playerF->syncMode = playerG->syncMode = playerH->syncMode = playerI->syncMode  = SuperpoweredAdvancedAudioPlayerSyncMode_TempoAndBeat;
  
  
  output = [[SuperpoweredIOSAudioIO alloc] initWithDelegate:(id<SuperpoweredIOSAudioIODelegate>)self preferredBufferSize:4 preferredMinimumSamplerate:sampleRate audioSessionCategory:AVAudioSessionCategoryPlayback channels:2 audioProcessingCallback:audioProcessing clientdata:(__bridge void *)self];
  
  if (output) {
    [output start];
    resolve(@"true");
  } else {
    reject(@"get_error", @"Error with output", nil);
  }
}

	....


RCT_REMAP_METHOD(playPause,
                 playPauseResolver:(RCTPromiseResolveBlock)resolve
                 playPauseRejecter:(RCTPromiseRejectBlock)reject)
{
  
  // Go to beginning
  playerA->seek(0);
  
  if (playerA->playing) {
    playerA->pause();
    ...

    isPlaying = false;
    
  } else {
    bool masterIsA = true;//(crossValue <= 0.5f);
        

      playerA->setTempo(tempoShift, true);
      playerA->setPitchShift(0);
      playerA->loopBetween(trackOffsetBegin,
                             trackDurationMs,
                             true,
                             255,
                             true);

    
    
      playerB->setTempo(tempoShift, true);
      playerB->setPitchShift(0);
      playerB->loopBetween(trackOffsetBegin,
                             trackDurationMs,
                             true,
                             255,
                             true);

    
	...
	
    isPlaying = true;
	
  };
  
   //SuperpoweredCPU::setSustainedPerformanceMode(isPlaying); // <-- Important to prevent audio dropouts.

  if (isPlaying) {
    resolve(@"true");
  } else {
    reject(@"get_error", @"Error while playPause", nil);
  }
}

**Comment by superpoweredSDK** [comment]
I quickly created a 10 seconds long file and a small example project playing it with the same loopBetween call and tempo. Works great.
However i don't see anything obvious in your code either. When are you calling those loopBetweens?

**Comment by CodeJd** [comment]
When are you calling those loopBetweens?
Its from react native click in button.

But i just tested your crossexample (not in react native) and have the problem
try setting the tempo to 1.5, or something above 1

**Comment by superpoweredSDK** [comment]
i modified crossexample too, with the following:

- open a 10 seconds long wav file
- in the load success event: settempo to 1.5f, loopbetween exactly how you do it

works great, no problem

how did you modify crossexample?

**Comment by CodeJd** [comment]
#import "ViewController.h"
#import "SuperpoweredAdvancedAudioPlayer.h"
#import "SuperpoweredFilter.h"
#import "SuperpoweredRoll.h"
#import "SuperpoweredFlanger.h"
#import "SuperpoweredIOSAudioIO.h"
#import "SuperpoweredSimple.h"
#import <stdlib.h>

#define HEADROOM_DECIBEL 3.0f
static const float headroom = powf(10.0f, -HEADROOM_DECIBEL * 0.025);

float tempoShift = 1.5f; //
/*
 This is a .mm file, meaning it's Objective-C++.
 You can perfectly mix it with Objective-C or Swift, until you keep the member variables and C++ related includes here.
 Yes, the header file (.h) isn't the only place for member variables.
 */
@implementation ViewController {
    SuperpoweredAdvancedAudioPlayer *playerA, *playerB, *playerC, *playerD, *playerE, *playerF, *playerG, *playerH, *playerI, *playerJ;
    SuperpoweredIOSAudioIO *output;
    //SuperpoweredRoll *roll;
    //SuperpoweredFilter *filter;
    //SuperpoweredFlanger *flanger;
    unsigned char activeFx;
    float *stereoBuffer, crossValue, volA, volB, volC, volD, volE, volF, volG, volH, volI, volJ;
    unsigned int lastSamplerate;
    
    
    NSString *fileName;
    BOOL isAllPlaying;
    BOOL isOnePlaying;
}

void playerEventCallbackA(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event, void *value) {
    printf(__FUNCTION__);
    if (event == SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess) {
        ViewController *self = (__bridge ViewController *)clientData;
        self->playerA->setBpm(120.0f);
        self->playerA->setFirstBeatMs(0);
        self->playerA->setPosition(self->playerA->firstBeatMs, false, false);
    };
}

void playerEventCallbackB(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event, void *value) {
    printf(__FUNCTION__);
    if (event == SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess) {
        ViewController *self = (__bridge ViewController *)clientData;
        self->playerB->setBpm(120.0f);
        self->playerB->setFirstBeatMs(0);
        self->playerB->setPosition(self->playerB->firstBeatMs, false, false);
    };
}

void playerEventCallbackC(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event, void *value) {
    printf(__FUNCTION__);
    if (event == SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess) {
        ViewController *self = (__bridge ViewController *)clientData;
        self->playerC->setBpm(120.0f);
        self->playerC->setFirstBeatMs(0);
        self->playerC->setPosition(self->playerC->firstBeatMs, false, false);
    };
}

void playerEventCallbackD(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event, void *value) {
    printf(__FUNCTION__);
    if (event == SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess) {
        ViewController *self = (__bridge ViewController *)clientData;
        self->playerD->setBpm(120.0f);
        self->playerD->setFirstBeatMs(1);
        self->playerD->setPosition(self->playerD->firstBeatMs, false, false);
    };
}


void playerEventCallbackE(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event, void *value) {
    printf(__FUNCTION__);
    if (event == SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess) {
        ViewController *self = (__bridge ViewController *)clientData;
        self->playerE->setBpm(120.0f);
        self->playerE->setFirstBeatMs(0);
        self->playerE->setPosition(self->playerE->firstBeatMs, false, false);
    };
}

void playerEventCallbackF(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event, void *value) {
    printf(__FUNCTION__);
    if (event == SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess) {
        ViewController *self = (__bridge ViewController *)clientData;
        self->playerF->setBpm(120.0f);
        self->playerF->setFirstBeatMs(0);
        self->playerF->setPosition(self->playerF->firstBeatMs, false, false);
    };
}

void playerEventCallbackG(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event, void *value) {
    printf(__FUNCTION__);
    if (event == SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess) {
        ViewController *self = (__bridge ViewController *)clientData;
        self->playerG->setBpm(120.0f);
        self->playerG->setFirstBeatMs(0);
        self->playerG->setPosition(self->playerG->firstBeatMs, false, false);
    };
}

void playerEventCallbackH(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event, void *value) {
    printf(__FUNCTION__);
    if (event == SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess) {
        ViewController *self = (__bridge ViewController *)clientData;
        self->playerH->setBpm(120.0f);
        self->playerH->setFirstBeatMs(0);
        self->playerH->setPosition(self->playerH->firstBeatMs, false, false);
    };
}


void playerEventCallbackI(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event, void *value) {
    printf(__FUNCTION__);
    if (event == SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess) {
        ViewController *self = (__bridge ViewController *)clientData;
        self->playerI->setBpm(120.0f);
        self->playerI->setFirstBeatMs(0);
        self->playerI->setPosition(self->playerI->firstBeatMs, false, false);
    };
}

void playerEventCallbackJ(void *clientData, SuperpoweredAdvancedAudioPlayerEvent event, void *value) {
    printf(__FUNCTION__);
    if (event == SuperpoweredAdvancedAudioPlayerEvent_LoadSuccess) {
        ViewController *self = (__bridge ViewController *)clientData;
        self->playerJ->setBpm(120.0f);
        self->playerJ->setFirstBeatMs(0);
        self->playerJ->setPosition(self->playerJ->firstBeatMs, false, false);
    };
}







// This is where the Superpowered magic happens.
static bool audioProcessing(void *clientdata, float **buffers, unsigned int inputChannels, unsigned int outputChannels, unsigned int numberOfSamples, unsigned int samplerate, uint64_t hostTime) {
    //printf(__FUNCTION__);
    
    __unsafe_unretained ViewController *self = (__bridge ViewController *)clientdata;
    if (samplerate != self->lastSamplerate) { // Has samplerate changed?
        self->lastSamplerate = samplerate;
        self->playerA->setSamplerate(samplerate);
        self->playerB->setSamplerate(samplerate);
        self->playerC->setSamplerate(samplerate);
        self->playerD->setSamplerate(samplerate);
        self->playerE->setSamplerate(samplerate);
  //      self->playerF->setSamplerate(samplerate);
        self->playerG->setSamplerate(samplerate);
        self->playerH->setSamplerate(samplerate);
        self->playerI->setSamplerate(samplerate);
        self->playerJ->setSamplerate(samplerate);

    };

    bool masterIsA = true;//(self->crossValue <= 0.5f);
    
    float masterBpm = self->playerA->currentBpm;//masterIsA ? self->playerA->currentBpm : self->playerB->currentBpm; // Players will sync to this tempo.
    
    double msElapsedSinceLastBeatA = self->playerA->msElapsedSinceLastBeat; // When playerB needs it, playerA has already stepped this value, so save it now.

    bool silence = !self->playerA->process(self->stereoBuffer, false, numberOfSamples, self->volA, masterBpm, self->playerB->msElapsedSinceLastBeat);
    
    if (self->playerB->process(self->stereoBuffer, !silence, numberOfSamples, self->volB, masterBpm, msElapsedSinceLastBeatA)) silence = false;
    if (self->playerC->process(self->stereoBuffer, !silence, numberOfSamples, self->volC, masterBpm, msElapsedSinceLastBeatA)) silence = false;
    if (self->playerD->process(self->stereoBuffer, !silence, numberOfSamples, self->volD, masterBpm, msElapsedSinceLastBeatA)) silence = false;
    if (self->playerE->process(self->stereoBuffer, !silence, numberOfSamples, self->volE, masterBpm, msElapsedSinceLastBeatA)) silence = false;
 //   if (self->playerF->process(self->stereoBuffer, !silence, numberOfSamples, self->volF, masterBpm, msElapsedSinceLastBeatA)) silence = false;
    if (self->playerG->process(self->stereoBuffer, !silence, numberOfSamples, self->volG, masterBpm, msElapsedSinceLastBeatA)) silence = false;
    if (self->playerH->process(self->stereoBuffer, !silence, numberOfSamples, self->volH, masterBpm, msElapsedSinceLastBeatA)) silence = false;
    if (self->playerI->process(self->stereoBuffer, !silence, numberOfSamples, self->volI, masterBpm, msElapsedSinceLastBeatA)) silence = false;
    if (self->playerJ->process(self->stereoBuffer, !silence, numberOfSamples, self->volJ, masterBpm, msElapsedSinceLastBeatA)) silence = false;
 
    
    
    if (!silence) SuperpoweredDeInterleave(self->stereoBuffer, buffers[0], buffers[1], numberOfSamples); // The stereoBuffer is ready now, let's put the finished audio into the requested buffers.
    return !silence;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    lastSamplerate = activeFx = 0;
    crossValue = volB = 0.0f;
    
    volA = 1.0f * headroom;
    volB = 1.0f * headroom;
    volC = 1.0f * headroom;
    volD = 1.0f * headroom;
    volE = 1.0f * headroom;
    volF = 1.0f * headroom;
    volG = 1.0f * headroom;
    volH = 1.0f * headroom;
    volI = 1.0f * headroom;
    volJ = 1.0f * headroom;
    
    if (posix_memalign((void **)&stereoBuffer, 16, 4096 + 128) != 0) abort(); // Allocating memory, aligned to 16.

    playerA = new SuperpoweredAdvancedAudioPlayer((__bridge void *)self, playerEventCallbackA, 44100, 0);
    playerA->open([[[NSBundle mainBundle] pathForResource:@"loop10" ofType:@"wav"] fileSystemRepresentation]);
    
    playerB = new SuperpoweredAdvancedAudioPlayer((__bridge void *)self, playerEventCallbackB, 44100, 0);
    playerB->open([[[NSBundle mainBundle] pathForResource:@"loop10" ofType:@"wav"] fileSystemRepresentation]);

    playerC = new SuperpoweredAdvancedAudioPlayer((__bridge void *)self, playerEventCallbackC, 44100, 0);
    playerC->open([[[NSBundle mainBundle] pathForResource:@"loop10" ofType:@"wav"] fileSystemRepresentation]);
 
    playerD = new SuperpoweredAdvancedAudioPlayer((__bridge void *)self, playerEventCallbackD, 44100, 0);
    playerD->open([[[NSBundle mainBundle] pathForResource:@"loop10" ofType:@"wav"] fileSystemRepresentation]);
    
    
    playerE = new SuperpoweredAdvancedAudioPlayer((__bridge void *)self, playerEventCallbackE, 44100, 0);
    playerE->open([[[NSBundle mainBundle] pathForResource:@"loop10" ofType:@"wav"] fileSystemRepresentation]);
    
    //playerF = new SuperpoweredAdvancedAudioPlayer((__bridge void *)self, playerEventCallbackF, 44100, 0);
    //playerF->open([[[NSBundle mainBundle] pathForResource:@"metronome" ofType:@"wav"] fileSystemRepresentation]);
    
    playerG = new SuperpoweredAdvancedAudioPlayer((__bridge void *)self, playerEventCallbackG, 44100, 0);
    playerG->open([[[NSBundle mainBundle] pathForResource:@"loop10" ofType:@"wav"] fileSystemRepresentation]);
    
    playerH = new SuperpoweredAdvancedAudioPlayer((__bridge void *)self, playerEventCallbackH, 44100, 0);
    playerH->open([[[NSBundle mainBundle] pathForResource:@"loop10" ofType:@"wav"] fileSystemRepresentation]);
    
    playerI = new SuperpoweredAdvancedAudioPlayer((__bridge void *)self, playerEventCallbackI, 44100, 0);
    playerI->open([[[NSBundle mainBundle] pathForResource:@"loop10" ofType:@"wav"] fileSystemRepresentation]);
 
    playerJ = new SuperpoweredAdvancedAudioPlayer((__bridge void *)self, playerEventCallbackJ, 44100, 0);
    playerJ->open([[[NSBundle mainBundle] pathForResource:@"loop10" ofType:@"wav"] fileSystemRepresentation]);
    
    
    
    playerA->syncMode = playerB->syncMode = playerC->syncMode = playerD->syncMode = playerE->syncMode = playerG->syncMode = playerH->syncMode = playerI->syncMode = playerJ->syncMode = SuperpoweredAdvancedAudioPlayerSyncMode_TempoAndBeat;
    
    
    output = [[SuperpoweredIOSAudioIO alloc] initWithDelegate:(id<SuperpoweredIOSAudioIODelegate>)self preferredBufferSize:12 preferredMinimumSamplerate:44100 audioSessionCategory:AVAudioSessionCategoryPlayback channels:2 audioProcessingCallback:audioProcessing clientdata:(__bridge void *)self];
    [output start];
}

- (void)dealloc {
    delete playerA;
    delete playerB;
    delete playerC;
    delete playerD;
    delete playerE;
    delete playerF;
    delete playerG;
    delete playerH;
    delete playerI;

    
    free(stereoBuffer);
#if !__has_feature(objc_arc)
    [output release];
    [super dealloc];
#endif
}

- (void)interruptionStarted {}
- (void)recordPermissionRefused {}
- (void)mapChannels:(multiOutputChannelMap *)outputMap inputMap:(multiInputChannelMap *)inputMap externalAudioDeviceName:(NSString *)externalAudioDeviceName outputsAndInputs:(NSString *)outputsAndInputs {}

- (void)interruptionEnded { // If a player plays Apple Lossless audio files, then we need this. Otherwise unnecessary.
    playerA->onMediaserverInterrupt();
    playerB->onMediaserverInterrupt();
    playerC->onMediaserverInterrupt();
    playerD->onMediaserverInterrupt();
    playerE->onMediaserverInterrupt();
    //playerF->onMediaserverInterrupt();
    playerG->onMediaserverInterrupt();
    playerH->onMediaserverInterrupt();
    playerI->onMediaserverInterrupt();
    playerJ->onMediaserverInterrupt();
    
}

- (IBAction)onPlayPause:(id)sender {
    UIButton *button = (UIButton *)sender;
    if (playerA->playing) {
        playerA->pause();
        playerB->pause();
        playerC->pause();
        playerD->pause();
        playerE->pause();
        //playerF->pause();
        playerG->pause();
        playerH->pause();
        playerI->pause();
        playerJ->pause();
    } else {
        bool masterIsA = true;//(crossValue <= 0.5f);
        
        playerA->setTempo(tempoShift, true);
        playerA->setPitchShift(0);
        playerA->loopBetween(0.0f,
                             10000,
                             true,
                             255,
                             true);
        
        playerB->setTempo(tempoShift, true);
        playerB->setPitchShift(0);
        playerB->loopBetween(0.0f,
                             10000,
                             true,
                             255,
                             true);
        
        playerC->setTempo(tempoShift, true);
        playerC->setPitchShift(0);
        playerC->loopBetween(0.0f,
                             10000,
                             true,
                             255,
                             true);
        playerD->setTempo(tempoShift, true);
        playerD->setPitchShift(0);
        playerD->loopBetween(0.0f,
                             10000,
                             true,
                             255,
                             true);
        
        playerE->setTempo(tempoShift, true);
        playerE->setPitchShift(0);
        playerE->loopBetween(0.0f,
                             10000,
                             true,
                             255,
                             true);
        
        playerG->setTempo(tempoShift, true);
        playerG->setPitchShift(0);
        playerG->loopBetween(0.0f,
                             10000,
                             true,
                             255,
                             true);
        
        
        playerH->setTempo(tempoShift, true);
        playerH->setPitchShift(0);
        playerH->loopBetween(0.0f,
                             10000,
                             true,
                             255,
                             true);
        
        playerI->setTempo(tempoShift, true);
        playerI->setPitchShift(0);
        playerI->loopBetween(0.0f,
                             10000,
                             true,
                             255,
                             true);

    };
    button.selected = playerA->playing;
}

@end

**Comment by CodeJd** [comment]
i can send you the project but only changed the above code

**Comment by superpoweredSDK** [comment]
What happens if you implement the durationchanged event? Does it trigger?

**Comment by superpoweredSDK** [comment]
yes, please send the project with the loop10 file too

**Comment by CodeJd** [comment]
https://wetransfer.com/downloads/bb8aaa96f98775fe7238ea868c7c9cfb20180118171611/342ca09a4646c882f819f51689342d7520180118171611/2ccaf4

**Comment by CodeJd** [comment]
xcode Version 9.2 (9C40b)

**Comment by superpoweredSDK** [comment]
I could identify a bug in our code. We are just ahead of a new release. I will see if i can make the fix in the next release, or you need to wait the release one after that.

**Comment by CodeJd** [comment]
ok, can you give me and estimate time for the realeases? because we would like to release your app in middle February

**Comment by superpoweredSDK** [comment]
I'm not able to provide an estimate, sorry. We are only able to provide guaranteed delivery to customers paying for support.

**Comment by CodeJd** [comment]
Ok, then we need to buy support ? website: $750/mo (pre-paid). My email josedinis[at]studio.com. Thanks
