### ISSUE TITLE
Passing in a null audiobuffer input into SuperPowered3BandEQ causes a crash

### ISSUE THREAD

**Issue by leegoodrich** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#42]
Superpowered Version: 0.8
iOS Version: 8.3
iPhone Version: iPhone 6

Hey guys,

I currently maintain a collection of SuperpoweredFX objects within a vector to streamline effects chain processing within the audio callback. My chain currently contains an EQ, Echo, and Reverb objects. I process all of these within a loop in the audio callback like so:

```
for (auto& effect : effects) { 
   isAudioGenerated = effect->process(isAudioGenerated ? stereoBuffer : NULL, 
stereoBuffer, numberOfSamples) || isAudioGenerated;
}
```

I use the ternary operator to pass in a null buffer if no audio was generated by the player because the echo and reverb effects do not render their tails properly otherwise, as is noted within their documentation.

However, adding an EQ to this chain does not work, because passing in a null pointer for the buffer results in a bad memory access that crashes the program. This forces me to call the EQ's process() method with different arguments than the rest of my effects, which really kills the usefulness of having an abstract SuperpoweredFX interface.

Could you update the Superpowered3BandEQ's process() method to handle a null audio buffer input gracefully, so its interface matches that of the other effects?

**Comment by superpoweredSDK** [comment]
Makes sense, will do with the next update.
