### ISSUE TITLE
offline time stretching quality

### ISSUE THREAD

**Issue by davidjung1234** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#422]
I tested the offline process sample on ubuntu, and found that the processed audio quality is NOT as good as i expected.

The attached zip has four files inside.[timestretch.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/1638228/timestretch.zip)

- freq440hz.mp3  : input to the time stretching process.
- offline2.wav       : output from the time stretching process.
- waveform.png    : wave forms of the two above.
- main.cpp            : source code
// used build command : g++ -g -I.. -L.. main.cpp -lSuperpoweredLinuxX86 -lpthread

I wonder if there is a way to improve the audio quality.

**Comment by superpoweredSDK** [comment]
You can see the effect of transient handling here. The time stretcher is confused of the pure sine wave, since it's tuned for music.
This is only a problem if you time-stretch pure signals (sine wave, sawtooth, etc.) -- which doesn't make sense. Always test with music.
