### ISSUE TITLE
jogTouchBegin() and jogTick()

### ISSUE THREAD

**Issue by shreyanshbangar** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#423]
Hi,
I am trying to make "Virtual jog wheel".

I have used jogTouchBegin() method in SuperpoweredAdvancedAudioPlayerJogMode_Scratch mode with scratchSlipMs=1000 and ticksPerTurn approx 2000.

I have used jogTick() method with ticks value minimum=0 and maximum=ticksPerTurn  i.e. 2000. 
parameterMode=false,
bendStretch=true,
bendMaxPercent=0.01f,
bendHoldMs=900.

have tried other combination of parameters too in jogTick() method. But i cannot get Scratch effect. 
After jogTouchBegin() method, song just get muted, nothing happens, no scratch.

**Comment by superpoweredSDK** [comment]
after jogTouchBegin() call the jogTick() method when the user moves the finger, and submit the delta to the last movement in pixels as the jog ticks

**Comment by shreyanshbangar** [comment]
Thanks, its working by delta value, but it only works when player is playing, can't I Scratch when player is paused?

**Comment by superpoweredSDK** [comment]
yes, you can scratch when the player is paused
just make sure you _always_ call the process() method of the player

**Comment by shreyanshbangar** [comment]
I have done it. thankyou.
