### ISSUE TITLE
iOS recording sometime fails, more often when doing a longer recording

### ISSUE THREAD

**Issue by LucasVanDongen** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#426]
Our app allows users to record their voice merged with a video and change it. First I developed the feature as a real-time conversion but as it would require people to use a mic and headphone to prevent feedback issues we decided to let the users change their voices after recording. This proved to be more problematic.

I've narrowed the problem down as follows:

1. I would always pause at the end of the recording before writing out the final file
2. The temporary file would play when the final conversion to the wav file would succeed, but it was unplayable when it would fail
3. It seemed more vulnerable to the problem when doing pitch shift (down?), but it wasn't exclusive to that particular filter
4. Longer files would have problems sooner. Short snippets under 10 seconds barely failed, a few minutes would fail reliably when I kept changing the post processing

**Comment by superpoweredSDK** [comment]
Are you using the SuperpoweredRecorder?
What do you mean "the temporary file would play"?

Please note that thousands of DJs are using the SuperpoweredRecorder every day to record DJ mixes, typically 60 minutes or more. There is a good chance you have some problem in your code.

**Comment by LucasVanDongen** [comment]
Using the SuperpoweredRecorder. If I put a breakpoint before the final I call `stop()` and check the files in the app bundle I see a temporary file. If I open this file in a wav recorder it will play unless the recording fails after calling `stop()`.

Also it wouldn't always fail with the same input and the same FX settings.

If DJ's record their live sets they're doing something different than I am, perhaps I'm hitting a weird corner case because offline processing taxes the CPU much more? Real-time voice processing and recording never was a problem!

**Comment by superpoweredSDK** [comment]
1. You should never use the temporary file for anything, because the recorder performs disk I/O operations on it.

2. You should not use the SuperpoweredRecorder for "offline" processing. There is no point to do that. The recorder is created to record audio in a "live" audio I/O callback, where disk I/O operations should be avoided.

For offline processing just use the createWAV, closeWAV and fwrite functions. The example projects are showing how.
