### ISSUE TITLE
There is no example where android get audiobuffer from inputstream

### ISSUE THREAD

**Issue by boris-dev** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#427]
It will be very helpfull for me if there is an example like **FrequencyDomain**, but with returning  `float[] audioFloatBuffer` which reading from inputstream.

Like in file **FrequencyDomain.cpp** has next line:
  `  new SuperpoweredAndroidAudioIO(samplerate, buffersize, true, true, audioProcessing, NULL, -1, SL_ANDROID_STREAM_MEDIA, buffersize * 2); // Start audio input/output.`
where **audioProcessing** is callback. It calls periodically.

It this callback we have code that I don't fully understand (I'm java programmer).
I just want to return in java code something like `float[] audioFloatBuffer` which I can transformate to pitch with some pitch detection algorithm.

Could you help me?

**Comment by superpoweredSDK** [comment]
I'm not able to help with generic JNI programming, sorry. This place is for Superpowered.
