### ISSUE TITLE
[Newbie Question] How is the stereoBuffer being organised?

### ISSUE THREAD

**Issue by gopencilsdev** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#428]
Hello, thank you for the wonderful SDK, I've relied on it to combat with the high latency on Android with great result. And now I tried to do some small 'audio processing' on the audio file, started with displaying volume on the left and right channel of the audio. My question is, aside from using the Frequency Domain (which is a little overkill for this small quest), can I use the stereoBuffer to calculate the amplitude/volume of the audio being play on left or right channel?

The stereoBuffer is as per this line of code in SuperpoweredExample.cpp from Android Example

`stereoBuffer = (float *)memalign(16, (buffersize + 16) * sizeof(float) * 2);`

The method it belong to:
```
SuperpoweredExample::SuperpoweredExample(unsigned int samplerate, unsigned int buffersize, const char *path, int fileAoffset, int fileAlength, int fileBoffset, int fileBlength) : activeFx(0), crossValue(0.0f), volB(0.0f), volA(1.0f * headroom) {
    stereoBuffer = (float *)memalign(16, (buffersize + 16) * sizeof(float) * 2);

    playerA = new SuperpoweredAdvancedAudioPlayer(&playerA , playerEventCallbackA, samplerate, 0);
    playerA->open(path, fileAoffset, fileAlength);
    playerB = new SuperpoweredAdvancedAudioPlayer(&playerB, playerEventCallbackB, samplerate, 0);
    playerB->open(path, fileBoffset, fileBlength);

    playerA->syncMode = playerB->syncMode = SuperpoweredAdvancedAudioPlayerSyncMode_TempoAndBeat;

    roll = new SuperpoweredRoll(samplerate);
    filter = new SuperpoweredFilter(SuperpoweredFilter_Resonant_Lowpass, samplerate);
    flanger = new SuperpoweredFlanger(samplerate);

    audioSystem = new SuperpoweredAndroidAudioIO(samplerate, buffersize, false, true, audioProcessing, this, -1, SL_ANDROID_STREAM_MEDIA, buffersize * 2);
}
```

Can I use the value in this buffer directly? If so, how is it being organised? Like, first half is for left channel, second half is for right channel, or anything else?

Thank you in advance :D

**Comment by superpoweredSDK** [comment]
"stereoBuffer" is just a name for some memory allocated on the heap. You can use it however you want to. It is as direct and open as it can be.
In the example we are using it to store audio samples. Each audio sample is a 32-bit floating point number. We are storing 2 channels interleaved, meaning the data order is left, right, left, right, ...
