### ISSUE TITLE
SuperpoweredIOSAudioIO echo cancellation with kAudioUnitSubType_VoiceProcessingIO in iOS

### ISSUE THREAD

**Issue by temkich** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#429]
I tried to use speex_echo for echo cancellation in SuperpoweredIOSAudioIO, but I did not succeed. 
And I tried to replace the line
`desc.componentSubType = kAudioUnitSubType_RemoteIO;`
in file SuperpoweredIOSAudioIO.mm, on a new line
`desc.componentSubType = kAudioUnitSubType_VoiceProcessingIO;`
and I got what I wanted. Echo cancellation worked.
But it does not work constantly, once I get an error
`[aurioc] 918: failed: -66635 (enable 3, outf< 2 ch,      0 Hz, Float32, non-inter> inf< 2 ch,      0 Hz, Float32, non-inter>)`
I do not understand what this error is and how can I solve it? 
Why the file SuperpoweredIOSAudioIO code is not used immediately `kAudioUnitSubType_VoiceProcessingIO` ? 

This does not work for iOS?

**Comment by superpoweredSDK** [comment]
Most developers are looking for low-latency I/O with zero or minimal additional processing, therefore we use RemoteIO.
I have no idea about that error. Perhaps VoiceProcessingIO also needs the AVAudioSessionModeVoiceChat category.
I wonder speex didn't work for you?

**Comment by temkich** [comment]
the method requires 4 params:
* @param st Echo canceller state
 * @param rec Signal from the microphone (near end + far end echo)
 * @param play Signal played to the speaker (received from far end)
 * @param out Returns near-end signal with echo removed

`void speex_echo_cancellation(SpeexEchoState *st, const spx_int16_t *rec, const spx_int16_t *play, spx_int16_t *out);`

in the audioProcessing method i have buffers only.
`static bool audioProcessing(void *clientdata, float **buffers, unsigned int inputChannels, unsigned int outputChannels, unsigned int numberOfSamples, unsigned int samplerate, uint64_t hostTime)`

in this array we get what goes with the microphone? and then what gets into the speaker? I do not understand how I get three arrays: one with a microphone, another for a speaker, and the third for an output?

**Comment by romanbsd** [comment]
Try starting from this code, I coded it quickly, but didn't get to using it. It might not work at all :)
https://gist.github.com/romanbsd/1fb7d1f85fd99060a48e3f0a918e1e71
I'm curious to hear how it goes.

**Comment by superpoweredSDK** [comment]
According to the params you mention:

rec Signal from the microphone <-- contents of "buffers" [coming from microphone] 
play Signal played to the speaker <-- the content you would originally put into "buffers" [going to speaker]
out Returns near-end signal with echo removed <-- the content you should put into "buffers"

**Comment by temkich** [comment]
@romanbsd I tried to use your code. I had a problem, what values should be **frameSize** and **filterLength**?
i use `bool process(float *input, float *output, unsigned int size)` method with different values for **frameSize** and **filterLength** and did not get the desired result. Could you help me with this?
And another question about this method 
`process(float *recordingBuffer, float *playbackBuffer, float *output, unsigned int size);`
Is it just a blank to make this process somehow different than in the previous method?
