### ISSUE TITLE
SuperpoweredTimeStretching samplerate

### ISSUE THREAD

**Issue by weepy** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#430]
Does this refer to the output of the timestretcher, the input sample rate or both ?

**Comment by superpoweredSDK** [comment]
Output of the time-stretcher.

**Comment by weepy** [comment]
So what samplerate is the input expected to be in ?

**Comment by superpoweredSDK** [comment]
It operates in the frequency domain. It doesn't care about the input sample rate.

**Comment by weepy** [comment]
But I'm supplying samples to it - I should assume it wants the same sample
rate as the output ? e.g. if I have an audio buffer in 44100 and the
timestretcher is in 48000 - I need to resample ? (or cheat and adjust the
pitch of the output slightly)

**Comment by superpoweredSDK** [comment]
I stand corrected, sorry for that. Output and input sample rate.

**Comment by weepy** [comment]
Cool thanks for confirming.

Last question - what is the point then of specifying the samplerate?  Is it
used internally somehow ?

**Comment by superpoweredSDK** [comment]
yes, at the part where the time-stretcher generates the output
