### ISSUE TITLE
Autotune 

### ISSUE THREAD

**Issue by weepy** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#431]
Is it possible to create an autotune type effect with super powered ? Ie track the pitch and then pitch shift to nearest note.

**Comment by lieff** [comment]
Yes, It's possible. You can take, for example, http://tombaran.info/autotalent.html and replace pitch shift by SuperpoweredTimeStretching.

**Comment by rtiwarihr** [comment]
Can I get any similar sample for iOS ?

**Comment by lieff** [comment]
@rtiwarihr This is C code, compiled with XCode without a problem.

**Comment by ArsalImam** [comment]
> Yes, It's possible. You can take, for example, http://tombaran.info/autotalent.html and replace pitch shift by SuperpoweredTimeStretching.

Hi @lieff Could you please make it more explanatory or create some example of it because I am very curious to learn the combination of pitch shifting and SuperpoweredTimeStretching

**Comment by lieff** [comment]
Hi)
Here SuperpoweredTimeStretching effect header with comments: https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/blob/master/Superpowered/SuperpoweredTimeStretching.h

I've use own pitch shift though, not Superpowered one. And that very long ago, so, no quick examples that I can show. But looking at header comments it should be good to use or even better.

I think closest example where it can be integrated is SuperpoweredEffect: https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/tree/master/Examples_Windows/SuperpoweredEffect
