### ISSUE TITLE
SuperpoweredStereoMixer issue

### ISSUE THREAD

**Issue by gostik** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#44]
Hi
I've faced with very strange issue. 
My task is overlaying input voice on background music. 
I use  SuperpoweredAndroidAudioIO from example for this.
I get voice callback for voice and for music correctly, after that i try to mix it 

        inputs[0]=voiceBuffer;
        inputs[1]=stereoBuffer;

        outputs[0]=comboBuffer;

        inputLevels[0]=1.0f;
        inputLevels[1]=1.0f;
        inputLevels[2]=1.0f;
        inputLevels[3]=1.0f;
        inputLevels[4]=1.0f;
        inputLevels[5]=1.0f;
        inputLevels[6]=1.0f;
        inputLevels[7]=1.0f;

        outputLevels[0]=1.0f;
        outputLevels[1]=1.0f;
        float inputMeters[8];
        float outputMeters[2];

            mixer->process(inputs,outputs,inputLevels,outputLevels,inputMeters,outputMeters,numberOfSamples);

On last row (mixer-process ) sometimes i have crash my app (one of this):

A/libc? Fatal signal 11 (SIGSEGV), code 2, fault addr 0x42c05f1f in tid 15455 (AudioTrack)

06-29 12:49:36.662  15663-17042/ry.aat.dev A/libc? Fatal signal 11 (SIGSEGV), code -6, fault addr 0x3d2f in tid 17042 (AudioTrack)

signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1c

A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x76c62405 (code=1), thread 14368 

Can you make me some idea about resolving this issue? Thanks

**Comment by gostik** [comment]
New one log example of crash:

06-29 16:25:05.984  26079-26559/? A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x0000ac44 (code=1), thread 26559 (AudioTrack)
06-29 16:25:05.992  15402-15402/? I/DEBUG﹕ *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-29 16:25:05.992  15402-15402/? I/DEBUG﹕ Build fingerprint: 'samsung/lt02wifixx/lt02wifi:4.1.2/JZO54K/T210XXANC2:user/release-keys'
06-29 16:25:05.992  15402-15402/? I/DEBUG﹕ pid: 26079, tid: 26559, name: AudioTrack  >>> uk.graph.aas.dev <<<
06-29 16:25:05.992  15402-15402/? I/DEBUG﹕ signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0000ac44
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ r0 000001ff  r1 66db2dc8  r2 66db2dc0  r3 64310748
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ r4 64d470e8  r5 64d51238  r6 0000ac44  r7 00000001
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ r8 643128c0  r9 00000059  sl 66db2d30  fp 6430f56c
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ ip 64374c40  sp 66db2cac  lr 6432b60c  pc 6433f040  cpsr 20000010
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ d0  3f5765ac3b000000  d1  0000000000000000
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ d2  006d006d3b000000  d3  002a002a3f800000
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ d4  0000000000000000  d5  0000000000000000
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ d6  0000000000000000  d7  0000000000000000
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ d8  0000000000000000  d9  0000000000000000
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ d10 0000000000000000  d11 0000000000000000
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ d12 3b0000003b000000  d13 3b0000003b000000
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ d14 3b0000003b000000  d15 3b0000003b000000
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ d16 3b2801503b3a0174  d17 be354cc6be4f4e18
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ d18 0000004c0000004c  d19 0000006d0000006d
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ d20 0000007e0000007e  d21 0000002a0000002a
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ d22 3b7c01f83b7c01f8  d23 3aa801503aa80150
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ d24 0000008f0000008f  d25 0000006d0000006d
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ d26 0000007e0000007e  d27 0000006d0000006d
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ d28 0000004c0000004c  d29 0000006d0000006d
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ d30 0000007e0000007e  d31 0000002a0000002a
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ scr 80000013
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ backtrace:
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ #00  pc 00022040  /data/data/uk.graph.aas.dev/lib/libAasAudioNative.so
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ #01  pc 0000e608  /data/data/uk.graph.aas.dev/lib/libAasAudioNative.so (SuperpoweredStereoMixer::process(float**, float**, float*, float*, float*, float*, unsigned int)+360)
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ stack:
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ 66db2c6c  64d6835c
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ 66db2c70  64d68590
06-29 16:25:06.187  15402-15402/? I/DEBUG﹕ 66db2c74  00000000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2c78  64d68358
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2c7c  00000200
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2c80  00000000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2c84  00000000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2c88  64d6856c
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2c8c  64d68598
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2c90  64d68360
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2c94  40800000  /system/lib/libicui18n.so
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2c98  00000000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2c9c  00000200
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2ca0  df0027ad
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2ca4  00000000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2ca8  64d68350
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ #00  66db2cac  3f800000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ ........  ........
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ #01  66db2cac  3f800000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2cb0  00000000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2cb4  3f800000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2cb8  00000000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2cbc  3f800000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2cc0  3f800000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2cc4  3f800000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2cc8  3f800000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2ccc  3f800000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2cd0  00000000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2cd4  3f800000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2cd8  00000000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2cdc  00000000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2ce0  00000000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2ce4  00000000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2ce8  00000000
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ memory near r1:
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2da8 66db2dc0 00000200 00000000 bff00000  .-.f............
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2db8 00000000 643e2008 00000000 66db2e60  ..... >d....`..f
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2dc8 64d66820 6438f1b3 66db2e20 00000000   h.d..8d ..f....
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2dd8 66bb4040 fffffe41 66bb4040 00000000  @@.fA...@@.f....
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2de8 43ebd866 643b7008 643169c0 643e2008  f..C.p;d.i1d. >d
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ memory near r2:
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2da0 641dd618 66db2dc8 66db2dc0 00000200  ...d.-.f.-.f....
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2db0 00000000 bff00000 00000000 643e2008  ............. >d
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2dc0 00000000 66db2e60 64d66820 6438f1b3  ....`..f h.d..8d
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2dd0 66db2e20 00000000 66bb4040 fffffe41   ..f....@@.fA...
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2de0 66bb4040 00000000 43ebd866 643b7008  @@.f....f..C.p;d
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ memory near r3:
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64310728 000067c0 00000000 00000000 00000000  .g..............
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64310738 00000001 00000000 66eb2f00 0000002b  ........./.f+...
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64310748 00000000 00000000 00000000 00000000  ................
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64310758 00000000 00000000 00000000 00000000  ................
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64310768 00000000 00000043 401c5e7c 00000051  ....C...|^.@Q...
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ memory near r4:
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64d470c8 5bb5c519 5b1b3560 64d51218 00000000  ...[`5.[...d....
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64d470d8 00000018 00001093 3b3a0174 3b280150  ........t.:;P.(;
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64d470e8 3aec01d8 3ac80190 3b180130 3b06010c  ...:...:0..;...;
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64d470f8 3b8f011e 3b7c01f8 3b5c01b8 3b3a0174  ...;..|;..\;t.:;
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64d47108 3b5c01b8 3b3a0174 3b5c01b8 3b3a0174  ..\;t.:;..\;t.:;
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ memory near r5:
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64d51218 5bb84a89 64d470c8 64d51130 00000000  .J.[.p.d0..d....
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64d51228 00000018 00001093 be4f4e18 be354cc6  .........NO..L5.
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64d51238 be3567b2 be1723e5 be2442d8 be0b18ee  .g5..#...B$.....
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64d51248 be4b631e be315456 be664294 be4a26bf  .cK.VT1..Bf..&J.
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64d51258 be39faf5 be23dde1 be0bb3c0 bdeb70a8  ..9...#......p..
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ memory near r6:
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 0000ac24 ffffffff ffffffff ffffffff ffffffff  ................
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 0000ac34 ffffffff ffffffff ffffffff ffffffff  ................
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 0000ac44 ffffffff ffffffff ffffffff ffffffff  ................
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 0000ac54 ffffffff ffffffff ffffffff ffffffff  ................
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 0000ac64 ffffffff ffffffff ffffffff ffffffff  ................
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ memory near r8:
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 643128a0 0000007d 0000001b 64d77c88 4012951c  }........|.d...@
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 643128b0 00000000 00000000 00000018 00001093  ................
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 643128c0 00000000 00000002 49f53f08 0000213a  .........?.I:!..
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 643128d0 80000000 00000000 64d7c7e8 00224073  ...........ds@".
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 643128e0 0000000c 64d7b7d8 00224073 0000000c  .......ds@".....
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ memory near sl:
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2d10 64d470e0 64d51230 0000ac44 00000001  .p.d0..dD.......
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2d20 643128c0 00000059 66db2d30 00000000  .(1dY...0-.f....
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2d30 3b000000 3b000000 3b000000 3b000000  ...;...;...;...;
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2d40 3b000000 3b000000 3b000000 3b000000  ...;...;...;...;
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2d50 00000000 00000000 00000000 00000000  ................
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ memory near fp:
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 6430f54c 64314158 6430f230 002f006b 641de160  XA1d0.0dk./.`..d
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 6430f55c 64d77ca8 641deaf0 641dd6f0 002f0073  .|.d...d...ds./.
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 6430f56c 64d51230 64d470e0 643128c0 00750000  0..d.p.d.(1d..u.
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 6430f57c 3f333333 3f5765ac 3f800000 00760101  333?.eW?...?..v.
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 6430f58c 641dd5c8 641dd5e0 641dd5f0 641dd618  ...d...d...d...d
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ memory near ip:
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64374c20 40138538 6432a9d0 6432a9bc 6432aa88  8..@..2d..2d..2d
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64374c30 6432a8d8 6432a948 6433f290 6433f200  ..2dH.2d..3d..3d
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64374c40 6433eff0 6433f100 6433ef30 6433f370  ..3d..3d0.3dp.3d
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64374c50 6433f3f0 6433f460 6433f5d0 6433f600  ..3d`.3d..3d..3d
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 64374c60 6433f500 6433f560 6433f320 40142138  ..3d`.3d .3d8!.@
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ memory near sp:
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2c8c 64d68598 64d68360 40800000 00000000  ...d`..d...@....
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2c9c 00000200 df0027ad 00000000 64d68350  .....'......P..d
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2cac 3f800000 00000000 3f800000 00000000  ...?.......?....
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2cbc 3f800000 3f800000 3f800000 3f800000  ...?...?...?...?
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 66db2ccc 3f800000 00000000 3f800000 00000000  ...?.......?....
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ code around pc:
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 6433f020 f423828f f42ac28f e2400001 f5d4f018  ..#...*...@.....
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 6433f030 f464078d f5d5f018 f465178d f5d6f018  ..d.......e.....
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 6433f040 f466278d f5d7f018 f467378d f3404dd8  .'f......7g..M@.
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 6433f050 f3426dda e2500001 f2088d4c f20aad4e  .mB...P.L...N...
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 6433f060 f2042da5 f2063da7 f3f98760 f3f9a762  .-...=..`...b...
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ code around lr:
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 6432b5ec e3540000 0a000006 e58d6000 e98d4420  ..T......`.. D..
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 6432b5fc e58d9010 e58d4014 e58d7018 ebffe8d7  .....@...p......
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 6432b60c ea000005 e58d6000 e98d4420 e58d9010  .....`.. D......
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 6432b61c e58d4014 e58d7018 ebffe8d3 e5980000  .@...p..........
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ 6432b62c e2801008 ed808a00 ed809a01 f401aa8f  ................
06-29 16:25:06.195  15402-15402/? I/DEBUG﹕ memory map around fault addr 0000ac44:
06-29 16:25:06.203  15402-15402/? I/DEBUG﹕ (no map below)
06-29 16:25:06.203  15402-15402/? I/DEBUG﹕ (no map for address)
06-29 16:25:06.203  15402-15402/? I/DEBUG﹕ 400ac000-400ae000 /system/bin/app_process

**Comment by superpoweredSDK** [comment]
voiceBuffer, stereoBuffer or comboBuffer is not big enough
or
inputs[2], inputs[3] or outputs[1] is not initialised to NULL

**Comment by samk17cmutpm** [comment]
Hello gostik !

I'm working with an android project that will record an audio and mix that audio with the current audio is playing (like singing with the beat), finally it will export a new mp3 file.

Could you show me the code how you did for me please ! I'm stuck here.

Thank you so much
