### ISSUE TITLE
Can not stop FrequencyDomain in FrequencyDomain Android Example

### ISSUE THREAD

**Issue by samk17cmutpm** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#45]
Hello,

I'm working with FrequencyDomain Example in Android Studio, the sound responses is very good. But I want to know how to stop the "Response" from FrequencyDomain Class.

Example : 
String samplerateString = null, buffersizeString = null;
        if (Build.VERSION.SDK_INT >= 17) {
            AudioManager audioManager = (AudioManager) this.getSystemService(Context.AUDIO_SERVICE);
            samplerateString = audioManager.getProperty(AudioManager.PROPERTY_OUTPUT_SAMPLE_RATE);
            buffersizeString = audioManager.getProperty(AudioManager.PROPERTY_OUTPUT_FRAMES_PER_BUFFER);
        }
        if (samplerateString == null) samplerateString = "44100";
        if (buffersizeString == null) buffersizeString = "512";

        System.loadLibrary("FrequencyDomain");
        FrequencyDomain(Integer.parseInt(samplerateString), Integer.parseInt(buffersizeString));

How can I stop FrequencyDomain ? Is there any method to stop it recording and responing

**Comment by superpoweredSDK** [comment]
Please check the SuperpoweredAndroidAudioIO class in our latest SDK (0.8.5), it has a stop method.

**Comment by samk17cmutpm** [comment]
Finally i got it, thank  you so much :)
