### ISSUE TITLE
Record Audio And Mix With The Current Audio 

### ISSUE THREAD

**Issue by samk17cmutpm** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#46]
Hello,

I'm working with an android project that will record an audio and mix that audio with the current audio is playing (like singing with the beat), finally it will export a new mp3 file.

Could you show me what classes do i need to implement it, or give an example.

Thank you so much !

**Comment by superpoweredSDK** [comment]
Hello,

the Superpowered SDK doesn't offer an out-of-the-box "record to memory" feature. You can implement a simple buffer yourself and copy the incoming audio there. You can mix using the SuperpoweredMixer class. We don't offer an mp3 encoder, decoder only.

**Comment by samk17cmutpm** [comment]
Hello, 
Thank you so much for your quick reply, I hope in the future you will support more features.
Anyway thank you so much
