### ISSUE TITLE
Toggleplayback not working on app suspended...

### ISSUE THREAD

**Issue by andresteves** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#48]
To summarise what i am saying:

1. App is playing fine when i lock the phone.
2. I am using core motion to see if user is stationary or not.
3. If user is moving the app keeps playing the music.
4. User stops and the music is paused.
5. User starts moving again but music do not play again until I unlock the device.

Any thoughts?

**Comment by superpoweredSDK** [comment]
Check the SuperpoweredIOSAudioOutput class. To save battery, it stops the audio processing callback when there is nothing playing for more than 1 second for an app in background. You can find this feature in the audio processing callback, and you can uncomment there.
