### ISSUE TITLE
Understanding CrossExample - LoadPlayerA()

### ISSUE THREAD

**Issue by AdmiralCrunch** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#49]
Hi :)
I just played around with the CrossExample to understand how it works.. so I got the EQ and Effects running, but after long try&error I just can't figure out how to set up only one Player(?) .. 

So I have my File-Select in Java and on the OnClicklistener I tried to call a modified copy of the SuperpoweredExample-Method .. 

    void SuperpoweredExample::LoadPlayerA(const char *audioPath, int *params) {
    pthread_mutex_init(&mutex, NULL); // This will keep our player volumes and playback states in sync.
    unsigned int samplerate = params[4], buffersize = params[5];
    stereoBuffer = (float *)memalign(16, (buffersize + 16) * sizeof(float) * 2);

    playerA->pause();
    delete playerA;
    playerA = new SuperpoweredAdvancedAudioPlayer(&playerA , playerEventCallbackA, samplerate, 0);
    playerA->open(audioPath, params[0], params[1]);

    playerA->syncMode = playerB->syncMode = SuperpoweredAdvancedAudioPlayerSyncMode_TempoAndBeat;

    audioSystem = new SuperpoweredAndroidAudioIO(samplerate, buffersize, false, true, audioProcessing, this, 0);
    }

and in my Java-Code

    fis = new FileInputStream(audioPath);
    fd = fis.getFD();
    File home = new File(audioPath);
    int length = (int) home.length();
    long[] params = {
                                0,
                                length,
                                Integer.parseInt(samplerateString),
                                Integer.parseInt(buffersizeString)
                        };
    LoadPlayerA(audioPath, params);

can someone push me in the right direction? .. whatever I do.. the new track is loaded to PlayerA, and the previous track of playerA is playing overall :/

**Comment by superpoweredSDK** [comment]
All important code is in that one .cpp file. Check how and where you call the open() method of a player in C++.
