### ISSUE TITLE
Provide (timing and tempo extraction) for iOS!

### ISSUE THREAD

**Issue by PrajeetShrestha** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#50]
Hello,
Can you please provide example for extracting timing and tempo from an audio for iOS please ! :)

**Comment by AdmiralCrunch** [comment]
That would be really helpfull fpr me, too :)))

**Comment by iliaskarim** [comment]
@PrajeetShrestha  & @AdmiralCrunch have you tried [SuperpoweredAnalyzer](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/blob/master/Superpowered/SuperpoweredAnalyzer.h)?

**Comment by PrajeetShrestha** [comment]
Yea I had look on SuperpoweredAnalyzer I couldn't figure out how to extract tempo and timing from it!

**Comment by AdmiralCrunch** [comment]
Me too :/ .. the are no errors but I still cant figure out how to get the bpm ..

**Comment by superpoweredSDK** [comment]
The main idea is to call the analyzer's process() method for your audio samples, then call getresults() after the end. There are the bpm and beat grid start ms parameters.
