### ISSUE TITLE
Need Example of Multiple SuperpoweredStereoMixer to process more than 4 songs - iOS

### ISSUE THREAD

**Issue by abhimanyujindal10** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#51]
Hi, I need to mix more than 5 sonts parallely. But, SuperpoweredStereoMixer takes 4 songs at a time. 

As mention in this thread:- https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/issues/41

I need to make 2 audio mixers and the output of the first mixer will be added as the input of the second. But the problem I am facing is that for the second mixer, the buffer is the one that is received from 

- (bool)audioProcessingCallback:(float **)buffers inputChannels:(unsigned int)inputChannels outputChannels:(unsigned int)outputChannels numberOfSamples:(unsigned int)numberOfSamples samplerate:(unsigned int)samplerate hostTime:(UInt64)hostTime 

But for the first mixer, how to create and initialize buffer. 

Currently, I have done it in this way :-

//1 -> Create a new Buffer
float **outPutBuffers1_4;

//2 -> Initialize it in my class constructor
if (posix_memalign((void **)&outPutBuffers1_4, 16, 4096 + 128) != 0) 
abort();

//3 -> Initialize Buffers for interleaved stereo 
outPutBuffers1_4[0] = (Float32 *)malloc(sizeof(Float32) * numberOfSamples);
outPutBuffers1_4[1] = (Float32 *)malloc(sizeof(Float32) * numberOfSamples);

//4 -> Process this buffer

audioMixer->process(mixerInputs, outPutBuffers1_4, mixerInputLevels, mixerOutputLevels, NULL, mixerOutputMeter, numberOfSamples);

//5 - > Add this buffer in mixer Inputs
mixerInputs1[0] = *outPutBuffers1_4;
mixerInputs1[1] = outPutBuffer_5;
mixerInputs1[2] = outPutBuffer_6;
mixerInputs1[3] = outPutBuffer_7;

//5 - > Process it in outPutBuffer which I am getting from the audioProcessingCallback method
audioMixer->process(mixerInputs1, outPutBuffers, mixerInputLevels, mixerOutputLevels, NULL, mixerOutputMeter, numberOfSamples);

This does not work. I think the issue is withe the outputBuffer1_4 allocation and initialization as well as the way it needs to be assigned to mixerInputs1[0]

Please help with this......

**Comment by superpoweredSDK** [comment]
Do not set two buffers as the output of the first mixer process, because you get a non-interleaved result. Use just one buffer as the output there (so the second pointer of the output will be NULL).

**Comment by abhimanyujindal10** [comment]
Can you provide the example of multiple mixers? I am not able to understand your comment.
