### ISSUE TITLE
Beat Tracking.

### ISSUE THREAD

**Issue by PrajeetShrestha** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#53]
Hi ,
With Superpoweredanalyzer I get the bpm of overall song, but is there anyway to find out which sections is considered beat in an audio file? umm may be Simply to print the occurence of each beat.

**Comment by AdmiralCrunch** [comment]
Can you post a example how you did that? .. 
i'm decoding and processing through the analyzer, but there is NO bpm information after getresults() :/

**Comment by superpoweredSDK** [comment]
The analyzer has a complex algorithm to detect which transients are fit to a beatgrid, and tries to find the most significant grid. It returns with the location of the first beat of the beatgrid, and the other beats can be calculated from the bpm. Therefore, it works for songs with fixed grids only (modern dance music).

**Comment by PrajeetShrestha** [comment]
@AdmiralCrunch  Here is my repo for BPM Detection and tracking each beats as suggested by @superpoweredSDK  https://github.com/PrajeetShrestha/SuperpoweredBeatDetection .

**Comment by PrajeetShrestha** [comment]
I think I have tracked the beat for fixed grid songs but challenge is to find beats for variable grid song. :)
