### ISSUE TITLE
How do enapleInput, enableOutput flags in SuperpoweredAndroidAudioIO really work?

### ISSUE THREAD

**Issue by iovorobiev** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#54]
I am trying to record audio from microphone to file in android application with the help of SuperpoweredAndroidAudioIO.

 I am using this kind of code:
```
audio = new SuperpoweredAndroidAudioIO(44100, buffersize, true, true, callback, this, latency);
```
where callback is
```
static bool callback(void *clientdata, short int *audioIO, int numberOfSamples, int samplerate) {
    return ((Recorder *)clientdata)->process(audioIO, numberOfSamples);
}
```
and  process() is:
```
bool Recorder::process(short int *audioIO, int numberOfSamples) {
    SuperpoweredShortIntToFloat(audioIO, buffer, numberOfSamples);
    return superpoweredRecorder->process(buffer, NULL, numberOfSamples);
}
```
When I set enableInput and enableOutput both to true, I am starting to hear what I've just recorded while recording process. But when I set one of these parameters to false (doesn't matter what exactly) audioIO array consists only from zeros. 

So my question is: what exactly enableOutput and enableInput flags do and how can I disable playing what I've just recorded?

**Comment by superpoweredSDK** [comment]
enableInput enables audio input, enableOutput enables audio output. In your case, you should set enableInput to true, enableOutput to false. The SuperpoweredAndroidAudioIO is open source, you can put a log statement at any point.
Please note, the SuperpoweredRecorder's process method requires floating point input. You need to convert the incoming buffer to floats using the SuperpoweredShortIntToFloat method.

**Comment by iovorobiev** [comment]
@superpoweredSDK it doesn't solve my problem. When I set enableInput to true and enableOutput to false I'm receiving only zeros in audioIO array. audioIO array contains real data only if both variables are true. How can I receive real data in audioIO array if I set enableInput to true and enable output to false?
