### ISSUE TITLE
How to get Meta Data

### ISSUE THREAD

**Issue by laurentNoudohounsi** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#55]
Hi!

I managed to compute the BPM of a track but now I would like to get the meta data of it (artist name and track name) but I don't understand how works the getMetaData method. 

What are the 2 last parameters: void *clientData & int maxFrameDataSize and how to use them?

Thanks for your help.

**Comment by superpoweredSDK** [comment]
If you would not like to manually process every ID3 frame, just set the callback and clientData to NULL, and maxFrameDataSize to 0.
