### ISSUE TITLE
SuperpoweredStereoMixer mixing tracks more than 4 songs - Example????

### ISSUE THREAD

**Issue by abhimanyujindal10** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#57]
Hi, 

I have asked this question multiple times. Please check following threads :- 

Here...
https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/issues/41

And here...
https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/issues/51

But, I did not get correct response or answer from the Superpowered team. It seems like Superpowered team is very much in hurry to close the issue. 

Please provide me either the detailed logic or example to do the audio mixing for more than 4 audios. I am developing application using Superpowered and stuck with this issue for more than a month.

**Comment by marsteini** [comment]
You can use two instances of SuperpoweredMixer to mix channels 1-4 and 5-8. Then mix this two output signals with a third mixer instance. Should work refering to the documentation!

**Comment by Kshitij1792** [comment]
@abhimanyujindal10  Hey abhimanu... Did you succeed to mix the first 4 audios correctly? I am supposed to mix two audios in my app. Could you guide me how to achive this mixing? I am a beginner in C++.
Thanks
