### ISSUE TITLE
use superpoweredSDK CrossExample to create a file.

### ISSUE THREAD

**Issue by tuyimiao** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#58]
Hi:
  Thanks for superpoweredSDK CrossExample,Now i can playing two audio file and change effect.but now i need to write the result to a file.I know i can get the data in SuperpoweredExample::process and write it to a file,but it's two slow.How can i do it?Thank you.

**Comment by superpoweredSDK** [comment]
Hi,

please use the SuperpoweredRecorder, which will asynchronously write the result into a WAV file.
