### ISSUE TITLE
Gradual pitch shift?

### ISSUE THREAD

**Issue by yangofzeal** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#6]
I saw in SuperAdvancedAudioPlayer.h that the following function shifts pitch:

```
/**
 @brief Sets the pitch shift value. Needs masterTempo enabled.
 
 @param pitchShift Note offset from -12 to 12. 0 means no pitch shift.
 */
    void setPitchShift(int pitchShift);
```

But the input is an int, and I need to pitch shift gradually from a whole or half-step lower to a whole or half-step higher, over, say, 2 seconds, gradually.  i.e. ```setPitchShift(1.0); setPitchShift(0.99); setPitchShift(0.98); ``` etc.

Is there any way to do this?  I see pitchBend() but this is for temporary tempo change, not gradual pitch shift.

Thanks.

**Comment by pouyanzm** [comment]
shit
