### ISSUE TITLE
How to work with OSx + Swift

### ISSUE THREAD

**Issue by gevariya-ajit** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#60]
MusicPlayer.framework is missing for OSx(Mac) development? i am new at mac so any help would be appreciated..

Thanks :)

**Comment by gevariya-ajit** [comment]
Gotcha

**Comment by superpoweredSDK** [comment]
Here is a tutorial by Apple how to link to a framework: https://developer.apple.com/library/ios/recipes/xcode_help-project_editor/Articles/AddingaLibrarytoaTarget.html
