### ISSUE TITLE
SuperpoweredDecoder and AIFF doesn't work

### ISSUE THREAD

**Issue by ppeau** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#61]
With all of my AIFF files, the SuperpoweredDecoder never returns the SUPERPOWEREDDECODER_EOF at the end. Even if the samplesPerFrame is equal to 0 at the end, it returns all the time SUPERPOWEREDDECODER_OK.

**Comment by superpoweredSDK** [comment]
This is a bug, will be fixed in the next update soon.
