### ISSUE TITLE
SuperpoweredDecoder and AAC return bad durationSample information

### ISSUE THREAD

**Issue by ppeau** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#63]
Hi, new bug in your SuperpoweredDecoder only with AAC file.
The durationSample information isn't correct for each AAC files I have tested.
You return too many samples than the reality. I have tested the mp3, AIFF and WAV file types and it is perfect. The bug appears just for the AAC file type.

**Comment by superpoweredSDK** [comment]
Please send an AAC file which fails the test to hello@superpowered.com -- all files we have here are correctly handled.

**Comment by superpoweredSDK** [comment]
Investigating...

**Comment by superpoweredSDK** [comment]
The return values of Bass and Core Audio are incorrect. Every AAC frame produces 1024 samples of audio, and Superpowered returns with the frame count multiplied by 1024. This is the exact amount of samples you will get while decoding. (Or the absolute maximum number of samples, if decoding returns less samples due a corrupt frame).

The return value of Bass and Core Audio is 16323081. It's not a multiple of 1024. This is a stored value in the m4a file. Perhaps it's the number of samples of the source audio when the AAC file was created. But it's always padded to 1024, as AAC encodes in 1024 samples steps.
