### ISSUE TITLE
libSuperpoweredAudio.a	is incompatible with Xcode 7 for OS X targets

### ISSUE THREAD

**Issue by scapula** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#64]
I've been getting the following linker error on Xcode 7 (both in the betas
and final):
>ld: in /.../SuperpoweredSDK/Superpowered/libSuperpoweredAudio.a(SuperpoweredAdvancedAudioPlayer.o), building for OSX, but linking in object file built for iOS, for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

My build target is OS X. The problem is that the supplied library defines
LC_VERSION_MIN_IPHONEOS for the contained object files.
And the new linker in Xcode 7 seems to require that the LC_VERSION_MIN_* command
matches the build target. I think [this bug report](http://www.openradar.me/21724015) might be related.

I've managed to workaround the issue by writing [a couple of scripts](https://gist.github.com/scapula/8a859fd0ef4ff00a78b5) to patch the object files in the x86-64 library.
The platform and SDK version are hardcoded in the code as 10.10.

**Comment by iliaskarim** [comment]
I've run into this issue as well and found reports of it on Apple's Develop Forums. thanks for the workaround script in the meantime before @superpoweredSDK publishes new .a files, @scapula!

**Comment by gevariya-ajit** [comment]
Yup, same problem!

**Comment by superpoweredSDK** [comment]
Thank you so much @scapula for the temporary workaround!

We are working hard on the new release, but it's not finished yet. Soon!

**Comment by gevariya-ajit** [comment]
great! thanks :)

Thanks & Regards,
AJit Gevariya
-----------------------------------------------------------------------------------------
HD Widgets <https://play.google.com/store/apps/details?id=cloudtv.hdwidgets> |
Colourform
<https://play.google.com/store/apps/details?id=cloudtv.hdthemes.colourform> |
Dayframe <https://play.google.com/store/apps/details?id=cloudtv.dayframe> |
Cloud.tv | Cloudtv Apps
<https://play.google.com/store/apps/developer?id=cloud.tv>

**Comment by christoff** [comment]
We are having the same issue as well. Looking forward to the new release.

**Comment by superpoweredSDK** [comment]
Please check the new version, 0.9 which has separate .a files for iOS and OSX.
