### ISSUE TITLE
URL is not working

### ISSUE THREAD

**Issue by mrazam110** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#65]
If I am sending any URL
[displayLink addToRunLoop:[NSRunLoop currentRunLoop] forMode:NSRunLoopCommonModes];
        [self performSelectorInBackground:@selector(processingThread:) withObject:inputUrl];

InputUrl = file:///Users/raza/Library/Developer/CoreSimulator/Devices/9A1E6D8F-F786-42C5-ACCE-2F3261A8951B/data/Containers/Data/Application/D5D118B3-6F3A-4074-AB1D-3A5D593A965F/Documents/FinalAudio12233.m4a

It is not working and throwing open error

**Comment by mrazam110** [comment]
using this class
https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/tree/master/SuperpoweredOfflineProcessingExample

**Comment by superpoweredSDK** [comment]
Please don't use the protocol prefix ("file://"), start simply with "/Users"

**Comment by mrazam110** [comment]
Its not working :(

2015-09-19 11:46:07.321 DubsApp[694:8764] open error: Can't open this file.
2015-09-19 11:46:07.321 DubsApp[694:8764] /Users/raza/Library/Developer/CoreSimulator/Devices/9A1E6D8F-F786-42C5-ACCE-2F3261A8951B/data/Containers/Data/Application/0346736F-A266-4D86-833F-2658CDFCB306/Documents/FinalAudio12233.m4a

**Comment by mrazam110** [comment]
2015-09-19 11:59:39.788 DubsApp[4746:952014] open error: Can't open this file.
2015-09-19 11:59:39.795 DubsApp[4746:952014] /var/mobile/Containers/Data/Application/399D64C2-D6E2-4075-98BD-FF6C25EC3F87/Documents/FinalAudio12233.m4a

**Comment by mrazam110** [comment]
[displayLink addToRunLoop:[NSRunLoop currentRunLoop] forMode:NSRunLoopCommonModes];
        [self performSelectorInBackground:@selector(processingThread:) withObject:[NSURL URLWithString:@"/var/mobile/Containers/Data/Application/399D64C2-D6E2-4075-98BD-FF6C25EC3F87/Documents/FinalAudio12233.m4a"]];
        NSLog(@"%@", inputUrl);

**Comment by superpoweredSDK** [comment]
Are you 100% sure that path is correct?? The simulator changes paths quite often... or do you get that path from your bundle?

**Comment by mrazam110** [comment]
Now it is working, it was my bug.

Sorry

**Comment by doozMen** [comment]
How did you get it to work. I get the same error. The path to the file is in my bundle.
