### ISSUE TITLE
How to get filtered audio file?

### ISSUE THREAD

**Issue by ruchiragile** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#66]
Hello there,

Its nice to have such a rich library. You guys did an awesome job, thanks! Still I have few questions to ask (and confirm).

1. One of my client asked me to apply filters on an audio file? For e.g. I have an audio file on which I’ve to apply Pitch filter, I found that, its available into the library but, I don’t know how to apply filters permanently and then get a new audio file? Is it possible? Any example would be helpful.

2. I’m looking for following filters :

- FadeIn/Out (Available or Not ? )
- Pitch 
- Reverb
- Delay (Equals to Echo ?)
- Studio (Available or Not ? )

How to apply filter and then save it as a new file (along with filters) ?

Please let me know if my question is not clear to you.

**Comment by superpoweredSDK** [comment]
1. Check the offline example project.
2. We did respond to this via email and Zendesk.
