### ISSUE TITLE
Provide examples for different filters

### ISSUE THREAD

**Issue by ruchiragile** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#67]
Please provide examples for each of the below filters.

FadeIn/Out
Pitch Shifting
Reverb
Delay (Echo)

**Comment by davut5** [comment]
can u make it? Please help me. 
i want to same like yours.

**Comment by ruchiragile** [comment]
@davut5, if you're using @superpoweredSDK, few things you should keep in mind.
1. You must know C++ & Obj-C++ 
2. You must know how's the audio filter is working.
3. You'll not have any support/sample from @superpoweredSDK as they don't have resources to get this done.

**Comment by davut5** [comment]
in swift?
