### ISSUE TITLE
Mix 2 audio signal?

### ISSUE THREAD

**Issue by davut5** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#68]
hi man.When HEADSET Connected.  Can i record video and my voice together (mix)?. 
maybe effect to my voice (reverb,echo ex.) ?

video is playing in UIVIEW.  (Youtube player helper pods.) 
sound is my voice in headset mic.

**Comment by superpoweredSDK** [comment]
Sorry, but we provide support for the Superpowered Audio SDK here, which doesn't offer video features.
