### ISSUE TITLE
About 10 seconds of silence included when recording from mic

### ISSUE THREAD

**Issue by kulkuroo** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#69]
Hi folks, I am trying to implement superpoweredSDK into an android application

The problem I encountered is that when I record a sound from micro phone
into a file, the result .wav file has about 9~10 seconds on silence in the begining
and the corresponding size of seconds of sound are missing in end part. (not recorded)

 As far as I know your API is pretty simple, and I could not find any reason
which might cause this problem.

 My code snippet is like below. 
It would be highly appreciated if you give me any clue to solve this issue.

Thanks in advance.

<Start recording>
pthread_mutex_lock(&mutex);

    if(this->mRecorder != NULL) {
        this->mRecorder->stop();
        delete this->mRecorder;
        this->mRecorder = NULL;
        this->mIsRecording = false;
    }

    if(this->mRecordAudioSystem != NULL) {
        this->mRecordAudioSystem->stop();
        delete this->mRecordAudioSystem;
        this->mRecordAudioSystem = NULL;
    }

    mRecorder = new SuperpoweredRecorder(SOME_TEMP_PATH, 44100);

    // create an instance of SuperpoweredAndroidAudioIO and register callback
    mRecordAudioSystem = new SuperpoweredAndroidAudioIO(44100, 3584, true, false, recordProcessing, this, 0);

    // Start new recording
    this->mRecorder->setSamplerate(44100);
    this->mRecorder->start(SOME_TARGET_PATH);
    this->mIsRecording = true;
    pthread_mutex_unlock(&mutex);

<Stop recording>

    if(this->mRecorder != NULL) {
        pthread_mutex_lock(&mutex);
        this->mRecorder->stop();
        this->mIsRecording = false;

        //delete audio system and recoreder
        if(this->mRecorder != NULL) {
            delete this->mRecorder;
            this->mRecorder = NULL;
        }

        if(this->mRecordAudioSystem != NULL) {
            this->mRecordAudioSystem->stop();
            delete this->mRecordAudioSystem;
            this->mRecordAudioSystem = NULL;
        }
        pthread_mutex_unlock(&mutex);
    }

<Callback function>

    if(!this->mIsRecording) {
        mRecorder->process(NULL, NULL, numberOfSamples);
        pthread_mutex_unlock(&mutex);
        return false;
    }

    SuperpoweredShortIntToFloat(audioInput, mRecordBuffer, numberOfSamples);
    mRecorder->process(mRecordBuffer, 0, numberOfSamples);
    pthread_mutex_unlock(&mutex);

    return true;

**Comment by superpoweredSDK** [comment]
Seems like you are adding silence under the condition: if (!this->mIsRecording)

Just don't process your audio input when you are not recording.

**Comment by kulkuroo** [comment]
Thank you for the answer. 

 I thought the snippet I wrote is the way to "Not" process the recording,
which by the way not seemed to work properly.

if(!this->mIsRecording) {
    mRecorder->process(NULL, NULL, numberOfSamples);
    pthread_mutex_unlock(&mutex);
    return false;
}

 Just one more question, to "Not" process the buffer do I have just to return false
on that callback function? (like below)

if(!this->mIsRecording) {
    pthread_mutex_unlock(&mutex);
    return false;
}

Thank you in advance.

**Comment by superpoweredSDK** [comment]
Returning false means you are returning no audio for output (silence).

The snipped you wrote has the condition if (!this->mIsRecording). It translates to "if not recording" for me. And you call process() there.

**Comment by kulkuroo** [comment]
Thank you for the answer.

The condition if (!this->mIsRecording) is just simple internal boolean variable
which indicates that the user press the "Record" button.
I understand that as soon as I create the instance of SuperpoweredAndroidAudioIO class as
"Input mode", the OpenSL callback function start to be called by system. So I wanted to
remove unwanted sound input when user did not press the record button. 

If I don't want to record a sound, now I understand that I don't have to call the process() function
of the SuperpoweredRecord class. My last question was that what boolean return value
do I have to take? (true? false?) by taking one of them, does it make any difference?

 Thank you in advance.

**Comment by superpoweredSDK** [comment]
The boolean return value has nothing to do with the recorder. It's the return value of the audio processing callback. Return true: you have put some audio into the buffers. Return false: you did not put audio into the buffers (return with silence).
