### ISSUE TITLE
No sound when mixing 2 or more songs iOS 9

### ISSUE THREAD

**Issue by Atulth2001** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#71]
Hi Superpowered Team,

I am facing this very major issue as I add more than one song for mixing, the song goes mute. The issue is arising when tracks are played on speakers but working fine with headphones. Kindly suggest any workaround or fix to resolve this issue. The app is in its final stage so kindly resolve the issue keeping the time constraint in mind.

Regards.

**Comment by superpoweredSDK** [comment]
This is a duplicate ticket, i close it now.
