### ISSUE TITLE
Speaker sound goes mute while mixing two or more songs

### ISSUE THREAD

**Issue by Atulth2001** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#72]
Hi Superpowered Team,

I had already reported this issue to Superpowered Team but you guys might be in a hurry to close the issue rather than resolving it. As I have already mentioned in the last ticket that our app is in final phase
 and we need your guidance and support to resolve the issue. The issue is when we start mixing two or more songs the speakers sound goes mute even in the native music app but works fine with the headphones plugged-in. The sound won't come back unless until we plug in the headphones or restart the device.  You guys can have a closer look in the video. The link of the video is mentioned below: 
http://202.164.44.244/portfolio/VID_20151008_125237920.mp4.zip . 

Thanks in advance.

**Comment by superpoweredSDK** [comment]
Thank you providing more data. Until the video downloads, please let us know how do you mix two songs together.

**Comment by superpoweredSDK** [comment]
We see the problem. Some NaN data goes to the media server, which then fails. Please let us know your signal path, perhaps the whole audio processing feedback's code.

**Comment by Atulth2001** [comment]
Hello Superpowered Team,

Thanks for your earliest response, the code for the mixing part is as:

- (void)processAudioMixerForTrackPlayers:(NSMutableArray *)trackPlayers andSamples:(unsigned int)numberOfSamples {
	int numberOfMixerRequired = 0;
	int mixerCount = 0;
	if (trackPlayers.count)
		mixerCount = (int)trackPlayers.count / 4;

	if (fmod(trackPlayers.count, 4) > 0)
		numberOfMixerRequired = mixerCount + 1;
	else
		numberOfMixerRequired = mixerCount;

	for (int mixerCount = 0; mixerCount < numberOfMixerRequired; mixerCount++) {
		int startTrackRange = mixerCount * 4;
		int lastTrackRange = startTrackRange + 3;

		if (lastTrackRange >= trackPlayers.count) {
			lastTrackRange = (int)trackPlayers.count - 1;
		}

		float mixerInputTrack1 = 0.0;
		float mixerInputTrack2 = 0.0;
		float mixerInputTrack3 = 0.0;
		float mixerInputTrack4 = 0.0;
		float mixerInputTrack5 = 0.0;
		float mixerInputTrack6 = 0.0;
		float mixerInputTrack7 = 0.0;
		float mixerInputTrack8 = 0.0;

		float mixerInputTrack9 = 0.0;
		float mixerInputTrack10 = 0.0;
		float mixerInputTrack11 = 0.0;
		float mixerInputTrack12 = 0.0;
		float mixerInputTrack13 = 0.0;
		float mixerInputTrack14 = 0.0;
		float mixerInputTrack15 = 0.0;
		float mixerInputTrack16 = 0.0;

		float mixerInputTrack17 = 0.0;
		float mixerInputTrack18 = 0.0;
		float mixerInputTrack19 = 0.0;
		float mixerInputTrack20 = 0.0;
		float mixerInputTrack21 = 0.0;
		float mixerInputTrack22 = 0.0;
		float mixerInputTrack23 = 0.0;
		float mixerInputTrack24 = 0.0;


		float *outPutBuffer_1 = NULL;
		float *outPutBuffer_2 = NULL;
		float *outPutBuffer_3 = NULL;
		float *outPutBuffer_4 = NULL;

		float *outPutBuffer_5 = NULL;
		float *outPutBuffer_6 = NULL;
		float *outPutBuffer_7 = NULL;
		float *outPutBuffer_8 = NULL;

		float *outPutBuffer_9 = NULL;
		float *outPutBuffer_10 = NULL;
		float *outPutBuffer_11 = NULL;
		float *outPutBuffer_12 = NULL;

		int counter = 0;
		for (int trackPlayerCount = startTrackRange; trackPlayerCount <= lastTrackRange; trackPlayerCount++) {
			TrackPlayer *player = trackPlayers[trackPlayerCount];

			switch (counter) {
				case 0:
				{
					outPutBuffer_1 = [player trackBuffer];
					mixerInputTrack1 = [player mixerInputLevel];
					mixerInputTrack2 = [player mixerInputLevel];
				}
				break;

				case 1:
				{
					outPutBuffer_2 = [player trackBuffer];
					mixerInputTrack3 = [player mixerInputLevel];
					mixerInputTrack4 = [player mixerInputLevel];
				}
				break;

				case 2:
				{
					outPutBuffer_3 = [player trackBuffer];
					mixerInputTrack5 = [player mixerInputLevel];
					mixerInputTrack6 = [player mixerInputLevel];
				}
				break;

				case 3:
				{
					outPutBuffer_4 = [player trackBuffer];
					mixerInputTrack7 = [player mixerInputLevel];
					mixerInputTrack8 = [player mixerInputLevel];
				}
				break;

				case 4:
				{
					outPutBuffer_5 = [player trackBuffer];
					mixerInputTrack9 = [player mixerInputLevel];
					mixerInputTrack10 = [player mixerInputLevel];
				}
				break;

				case 5:
				{
					outPutBuffer_6 = [player trackBuffer];
					mixerInputTrack11 = [player mixerInputLevel];
					mixerInputTrack12 = [player mixerInputLevel];
				}
				break;

				case 6:
				{
					outPutBuffer_7 = [player trackBuffer];
					mixerInputTrack13 = [player mixerInputLevel];
					mixerInputTrack14 = [player mixerInputLevel];
				}
				break;

				case 7:
				{
					outPutBuffer_8 = [player trackBuffer];
					mixerInputTrack15 = [player mixerInputLevel];
					mixerInputTrack16 = [player mixerInputLevel];
				}
				break;

				case 8:
				{
					outPutBuffer_9 = [player trackBuffer];
					mixerInputTrack17 = [player mixerInputLevel];
					mixerInputTrack18 = [player mixerInputLevel];
				}
				break;

				case 9:
				{
					outPutBuffer_10 = [player trackBuffer];
					mixerInputTrack19 = [player mixerInputLevel];
					mixerInputTrack20 = [player mixerInputLevel];
				}
				break;

				case 10:
				{
					outPutBuffer_11 = [player trackBuffer];
					mixerInputTrack21 = [player mixerInputLevel];
					mixerInputTrack22 = [player mixerInputLevel];
				}
				break;

				case 11:
				{
					outPutBuffer_12 = [player trackBuffer];
					mixerInputTrack23 = [player mixerInputLevel];
					mixerInputTrack24 = [player mixerInputLevel];
				}
				break;

				default:
                    outPutBuffer_1 = [player trackBuffer];
                    mixerInputTrack1 = [player mixerInputLevel];
                    mixerInputTrack2 = [player mixerInputLevel];

					break;
			}
			counter++;
		}

		float *mixerInputs[4];
		float *mixerInputs1[4];
//		float *mixerInputs2[4];

		if (mixerCount == 0 && numberOfMixerRequired == 1) {
			//   NSLog(@"First four mixing");
			mixerInputs[0] = outPutBuffer_1;
			mixerInputs[1] = outPutBuffer_2;
			mixerInputs[2] = outPutBuffer_3;
			mixerInputs[3] = outPutBuffer_4;

			float mixerInputLevels[8] = { 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f };
			float mixerOutputLevels[2] = { 1.0f, 1.0f };
			float mixerOutputMeter[2] = { 0.0f, 0.0f };
			audioMixer->process(mixerInputs, outPutBuffers, mixerInputLevels, mixerOutputLevels, NULL, mixerOutputMeter, numberOfSamples);

//            audioMixer->process(mixerInputs, outPutBuffers, mixerInputLevels, mixerInputLevels[7], numberOfSamples);

//            mixerInputs[0] = *outPutBuffers;
//            mixerInputs[1] = outPutBuffer_5;
//            mixerInputs[2] = outPutBuffer_6;
//            mixerInputs[3] = outPutBuffer_7;
//
//            audioMixer1->process(mixerInputs, outPutBuffers2, mixerInputLevels, mixerOutputLevels, NULL, mixerOutputMeter, numberOfSamples);

			[self postNotificationWithMixerOutputMeter:mixerOutputMeter];
		}
		else if (mixerCount == 0 && numberOfMixerRequired == 2) {
			//   NSLog(@"First four NOT mixing");

			mixerInputs[0] = outPutBuffer_1;
			mixerInputs[1] = outPutBuffer_2;
			mixerInputs[2] = outPutBuffer_3;
			mixerInputs[3] = outPutBuffer_4;

			float mixerInputLevels[8] = { 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f };
			float mixerOutputLevels[2] = { 1.0f, 1.0f };
			float mixerOutputMeter[2] = { 0.0f, 0.0f };

			audioMixer->process(mixerInputs, outPutBuffers, mixerInputLevels, mixerOutputLevels, NULL, mixerOutputMeter, numberOfSamples);
		}
		else {
			// NSLog(@"Last Track Mixing");
/*
            mixerInputs[0] = *outPutBufferFinal;
            mixerInputs[1] = outPutBuffer_1;
            mixerInputs[2] = outPutBuffer_2;
            mixerInputs[3] = outPutBuffer_3;

            float mixerInputLevels[8] = { 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f };

            float mixerOutputLevels[2] = { 1.0f, 1.0f };
            float mixerOutputMeter[2] = { 0.0f, 0.0f };

            audioMixer1->process(mixerInputs, outPutBuffers, mixerInputLevels, mixerOutputLevels, NULL, mixerOutputMeter, numberOfSamples);
 */
			mixerInputs[0] = outPutBuffer_1;
			mixerInputs[1] = outPutBuffer_2;
			mixerInputs[2] = outPutBuffer_3;
			mixerInputs[3] = outPutBuffer_4;

			float mixerInputLevels[8] = { 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f };
			float mixerOutputLevels[2] = { 1.0f, 1.0f };
			float mixerOutputMeter[2] = { 0.0f, 0.0f };
			//AudioBufferList *ioData;
			//outPutBuffers1_4[0] = (float *)ioData->mBuffers[0].mData;

			outPutBuffers1_4[0] = (Float32 *)malloc(sizeof(Float32) * numberOfSamples);
			outPutBuffers1_4[1] = (Float32 *)malloc(sizeof(Float32) * numberOfSamples);

			audioMixer->process(mixerInputs, outPutBuffers1_4, mixerInputLevels, mixerOutputLevels, NULL, mixerOutputMeter, numberOfSamples);

			//outPutBuffers2 = outPutBuffers;

			mixerInputs1[0] = *outPutBuffers1_4;
			mixerInputs1[1] = outPutBuffer_5;
			mixerInputs1[2] = outPutBuffer_6;
			mixerInputs1[3] = outPutBuffer_7;

			audioMixer->process(mixerInputs1, outPutBuffers, mixerInputLevels, mixerOutputLevels, NULL, mixerOutputMeter, numberOfSamples);
			[self postNotificationWithMixerOutputMeter:mixerOutputMeter];
		}
	}
}


Please let me know if you need to know anything else.

Thanks

**Comment by superpoweredSDK** [comment]
mixerInputs1[0] = *outPutBuffers1_4 is wrong, remove the asterisk please

are doing two mallocs in every turn of the audio processing callback? do you know what malloc does?

**Comment by Atulth2001** [comment]
I am doing it as you have mentioned above but still getting the same results. Could you please provide a small example of mixing audios.

Thanks in Advance.
