### ISSUE TITLE
Time-stretching below 0.5 or above 2.0 in AdvancedAudioPlayer

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#73]
For some reason player->setTempo(0.33, true); for example will shift the pitch as well as the tempo. There's no notice of this in the docs, how come we can't get time stretching above or below those values? I don't care if there's a little more latency I would like the option to set it. Now I would have to add in a lot more complexity in order to compensate the pitch.

**Comment by superpoweredSDK** [comment]
We will make it adjustable in the next version. Please note however latency is not the issue with these limits, but CPU power. Some older mobile devices (such as the first iPad) can't finish calculations in time if you are using 128 samples of buffer size (low latency) outside the 0.5-2.0 range.
