### ISSUE TITLE
Visualizer from sessionId = 0

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#74]
On Android we can get the Visualizer input with the Visualizer API class. I know there is no way to get the specific sessionID of openSL instance, but we should be able to monitor the output mix with audioSession = 0. I can monitor other openSL and Java audio apps with audioSession = 0 on my devices through my own app, but when I use superpoweredSDK it is flatlined. Is there something to do?

**Comment by superpoweredSDK** [comment]
When native audio happens on Android (using OpenSL ES), don't expect the higher Java levels see anything from that.
