### ISSUE TITLE
What are the acceptable sampling rates for SuperpoweredAdvancedAudioPlayer?

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#78]
It seems like there is resampling within, because tracks which are not at the sampling rate passed to the constructor still play at the correct rate. However, some sampling rates are not supported. I have encountered 22050 mp3, and 88200 and 96000 wav's which get load error. These files otherwise will play fine with AdvancedAudioPlayer, if they are resampled, and they also play fine on all other music players as they are.

I am converting formats and can resample with ffmpeg, but it is really slow to resample on mobile and I want to avoid unless it is necessary - is there guidelines for which sampling rates will work with SuperpoweredAdvancedAudioPlayer?

**Comment by superpoweredSDK** [comment]
MP3 is MPEG-1 Audio Layer III. The MPEG-1 Audio Layer III standard has 3 sample rates, and Superpowered supports them: 32000 Hz, 44100 Hz, 48000 Hz. 

MPEG-2 Audio Layer III defines more rates, but that's not MP3. So, there is no such thing as 22050 Hz MP3, but it's an MPEG-2 AL III file.

There is no sample rate limitation for WAV, perhaps the fmt tag is invalid? Plz send us a WAV file which doesn't load.

**Comment by svenoaks** [comment]
Thanks for the info, I sent an example of wav file to hello@superpowered.com

**Comment by svenoaks** [comment]
I should also point out that the wiki article on MP3 says: "MPEG-1 or MPEG-2 Audio Layer III, more commonly referred to as MP3" - the MPEG-2 is just the last update of the format, they both have .mp3 file extension, same mime type, etc. I'm just saying maybe the docs should be a little more specific there, so we don't get surprised.

**Comment by svenoaks** [comment]
wav file link: https://drive.google.com/file/d/0B8c5OMd0SwnCekVlN2tZR05Jb1U/view?usp=sharing

**Comment by superpoweredSDK** [comment]
The wav file you sent does not contain PCM audio. The wav format can host many exotic formats inside, but wav is used for uncompressed PCM audio in 99.999999% of every case.

This file has the "extensible" format: https://msdn.microsoft.com/en-us/library/windows/hardware/dn653308(v=vs.85).aspx

If you encode your file to PCM wav with 88 kHz, it will work. We are not able to support every exotic format variation, sorry.

**Comment by svenoaks** [comment]
Every way of reading the file I have says the audio is PCM - PCM signed 16-bit little-endian, Furthermore if I reencode it (or other files) at 96 kHz sampling rate, it still doesn't load in AdvancedAudioPlayer, but reencoding it at 48 kHz allows it to play:

ffmpeg -i badwav.wav -ar 96000  bad96.wav

https://drive.google.com/file/d/0B8c5OMd0SwnCWFIzeW5kenVVV3c/view?usp=sharing

ffmpeg -i badwav.wav -ar 48000  bad48.wav

https://drive.google.com/file/d/0B8c5OMd0SwnCc21BTnlqSHlSajA/view?usp=sharing

Could superpowered be incorrectly reporting the audio within as not PCM with higher sampling rates?

**Comment by superpoweredSDK** [comment]
If it's a 16-bit little endian file, then the fmt tag should not refer to the extensible format. I can see that in  a hex editor too.

**Comment by svenoaks** [comment]
It's a valid format, you will notice in the MSDN doc you linked there is a SubFormat field, which can specify WAVE_FORMAT_PCM or WAVE_FORMAT_IEEE_FLOAT, which you are supporting in superpowered. 

It looks like it is not a hard modification to make it support WAV_FORMAT_EXTENSIBLE when it has the right underlying SubFormat:
http://www.juce.com/forum/topic/no-support-waveformatextensible-proposed-fix

It appears ffmpeg is changing to WAV_FORMAT_EXTENSIBLE when the sample rate is high by default, I'm not really sure why though. But you may want to consider adding support for it since ffmpeg is pretty ubiquitous for making audio files.

I will figure out how to force ffmpeg to use WAV_FORMAT_PCM in the mean time.

**Comment by svenoaks** [comment]
Here's the block of code in ffmpeg:

waveformatextensible = (enc->channels > 2 && enc->channel_layout) ||
                           enc->sample_rate > 48000 ||
                           enc->codec_id == AV_CODEC_ID_EAC3 ||
                           av_get_bits_per_sample(enc->codec_id) > 16;

The channels and the bps follow the microsoft spec for WAV_FORMAT_PCM, 1 or 2 channels and 8 or 16 bit only: https://msdn.microsoft.com/en-us/library/windows/desktop/dd390970(v=vs.85).aspx

Sample rate however seems optional to use WAV_FORMAT_EXTENSIBLE there, I comment out sample_rate part and force 2-channel and 16-bit and now I am set in my case.

**Comment by superpoweredSDK** [comment]
Yes, it seems like a little bug in FFMPEG. Just because the sample rate is > 48000, they should not choose the extensible format.
