### ISSUE TITLE
Android ACDB-LOADER Error

### ISSUE THREAD

**Issue by andreaperizzato** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#79]
Hi,
i'm trying the SuperpoweredSDK on Android but I'm getting the following pair of errors when the microphone is enabled:

```
E/AudFlgTh: read failed: framesRead=-2147483631
E/ACDB-LOADER: Error: ACDB AudProc vol returned = -19
```

Both errors appear in LogCat every 210ms.

My device is an HTC One M8, Android 5.0.1, Software Number 4.16.401.13, which features low latency audio hardware (FEATURE_AUDIO_LOW_LATENCY).

Also, when using `AudioRecord` the errors don't show up.

Those errors appear also when running your _FrequencyDomain_ example for Android.
I googled it, but i couldn't find anything useful.

**Comment by superpoweredSDK** [comment]
Does your app or the FrequencyDomain example work okay otherwise? (We have no idea what that ACDB stuff really does. It's some component of the audio driver --- system stuff, has nothing to do with Superpowered.)

**Comment by andreaperizzato** [comment]
Yep, I tried to switch off the input and also tried with another device and the errors go away. 
Sure it's related to something HTC has done when customising the software.

**Comment by svenoaks** [comment]
This same error happened on HTC One M7 GPE, when using the audio input. It would seem to occur randomly after the microphone was open for a long time.

**Comment by andreaperizzato** [comment]
Thanks @svenoaks, I tried but it doesn't work. I guess HTC made it even worse on the M8.
I guess it might be solved since `AudioRecord` works properly, but that errors don't say that much to further investigate the actual cause.

**Comment by superpoweredSDK** [comment]
Unfortunately, Android OEMs often create buggy HALs for audio.
