### ISSUE TITLE
Android Marshmallow dropouts

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#81]
I am wondering if the current version is tested on Android 6.0. I am getting significant audio dropouts using SuperpoweredAdvancedAuioPlayer and the Android IO class on Nexus 9. Didn't have this problem before upgrade.

**Comment by superpoweredSDK** [comment]
Just tested our CrossExample project on the Nexus 9 with Android 6.0, runs perfectly without any dropouts.
We have changed the Android IO class a bit, you will see in the next update. Although the modifications have very little to do with dropouts.
