### ISSUE TITLE
Issue #73 time stretching below 0.5 and above 2.0

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#82]
In issue #73 it was said that the limitation of SuperpoweredAdvancedAudioPlayer would be removed in the next version, but it didn't make it into 0.9.1. When will this be done, I was counting on it.

**Comment by superpoweredSDK** [comment]
Please check the new minTimeStretchingTempo and maxTimeStretchingTempo parameters.
