### ISSUE TITLE
swift 2?

### ISSUE THREAD

**Issue by davut5** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#83]
i watched your video from here https://www.youtube.com/watch?v=kOXe9nnJo38

I want to record my voice with a background song playing. i am using SWIFT 2. 
how can i do that?   will u make a POD?  help me please

**Comment by superpoweredSDK** [comment]
I'm sorry, but we are not able to provide an example code for every case -- there are millions of possible combinations and use cases. The frequencies example project shows how to use Superpowered in a project where Swift is the main language for the user interface. No, we have no plans for a pod -- you can simply drag and drop the static library and the required header files into your project.
