### ISSUE TITLE
High sample rate .m4a causes crash

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#84]
First of all thanks guys for all your hard work on Superpowered, I am almost ready to release the update for my app using it. 

One last problem I have noticed - though not common a 96,000 and probably 88,200 sample rate m4a will cause AdvancedAudioPlayer to take a dump and crash, when play is called on it. It should give onError, at least. Here is an example file:

https://drive.google.com/file/d/0B8c5OMd0SwnCSXNJRFFIbFRLSjg/view?usp=sharing

Do you think a quick work-around for this would be to look at file extension and open the file with SuperpoweredDecoder to get what the sampling rate for the file is first, so I could do something else besides crashing?

Here are some other issues I noticed:

When we seek to 1.0, (passes == in all cases), sometimes EOF is called and sometimes not, I think it depends on the file. This causes a pain to get consistent behavior when user drags seekbar all the way to the right.

Also shouldn't positionMs be updated immediately following a seek? It doesn't happen until process is called on the audio thread, which makes it hard to get a proper reading of the position. I had issues with my seekbar jumping around without a workaround.

One more question for you - is reading the read only fields from AdvancedAudioPlayer considered thread safe? I haven't seen it but could I get garbage values because they are being written on audio thread?

**Comment by superpoweredSDK** [comment]
The file you linked has corrupt sample rate information. The MVHD atom tells it's 1000 Hz, the STSD atom tells it's 0 Hz. I will build a safety mechanism into the next update, where the decoder will fail in this case.

I recommend to not send 1.0f with your seekbar, just 0.99f.

positionMs is updated in the audio processing callback only, yes. This provides a very precise information about where the current playback really is.

The read only fields are thread safe, yes. Thread safety means you can read them from any thread. Thread safety doesn't mean you don't get garbage values.

**Comment by svenoaks** [comment]
Thanks, don't think I agree with that definition of thread safety, it's a potential race condition. I would suggest guarantee that variables be atomic reads.

**Comment by svenoaks** [comment]
Also, without reading through the mp4 spec, the file is created with prebuilt ffmpeg, and plays on all other players, everything reports it's sample rate as 96000.

**Comment by svenoaks** [comment]
I take the last post back, it doesn't play on some media players. Guess ffmpeg is making them wrong at that sample rate for some reason.
