### ISSUE TITLE
Calling open with a path to .m4a on Android returns "Unknown file format"

### ISSUE THREAD

**Issue by SeanAsby** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#85]
When calling open on the audio player with a path to this file [Clap.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/58159/Clap.zip) on Android, the ```playerEventCallback``` is passed ```SuperpoweredAdvancedAudioPlayerEvent_LoadError``` with the error "Unknown file format". The file works fine when playing in other mediaplayers on desktop and Android

**Comment by superpoweredSDK** [comment]
This is a corrupted file. The mp4 container structure consists of atoms, where the first 4 bytes of the atom is the atom's size in bytes, the second 4 bytes is the atom's name. This file has an mdat atom with the size 1 bytes, while it is several kbytes long (as it contains audio data). Please check the software which produced this invalid file.
