### ISSUE TITLE
SuperpoweredAndroidAudioIO the destructor can cause ANR

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#86]
(*internals->outputBufferQueue)->Destroy(internals->outputBufferQueue);

I have repo'd it on several devices and Android versions, this line will block forever sporadically. You are sleeping the thread destructor is in hoping the audio thread will stop in time, but sometimes it does not and we get UB or maybe deadlock inside OpenSL. If I increase the sleep time that you have there from 10ms to 200ms the problem will never occur in practice, though this isn't a very good solution. There needs to be some kind of wait/notify thing, but I can't really think of 100% solution yet. 

Also, in CrossExample destructor, you are deleting the players before the audiosystem, I think this could lead to UB too, the audio callback could call the player's process methods after they are deleted.

**Comment by superpoweredSDK** [comment]
I think increasing the sleep time is a good solution. Waiting for a notification (if there is any) might be even less reliable on those devices, where the audio stack's implementation is not so good.

Thank you very much notifying us for these bugs. Will be fixed in the upcoming release.
