### ISSUE TITLE
aac decoder crashes

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#88]
I have this as top in crash log (though only 0.1% of users afflicted by all of them combined):

http://crashes.to/s/84a2af442da
http://crashes.to/s/a8f7adc8333
http://crashes.to/s/fa22826d881

This after opening all m4a with decoder to check samplerate == 0 to successfully prevent crash as in #84.

Only 1 or 2 from mp3 or PCM decoder, Superpowered is pretty stable.

**Comment by superpoweredSDK** [comment]
These crashes tell that the source file gets corrupted or moved away. It happens with my DJ Player app as well, which has 2 million downloads so far and 10 similar crashes every day. Preventing these is not possible at all, the code has many safety mechanisms around those lines of code.

**Comment by svenoaks** [comment]
Thanks, what's your app called. Mine: https://play.google.com/store/apps/details?id=com.smp.musicspeed&hl=en Nearing 500k
