### ISSUE TITLE
AdvancedAudioPlayer seeking with setReverse()

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#89]
Play normally, call setReverse(true, 0), plays in reverse, call seek(x). Subsequent calls to process() on the audio thread result in 'false' (silence). I find it must be 'primed' in forward playback for an unknown amount of time before playing in reverse will work again. 

I tried setting to setReverse(false, 0) and a single call to process(), then switching back to setReverse(true, 0) on the audio thread when a seek happens as a workaround but it didn't work.

I would like to be able to have accurate seeks in reverse mode, and seeks in reverse mode when the player is paused, could this be improved in later release of Superpowered and is there a good workaround for me now?

**Comment by superpoweredSDK** [comment]
This will be fixed in the next update (fixed already, but there are not enough bugs for a release yet).

**Comment by Kshitij1792** [comment]
Hey @svenoaks 
I viewed all of the issues and while going through issues raised by you, it seemed like you had good knowledge of audio programming. I am trying to mix 2  audios of different formats(.mp3 and .m4a) in Android using this library.
I know its pretty basic but could you help me with the exact steps to mix them in android(If not with code just with steps). it would be a big help.
Just need right direction to get me going. 
Thank you.
