### ISSUE TITLE
How to integrate the library in Xcode

### ISSUE THREAD

**Issue by abhimanyujindal10** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#9]
I am getting linker errors while integrating in Xcode. Can you please provide the steps to integrate library in Xcode Project?

**Comment by superpoweredSDK** [comment]
I guess you have arm64 enabled, but we will release the arm64 version of the library later this month. Until then please remove arm64 from the valid architectures in your build settings.

**Comment by abhimanyujindal10** [comment]
Yes, thanks for the reply. I disabled arm64 and now it is working. Thanks a lot.
