### ISSUE TITLE
SuperpoweredDecoder open Issues

### ISSUE THREAD

**Issue by pound23** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#90]
I am trying to time stretch some high quality audio (foreign language learning app).  The idea is to slow down some speech so the user can listen closely.  We have a high quality voice recording of a native speaker (done in studio) and in the program as MP3.  Sounds great.

But when it is time stretched using SuperPowered ... The voice get a metallic sound to it.  I am using a rte of 80% (0.8) and the output is poor quality and metallic in sound.

Any ideas?  Or is your technology more suited to music?

**Comment by superpoweredSDK** [comment]
Can you send a recording, so we can check? It should sound great at 0.8.

**Comment by pound23** [comment]
Hi!  Thanks for quick response!

I am attaching a couple of samples (original MP3 and 75% slowed).  If you
can't get the attachments please email me again from your direct email!

I expect some degradation, but as you can hear the voice becomes very
metallic and you lose a lot of the softness.  Please comment on if this is
considered normal.

I have tried a few other online samples of time stretching ... with web
sites that give their own original/slowed ... and quality seems to be
usually very good.  So just curious as to what might be going on.

Let me know if I can send you anything else ...

**Comment by superpoweredSDK** [comment]
Seems like your subjective preference is difference to ours. This is how our time stretcher sounds, and yes, it's tuned to music.
