### ISSUE TITLE
Audio Recording mono from michrophone

### ISSUE THREAD

**Issue by drusak** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#91]
Hello,

I have a problem with SuperpoweredRecorder and devices with solo microphone (stereo not supported). If audio is stereo - everything is fine.

Do you have some instructions regarding mono recording?

Thanks!

**Comment by superpoweredSDK** [comment]
The SuperpoweredRecorder doesn't support mono sources. Convert a mono source using SuperpoweredInterleave to stereo.
