### ISSUE TITLE
Occasional crash in SuperpoweredStereoMixerFloatToShortIntInterleaved

### ISSUE THREAD

**Issue by namannik** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#92]
My app occasionally experiences crashes that appear to occur in a function called `SuperpoweredStereoMixerFloatToShortIntInterleaved `, according to crash logs.  I haven't determined a way to reliably duplicate this crash.  It occurs pretty infrequently.  Do you have any ideas about what's going on and what I should do differently to prevent these crashes?  The app is using version 0.9.1 of Superpowered.

Below are the stack traces for these crashes.

```
0  0x1005276e8 SuperpoweredStereoMixerFloatToShortIntInterleaved (SuperpoweredStereoMixerConvertersARM64.S:68)
1  0x100527284 SuperpoweredFloatToShortInt(float*, short*, unsigned int) (SuperpoweredMixer.cpp:424)
2  0x100073f08 getPacket (htvAudioReceive.c:287)
3  0x100073ab8 playStream (htvAudioReceive.c:311)
```

```
0  0x48ec08 SuperpoweredStereoMixerFloatToShortIntInterleaved (SuperpoweredStereoMixerConvertersARM.S:80)
1  0x48e5df SuperpoweredFloatToShortInt(float*, short*, unsigned int) (SuperpoweredMixer.cpp:416)
2  0xd58a7 getPacket (htvAudioReceive.c:287)
3  0xd54d7 playStream (htvAudioReceive.c:311)
```

```
0  0x1004c36e4 SuperpoweredStereoMixerFloatToShortIntInterleaved (SuperpoweredStereoMixerConvertersARM64.S:67)
1  0x1004c3284 SuperpoweredFloatToShortInt(float*, short*, unsigned int) (SuperpoweredMixer.cpp:424)
2  0x10000ff08 getPacket (htvAudioReceive.c:287)
3  0x10000fab8 playStream (htvAudioReceive.c:311)
```

Here are the full crash reports:

http://crashes.to/s/cf655e4c908
http://crashes.to/s/daf34bd2977
http://crashes.to/s/fb09650ac21

**Comment by superpoweredSDK** [comment]
It means that the buffers you pass are either too short compared to the number of samples value you pass, or they are null maybe. Please note, the number of samples value corresponds to a stereo input -- if you have a stereo input with 2x256 samples, you should pass 256.
