### ISSUE TITLE
SuperopoweredEcho on Android x86 device not applied

### ISSUE THREAD

**Issue by drusak** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#94]
I faced with the problem on device with x86 arch.
I have single track in player and added Echo effect. Method _process_  of effect returns true (means it processed fine). On devices with ARM arch it works fine, but on x86 it's not applied.
I tried the same player with Reverb effect and it works fine on both architectures.

Have you faced with the same issue?

Thanks in advance,
Dmitry

**Comment by superpoweredSDK** [comment]
We will test this in a week as we are at NAMM currently, sorry for the delay.

**Comment by superpoweredSDK** [comment]
We will release a new version of the library soon, which will have the fix for this. Sorry for the bug.
