### ISSUE TITLE
EXC_BAD_ACCESS when calling open on audio player on 64-bit iOS devices

### ISSUE THREAD

**Issue by SeanAsby** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#95]
Periodically when calling open on SuperPoweredAdvancedAudioPlayer my project is crashing with ```EXC_BAD_ACCESS```, but only on iOS devices with 64-bit processor(iPhone 5s and newer). The functions it is crashing in are called ```readThreadDurationCheck``` and ```createInternals```. When crashing in ```readThreadDurationCheck``` there is no output. When crashing in ```createInternals``` i get this output: ```SuperpoweredNativeTest(548,0x1a0919000) malloc: *** mach_vm_map(size=13615988736) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
SuperpoweredNativeTest(548,0x1a0919000) malloc: *** mach_vm_map(size=13615988736) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
SuperpoweredNativeTest(548,0x1a0919000) malloc: *** mach_vm_map(size=1702002688) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug```

Is this a known issue? I've attached my complete project for reference.

[SuperpoweredNativeTest.zip](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/files/97651/SuperpoweredNativeTest.zip)

**Comment by superpoweredSDK** [comment]
Hello,
according to the messages, mach_vm_map fails because your iOS can not provide more memory to your application. Superpowered uses extremely low amount of memory, and for some reason it tries to allocate 13 GB this time, which is strange. I wonder if setting cachedPointCount to 1 in the advanced audio player's constructor fixes this?

**Comment by SeanAsby** [comment]
Setting ```cachedPointCount``` to 1 did not help. It is still crashing in the same locations

**Comment by SeanAsby** [comment]
Any update on this issue?

**Comment by superpoweredSDK** [comment]
We did NAMM last week and traveling on this one. Sorry for the delay. We can look into this next week.

**Comment by SeanAsby** [comment]
Have you looked at the issue?

**Comment by superpoweredSDK** [comment]
Not yet, sorry.

**Comment by superpoweredSDK** [comment]
This bug can not be reproduced, only with this project's files. The error is that for some reason the program doesn't allocate enough heap memory while creating the SuperpoweredAdvancedAudioPlayer C++ object with new. We could not find the cause of this, but it's outside the Superpowered library, as this error can not be reproduced with other projects.
Please try modifying the CrossExample project's code gradually (by removing the components until one player is left) until you encounter this error. We spent 4 hours debugging your project, but we're not able to spend more time with this.

**Comment by snap608** [comment]
I have the same issue.

The bug occurs when I build @SeanAsby project for 64-bit architecture and works as it should when I target 32-bit architecture. So I believe this have to be an issue connected to the target architecture.

@superpoweredSDK have you tried to debuging the project on 32-bit vs. 64-bit?
