### ISSUE TITLE
Unable to stream mp3 

### ISSUE THREAD

**Issue by Vivekban** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#98]
I am unable to play mp3 streaming url in my app. In hlsexample prject i just add another test url  [http://icecast.omroep.nl/radio1-bb-mp3](url) even try [http://icecast.omroep.nl/radio1-bb-aac](url). But when i click log shows " Open error: Can't open this file". Why..?   When i open these urls in browser, they are working fine.  
Please Help

Thanks in advance

**Comment by superpoweredSDK** [comment]
The linked resources doesn't confirm to the HTTP Live Streaming protocol. Please learn about the standard here: https://developer.apple.com/streaming/
