### ISSUE TITLE
Trouble syncing newly opened tracks

### ISSUE THREAD

**Issue by SFowler9** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#99]
Hi,

I want to be able to load tracks automatically towards the end of the currently playing song and have the song start on-beat. At the moment I can't get them to sync unless they are both loaded at the same time. 

They do sync up when I pause playback and play it again. The problem seems to be that the song starts immediately.

Here's my code for loading, taken from the examples and slightly modified to my needs:
```
void SuperpoweredBluetooth::loadSong(const char* path, double bpm, double beatStart, bool isPlayerA) {
    pthread_mutex_lock(&mutex);

    if (isPlayerA) {
        playerA->open(path);
        playerA->setBpm(bpm);
        playerA->setFirstBeatMs(beatStart);
        playerA->setPosition(0, false, true);
    } else {
        playerB->open(path);
        playerB->setBpm(bpm);
        playerB->setFirstBeatMs(beatStart);
        playerB->setPosition(0, false, true);
    }

    // Sync the players together
    pthread_mutex_unlock(&mutex);
}

void SuperpoweredBluetooth::onPlayPause(bool play) {
    pthread_mutex_lock(&mutex);
    if (!play) {
        playerA->pause();
        playerB->pause();
    } else {
        bool masterIsA = (crossValue <= 0.5f);
        playerA->play(!masterIsA);
        playerB->play(masterIsA);
    };
    pthread_mutex_unlock(&mutex);
}


```

You can see I took the "playerA->setBpm()" and the like out of the callback so I could pass the value for each individual file - I wasn't sure how to pass them to the callback as this is my first experience of C++.

Here's my constructor, in case that helps. You'll also see that I'm setting syncMode and waitForNextBeatWithSync.

```
SuperpoweredBluetooth::SuperpoweredBluetooth(const char *path, int *params) : activeFx(0), crossValue(0.0f), volB(0.0f), volA(1.0f * headroom) {
    pthread_mutex_init(&mutex, NULL); // This will keep our player volumes and playback states in sync.
    unsigned int samplerate = params[0], buffersize = params[1];
    stereoBuffer = (float *)memalign(16, (buffersize + 16) * sizeof(float) * 2);

    playerA = new SuperpoweredAdvancedAudioPlayer(&playerA , playerEventCallbackA, samplerate, 0);
    playerB = new SuperpoweredAdvancedAudioPlayer(&playerB, playerEventCallbackB, samplerate, 0);

    playerA->syncMode = playerB->syncMode = SuperpoweredAdvancedAudioPlayerSyncMode_TempoAndBeat;
    playerA->waitForNextBeatWithBeatSync = playerB->waitForNextBeatWithBeatSync = true;

    audioSystem = new SuperpoweredAndroidAudioIO(samplerate, buffersize, false, true, audioProcessing, this, -1, SL_ANDROID_STREAM_MEDIA, buffersize * 2);
}
```

Any pointers would be greatly appreciated!

**Comment by superpoweredSDK** [comment]
Syncing happens in the audio processing callback. Please check the CrossExample example project's code how it is done. You can sync any player to an imaginary beatgrid, so if you sync both players and start playback of player B after player A is finished, you will always be on beat.

**Comment by SFowler9** [comment]
Thanks, I have no doubt that will solve my issue.

Hopefully you could answer me this though. How do I pass some values, such as the bpm and beatgridstart to the callback? Sorry for my ignorance...

**Comment by mateusgrb** [comment]
@SFowler9 did you manage to solve your issue? I'm a beginner at C++ and I'm also struggling to pass data to callback and sync tracks started at different times.
